### ISSUE TITLE
scripts.newick.NewickError:

### ISSUE THREAD

**Issue by chengbing0404** [davidemms/OrthoFinder#133]
Hi David,
I'm using the newest version of OrthoFinder/2.2.0 (installed on HPC), however, I still got the error as the previous issue reported in Sep 2016. The error message was as below. Can you please advise? Thanks very much in advance!
The script I'm running the job is `orthofinder -f directory`
**********************************************************************************************************
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1549, in <module>
  File "orthofinder/orthofinder.py", line 1398, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 948, in OrthologuesWorkflow
  File "orthofinder/scripts/orthologues.py", line 408, in RunAnalysis
  File "orthofinder/scripts/stag.py", line 252, in Run_ForOrthoFinder
  File "orthofinder/scripts/stag.py", line 237, in InferSpeciesTree
  File "orthofinder/scripts/consensus_tree.py", line 248, in ConsensusTree
  File "orthofinder/scripts/consensus_tree.py", line 152, in GetAllSplits
  File "orthofinder/scripts/tree.py", line 180, in __init__
  File "orthofinder/scripts/newick.py", line 231, in read_newick
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
Failed to execute script orthofinder
************************************************************************************************************
Kind regards,

**Comment by rafaeltiveron** [comment]
Just type `orthofinder -f directory` . Don't type `/file.fasta`. You have to check that there are only the interested files on this directory.

**Comment by chengbing0404** [comment]
Sorry it was my mistake didn't double check before posting. **Yes my script was without the file.fasta** but only a directory.
I have two fasta files in the directory. Then I got this NewickError: error.

**Comment by chengbing0404** [comment]
Thanks for your reply, David. 
-The previous issue is: #31 
-I rerun orthofinder with the data downloaded from NCBI (yeast.fa and swissprot.fa) and the output file is as below:
*********************************************************************************

OrthoFinder version 2.2.0 Copyright (C) 2014 David Emms

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "fastme -i /test_orthofinder/SimpleTest.phy -o /test_orthofinder/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-02-27 12:59:50 : Creating Blast database 1 of 2
2018-02-27 12:59:51 : Creating Blast database 2 of 2

Running BLAST all-versus-all
----------------------------
Using 16 thread(s)
2018-02-27 12:59:51 : This may take some time....

Running OrthoFinder algorithm
-----------------------------
2018-02-27 13:47:57 : Initial processing of each species
2018-02-27 13:48:03 : Initial processing of species 0 complete
2018-02-27 13:48:05 : Initial processing of species 1 complete
2018-02-27 13:48:09 : Connected putatitive homologs
2018-02-27 13:48:13 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /test_orthofinder/Results_Feb27/Orthogroups.csv
   /test_orthofinder/Results_Feb27/Orthogroups.txt (OrthoMCL format)
   /test_orthofinder/Results_Feb27/Orthogroups_UnassignedGenes.csv
2018-02-27 13:48:14 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2018-02-27 13:48:27 : Done 0 of 156
2018-02-27 13:48:28 : Done 10 of 156
2018-02-27 13:48:29 : Done 20 of 156
2018-02-27 13:48:30 : Done 30 of 156
2018-02-27 13:48:30 : Done 40 of 156
2018-02-27 13:48:31 : Done 50 of 156
2018-02-27 13:48:32 : Done 60 of 156
2018-02-27 13:48:33 : Done 70 of 156
2018-02-27 13:48:33 : Done 80 of 156
2018-02-27 13:48:34 : Done 90 of 156
2018-02-27 13:48:35 : Done 100 of 156
2018-02-27 13:48:36 : Done 110 of 156
2018-02-27 13:48:37 : Done 120 of 156
2018-02-27 13:48:38 : Done 130 of 156
2018-02-27 13:48:38 : Done 140 of 156
2018-02-27 13:48:39 : Done 150 of 156
2018-02-27 13:48:24 : Done

Inferring gene and species trees
--------------------------------

151 trees had all species present and will be used by STAG to infer the species tree

2018-02-27 13:48:10 : Written final scores for species 0 to graph file
2018-02-27 13:48:11 : Written final scores for species 1 to graph file
***********************************************************************************************************

Please let me know if further details!

Thanks!

Kind regards,
Bing

**Comment by rafaeltiveron** [comment]
I've the same error, after I started to use the most recent release.

**Comment by davidemms** [comment]
Hi

Thanks for posting this issue, it's now been resolved and the code is available on the main repository page. I'll create a new release package that contains this fix soon, which will package together a few changes. 

As a general bit of advice, you'll always get better results if you include a better sampling of related species, I'd recommend a minimum of 5. Also, 'swissprot.fa' sounds like it's not a species? If the input data is different from what OrthoFinder is expecting (individual fasta files containing the proteomes for individual species) then the results will probably also be different from what you're expecting.

All the best
David

**Comment by chengbing0404** [comment]
Thanks for the efforts! Yes I agree good results from close species. 
In this case, the subset of the yeast and swissprot data were just randomly used as a small test to show you where the issue is as the example dataset provided is probably being tested before the release. 

Thanks again for the update!

Kind regards,

Bing
