### ISSUE TITLE
Error doing "Best outgroups(s) for species tree"

### ISSUE THREAD

**Issue by spleonard1** [davidemms/OrthoFinder#137]
I'm running orthofinder on a collection of 58 bacterial genomes, should be all the same species. At the "best outgroup(s) for species tree" step I get the following error:

Best outgroup(s) for species tree
---------------------------------
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1549, in <module>
  File "orthofinder/orthofinder.py", line 1398, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 976, in OrthologuesWorkflow
  File "orthofinder/scripts/stride.py", line 504, in GetRoot
  File "multiprocessing/pool.py", line 250, in map
  File "multiprocessing/pool.py", line 554, in get
Exception
Failed to execute script orthofinder

Surprisingly, I have successfully run orthofinder on a collection of 84 bacterial genomes on the same machine without issues. Could something weird in a particular .faa file cause this error?

**Comment by davidemms** [comment]
Hi, do you have some more output from the OrthoFinder run? I'll take a look and see what's going on.

Thanks
David

**Comment by spleonard1** [comment]
I've tried to reduce the number of genomes but keep getting the same error. Here's the full output. Let me know if you need further info...

spl552@ochmcomp01:~/projects/orthologs$ orthofinder -t 32 -S diamond -f some_snod/ 

OrthoFinder version 2.2.0 Copyright (C) 2014 David Emms

32 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /stor/home/spl552/projects/orthologs/some_snod/SimpleTest.phy -o /stor/home/spl552/projects/orthologs/some_snod/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-03-01 18:18:32 : Creating diamond database 1 of 34
2018-03-01 18:18:32 : Creating diamond database 2 of 34
2018-03-01 18:18:32 : Creating diamond database 3 of 34
2018-03-01 18:18:32 : Creating diamond database 4 of 34
2018-03-01 18:18:32 : Creating diamond database 5 of 34
2018-03-01 18:18:32 : Creating diamond database 6 of 34
2018-03-01 18:18:32 : Creating diamond database 7 of 34
2018-03-01 18:18:32 : Creating diamond database 8 of 34
2018-03-01 18:18:32 : Creating diamond database 9 of 34
2018-03-01 18:18:32 : Creating diamond database 10 of 34
2018-03-01 18:18:32 : Creating diamond database 11 of 34
2018-03-01 18:18:32 : Creating diamond database 12 of 34
2018-03-01 18:18:32 : Creating diamond database 13 of 34
2018-03-01 18:18:32 : Creating diamond database 14 of 34
2018-03-01 18:18:32 : Creating diamond database 15 of 34
2018-03-01 18:18:32 : Creating diamond database 16 of 34
2018-03-01 18:18:32 : Creating diamond database 17 of 34
2018-03-01 18:18:32 : Creating diamond database 18 of 34
2018-03-01 18:18:32 : Creating diamond database 19 of 34
2018-03-01 18:18:32 : Creating diamond database 20 of 34
2018-03-01 18:18:32 : Creating diamond database 21 of 34
2018-03-01 18:18:32 : Creating diamond database 22 of 34
2018-03-01 18:18:32 : Creating diamond database 23 of 34
2018-03-01 18:18:32 : Creating diamond database 24 of 34
2018-03-01 18:18:32 : Creating diamond database 25 of 34
2018-03-01 18:18:32 : Creating diamond database 26 of 34
2018-03-01 18:18:32 : Creating diamond database 27 of 34
2018-03-01 18:18:32 : Creating diamond database 28 of 34
2018-03-01 18:18:32 : Creating diamond database 29 of 34
2018-03-01 18:18:33 : Creating diamond database 30 of 34
2018-03-01 18:18:33 : Creating diamond database 31 of 34
2018-03-01 18:18:33 : Creating diamond database 32 of 34
2018-03-01 18:18:33 : Creating diamond database 33 of 34
2018-03-01 18:18:33 : Creating diamond database 34 of 34

Running diamond all-versus-all
------------------------------
Using 32 thread(s)
2018-03-01 18:18:33 : This may take some time....
2018-03-01 18:18:33 : Done 0 of 1156
2018-03-01 18:19:01 : Done 100 of 1156
2018-03-01 18:19:24 : Done 200 of 1156
2018-03-01 18:19:47 : Done 300 of 1156
2018-03-01 18:20:10 : Done 400 of 1156
2018-03-01 18:20:33 : Done 500 of 1156
2018-03-01 18:20:57 : Done 600 of 1156
2018-03-01 18:21:19 : Done 700 of 1156
2018-03-01 18:21:44 : Done 800 of 1156
2018-03-01 18:22:05 : Done 900 of 1156
2018-03-01 18:22:20 : Done 1000 of 1156
2018-03-01 18:22:34 : Done 1100 of 1156

Running OrthoFinder algorithm
-----------------------------
2018-03-01 18:22:45 : Initial processing of each species
2018-03-01 18:22:50 : Initial processing of species 0 complete
2018-03-01 18:22:55 : Initial processing of species 1 complete
2018-03-01 18:23:00 : Initial processing of species 2 complete
2018-03-01 18:23:05 : Initial processing of species 3 complete
2018-03-01 18:23:09 : Initial processing of species 4 complete
2018-03-01 18:23:12 : Initial processing of species 5 complete
2018-03-01 18:23:16 : Initial processing of species 6 complete
2018-03-01 18:23:21 : Initial processing of species 7 complete
2018-03-01 18:23:26 : Initial processing of species 8 complete
2018-03-01 18:23:31 : Initial processing of species 9 complete
2018-03-01 18:23:36 : Initial processing of species 10 complete
2018-03-01 18:23:41 : Initial processing of species 11 complete
2018-03-01 18:23:46 : Initial processing of species 12 complete
2018-03-01 18:23:51 : Initial processing of species 13 complete
2018-03-01 18:23:56 : Initial processing of species 14 complete
2018-03-01 18:24:01 : Initial processing of species 15 complete
2018-03-01 18:24:06 : Initial processing of species 16 complete
2018-03-01 18:24:11 : Initial processing of species 17 complete
2018-03-01 18:24:16 : Initial processing of species 18 complete
2018-03-01 18:24:21 : Initial processing of species 19 complete
2018-03-01 18:24:26 : Initial processing of species 20 complete
2018-03-01 18:24:31 : Initial processing of species 21 complete
2018-03-01 18:24:36 : Initial processing of species 22 complete
2018-03-01 18:24:41 : Initial processing of species 23 complete
2018-03-01 18:24:46 : Initial processing of species 24 complete
2018-03-01 18:24:51 : Initial processing of species 25 complete
2018-03-01 18:24:56 : Initial processing of species 26 complete
2018-03-01 18:25:00 : Initial processing of species 27 complete
2018-03-01 18:25:05 : Initial processing of species 28 complete
2018-03-01 18:25:10 : Initial processing of species 29 complete
2018-03-01 18:25:16 : Initial processing of species 30 complete
2018-03-01 18:25:20 : Initial processing of species 31 complete
2018-03-01 18:25:26 : Initial processing of species 32 complete
2018-03-01 18:25:30 : Initial processing of species 33 complete
2018-03-01 18:25:55 : Connected putatitive homologs
2018-03-01 18:25:57 : Written final scores for species 0 to graph file
2018-03-01 18:26:00 : Written final scores for species 1 to graph file
2018-03-01 18:26:02 : Written final scores for species 2 to graph file
2018-03-01 18:26:04 : Written final scores for species 3 to graph file
2018-03-01 18:26:06 : Written final scores for species 4 to graph file
2018-03-01 18:26:08 : Written final scores for species 5 to graph file
2018-03-01 18:26:09 : Written final scores for species 6 to graph file
2018-03-01 18:26:11 : Written final scores for species 7 to graph file
2018-03-01 18:26:14 : Written final scores for species 8 to graph file
2018-03-01 18:26:16 : Written final scores for species 9 to graph file
2018-03-01 18:26:18 : Written final scores for species 10 to graph file
2018-03-01 18:26:20 : Written final scores for species 11 to graph file
2018-03-01 18:26:22 : Written final scores for species 12 to graph file
2018-03-01 18:26:25 : Written final scores for species 13 to graph file
2018-03-01 18:26:27 : Written final scores for species 14 to graph file
2018-03-01 18:26:29 : Written final scores for species 15 to graph file
2018-03-01 18:26:31 : Written final scores for species 16 to graph file
2018-03-01 18:26:33 : Written final scores for species 17 to graph file
2018-03-01 18:26:36 : Written final scores for species 18 to graph file
2018-03-01 18:26:38 : Written final scores for species 19 to graph file
2018-03-01 18:26:40 : Written final scores for species 20 to graph file
2018-03-01 18:26:42 : Written final scores for species 21 to graph file
2018-03-01 18:26:44 : Written final scores for species 22 to graph file
2018-03-01 18:26:46 : Written final scores for species 23 to graph file
2018-03-01 18:26:49 : Written final scores for species 24 to graph file
2018-03-01 18:26:51 : Written final scores for species 25 to graph file
2018-03-01 18:26:53 : Written final scores for species 26 to graph file
2018-03-01 18:26:55 : Written final scores for species 27 to graph file
2018-03-01 18:26:57 : Written final scores for species 28 to graph file
2018-03-01 18:27:00 : Written final scores for species 29 to graph file
2018-03-01 18:27:02 : Written final scores for species 30 to graph file
2018-03-01 18:27:04 : Written final scores for species 31 to graph file
2018-03-01 18:27:07 : Written final scores for species 32 to graph file
2018-03-01 18:27:09 : Written final scores for species 33 to graph file
2018-03-01 18:27:31 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /stor/home/spl552/projects/orthologs/some_snod/Results_Mar01_7/Orthogroups.csv
   /stor/home/spl552/projects/orthologs/some_snod/Results_Mar01_7/Orthogroups.txt (OrthoMCL format)
   /stor/home/spl552/projects/orthologs/some_snod/Results_Mar01_7/Orthogroups_UnassignedGenes.csv
2018-03-01 18:27:33 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2018-03-01 18:30:12 : Done

Inferring gene and species trees
--------------------------------
2018-03-01 18:30:12 : Done 0 of 2722
2018-03-01 18:30:21 : Done 1000 of 2722
2018-03-01 18:30:26 : Done 2000 of 2722

203 trees had all species present and will be used by STAG to infer the species tree


Best outgroup(s) for species tree
---------------------------------
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1549, in <module>
  File "orthofinder/orthofinder.py", line 1398, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 976, in OrthologuesWorkflow
  File "orthofinder/scripts/stride.py", line 504, in GetRoot
  File "multiprocessing/pool.py", line 250, in map
  File "multiprocessing/pool.py", line 554, in get
Exception
Failed to execute script orthofinder

**Comment by FloFlo93** [comment]
I got the same error today!

**Comment by davidemms** [comment]
Hi 

I believe the issue was from an unresolved species tree, the latest commit (f6e9d0b) should fix the it. Thanks for reporting it.

All the best
David
