### ISSUE TITLE
Error in GetOrthologues 

### ISSUE THREAD

**Issue by jeakeller** [davidemms/OrthoFinder#147]
Dear OrthoFinder developers,

I am using OrthoFinder 2.2.1 on few plant species (2 to 10 for testing) and I got the following error in run with more than 2 species (one run with 2 species worked): 

[mcl] cut <22> instances of overlap
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1549, in <module>
  File "orthofinder/orthofinder.py", line 1398, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 1085, in OrthologuesWorkflow
  File "orthofinder/scripts/orthologues.py", line 859, in ReconciliationAndOrthologues
  File "orthofinder/scripts/trees2ologs_of.py", line 562, in DoOrthologuesForOrthoFinder
  File "orthofinder/scripts/trees2ologs_of.py", line 296, in GetOrthologues_for_tree
  File "orthofinder/scripts/trees2ologs_of.py", line 471, in Resolve
  File "orthofinder/scripts/resolve.py", line 229, in resolve
ValueError: too many values to unpack
Failed to execute script orthofinder

I am working on a SGE cluster with the following parameter for OrthoFinder: -S diamond -M msa -t 12

Do you know what could cause this error ?

Thank you in advance,

Jean

**Comment by davidemms** [comment]
Hi Jean

Just to keep you updated, I've identified the cause of the error and will work on a fix tomorrow. It's caused by an incorrect assumption that in a certain situation a node in the gene tree will be binary, which in general will not always be the case. It should be relatively straight-forward to resolve.

All the best
David

**Comment by jeakeller** [comment]
Hi Pr Emms,

Thank you for the quick fix ! 

Jean
