### ISSUE TITLE
Orthofinder algorithm with Diamond: malformatted line in

### ISSUE THREAD

**Issue by rafaeltiveron** [davidemms/OrthoFinder#148]
I was starting comparison between two FAA files when I received this:

```
root@user-lubuntu:/mnt/hgfs/SharedFolders/Orthoanalysis/corridas_proteins/ORFs_ixodesricinus# orthofinder -f NCBI_X_ORFs_predictedbyORFFinder -S diamond -a 2

OrthoFinder version 2.2.1 Copyright (C) 2014 David Emms

16 thread(s) for highly parallel tasks (BLAST searches etc.)
2 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /mnt/hgfs/SharedFolders/Orthoanalysis/corridas_proteins/ORFs_ixodesricinus/NCBI_X_ORFs_predictedbyORFFinder/SimpleTest.phy -o /mnt/hgfs/SharedFolders/Orthoanalysis/corridas_proteins/ORFs_ixodesricinus/NCBI_X_ORFs_predictedbyORFFinder/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-03-29 15:57:50 : Creating diamond database 1 of 2
2018-03-29 15:59:15 : Creating diamond database 2 of 2

Running diamond all-versus-all
------------------------------
Using 16 thread(s)
2018-03-29 15:59:17 : This may take some time....

Running OrthoFinder algorithm
-----------------------------
2018-03-29 18:54:24 : Initial processing of each species
Malformatted line in /mnt/hgfs/SharedFolders/Orthoanalysis/corridas_proteins/ORFs_ixodesricinus/NCBI_X_ORFs_predictedbyORFFinder/Results_Mar29/WorkingDirectory/Blast1_0.txt
Offending line was:

Process Process-19:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
  File "orthofinder/scripts/blast_file_processor.py", line 63, in GetBLAST6Scores
Error: line contains NULL byte
Malformatted line in /mnt/hgfs/SharedFolders/Orthoanalysis/corridas_proteins/ORFs_ixodesricinus/NCBI_X_ORFs_predictedbyORFFinder/Results_Mar29/WorkingDirectory/Blast0_0.txt
Offending line was:

Process Process-18:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
  File "orthofinder/scripts/blast_file_processor.py", line 63, in GetBLAST6Scores
Error: line contains NULL byte
ERROR: An error occurred, please review error messages for more information.

```
I've investigated these two files and both are good formatted. What is happening?
* Diamond version 0.9.19

**Comment by rafaeltiveron** [comment]
I didn't recognize issue #43 before
