### ISSUE TITLE
Unable to reconcile gene and species trees with an user-provided species tree

### ISSUE THREAD

**Issue by albertoperezposada** [davidemms/OrthoFinder#150]
Hi David,

Thank you very much for your development and support of this tool. I am trying to run orthofinder using a user-provided species tree for reconciliation and everything goes fine until the reconciliation part, where I get the output you can find below. I have made sure I have the same species in my tree and in my proteome dataset.

This is the command I use for orthofinder:
`orthofinder -t 18 -T iqtree -s ../species_tree_reconcile.nwk -ft Results_Apr03_2/Orthologues_Apr03/
`

My orthofinder version is 2.1.2 .
My python version is 3.6.2 .

I am also attaching the textline of the nwk tree, just in case something is missing and I haven’t noticed:
`((((((((((((Hsap,Mmus),Cint),(Dmel,Cele)),Nvec),Aque),Sros),Cowc)),(Sarc4,Clim)),(((((((Ncra,Scer),Spom),Cneo),Mver),Rory),Falb))),Ddis),(((((  Atha,Smoe),(Crei,Vcar)),Ppur),((Esil,Tpse),Tthe)),Ngru));`

I hope I could provide everything that might be needed to solve it. If not, do not hesitate to ask for it. Thank you very much for everything,

Alberto

‘——————

```
Reconciling gene and species trees
—————————————————
2018-04-04 09:54:18 : Done 0 of 12105
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1581, in <module>
  File "orthofinder/orthofinder.py", line 1404, in GetOrthologues_FromTrees
  File "orthofinder/scripts/orthologues.py", line 847, in OrthologuesFromTrees
  File "orthofinder/scripts/orthologues.py", line 792, in ReconciliationAndOrthologues
  File "orthofinder/scripts/trees2ologs_of.py", line 387, in DoOrthologuesForOrthoFinder
  File "orthofinder/scripts/trees2ologs_of.py", line 220, in GetOrthologues_for_tree
  File "orthofinder/scripts/trees2ologs_of.py", line 198, in GetRoot
  File "orthofinder/scripts/trees2ologs_of.py", line 95, in GetRoots
ValueError: need more than 1 value to unpack
Failed to execute script orthofinder
```

**Comment by davidemms** [comment]
Hi Alberto

I'm glad you're finding OrthoFinder useful. I think this is related to the tree library that OrthoFinder users to read the newick file combined with a 'sort of' problem in the species tree you've provided. There are duplicate pairs of brackets in a couple of places shown in bold here:

((((( **((** (((((Hsap,Mmus),Cint),(Dmel,Cele)),Nvec),Aque),Sros),Cowc **))** ,(Sarc4,Clim)), **((** (((((Ncra,Scer),Spom),Cneo),Mver),Rory),Falb **))** ),Ddis),((((( Atha,Smoe),(Crei,Vcar)),Ppur),((Esil,Tpse),Tthe)),Ngru));

I think this version should work:

(((((((((((Hsap,Mmus),Cint),(Dmel,Cele)),Nvec),Aque),Sros),Cowc),(Sarc4,Clim)),((((((Ncra,Scer),Spom),Cneo),Mver),Rory),Falb)),Ddis),((((( Atha,Smoe),(Crei,Vcar)),Ppur),((Esil,Tpse),Tthe)),Ngru));
 
Let me know if this resolves the issue. If it does then I'll add some code to resolve this problem automatically in future versions.

Thanks
David

**Comment by albertoperezposada** [comment]
Hi David,

Thank you for the quick response! Indeed, your suggestion solves the issue. It seems the problem was due to these duplicate brackets that were left after some manual adjusting on the tree file. I was able to run OrthoFinder properly, thank you very much!

Best,
Alberto
