### ISSUE TITLE
All vs All stopped (?) and Orthofinder cannot find the wanted files

### ISSUE THREAD

**Issue by setarehi** [davidemms/OrthoFinder#157]
Hi, 

I have succesfully run Orthofinder. But when I used it on a large dataset of 40 species it stopped. 

I got the following output:

#####
Running BLAST all-versus-all
----------------------------
Using 30 thread(s)
2018-04-06 11:04:27 : This may take some time....
2018-04-06 11:04:27 : Done 0 of 1600
2018-04-09 12:00:32 : Done 100 of 1600
2018-04-10 14:50:33 : Done 200 of 1600
2018-04-11 10:33:17 : Done 300 of 1600
2018-04-12 14:36:55 : Done 400 of 1600
2018-04-13 15:21:51 : Done 500 of 1600
2018-04-14 06:20:35 : Done 600 of 1600
2018-04-14 20:45:56 : Done 700 of 1600
2018-04-15 11:16:23 : Done 800 of 1600
2018-04-16 05:44:29 : Done 900 of 1600
2018-04-16 22:12:58 : Done 1000 of 1600
2018-04-17 14:22:55 : Done 1100 of 1600
2018-04-18 03:25:31 : Done 1200 of 1600
2018-04-18 16:55:10 : Done 1300 of 1600
2018-04-19 04:13:54 : Done 1400 of 1600
2018-04-19 15:05:25 : Done 1500 of 1600

Running OrthoFinder algorithm
-----------------------------
2018-04-20 00:20:03 : Initial processing of each species
Malformatted line in /home/biosys3/Users/Setareh/OrthFinderPrograms/OrthoFinder-2.2.1/Sequences/Results_Apr06/WorkingDirectory/Blast0_0.txt
Offending line was:

Process Process-32:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
  File "orthofinder/scripts/blast_file_processor.py", line 61, in GetBLAST6Scores
IOError: [Errno 2] No such file or directory: '/home/biosys3/Users/Setareh/OrthFinderPrograms/OrthoFinder-2.2.1/Sequences/Results_Apr06/WorkingDirectory/Blast0_0.txt'
ERROR: An error occurred, please review error messages for more information.
###

However when I try to run it with the -b option it outputs ~100 BlastX_X.txt files that it cannot find. Is there a way to run just these final 100 All vs All blasts?

My best,
Setareh

**Comment by davidemms** [comment]
Hi Setareh

I'd be interested to know if the Blast files weren't created because of OrthoFinder or because of something that happened on your server that stopped them being produced? If there was a problem in OrthoFinder then it needs to be fixed. However, this code has been in OrthoFinder for a long time and hundreds of people have run it without reporting any problems so I wondered whether the cause might have been something else? If not, then I'd like to track down what needs fixing.

Thanks for your help
David

**Comment by setarehi** [comment]
Hi David,

Sorry for responding so late. I think that the files were not created
because of a lack of space on our devices. So we are dealing with that now
(multiple users, not that much space) before I can give it another go. I do
think that that should solve the problem. I will let you know ptherwise.
Thank you for all your help.

Cheerio,
Setareh
