### ISSUE TITLE
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.

### ISSUE THREAD

**Issue by CelinePB** [davidemms/OrthoFinder#159]
Dear David, 

I am trying to run Orthofinder, and I had several failed and it seems that this is the same error several time: (see slurm file attached too).

Would you be able to help me?
Thank you.
Celine

Lines 1820/1828 of the slurm outfile:
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1565, in <module>
  File "orthofinder/orthofinder.py", line 1396, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 950, in OrthologuesWorkflow
  File "orthofinder/scripts/stride.py", line 496, in GetRoot
  File "orthofinder/scripts/tree.py", line 180, in __init__
  File "orthofinder/scripts/newick.py", line 231, in read_newick
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
Failed to execute script orthofinder

**Comment by stubbsrl** [comment]
Hi - Just a heads up this same issue is already open [(#151)](https://github.com/davidemms/OrthoFinder/issues/151). Subscribe to that thread. It appears this issue is being encountered by multiple people.

Best,
Rebecca

**Comment by CelinePB** [comment]
Thank Rebecca, 
I have seen this issue, but it is not exactly the same error message, so I created a new one.
I will check the things David asked in the #151 nonetheless! :)

**Comment by davidemms** [comment]
Hi Celine

I think this is probably as issue that has been corrected in version 2.2.0 onwards (commit: https://github.com/davidemms/OrthoFinder/commit/f58c40e1a741afd47c4dcd084462212f8cc77253), basically the code read the species tree expecting it to be a certain format, which wasn't always the case. You can check what version is being used at the top of the OrthoFinder output in your slurm file. If it's an older version, could you try with the [latest OrthoFinder release](https://github.com/davidemms/OrthoFinder/releases/tag/v2.2.3). You can use the '-fg' option to restart from the already calculated orthogroups rather than having to start at the beginning of the analysis. E.g.

`orthofinder -fg ExampleDirectory/Results_Apr24`

Al the best
David

**Comment by CelinePB** [comment]
Dear David, 
Thank you very much for your answer.
In fact, when dealing with this problems, we realised that we didn't had the latest version, so we updated it, and we just got exactly the same error. 
I should also precise that we have been using Orthofinder on other datasets on the same cluster, and that it did worked fine. 
This dataset is pretty huge in term of quantity of data per genome too.

Do you think I should check the propositions explained in the issue #151 ?
Thank you again!
All the best, 
Celine

**Comment by jananiharan** [comment]
Hi David, 

I have the same issue, here is my traceback:

```
Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
/tmp/_MEIBukks1/numpy/core/fromnumeric.py:2374: RuntimeWarning: invalid value encountered in double_scalars
2019-02-19 16:39:07 : Done 0 of 25
2019-02-19 16:40:44 : Done 10 of 25
2019-02-19 16:40:44 : Done 20 of 25
2019-02-19 16:39:05 : Done
Using fallback species tree inference method

Inferring gene and species trees
--------------------------------
A duplicate accession was found using just first part: Scaffold_1_1
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

Best outgroup(s) for species tree
---------------------------------
2019-02-19 16:40:45 : Starting STRIDE
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1620, in <module>
  File "orthofinder/orthofinder.py", line 1429, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 1097, in OrthologuesWorkflow
  File "orthofinder/scripts/stride.py", line 502, in GetRoot
  File "orthofinder/scripts/tree.py", line 217, in __init__
  File "orthofinder/scripts/newick.py", line 212, in read_newick
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
Failed to execute script orthofinder
```

These are the contents of /home/janani/2_5_9_14T/Results_Feb16/WorkingDirectory/Orthologues_Feb17/WorkingDirectory:

Distances
SpeciesTree_ids.txt
Trees_ids

SpeciesTree_ids.txt is empty, but the two directories have files in them. 

Could you help with this? Thanks in advance!

**Comment by davidemms** [comment]
Hi Janani

Sorry, I must have missed this issue when you posted it. Would you be able to send me the input files that you used and the OrthoFinder command and I will take a look. My email address is in the comments at the start of each of the python files: https://github.com/davidemms/OrthoFinder/blob/master/orthofinder/orthofinder.py

All the best
David

**Comment by jananiharan** [comment]
Hi David, 

This issue has been resolved through our email correspondence. Thanks for checking in!

Janani

**Comment by davidemms** [comment]
Hi Janani

Yes, of course, I'd forgotten! Thanks

David

**Comment by shrhops** [comment]
Hi @davidemms, I've run into the exact same issue with version 2.5.4. I also had one successful run, but this specific run has resulted in this error consistently. The full output is as follows: 

> 2022-01-24 13:56:07 : Starting OrthoFinder 2.5.4
28 thread(s) for highly parallel tasks (BLAST searches etc.)
3 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /home/ubuntu/NAS/orthofinder_try/primary_transcripts/OrthoFinder/Results_Jan24/WorkingDirectory/SimpleTest.phy -o /home/ubuntu/NAS/orthofinder_tr   y/primary_transcripts/OrthoFinder/Results_Jan24/WorkingDirectory/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2022-01-24 13:59:00 : Creating diamond database 1 of 4
2022-01-24 13:59:01 : Creating diamond database 2 of 4
2022-01-24 13:59:01 : Creating diamond database 3 of 4
2022-01-24 13:59:02 : Creating diamond database 4 of 4

Running diamond all-versus-all
------------------------------
Using 28 thread(s)
2022-01-24 13:59:04 : This may take some time....
2022-01-24 14:11:03 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2022-01-24 14:11:55 : Initial processing of each species
WARNING: Too few hits between species 2 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 1 and species 2 to normalise the scores, these hits will be ignored
2022-01-24 14:11:58 : Initial processing of species 2 complete
2022-01-24 14:11:58 : Initial processing of species 1 complete
2022-01-24 14:11:58 : Initial processing of species 0 complete
2022-01-24 14:13:11 : Initial processing of species 3 complete
2022-01-24 14:13:44 : Connected putative homologues
2022-01-24 14:13:45 : Written final scores for species 0 to graph file
2022-01-24 14:13:45 : Written final scores for species 2 to graph file
2022-01-24 14:13:45 : Written final scores for species 1 to graph file
2022-01-24 14:14:36 : Written final scores for species 3 to graph file
2022-01-24 14:15:07 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 45450 genes (94.1% of total) to 6093 orthogroups. Fifty percent of all genes were in orthogroups with 11 or more genes (G50 was 11) and were contained in the largest 1011 orthogroups (O50 was 1011). There were 0 orthogroups with all species present and 0 of these consisted entirely of single-copy genes.

2022-01-24 14:39:08 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2022-01-24 14:48:56 : Done
Using fallback species tree inference method
/tmp/_MEID730lK/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
/tmp/_MEID730lK/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars

Inferring gene and species trees
--------------------------------
2022-01-24 14:48:57 : Done 0 of 3446
2022-01-24 14:49:18 : Done 1000 of 3446
2022-01-24 14:49:38 : Done 2000 of 3446
2022-01-24 14:50:01 : Done 3000 of 3446

Best outgroup(s) for species tree
---------------------------------
2022-01-24 14:50:13 : Starting STRIDE
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1778, in main
  File "scripts_of/__main__.py", line 1558, in GetOrthologues
  File "scripts_of/orthologues.py", line 1039, in OrthologuesWorkflow
  File "scripts_of/stride.py", line 509, in GetRoot
  File "scripts_of/tree.py", line 221, in __init__
  File "scripts_of/newick.py", line 216, in read_newick
scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
[4059637] Failed to execute script orthofinder

There are 3 subdirectories under WorkingDirectory: 
Distances/  
Trees_ids/  
pickle/

but I don't see an Orthologues directory for this set of results. Could you please help? 
Thanks!

**Comment by RNieuwenhuis** [comment]
I run into exactly the same issue as @shrhops. Any updates?

**Comment by SuPrSh** [comment]
Any update on the following error. I am also getting the same error. No output file generated in gene tree, orthologues and single copy orthologous directory using test data available at https://davidemms.github.io/orthofinder_tutorials/running-an-example-orthofinder-analysis.html.

The detailed error is attached below:

[nohup.out.txt](https://github.com/davidemms/OrthoFinder/files/8348801/nohup.out.txt)

Thanks!

**Comment by shangguandong1996** [comment]
I also meet the same issue with @SuPrSh 

The data is same as tutorial data. But I just download this pep fa today.

```bash
OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms

2022-05-06 10:57:38 : Starting OrthoFinder 2.5.4
192 thread(s) for highly parallel tasks (BLAST searches etc.)
16 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/SimpleTest.phy -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2022-05-06 10:57:39 : Creating diamond database 1 of 6
2022-05-06 10:57:40 : Creating diamond database 2 of 6
2022-05-06 10:57:40 : Creating diamond database 3 of 6
2022-05-06 10:57:40 : Creating diamond database 4 of 6
2022-05-06 10:57:40 : Creating diamond database 5 of 6
2022-05-06 10:57:40 : Creating diamond database 6 of 6

Running diamond all-versus-all
------------------------------
Using 192 thread(s)
2022-05-06 10:57:40 : This may take some time....

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies0 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species3.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast3_0.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies0 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species2.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast2_0.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies2 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species3.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast3_2.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies2 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species2.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast2_2.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies3 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species2.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast2_3.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies4 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species2.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast2_4.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies3 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species3.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast3_3.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies5 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species2.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast2_5.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies4 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species3.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast3_4.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies5 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species3.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast3_5.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies1 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species2.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast2_1.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/diamondDBSpecies1 -q /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Species3.fa -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/Blast3_1.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.\n'
2022-05-06 11:06:06 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2022-05-06 11:06:06 : Initial processing of each species
WARNING: Too few hits between species 2 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 3 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 3 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 4 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 4 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 5 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 5 to normalise the scores, these hits will be ignored
2022-05-06 11:06:09 : Initial processing of species 3 complete
2022-05-06 11:06:09 : Initial processing of species 2 complete
2022-05-06 11:06:14 : Initial processing of species 1 complete
2022-05-06 11:06:20 : Initial processing of species 5 complete
2022-05-06 11:06:21 : Initial processing of species 4 complete
2022-05-06 11:06:30 : Initial processing of species 0 complete
2022-05-06 11:06:34 : Connected putative homologues
2022-05-06 11:06:36 : Written final scores for species 1 to graph file
2022-05-06 11:06:37 : Written final scores for species 3 to graph file
2022-05-06 11:06:37 : Written final scores for species 2 to graph file
2022-05-06 11:06:37 : Written final scores for species 5 to graph file
2022-05-06 11:06:37 : Written final scores for species 4 to graph file
2022-05-06 11:06:38 : Written final scores for species 0 to graph file

WARNING: program called by OrthoFinder produced output to stderr

Command: mcl /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/OrthoFinder_graph.txt -I 1.5 -o /data5/sgd_data/newProject/test/test_OrthoFinder/proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/clusters_OrthoFinder_I1.5.txt -te 16 -V all

stdout
------
b''
stderr
------
b'[mcl] cut <2770> instances of overlap\n'
2022-05-06 11:06:57 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 89309 genes (67.8% of total) to 18890 orthogroups. Fifty percent of all genes were in orthogroups with 4 or more genes (G50 was 4) and were contained in the largest 10300 orthogroups (O50 was 10300). There were 0 orthogroups with all species present and 0 of these consisted entirely of single-copy genes.

2022-05-06 11:07:31 : Done orthogroups
Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2022-05-06 11:08:02 : Done
Using fallback species tree inference method
/home/sgd/miniconda3/envs/env_OrthoFinder/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/sgd/miniconda3/envs/env_OrthoFinder/lib/python3.10/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

Inferring gene and species trees
--------------------------------
2022-05-06 11:08:04 : Done 0 of 11975
2022-05-06 11:08:04 : Done 1000 of 11975
2022-05-06 11:08:05 : Done 2000 of 11975
2022-05-06 11:08:05 : Done 3000 of 11975
2022-05-06 11:08:05 : Done 4000 of 11975
2022-05-06 11:08:06 : Done 5000 of 11975
2022-05-06 11:08:06 : Done 6000 of 11975
2022-05-06 11:08:06 : Done 7000 of 11975
2022-05-06 11:08:07 : Done 8000 of 11975
2022-05-06 11:08:07 : Done 9000 of 11975
2022-05-06 11:08:08 : Done 10000 of 11975
2022-05-06 11:08:08 : Done 11000 of 11975

Best outgroup(s) for species tree
---------------------------------
2022-05-06 11:08:09 : Starting STRIDE
Traceback (most recent call last):
  File "/home/sgd/miniconda3/envs/env_OrthoFinder/bin/scripts_of/stride.py", line 506, in GetRoot
    speciesTree = tree.Tree(speciesTreeFN, format=2)
  File "/home/sgd/miniconda3/envs/env_OrthoFinder/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/sgd/miniconda3/envs/env_OrthoFinder/bin/scripts_of/newick.py", line 216, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sgd/miniconda3/envs/env_OrthoFinder/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/sgd/miniconda3/envs/env_OrthoFinder/bin/scripts_of/__main__.py", line 1778, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/sgd/miniconda3/envs/env_OrthoFinder/bin/scripts_of/__main__.py", line 1540, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
  File "/home/sgd/miniconda3/envs/env_OrthoFinder/bin/scripts_of/orthologues.py", line 1039, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
  File "/home/sgd/miniconda3/envs/env_OrthoFinder/bin/scripts_of/stride.py", line 509, in GetRoot
    speciesTree = tree.Tree(speciesTreeFN, format=1)
  File "/home/sgd/miniconda3/envs/env_OrthoFinder/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/sgd/miniconda3/envs/env_OrthoFinder/bin/scripts_of/newick.py", line 216, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
```
