### ISSUE TITLE
Error on space while there is enough space?

### ISSUE THREAD

**Issue by setarehi** [davidemms/OrthoFinder#168]
Hi,

I have an issue with the last steps of orthofinder. Everything runs fine until the finding the orthogroups step. I get an internal error about lack of space. But when I check the amount of space I have there is more than 600GB left. Could you please help me with this? The error is as follows:

Analysing Orthogroups
=====================
A duplicate accession was found using just first part: Alp215600
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1568, in <module>
  File "orthofinder/orthofinder.py", line 1398, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 974, in OrthologuesWorkflow
  File "orthofinder/scripts/trees_msa.py", line 322, in DoTrees
  File "orthofinder/scripts/trees_msa.py", line 282, in WriteFastaFiles
  File "orthofinder/scripts/trees_msa.py", line 71, in WriteSeqsToFasta_withNewAccessions
IOError: [Errno 28] No space left on device: '/media/biosys3/UNTITLED/OrthFinderPrograms/OrthoFinder-2.2.1/Sequences/Results_May02_1/WorkingDirectory/Orthologues_May23/Sequences/OG0032766.fa'
Failed to execute script orthofinder

Thank you very much in advance.

**Comment by davidemms** [comment]
HI

I'm afraid I can't help with that, I think you'll have to investigate your system. Perhaps where '/media' doesn't have any space left even though other areas on your system do have space? You can run the linux command 'df -h' to investigate this.

All the best
David
