### ISSUE TITLE
"No such file or directory" in blast_file_processor.py with v2.2.6

### ISSUE THREAD

**Issue by abretaud** [davidemms/OrthoFinder#170]
Hi,
OrthoFinder 2.2.6 is crashing with my dataset with the following output:

stderr:
```
Malformatted line in /somewhere.../data/Results_May29/WorkingDirectory/Blast0_5.txt
Offending line was:

Process Process-22:
Traceback (most recent call last):
  File "/local/miniconda3/envs/orthofinder-2.2.6/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/local/miniconda3/envs/orthofinder-2.2.6/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/local/miniconda3/envs/orthofinder-2.2.6/bin/orthofinder", line 484, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, qDoubleBlast=qDoubleBlast)
  File "/local/miniconda3/envs/orthofinder-2.2.6/bin/orthofinder", line 471, in ProcessBlastHits
    Bij = BlastFileProcessor.GetBLAST6Scores(seqsInfo, fileInfo, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
  File "/softs/local/miniconda3/envs/orthofinder-2.2.6/bin/scripts/blast_file_processor.py", line 61, in GetBLAST6Scores
    with (gzip.open(fn + ".gz", 'rb') if os.path.exists(fn + ".gz") else open(fn, 'rb')) as blastfile:
IOError: [Errno 2] No such file or directory: '/somewhere.../data/Results_May29/WorkingDirectory/Blast0_5.txt'

```

stdout:

```

OrthoFinder version 2.2.6 Copyright (C) 2014 David Emms

20 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /somewhere.../data/SimpleTest.phy -o /somewhere.../data/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-05-29 14:35:00 : Creating diamond database 1 of 12
2018-05-29 14:35:00 : Creating diamond database 2 of 12
2018-05-29 14:35:00 : Creating diamond database 3 of 12
2018-05-29 14:35:00 : Creating diamond database 4 of 12
2018-05-29 14:35:00 : Creating diamond database 5 of 12
2018-05-29 14:35:01 : Creating diamond database 6 of 12
2018-05-29 14:35:01 : Creating diamond database 7 of 12
2018-05-29 14:35:01 : Creating diamond database 8 of 12
2018-05-29 14:35:01 : Creating diamond database 9 of 12
2018-05-29 14:35:01 : Creating diamond database 10 of 12
2018-05-29 14:35:01 : Creating diamond database 11 of 12
2018-05-29 14:35:01 : Creating diamond database 12 of 12

Running diamond all-versus-all
------------------------------
Using 20 thread(s)
2018-05-29 14:35:01 : This may take some time....
2018-05-29 14:35:01 : Done 10 of 144
2018-05-29 14:36:27 : Done 90 of 144
2018-05-29 14:35:02 : Done 50 of 144
2018-05-29 14:38:00 : Done 120 of 144
2018-05-29 14:37:35 : Done 110 of 144
2018-05-29 14:35:02 : Done 70 of 144
2018-05-29 14:35:02 : Done 40 of 144
2018-05-29 14:35:02 : Done 60 of 144
2018-05-29 14:35:01 : Done 20 of 144
2018-05-29 14:35:01 : Done 0 of 144
2018-05-29 14:35:02 : Done 80 of 144
2018-05-29 14:37:06 : Done 100 of 144
2018-05-29 14:35:02 : Done 30 of 144

Running OrthoFinder algorithm
-----------------------------
2018-05-29 14:41:49 : Initial processing of each species
ERROR: An error occurred, please review error messages for more information.
```

And I run it like this (using the latest conda package from bioconda):

```
orthofinder -t 20 -S diamond -f data
```

Do you know what could be causing this problem? Is there a way to maybe get more logs from the blast process which seems to be failing to generate its results?

**Comment by abretaud** [comment]
The problem came from malformed input sequences. `diamond makedb` failed so the db didn't exist so diamond couldn't generate its result.
I had t manually run the makedb to find the error

**Comment by davidemms** [comment]
Hi 

Thanks for that, it's very useful to know. I'd been thinking about it and hadn't come up with any ideas of what the problem could be, so the update is very helpful. In this case it would likely be better if OrthoFinder output any messages from diamond as this would make it easier for the user to diagnose.

All the best
David
