### ISSUE TITLE
Orthofinder dies while calculating gene distances

### ISSUE THREAD

**Issue by jmwhelpley** [davidemms/OrthoFinder#172]
Hi! 
I'm using Orthofinder (v2.2.3) on 41 transcriptomes and when I run the command `orthofinder -b /[pathwaytodirectory]/Results_May09/WorkingDirectory -t 150 -a 225 > ofb.out 2> ofb.err &` Orthofinder doesn't complete and I receive the following error message:

`[mcl] cut <350> instances of overlap`

I was wondering if you could possibly help in resolving this? Here is my output file: 

```
OrthoFinder version 2.2.3 Copyright (C) 2014 David Emms

42 thread(s) for highly parallel tasks (BLAST searches etc.)
700 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/Results_May09/WorkingDirectory/SimpleTest.phy -o /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/Results_May09/WorkingDirectory/SimpleTest.tre" - ok
Using previously calculated BLAST results in /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/Results_May09/WorkingDirectory/

Running OrthoFinder algorithm
-----------------------------
2018-05-18 12:27:52 : Initial processing of each species
2018-05-18 12:53:22 : Initial processing of species 12 complete
2018-05-18 12:54:12 : Initial processing of species 18 complete
2018-05-18 12:54:12 : Initial processing of species 26 complete
2018-05-18 12:54:26 : Initial processing of species 31 complete
2018-05-18 12:55:14 : Initial processing of species 8 complete
2018-05-18 12:55:14 : Initial processing of species 30 complete
2018-05-18 12:55:14 : Initial processing of species 14 complete
2018-05-18 12:55:23 : Initial processing of species 13 complete
2018-05-18 12:55:41 : Initial processing of species 23 complete
2018-05-18 12:55:44 : Initial processing of species 39 complete
2018-05-18 12:56:25 : Initial processing of species 7 complete
2018-05-18 12:56:27 : Initial processing of species 33 complete
2018-05-18 12:56:39 : Initial processing of species 34 complete
2018-05-18 12:56:48 : Initial processing of species 35 complete
2018-05-18 12:56:49 : Initial processing of species 20 complete
2018-05-18 12:56:53 : Initial processing of species 16 complete
2018-05-18 12:56:53 : Initial processing of species 3 complete
2018-05-18 12:56:55 : Initial processing of species 37 complete
2018-05-18 12:57:03 : Initial processing of species 5 complete
2018-05-18 12:57:07 : Initial processing of species 22 complete
2018-05-18 12:57:20 : Initial processing of species 29 complete
2018-05-18 12:57:29 : Initial processing of species 25 complete
2018-05-18 12:57:29 : Initial processing of species 10 complete
2018-05-18 12:57:38 : Initial processing of species 0 complete
2018-05-18 12:57:42 : Initial processing of species 24 complete
2018-05-18 12:57:52 : Initial processing of species 28 complete
2018-05-18 12:57:55 : Initial processing of species 4 complete
2018-05-18 12:58:50 : Initial processing of species 11 complete
2018-05-18 12:59:12 : Initial processing of species 36 complete
2018-05-18 12:59:31 : Initial processing of species 27 complete
2018-05-18 12:59:50 : Initial processing of species 1 complete
2018-05-18 12:59:57 : Initial processing of species 17 complete
2018-05-18 13:02:06 : Initial processing of species 15 complete
2018-05-18 13:02:21 : Initial processing of species 38 complete
2018-05-18 13:03:34 : Initial processing of species 40 complete
2018-05-18 13:04:08 : Initial processing of species 19 complete
2018-05-18 13:05:56 : Initial processing of species 6 complete
2018-05-18 13:06:30 : Initial processing of species 2 complete
2018-05-18 13:10:33 : Initial processing of species 21 complete
2018-05-18 13:10:39 : Initial processing of species 9 complete
2018-05-18 13:26:07 : Initial processing of species 32 complete
2018-05-18 13:30:39 : Connected putatitive homologs
2018-05-18 16:25:03 : Ran MCL

Writing orthogroups to file
---------------------------
A duplicate accession was found using just first part: Scle_bria.00004_2
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

Orthogroups have been written to tab-delimited files:
   /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/Results_May09/WorkingDirectory/Orthogroups_1.csv
   /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/Results_May09/WorkingDirectory/Orthogroups_1.txt (OrthoMCL format)
   /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/Results_May09/WorkingDirectory/Orthogroups_1_UnassignedGenes.csv
2018-05-18 16:26:39 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2018-05-18 17:47:45 : Done 3000 of 48817
2018-05-18 17:48:45 : Done 29000 of 48817
2018-05-18 17:48:42 : Done 27000 of 48817
2018-05-18 17:49:21 : Done 47000 of 48817
2018-05-18 17:48:31 : Done 20000 of 48817
2018-05-18 17:48:39 : Done 25000 of 48817
2018-05-18 17:48:17 : Done 12000 of 48817
2018-05-18 17:48:49 : Done 32000 of 48817
2018-05-18 17:47:23 : Done 1000 of 48817
2018-05-18 17:48:19 : Done 13000 of 48817
2018-05-18 17:49:02 : Done 40000 of 48817
2018-05-18 17:48:15 : Done 11000 of 48817
2018-05-18 17:48:29 : Done 19000 of 48817
2018-05-18 17:49:01 : Done 39000 of 48817
2018-05-18 17:48:22 : Done 15000 of 48817
2018-05-18 17:48:24 : Done 16000 of 48817
2018-05-18 17:48:36 : Done 23000 of 48817
2018-05-18 17:47:54 : Done 5000 of 48817
2018-05-18 17:48:05 : Done 8000 of 48817
2018-05-18 17:48:59 : Done 38000 of 48817
2018-05-18 17:48:33 : Done 21000 of 48817
2018-05-18 17:48:58 : Done 37000 of 48817
2018-05-18 17:49:20 : Done 46000 of 48817
2018-05-18 17:49:16 : Done 44000 of 48817
2018-05-18 17:48:56 : Done 36000 of 48817
2018-05-18 17:49:10 : Done 42000 of 48817
2018-05-18 17:47:58 : Done 6000 of 48817
2018-05-18 17:48:48 : Done 31000 of 48817
2018-05-18 17:48:34 : Done 22000 of 48817
2018-05-18 17:48:09 : Done 9000 of 48817
2018-05-18 17:48:20 : Done 14000 of 48817
2018-05-18 17:48:12 : Done 10000 of 48817
2018-05-18 17:49:13 : Done 43000 of 48817
2018-05-18 17:49:18 : Done 45000 of 48817
2018-05-18 17:49:07 : Done 41000 of 48817
2018-05-18 17:48:43 : Done 28000 of 48817
2018-05-18 17:48:46 : Done 30000 of 48817
2018-05-18 17:47:38 : Done 2000 of 48817
2018-05-18 17:47:50 : Done 4000 of 48817
2018-05-18 17:48:51 : Done 33000 of 48817
2018-05-18 17:49:23 : Done 48000 of 48817
2018-05-18 17:48:37 : Done 24000 of 48817
2018-05-18 17:48:02 : Done 7000 of 48817
2018-05-18 17:48:53 : Done 34000 of 48817
2018-05-18 17:46:04 : Done 0 of 48817
2018-05-18 17:48:54 : Done 35000 of 48817
2018-05-18 17:48:28 : Done 18000 of 48817
2018-05-18 17:48:26 : Done 17000 of 48817
2018-05-18 17:48:40 : Done 26000 of 48817
```

Thank you for your time!

**Comment by davidemms** [comment]
Hi

Were there any other messages after that? It looks likely that the out of memory killer is killing the parallel processes and this is the most likely cause of the failure. Do you know how much RAM each core has and how many nodes/cores you have? 

If you upgrade to the latest version, this will detect if and processes are killed by the OOM killer and print messages to the console to tell you. In combination with this, you should be able to reduce the RAM requirements by reducing '-a 225' (the number of parallel threads for algorithm steps). As the maximum number of parallel tasks it 41 (the number of species) I would try something like 20 and see if this is successful. Let me know how you get on.

All the best
David

**Comment by jmwhelpley** [comment]
Thanks for your response! On that server I was using I had 256Gb of RAM and 176 cores. I adjusted the command based on your recommendation and set -a to 20 and downloaded the newest version of orthofinder. Unfortunately, it died again with the same error` [mcl] cut <350> instances of overlap` before it began calculating the gene distances. 

`OrthoFinder version 2.2.6 Copyright (C) 2014 David Emms

45 thread(s) for highly parallel tasks (BLAST searches etc.)
20 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/01-OLD/Results_May09/WorkingDirectory/SimpleTest.phy -o /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/01-OLD/Results_May09/WorkingDirectory/SimpleTest.tre" - ok
Using previously calculated BLAST results in /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/01-OLD/Results_May09/WorkingDirectory/

Running OrthoFinder algorithm
-----------------------------
2018-06-06 19:09:03 : Initial processing of each species
2018-06-06 19:37:12 : Initial processing of species 6 complete
2018-06-06 19:37:44 : Initial processing of species 2 complete
2018-06-06 19:28:39 : Initial processing of species 1 complete
2018-06-06 19:39:25 : Initial processing of species 33 complete
2018-06-06 19:14:56 : Initial processing of species 14 complete
2018-06-06 19:40:57 : Initial processing of species 19 complete
2018-06-06 19:27:13 : Initial processing of species 11 complete
2018-06-06 19:41:20 : Initial processing of species 29 complete
2018-06-06 19:11:32 : Initial processing of species 12 complete
2018-06-06 19:31:25 : Initial processing of species 17 complete
2018-06-06 19:42:12 : Initial processing of species 34 complete
2018-06-06 19:25:50 : Initial processing of species 4 complete
2018-06-06 19:43:03 : Initial processing of species 28 complete
2018-06-06 19:19:45 : Initial processing of species 5 complete
2018-06-06 19:27:52 : Initial processing of species 23 complete
2018-06-06 19:36:18 : Initial processing of species 30 complete
2018-06-06 19:43:12 : Initial processing of species 39 complete
2018-06-06 19:24:54 : Initial processing of species 10 complete
2018-06-06 19:43:32 : Initial processing of species 27 complete
2018-06-06 19:14:46 : Initial processing of species 8 complete
2018-06-06 19:18:49 : Initial processing of species 18 complete
2018-06-06 19:31:45 : Initial processing of species 22 complete
2018-06-06 19:44:40 : Initial processing of species 35 complete
2018-06-06 19:45:09 : Initial processing of species 9 complete
2018-06-06 19:16:35 : Initial processing of species 13 complete
2018-06-06 19:28:08 : Initial processing of species 20 complete
2018-06-06 19:34:10 : Initial processing of species 31 complete
2018-06-06 19:45:27 : Initial processing of species 37 complete
2018-06-06 19:33:16 : Initial processing of species 15 complete
2018-06-06 19:51:34 : Initial processing of species 36 complete
2018-06-06 19:18:31 : Initial processing of species 7 complete
2018-06-06 19:52:53 : Initial processing of species 21 complete
2018-06-06 19:22:29 : Initial processing of species 0 complete
2018-06-06 19:36:06 : Initial processing of species 25 complete
2018-06-06 19:59:24 : Initial processing of species 38 complete
2018-06-06 19:20:24 : Initial processing of species 16 complete
2018-06-06 19:36:29 : Initial processing of species 24 complete
2018-06-06 19:59:46 : Initial processing of species 40 complete
2018-06-06 19:22:57 : Initial processing of species 3 complete
2018-06-06 19:28:21 : Initial processing of species 26 complete
2018-06-06 20:17:52 : Initial processing of species 32 complete
2018-06-06 20:23:12 : Connected putatitive homologs
2018-06-06 22:43:09 : Ran MCL

Writing orthogroups to file
---------------------------
A duplicate accession was found using just first part: Scle_bria.00004_2
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

Orthogroups have been written to tab-delimited files:
   /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/01-OLD/Results_May09/WorkingDirectory/Orthogroups_1.csv
   /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/01-OLD/Results_May09/WorkingDirectory/Orthogroups_1.txt (OrthoMCL format)
   /bwdata1/jessie/01-SEACUCUMBER/04-AIFILTERED/01-OLD/Results_May09/WorkingDirectory/Orthogroups_1_UnassignedGenes.csv
2018-06-06 22:44:36 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------`

I was wondering if the duplicate accession could be a possible issue?

**Comment by zhaotao1987** [comment]
Hi David,

Sorry to bother you. I got a similar problem like this: 
=========================================
OrthoFinder version 2.3.1 Copyright (C) 2014 David Emms

2019-05-15 00:20:02 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Using previously calculated BLAST results in /ngsprojects/synnet/data_archive/Project_Trial/Arthur_trial/fix_blastfiles/fixed/

Running OrthoFinder algorithm
-----------------------------
2019-05-15 00:20:09 : Initial processing of each species
2019-05-15 00:21:06 : Initial processing of species 0 complete
2019-05-15 00:22:51 : Initial processing of species 1 complete
2019-05-15 00:23:40 : Initial processing of species 2 complete
2019-05-15 00:24:29 : Initial processing of species 3 complete
2019-05-15 00:25:30 : Initial processing of species 4 complete
2019-05-15 00:26:56 : Initial processing of species 5 complete
2019-05-15 00:27:53 : Initial processing of species 6 complete
2019-05-15 00:28:50 : Initial processing of species 7 complete
2019-05-15 00:29:34 : Initial processing of species 8 complete
2019-05-15 00:30:24 : Initial processing of species 9 complete
2019-05-15 00:31:51 : Connected putatitive homologs
2019-05-15 00:32:10 : Written final scores for species 0 to graph file
2019-05-15 00:32:45 : Written final scores for species 1 to graph file
2019-05-15 00:32:58 : Written final scores for species 2 to graph file
2019-05-15 00:33:14 : Written final scores for species 3 to graph file
2019-05-15 00:33:36 : Written final scores for species 4 to graph file
2019-05-15 00:34:09 : Written final scores for species 5 to graph file
2019-05-15 00:34:25 : Written final scores for species 6 to graph file
2019-05-15 00:34:45 : Written final scores for species 7 to graph file
2019-05-15 00:34:59 : Written final scores for species 8 to graph file
2019-05-15 00:35:18 : Written final scores for species 9 to graph file
**[mcl] cut <74> instances of overlap**
2019-05-15 00:38:44 : Ran MCL

Writing orthogroups to file
---------------------------

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2015), Genome Biology 16:157

 If you use the species tree in your work then please also cite:
 Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
 Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101/267914
**Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1646, in <module>
  File "orthofinder/orthofinder.py", line 1307, in DoOrthogroups
  File "orthofinder/orthofinder.py", line 204, in WriteOrthogroupFiles
  File "orthofinder/scripts/util.py", line 378, in __init__
ValueError: need more than 1 value to unpack
Failed to execute script orthofinder**
==================================

**Comment by davidemms** [comment]
Hi Tao

This issue looks like it's unrelated to the issue in this thread so I've opened a new issue with your question and have answered it there: https://github.com/davidemms/OrthoFinder/issues/261

All the best
David
