### ISSUE TITLE
No such file or directory: '.../clusters_OrthoFinder_v2.2.6_I1.5_1.txt'

### ISSUE THREAD

**Issue by aussieEd** [davidemms/OrthoFinder#187]
Hi David,

I am having trouble completing an orthofinder run.

Below is the error message that is recieved. The error suggests that the file "clusters_OrthoFinder_v2.2.6_I1.5_1.txt" is not found, however, when I look at the directory the file is present, but it just doesn't seem to be detected.

Any idea one what to do next?

Thanks,
Ed.

````
Traceback (most recent call last):
  File "./orthofinder.py", line 1593, in <module>
    clustersFilename_pairs, statsFile, summaryText, orthogroupsResultsFilesString = DoOrthogroups(options, dirs, seqsInfo, options.qDoubleBlast, options.separatePickleDir)    
  File "./orthofinder.py", line 1263, in DoOrthogroups
    MCLread.ConvertSingleIDsToIDPair(seqsInfo, clustersFilename, clustersFilename_pairs)   
  File "/mnt/orthofinder/scripts/mcl.py", line 76, in ConvertSingleIDsToIDPair
    with open(clustersFilename, 'rb') as clusterFile, open(newFilename, "wb") as output:
IOError: [Errno 2] No such file or directory: '/mnt/orthofinder/phyto/Results_Jul08/WorkingDirectory/clusters_OrthoFinder_v2.2.6_I1.5_1.txt'

````

**Comment by davidemms** [comment]
Hi Ed

I'm afraid I've not seen an issue like that before. I notice that it is under '/mnt', could it be that the location was unmounted when OrthoFinder was looking for it? Or some other filesystem issue? I'd be fairly confident that this isn't an OrthoFinder issue and that the file couldn't be accessed at the time. Have you tried running it again to see what happens this time? 

All the best 
David

**Comment by aussieEd** [comment]
Hi David,

As it happens, I have tried it a few times with pretty much the same result. I have even tried running orthofinder from the beginning to see if something strange happened in the diamond blast, but again the system halted when running MCL.

To try and work out what is happening I tried to follow your suggestion to another user "Sishuo", and ran the following command:

> $ mcl OrthoFinder_v2.2.6_graph.txt -I 1.5 -o clusters_OrthoFinder_v2.2.6_I1.5.txt -te 16

The command completed successfully and the output is provided below. Any thoughts on how I can recover from this and continue the orthofinder analysis??? At the very least I'd like to try and work out the orthogroups.

Thanks,
Ed.

[mclIO] reading <OrthoFinder_v2.2.6_graph.txt>
.......................................
[mclIO] read native interchange 6819611x6819611 matrix with 1053766185 entries
[mcl] pid 4752
 ite   chaos  time hom(avg,lo,hi) m-ie m-ex i-ex fmv
  1   310.29 20057.53 1.06/0.00/28.70 9.44 2.22 2.22   3
  2   348.09 55339.55 0.84/0.00/12.09 9.66 0.93 2.07  18
  3   349.42 41442.51 0.80/0.01/14.68 6.57 0.84 1.75  16
  4   343.59 25766.57 0.76/0.01/18.02 4.18 0.79 1.38  11
  5   258.14 12906.19 0.71/0.01/30.77 2.70 0.75 1.04   4
  6   203.43 5510.72 0.68/0.01/23.43 1.87 0.75 0.77   1
  7   182.73 2632.53 0.66/0.02/7.11 1.42 0.73 0.57   0
  8   143.93 1291.70 0.68/0.03/3.71 1.21 0.70 0.39   0
  9   124.60 678.66 0.72/0.06/2.35 1.11 0.64 0.25   0
 10    50.50 308.57 0.79/0.09/1.66 1.06 0.58 0.14   0
 11    31.13 126.62 0.85/0.09/2.29 1.03 0.54 0.08   0
 12    19.71 52.91 0.90/0.15/1.90 1.02 0.54 0.04   0
 13    10.84 27.47 0.93/0.13/1.54 1.01 0.57 0.02   0
 14     9.68 16.85 0.95/0.14/1.31 1.01 0.68 0.02   0
 15     6.49 12.40 0.97/0.16/1.69 1.00 0.78 0.01   0
 16     7.84 11.50 0.98/0.17/1.46 1.00 0.84 0.01   0
 17     5.73 10.65 0.99/0.08/1.20 1.00 0.90 0.01   0
 18     6.04 10.32 0.99/0.16/1.65 1.00 0.93 0.01   0
 19     6.20 10.17 0.99/0.18/1.19 1.00 0.96 0.01   0
 20     5.90 11.77 0.99/0.19/1.17 1.00 0.97 0.01   0
 21     5.39 10.38 1.00/0.29/1.18 1.00 0.98 0.01   0
 22     3.00  9.36 1.00/0.31/1.14 1.00 0.98 0.01   0
 23     2.58  9.36 1.00/0.24/1.17 1.00 0.99 0.01   0
 24     3.48  9.09 1.00/0.28/1.14 1.00 0.99 0.01   0
 25     3.37 12.39 1.00/0.18/1.00 1.00 0.99 0.01   0
 26     5.52  9.22 1.00/0.20/1.00 1.00 1.00 0.01   0
 27     5.08  9.21 1.00/0.30/1.00 1.00 1.00 0.01   0
 28     4.05  9.32 1.00/0.16/1.00 1.00 1.00 0.01   0
 29     5.96  8.85 1.00/0.26/1.00 1.00 1.00 0.01   0
 30     3.78  9.06 1.00/0.37/1.00 1.00 1.00 0.01   0
 31     1.96  8.85 1.00/0.35/1.00 1.00 1.00 0.01   0
 32     2.17  9.11 1.00/0.29/1.00 1.00 1.00 0.01   0
 33     2.46  8.52 1.00/0.36/1.00 1.00 1.00 0.01   0
 34     1.98  8.67 1.00/0.34/1.00 1.00 1.00 0.01   0
 35     1.77  9.70 1.00/0.35/1.00 1.00 1.00 0.01   0
 36     2.18 10.25 1.00/0.33/1.00 1.00 1.00 0.01   0
 37     1.94  9.13 1.00/0.54/1.00 1.00 1.00 0.01   0
 38     0.86  9.68 1.00/0.51/1.00 1.00 1.00 0.01   0
 39     1.00  9.18 1.00/0.49/1.00 1.00 1.00 0.01   0
 40     0.79  8.69 1.00/0.53/1.00 1.00 1.00 0.01   0
 41     0.70  8.93 1.00/0.64/1.00 1.00 1.00 0.01   0
 42     1.11 10.20 1.00/0.51/1.00 1.00 1.00 0.01   0
 43     1.70  8.87 1.00/0.33/1.00 1.00 1.00 0.01   0
 44     2.23  9.13 1.00/0.34/1.00 1.00 1.00 0.01   0
 45     1.79  9.69 1.00/0.56/1.00 1.00 1.00 0.01   0
 46     0.55  9.07 1.00/0.63/1.00 1.00 1.00 0.01   0
 47     0.47 10.25 1.00/0.66/1.00 1.00 1.00 0.01   0
 48     0.30  9.55 1.00/0.76/1.00 1.00 1.00 0.01   0
 49     0.20  9.05 1.00/0.81/1.00 1.00 1.00 0.01   0
 50     0.10  9.20 1.00/0.90/1.00 1.00 1.00 0.01   0
 51     0.03  9.26 1.00/0.97/1.00 1.00 1.00 0.01   0
 52     0.00  9.77 1.00/1.00/1.00 1.00 1.00 0.01   0
 53     0.00  9.57 1.00/1.00/1.00 1.00 1.00 0.01   0
[mcl] cut <10662> instances of overlap
[mcl] jury pruning marks: <37,60,75>, out of 100
[mcl] jury pruning synopsis: <47.5 or shabby> (cf -scheme, -do log)
[mclIO] writing <clusters_OrthoFinder_v2.2.6_I1.5.txt>
.......................................
[mclIO] wrote native interchange 6819611x2980044 matrix with 6819611 entries to stream <clusters_OrthoFinder_v2.2.6_I1.5.txt>
[mcl] 2980044 clusters found
[mcl] output is in clusters_OrthoFinder_v2.2.6_I1.5.txt

Please cite:
    Stijn van Dongen, Graph Clustering by Flow Simulation.  PhD thesis,
    University of Utrecht, May 2000.
       (  http://www.library.uu.nl/digiarchief/dip/diss/1895620/full.pdf
       or  http://micans.org/mcl/lit/svdthesis.pdf.gz)
OR
    Stijn van Dongen, A cluster algorithm for graphs. Technical
    Report INS-R0010, National Research Institute for Mathematics
    and Computer Science in the Netherlands, Amsterdam, May 2000.
       (  http://www.cwi.nl/ftp/CWIreports/INS/INS-R0010.ps.Z
       or  http://micans.org/mcl/lit/INS-R0010.ps.Z)

$

**Comment by davidemms** [comment]
Hi

Sorry for the delay it getting back to this. I can't think of any way of getting OrthoFinder to use an externally calculated MCL results file--there are too many other bits of data that it prepares in the earlier stages of the run that it would need access to. I think it would need to be able to run the MCL program successfully itself. I don't suppose you were able to work out any more about why MCL was having problems?

Thanks
David

**Comment by sunjiahe-hub** [comment]
@davidemms Can you tell me what the '... /WorkingDirectory/OrthoFinder_graph.txt' file means what? It looks like a score matrix, is it a score matrix between two two protein sequences? What I can confirm is that it is the input file for MCL clustering, what I am confused about is why the matrix is incomplete?

Looking forward to your reply, sincerely

**Comment by sunjiahe-hub** [comment]
Additional question： How can I convert "OrthoFinder_graph.txt" to "OrthoFinder_graph.abc" format? Is this feasible?
