### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by senaj** [davidemms/OrthoFinder#196]
Hi davidemms,

I attempted to run orthofinder twice but it fails with the following error messege

IOError: [Errno 2] No such file or directory: '/home/projects/redgillite/js_redgillite/griesmann_assemblies/peptide/Results_nfn_symbiosis_griesmann_Aug21/WorkingDirectory/Blast0_0.txt'

Please see below. 

I can confirm that the Blast0_0.txt file is not in /home/projects/redgillite/js_redgillite/griesmann_assemblies/peptide/Results_nfn_symbiosis_griesmann_Aug21/WorkingDirectory/

Do you know why this file would be missing?

Thanks for your help!

OrthoFinder version 2.2.6 Copyright (C) 2014 David Emms

8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /home/projects/redgillite/js_redgillite/griesmann_assemblies/peptide/SimpleTest.phy -o /home/projects/redgillite/js_redgillite/griesmann_assemblies/pep
tide/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-08-21 09:14:14 : Creating diamond database 1 of 25
2018-08-21 09:14:14 : Creating diamond database 2 of 25
2018-08-21 09:14:15 : Creating diamond database 3 of 25
2018-08-21 09:14:16 : Creating diamond database 4 of 25
2018-08-21 09:14:17 : Creating diamond database 5 of 25
2018-08-21 09:14:18 : Creating diamond database 6 of 25
2018-08-21 09:14:19 : Creating diamond database 7 of 25
2018-08-21 09:14:20 : Creating diamond database 8 of 25
2018-08-21 09:14:20 : Creating diamond database 9 of 25
2018-08-21 09:14:21 : Creating diamond database 10 of 25
2018-08-21 09:14:23 : Creating diamond database 11 of 25
2018-08-21 09:14:24 : Creating diamond database 12 of 25
2018-08-21 09:14:25 : Creating diamond database 13 of 25
2018-08-21 09:14:26 : Creating diamond database 14 of 25
2018-08-21 09:14:27 : Creating diamond database 15 of 25
2018-08-21 09:14:27 : Creating diamond database 16 of 25
2018-08-21 09:14:29 : Creating diamond database 17 of 25
2018-08-21 09:14:30 : Creating diamond database 18 of 25
2018-08-21 09:14:32 : Creating diamond database 19 of 25
2018-08-21 09:14:33 : Creating diamond database 20 of 25
2018-08-21 09:14:35 : Creating diamond database 21 of 25
2018-08-21 09:14:36 : Creating diamond database 22 of 25
2018-08-21 09:14:37 : Creating diamond database 23 of 25
2018-08-21 09:14:38 : Creating diamond database 24 of 25
2018-08-21 09:14:40 : Creating diamond database 25 of 25

Running diamond all-versus-all
------------------------------
Using 8 thread(s)
2018-08-21 09:14:40 : This may take some time....
2018-08-21 09:14:40 : Done 0 of 625
2018-08-21 12:18:52 : Done 100 of 625
2018-08-21 14:40:17 : Done 200 of 625
2018-08-21 16:41:30 : Done 300 of 625
2018-08-21 18:30:49 : Done 400 of 625
2018-08-21 19:52:18 : Done 500 of 625
2018-08-21 20:33:57 : Done 600 of 625

Running OrthoFinder algorithm
-----------------------------
2018-08-21 20:35:59 : Initial processing of each species
Malformatted line in /home/projects/redgillite/js_redgillite/griesmann_assemblies/peptide/Results_nfn_symbiosis_griesmann_Aug21/WorkingDirectory/Blast0_0.txt
Offending line was:

Process Process-10:
Traceback (most recent call last):
  File "/home/jsena/anaconda3/envs/orthofinder/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/jsena/anaconda3/envs/orthofinder/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jsena/anaconda3/envs/orthofinder/bin/orthofinder", line 484, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, qDoubleBlast=qDoubleBlast)
  File "/home/jsena/anaconda3/envs/orthofinder/bin/orthofinder", line 471, in ProcessBlastHits
    Bij = BlastFileProcessor.GetBLAST6Scores(seqsInfo, fileInfo, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
  File "/home/jsena/anaconda3/envs/orthofinder/bin/scripts/blast_file_processor.py", line 61, in GetBLAST6Scores
    with (gzip.open(fn + ".gz", 'rb') if os.path.exists(fn + ".gz") else open(fn, 'rb')) as blastfile:
IOError: [Errno 2] No such file or directory: '/home/projects/redgillite/js_redgillite/griesmann_assemblies/peptide/Results_nfn_symbiosis_griesmann_Aug21/WorkingDirectory/Blast0_0.txt'

**Comment by davidemms** [comment]
Hi 

I think there's a couple of things this might be:

1. There was a problem with DIAMOND in some of the versions before v0.9.20 on 19th April. If you're using an older version then update DIAMOND (For completeness sake here is a cross-reference the original issue: https://github.com/davidemms/OrthoFinder/issues/43 but it's probably not worth reading).  

2. It could be that there is a problem with the formatting of the input sequences, see here: https://github.com/davidemms/OrthoFinder/issues/170. The solution was to run `diamond makedb` on the input files to check if there are any problems and then correct the files if there are.

Let me know if either of these are successful, or if it looks like there is a different problem.

All the best
David

**Comment by senaj** [comment]
Hi Davidemms,

Thanks for your help!

I think that it was a problem with one of my input files. One of the files
contained periods in the sequences. I assume these were stop codons but
usually these are denoted with an asterisk. I removed the periods and
re-ran the analysis on a different server with the same
anaconda/orthofinder environment and it ran fine.

Thanks again for your help!

Sincerely,

**Comment by davidemms** [comment]
Great, glad it's working and thanks for letting me know.

David
