### ISSUE TITLE
Orthofinder stops at Calculating gene distances

### ISSUE THREAD

**Issue by zephyris** [davidemms/OrthoFinder#215]
Hi, I'm having a problem running orthofinder, it seems to quit after starting to calculating gene distances without giving the normal output. I'm certain all programs are installed and running correctly, I can run orthofinder on another proteome set, it's just on this one where it seems to stop before giving an output.

An example console output, starting from pre-calculated BLASTs, is:
```
OrthoFinder version 2.2.7 Copyright (C) 2014 David Emms

2018-11-04 10:17:05 : Starting OrthoFinder
11 thread(s) for highly parallel tasks (BLAST searches etc.)
11 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i [path]/Results_Nov02/WorkingDirectory/SimpleTest.phy -o [path]/Results_Nov02/WorkingDirectory/SimpleTest.tre" - ok
Using previously calculated BLAST results in [path]/Results_Nov02/WorkingDirectory/

Running OrthoFinder algorithm
-----------------------------
2018-11-04 10:17:10 : Initial processing of each species
...
2018-11-04 10:30:36 : Initial processing of species 41 complete
2018-11-04 10:32:16 : Connected putatitive homologs
2018-11-04 10:32:25 : Written final scores for species 10 to graph file
...
2018-11-04 10:36:49 : Written final scores for species 41 to graph file
[mcl] cut <226> instances of overlap
2018-11-04 22:31:00 : Ran MCL

Writing orthogroups to file
---------------------------
A duplicate accession was found using just first part: Chlre4_382136
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

Orthogroups have been written to tab-delimited files:
[path]/Results_Nov02/WorkingDirectory/Orthogroups.csv
[path]/eukaryotesFasta/Results_Nov02/WorkingDirectory/Orthogroups.txt (OrthoMCL format)
[path]/eukaryotesFasta/Results_Nov02/WorkingDirectory/Orthogroups_UnassignedGenes.csv
2018-11-04 22:31:29 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
```

Do you think this is a silent error calculating gene distances due to the duplicate accession, or do you think it could be something else?

Thanks!

**Comment by davidemms** [comment]
Hi 

There can be some issues with RAM using the '-a' option but the version you are using should alert you to any issues like that so that seems unlikely (you'd get a message starting, "ERROR: The computer ran out of RAM and killed OrthoFinder processes"). A couple of questions, are you using the source code version of the binary version of orthofinder? And what happens if you run it without the '-a 11' command line option? I'm wondering if there's an issue lurking in the binary version that I'm not aware of.

Thanks
David

**Comment by zephyris** [comment]
Hey,
I'm running the binary version. I didn't notice any RAM issues so I agree that's unlikely, I'll run it with without -a 11 and let you know though... If I get a chance I'll run the source code version on a parallel copy of the BLAST results too.
Thanks again!

**Comment by zephyris** [comment]
The run without the -a parameter (still using the binary version of orthofinder) just failed identically: Same console output and same (lack) of output.

Time to try the python version?

**Comment by davidemms** [comment]
Yes, I'd try that. If it works or if it fails then let me know, it sounds like there's something I need to look into.

Thanks
David

**Comment by zephyris** [comment]
I may have found an alternative explanation for my problems! I had a stray copy of clusters_OrthoFinder_v2.2.7_I1.5 in the Working directory, I guess from a run which crashed/failed somehow. Could that've been causing issues?

**Comment by davidemms** [comment]
Probably not, I don't think that would cause a problem.

**Comment by zephyris** [comment]
Hmm. Ok, this is definitely a peculiar one then - I can't get it to replicate reliably. The python version has consistently run with no problems. The compiled version has failed for this particular proteome set on all times I've tried it, except one.

**Comment by davidemms** [comment]
Would you be able to let me know the details of the machine it's running on and I will see if I can investigate:
- operating system and version
- kernel version
- libc version (run "ldd --version")
- How much RAM does it have

Thanks
David

**Comment by zephyris** [comment]
Of course:
Ubuntu 16.04.5 LTS running as a Linux subsystem for Windows 10
4.4.0-17134-Microsoft
ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23
32 Gb RAM

**Comment by YingyingYang2019** [comment]
Hi, I'm having a similar problem running orthofinder2. My OrthoFinder-2.3.3_source.tar.gz were downloaded from github, and my command are set like this: 
orthofinder.py -f pep_faa/ -t 90 -a 6 -S diamond
My program was stuck for five days. 
2019-06-28 00:58:00 : Done 72000 of 100048
2019-06-28 00:58:16 : Done 76000 of 100048
2019-06-28 00:58:20 : Done 77000 of 100048
2019-06-28 00:58:24 : Done 78000 of 100048
2019-06-28 00:58:28 : Done 79000 of 100048
2019-06-28 00:58:40 : Done 82000 of 100048
2019-06-28 00:58:44 : Done 83000 of 100048
2019-06-28 00:58:52 : Done 85000 of 100048
2019-06-28 00:59:11 : Done 90000 of 100048
2019-06-28 00:59:20 : Done 92000 of 100048
I donot know if it is normal because I have 185 species in my dataset. Should I wait for the next process or restart it with -fg?

**Comment by davidemms** [comment]
Hi

The best way to see is to look if anything is running using a command such as 'top' or 'pstree'. The most likely thing is that a particular command that has been launched by OrthoFinder is taking disproportionately long, most likely because the largest orthogroup is significantly bigger than all the other ones. If something is running you will see it using close to 100% cpu using top. If this is the case then I would definitely leave it running since restarting will probably take just put you 5 days behind where you currently are. Another thing to check is whether all the RAM has been used up on the computer, forcing it to use swap space. If this has happened it would slow things down considerably.

There is the nuclear option if you really can't wait. If you kill the process for inferring the tree that has been running for ages (i.e. **not** the orthofinder process itself!) then OrthoFinder will carry on with the remaining trees and then move onto the later steps of the algorithm. There is a big consequence of this though--no orthologues will be inferred for any of the genes in this orthogroup as OrthoFinder won't have the tree to examine in order to identify the orthologues. Taking this step isn't recommended.

All the best
David

**Comment by YingyingYang2019** [comment]
Hi David,


Thank you very much for your reply! I have checked the cpu, and they were nearly 100% used. I would leave it running and keep waiting. Thank you very much!
And since I didnot find your email address, I sent an email to Kelly Steven whose email address  was provided by the article yesterday earlier. I am very very sorry for disturbing!


Best wishes!
Yang








At 2019-07-03 17:34:06, "David Emms" <notifications@github.com> wrote:


Hi

The best way to see is to look if anything is running using a command such as 'top' or 'pstree'. The most likely thing is that a particular command that has been launched by OrthoFinder is taking disproportionately long, most likely because the largest orthogroup is significantly bigger than all the other ones. If something is running you will see it using close to 100% cpu using top. If this is the case then I would definitely leave it running since restarting will probably take just put you 5 days behind where you currently are. Another thing to check is whether all the RAM has been used up on the computer, forcing it to use swap space. If this has happened it would slow things down considerably.

There is the nuclear option if you really can't wait. If you kill the process for inferring the tree that has been running for ages (i.e. not the orthofinder process itself!) then OrthoFinder will carry on with the remaining trees and then move onto the later steps of the algorithm. There is a big consequence of this though--no orthologues will be inferred for any of the genes in this orthogroup as OrthoFinder won't have the tree to examine in order to identify the orthologues. Taking this step isn't recommended.

All the best
David

**Comment by KVin1456** [comment]
Hi, I have the same issue (out of RAM, Ubuntu 24.04.3 LTS, Intel® Core™ i5-2430M × 4, 16Gb RAM) at calculating gene distances stage. It happens both when I tried with Example data and 2 species proteomes I working with. An example console output is below (the -a parameter was limited at 1, as recommended). Would you recommend to try a 3.0 beta version?

~/OrthoFinder_source$ python orthofinder.py -f Data_Tc/ -a 1

OrthoFinder version 2.5.5 Copyright (C) 2014 David Emms

2026-02-04 17:52:04 : Starting OrthoFinder 2.5.5
4 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /home/konstantin/OrthoFinder_source/Data_Tc/OrthoFinder/Results_Feb04/WorkingDirectory/dependencies/SimpleTest.phy -o /home/konstantin/OrthoFinder_source/Data_Tc/OrthoFinder/Results_Feb04/WorkingDirectory/dependencies/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2026-02-04 17:52:04 : Creating diamond database 1 of 2
2026-02-04 17:52:05 : Creating diamond database 2 of 2

Running diamond all-versus-all
------------------------------
Using 4 thread(s)
2026-02-04 17:52:05 : This may take some time....
2026-02-04 17:52:05 : Done 0 of 4
2026-02-04 18:07:59 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2026-02-04 18:07:59 : Initial processing of each species
2026-02-04 18:08:05 : Initial processing of species 0 complete
2026-02-04 18:08:05 : Initial processing of species 1 complete
2026-02-04 18:08:07 : Connected putative homologues
2026-02-04 18:08:09 : Written final scores for species 0 to graph file
2026-02-04 18:08:09 : Written final scores for species 1 to graph file
2026-02-04 18:08:15 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 19517 genes (87.4% of total) to 3395 orthogroups. Fifty percent of all genes were in orthogroups with 7 or more genes (G50 was 7) and were contained in the largest 714 orthogroups (O50 was 714). There were 26 orthogroups with all species present and 18 of these consisted entirely of single-copy genes.

2026-02-04 18:08:16 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
Process Process-9:
Traceback (most recent call last):
  File "/home/konstantin/miniconda3/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/konstantin/miniconda3/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/konstantin/OrthoFinder_source/scripts_of/orthologues.py", line 263, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
    m[i][j] = 0.5*max(B[gi.iSeq, gj.iSeq], mins[gi.iSeq]) * maxes_inv[gi.iSeq]
    ~~~~^^^
TypeError: only 0-dimensional arrays can be converted to Python scalars
ERROR: The computer ran out of RAM and killed OrthoFinder processes
Try using a computer with more RAM. If you used the '-a' option
it may be possible to complete the run by removing this option.
ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.
(base) konstantin@konstantin-ThinkPad-T520:~/OrthoFinder_source$

**Comment by margaretc-ho** [comment]
@davidemms 

I have exactly the same issue with (OrthoFinder version 2.5.5, installed from bioconda repository) and it appears to have nothing to do with the amount of RAM (see seff jobid below). It's a segmentation fault from the Python TypeError below. I am not using the -a option:

My command is `orthofinder -t 4 -f ${inputdir}/primary_transcripts/ -o ${outputdir}/O13_orthofinder_fasttree_results`
I am comparing two genomes (44MB and 145MB, really not huge)

stdout:
```
Command: mcl /data/bcbb/homc/Grigglab/Tcas2/Tcas_rev2_MASURCA_ClecWolbfilt/2025Feb_orthofinder_analysis_Tcas_Tmu/O13_orthofinder_fasttree_results/Results_Feb25/WorkingDirectory/OrthoFinder_graph.txt -I 1.5 -o /data/bcbb/homc/Grigglab/Tcas2/Tcas_rev2_MASURCA_ClecWolbfilt/2025Feb_orthofinder_analysis_Tcas_Tmu/O13_orthofinder_fasttree_results/Results_Feb25/WorkingDirectory/clusters_OrthoFinder_I1.5.txt -te 1 -V all
stdout
------
b''
stderr
------
b'[mcl] cut <4> instances of overlap\n'
2026-02-25 12:35:54 : Ran MCL
Writing orthogroups to file
---------------------------
OrthoFinder assigned 120808 genes (100.0% of total) to 41188 orthogroups. Fifty percent of all genes were in orthogroups with 4 or more genes (G50 was 4) and were contained in the largest 12428 orthogroups (O50 was 12428). There were 11219 orthogroups with all species present and 9364 of these consisted entirely of single-copy genes.

2026-02-25 12:36:08 : Done orthogroups

Analysing Orthogroups
=====================
Calculating gene distances
--------------------------
ERROR: The computer ran out of RAM and killed OrthoFinder processes
Try using a computer with more RAM. If you used the '-a' option
it may be possible to complete the run by removing this option.
ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.
```

The error I get is
```
Process Process-9:
Traceback (most recent call last):
  File "/data/bcbb/homc/conda_envs/envs/orthofinder/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/data/bcbb/homc/conda_envs/envs/orthofinder/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/bcbb/homc/conda_envs/envs/orthofinder/bin/scripts_of/orthologues.py", line 263, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
    m[i][j] = 0.5*max(B[gi.iSeq, gj.iSeq], mins[gi.iSeq]) * maxes_inv[gi.iSeq]
    ~~~~^^^
TypeError: only 0-dimensional arrays can be converted to Python scalars
```

When I run seff on the jobid I get:

```
seff 4626325
Job ID: 4626325
Cluster: skyline-prod
User/Group: homc/homc
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 4
CPU Utilized: 01:16:01
CPU Efficiency: 91.73% of 01:22:52 core-walltime
Job Wall-clock time: 00:20:43
Memory Utilized: 6.25 GB
Memory Efficiency: 2.44% of 256.00 GB (256.00 GB/node)
Segmentation fault (core dumped)
```

As you can see it barely used any of the 256GB that was assigned to the job.

**Comment by achurcher** [comment]
I have had a similar issue with OrthoFinder version 2.5.5 (installed from bioconda repository). It resolved when I used numpy=2.3.5 instead of numpy 2.4.3

**Comment by tonyaseverson** [comment]
I had the same issue - OrthoFinder version 2.5.5 installed from bioconda, ran on ExampleData with orthofinder -f ExampleData/. All ran fine until calculating gene distance (Process Process-13):

> File "/home/tonya/miniconda3/envs/orthofinder/bin/scripts_of/orthologues.py", line 263, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
>     m[i][j] = 0.5*max(B[gi.iSeq, gj.iSeq], mins[gi.iSeq]) * maxes_inv[gi.iSeq]
> 
> TypeError: only 0-dimensional arrays can be converted to Python scalars
> ERROR: The computer ran out of RAM and killed OrthoFinder processes
> Try using a computer with more RAM. If you used the '-a' option
> it may be possible to complete the run by removing this option.

*The version in the repo worked perfectly, as did the version I installed from bioconda once I downgraded to numpy=2.3.5. Thank you to @achurcher for posting your solution!*
