### ISSUE TITLE
"IOError: [Errno 2] No such file or directory:" while it does exist 

### ISSUE THREAD

**Issue by ESDeutekom** [davidemms/OrthoFinder#216]
Hi, 
I ran into a problem using Orthofinder  (v2.2.6) on a big dataset of 165 species with precomputed blast results (in the format orthofinder wants using the -op option). During the initial processing of the species, species 125 runs into problems and stops Orthofinder, with the error the file does not exist. I checked and it does exist. 
 
Process Process-2:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
  File "orthofinder/scripts/blast_file_processor.py", line 61, in GetBLAST6Scores
IOError: [Errno 2] No such file or directory:"/home/myfilepath/"

For the species before, B*.pic and BH*.pic files are generated. I ran orthofinder on two species from my set, to check if it ran through completely, and it does.

Is there a way to rerun orthofinder from its last point (species 125) or do I have to redo all of that? It took a while.
And what could the problem be? 
Kind regards and thank you in advance,

**Comment by davidemms** [comment]
Hi

Would you be able to post the complete output that OrthoFinder printed to screen or attach/email it in a file please and I'll take a look. 

Thanks
David

**Comment by ESDeutekom** [comment]
Dear David, 
Here is the full output

eva@scarab:[SCREEN]:~:orthofinder -b /somepathway/Results_Aug23_1/
OrthoFinder version 2.2.6 Copyright (C) 2014 David Emms

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /somepathway/Results_Aug23_1/SimpleTest.phy -o /somepathway/Results_Aug23_1/Si
mpleTest.tre" - ok
Using previously calculated BLAST results in /somepathway/Results_Aug23_1/

Running OrthoFinder algorithm
-----------------------------
2018-10-31 14:42:41 : Initial processing of each species
2018-10-31 15:05:56 : Initial processing of species 0 complete
2018-10-31 15:38:16 : Initial processing of species 1 complete
2018-10-31 15:53:23 : Initial processing of species 2 complete
2018-10-31 16:26:05 : Initial processing of species 3 complete
2018-10-31 17:28:12 : Initial processing of species 4 complete
2018-10-31 17:55:07 : Initial processing of species 5 complete
2018-10-31 18:51:19 : Initial processing of species 6 complete
2018-10-31 19:20:10 : Initial processing of species 7 complete
2018-10-31 19:42:14 : Initial processing of species 8 complete
2018-10-31 20:05:01 : Initial processing of species 9 complete
2018-10-31 20:32:08 : Initial processing of species 10 complete
2018-10-31 21:03:41 : Initial processing of species 11 complete
2018-10-31 21:31:30 : Initial processing of species 12 complete
2018-10-31 22:10:42 : Initial processing of species 13 complete
2018-10-31 23:31:58 : Initial processing of species 14 complete
2018-10-31 23:57:43 : Initial processing of species 15 complete
2018-11-01 00:56:32 : Initial processing of species 16 complete
2018-11-01 01:41:44 : Initial processing of species 17 complete
2018-11-01 03:09:24 : Initial processing of species 18 complete
2018-11-01 03:16:02 : Initial processing of species 19 complete
2018-11-01 03:30:13 : Initial processing of species 20 complete
2018-11-01 04:51:53 : Initial processing of species 21 complete
2018-11-01 05:02:26 : Initial processing of species 22 complete
2018-11-01 05:23:33 : Initial processing of species 23 complete
2018-11-01 05:50:58 : Initial processing of species 24 complete
2018-11-01 06:17:07 : Initial processing of species 25 complete
2018-11-01 06:52:09 : Initial processing of species 26 complete
2018-11-01 07:20:34 : Initial processing of species 27 complete
2018-11-01 07:37:15 : Initial processing of species 28 complete
2018-11-01 07:52:03 : Initial processing of species 29 complete
2018-11-01 08:06:01 : Initial processing of species 30 complete
2018-11-01 08:36:07 : Initial processing of species 31 complete
2018-11-01 08:52:27 : Initial processing of species 32 complete
2018-11-01 09:41:29 : Initial processing of species 33 complete
2018-11-01 10:09:37 : Initial processing of species 34 complete
2018-11-01 10:16:37 : Initial processing of species 35 complete
2018-11-01 11:02:21 : Initial processing of species 36 complete
2018-11-01 11:08:39 : Initial processing of species 37 complete
2018-11-01 11:18:53 : Initial processing of species 38 complete
2018-11-01 11:57:56 : Initial processing of species 39 complete
2018-11-01 12:20:05 : Initial processing of species 40 complete
2018-11-01 12:26:12 : Initial processing of species 41 complete
2018-11-01 12:59:09 : Initial processing of species 42 complete
2018-11-01 13:24:13 : Initial processing of species 43 complete
2018-11-01 13:35:29 : Initial processing of species 44 complete
2018-11-01 13:50:23 : Initial processing of species 45 complete
2018-11-01 14:47:29 : Initial processing of species 46 complete
2018-11-01 15:19:03 : Initial processing of species 47 complete
2018-11-01 15:35:44 : Initial processing of species 48 complete
2018-11-01 16:20:56 : Initial processing of species 49 complete
2018-11-01 16:44:12 : Initial processing of species 50 complete
2018-11-01 17:11:24 : Initial processing of species 51 complete
2018-11-01 17:54:31 : Initial processing of species 52 complete
2018-11-01 19:21:35 : Initial processing of species 53 complete
2018-11-01 19:30:59 : Initial processing of species 54 complete
2018-11-01 19:47:11 : Initial processing of species 55 complete
2018-11-01 20:41:07 : Initial processing of species 56 complete
2018-11-01 20:44:05 : Initial processing of species 57 complete
2018-11-01 21:10:42 : Initial processing of species 58 complete
2018-11-01 21:39:53 : Initial processing of species 59 complete
2018-11-01 21:51:52 : Initial processing of species 60 complete
2018-11-01 22:23:44 : Initial processing of species 61 complete
2018-11-01 22:38:20 : Initial processing of species 62 complete
2018-11-01 22:46:15 : Initial processing of species 63 complete
2018-11-01 22:55:56 : Initial processing of species 64 complete
2018-11-01 23:40:40 : Initial processing of species 65 complete
2018-11-02 00:14:31 : Initial processing of species 66 complete
2018-11-02 00:32:52 : Initial processing of species 67 complete
2018-11-02 01:37:20 : Initial processing of species 68 complete
2018-11-02 02:16:12 : Initial processing of species 69 complete
2018-11-02 02:30:25 : Initial processing of species 70 complete
2018-11-02 02:53:06 : Initial processing of species 71 complete
2018-11-02 03:19:42 : Initial processing of species 72 complete
2018-11-02 03:27:37 : Initial processing of species 73 complete
2018-11-02 04:09:35 : Initial processing of species 74 complete
2018-11-02 04:22:46 : Initial processing of species 75 complete
2018-11-02 05:16:32 : Initial processing of species 76 complete
2018-11-02 05:37:56 : Initial processing of species 77 complete
2018-11-02 05:58:20 : Initial processing of species 78 complete
2018-11-02 06:03:06 : Initial processing of species 79 complete
2018-11-02 06:29:51 : Initial processing of species 80 complete
2018-11-02 06:48:21 : Initial processing of species 81 complete
2018-11-02 07:11:11 : Initial processing of species 82 complete
2018-11-02 07:36:59 : Initial processing of species 83 complete
2018-11-02 08:07:34 : Initial processing of species 84 complete
2018-11-02 08:24:27 : Initial processing of species 85 complete
2018-11-02 08:46:39 : Initial processing of species 86 complete
2018-11-02 09:00:16 : Initial processing of species 87 complete
2018-11-02 09:12:00 : Initial processing of species 88 complete
2018-11-02 09:41:48 : Initial processing of species 89 complete
2018-11-02 10:39:32 : Initial processing of species 90 complete
2018-11-02 11:18:20 : Initial processing of species 91 complete
2018-11-02 12:05:40 : Initial processing of species 92 complete
2018-11-02 12:50:05 : Initial processing of species 93 complete
2018-11-02 14:07:43 : Initial processing of species 94 complete
2018-11-02 14:36:48 : Initial processing of species 95 complete
2018-11-02 14:48:47 : Initial processing of species 96 complete
2018-11-02 15:55:17 : Initial processing of species 97 complete
2018-11-02 16:42:10 : Initial processing of species 98 complete
2018-11-02 18:20:17 : Initial processing of species 99 complete
2018-11-02 18:43:24 : Initial processing of species 100 complete
2018-11-02 19:02:21 : Initial processing of species 101 complete
2018-11-02 19:35:04 : Initial processing of species 102 complete
2018-11-02 19:42:02 : Initial processing of species 103 complete
2018-11-02 19:49:51 : Initial processing of species 104 complete
2018-11-02 20:11:33 : Initial processing of species 105 complete
2018-11-02 20:34:56 : Initial processing of species 106 complete
2018-11-02 20:44:02 : Initial processing of species 107 complete
2018-11-02 21:12:45 : Initial processing of species 108 complete
2018-11-02 21:43:41 : Initial processing of species 109 complete
2018-11-02 22:05:33 : Initial processing of species 110 complete
2018-11-02 22:54:40 : Initial processing of species 111 complete
2018-11-02 23:21:08 : Initial processing of species 112 complete
2018-11-02 23:35:27 : Initial processing of species 113 complete
2018-11-03 00:23:26 : Initial processing of species 114 complete
2018-11-03 00:46:20 : Initial processing of species 115 complete
2018-11-03 02:22:51 : Initial processing of species 116 complete
2018-11-03 02:39:07 : Initial processing of species 117 complete
2018-11-03 03:03:58 : Initial processing of species 118 complete
2018-11-03 03:14:57 : Initial processing of species 119 complete
2018-11-03 03:28:27 : Initial processing of species 120 complete
2018-11-03 04:51:13 : Initial processing of species 121 complete
2018-11-03 05:41:15 : Initial processing of species 122 complete
2018-11-03 05:51:32 : Initial processing of species 123 complete
2018-11-03 06:23:34 : Initial processing of species 124 complete
Malformatted line in /somepathway/Results_Aug23_1/Blast125_17.txt
Offending line was:

Process Process-2:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
  File "orthofinder/scripts/blast_file_processor.py", line 61, in GetBLAST6Scores
IOError: [Errno 2] No such file or directory: '/somepathway/Results_Aug23_1/Blast125_17.txt'
ERROR: An error occurred, please review error messages for more information.

**Comment by davidemms** [comment]
So what happens if you type 
`ls -l /somepathway/Results_Aug23_1/Blast125_17.txt`
at the terminal?

And `
ls -l /somepathway/Results_Aug23_1/Blast125_1*.txt`
?

The error message you're seeing is directly from python (rather than orthofinder code) when the python `open` method is called on that file. I'd suggests carefully checking why the file can't be open. I.e. is it there, what are the read/write permissions, is it corrupted, could there have been a temporary error accessing the disk etc. Let me know how you get on.

All the best
David

**Comment by ESDeutekom** [comment]
Dear David, 
Thanks a lot for the comments. I indeed checked all these, the file exists, is not corrupted, most other blast vs blast with species 125 seem fine (all 165 are present), all reading and writing rights permissions like the rest. Last file to be made: 
eva@alive:/somepathway/Results_Aug23_1:ls -lhst | head
total 895G
 364K -rw-r--r-- 1 eva binf  364K Nov  3 06:23 BH124_164.pic
 372K -rw-r--r-- 1 eva binf  371K Nov  3 06:23 BH124_163.pic
 368K -rw-r--r-- 1 eva binf  366K Nov  3 06:23 BH124_162.pic
 368K -rw-r--r-- 1 eva binf  365K Nov  3 06:23 BH124_161.pic
 368K -rw-r--r-- 1 eva binf  365K Nov  3 06:23 BH124_160.pic
 376K -rw-r--r-- 1 eva binf  376K Nov  3 06:23 BH124_159.pic

The only thing I can think of, is indeed, somehow there was a temporary connection error to the disk just as it started reading species 125. 
So, my questiones mainly would be, if I start up orthofinder again, is there a way to start from the last .pic file? From species 125 essentially? Or does orthofinder overwrite everything and start anew (overwrite .pic files)? I want to recreate it (if there is any error), and not have to wait for it to crash again after a few days, and *mainly* that all the files created now are not corrupted, so should I delete the .pic files first for instance? 
Kind regards and thank kindly for you for the help.

**Comment by davidemms** [comment]
Hi

Unfortunately you'll need to start again from the BLAST results. It will just overwrite the .pic files so you don't have to worry about them. 

Probably the best thing to try is a test of the problem file first. Comment out all the species in the SpeciesIDs.txt file with a '#' except for 125, 17 and two other species and run OrthoFinder on that reduced dataset. It will be pretty quick and would let you know if it was a temporary or a real issue with the Blast125_17.txt file. If that runs successfully then re-include all the species and run it on the full dataset. You can keep things a bit tidier by deleting all the new files produced by the test run (OrthoFinder_v2.2.7_graph.txt, clusters*, Orthogroups*, Statistics* etc) before starting the full run.

All the best
David

**Comment by ESDeutekom** [comment]
Thanks a lot. That is a good tip, to comment out the species in the ID file. 
Kind regards, 
Eva
