### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by jorgeibarracaballero** [davidemms/OrthoFinder#218]
Hi,
What are possible causes of this (after Done all-versus-all sequence search):

at the beginning I got these messages:

['BLAST options error: /home/jorge_lbarras/Raffaelea/proteins/Results_Nov12/WorkingDirectory/Species0.fa does not match input format type, default input type is FASTA\n']

for databases 1 of 18 to 9 of 18,
but then:

2018-11-12 12:47:23 : Creating Blast database 10 of 18
2018-11-12 12:47:23 : Creating Blast database 11 of 18
2018-11-12 12:47:23 : Creating Blast database 12 of 18
2018-11-12 12:47:24 : Creating Blast database 13 of 18
2018-11-12 12:47:24 : Creating Blast database 14 of 18
2018-11-12 12:47:25 : Creating Blast database 15 of 18
2018-11-12 12:47:25 : Creating Blast database 16 of 18
2018-11-12 12:47:26 : Creating Blast database 17 of 18
2018-11-12 12:47:26 : Creating Blast database 18 of 18

Running BLAST all-versus-all
----------------------------
Using 16 thread(s)
2018-11-12 12:47:26 : This may take some time....
2018-11-12 17:53:49 : Done 100 of 324
2018-11-12 17:53:55 : Done 200 of 324
2018-11-12 17:54:02 : Done 300 of 324
2018-11-12 12:47:26 : Done 0 of 324
2018-11-12 18:39:36 : Done all-versus-all sequence search

 weird that 0 of 324 came last

at then this came:

Running OrthoFinder algorithm
-----------------------------
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1588, in <module>
  File "orthofinder/orthofinder.py", line 1239, in DoOrthogroups
  File "orthofinder/orthofinder.py", line 349, in GetSequenceLengths
IndexError: index out of bounds
Failed to execute script orthofinder

and the program stopped.

I used my proteins fasta files with other programs and they worked fine. Maybe they have to have a specific format on the sequences names or something like that?

I will look for that and will try to run again, but maybe you can help. Thank you!

Jorge

**Comment by jorgeibarracaballero** [comment]
It worked, it failed because of the DS_Store files that were in the folder when I made the tar ball. Sorry. I hope this could be useful for others

**Comment by davidemms** [comment]
Thanks, I hadn't been aware of them and they would currently get through the checks I do. I only check the extension is one of: ".fa", ".faa", ".fasta" or ".fas". It sounds like the ".\_" prefix files are ["resource fork segments of files"](https://www.cnet.com/news/invisible-files-with-prefix-are-created-on-some-shared-volumes-and-external-disks/). I think it would be best if I specifically exclude these. A file called ".DS_Store" would currently be ignored by OrthoFinder.
