### ISSUE TITLE
Vague Problem with execution

### ISSUE THREAD

**Issue by RobertBakaric** [davidemms/OrthoFinder#220]
Any ideas on this issue:

```
Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2018-11-15 13:55:43 : Done 0 of 2242
2018-11-15 13:56:30 : Done 1000 of 2242
2018-11-15 13:57:20 : Done 2000 of 2242
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1629, in <module>
  File "orthofinder/orthofinder.py", line 1470, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 897, in OrthologuesWorkflow
  File "orthofinder/scripts/trees_msa.py", line 346, in DoTrees
  File "orthofinder/scripts/trees_msa.py", line 215, in CreateConcatenatedAlignment
  File "orthofinder/scripts/trees_msa.py", line 207, in ReadAlignment
  File "orthofinder/scripts/trees_msa.py", line 182, in __init__
IndexError: list index out of range
Failed to execute script orthofinder
```
I am using: 

`OrthoFinder version 2.3.1 Copyright (C) 2014 David Emms`

Thnx

**Comment by davidemms** [comment]
Hi

Do you have the rest of the output?

Thanks
David

**Comment by RobertBakaric** [comment]
Sure, no problem ... it is probably something stupid ....

```
orthofinder -f Global/InP/ -t 40 -a 40 -M msa

OrthoFinder version 2.3.1 Copyright (C) 2014 David Emms

2018-11-15 20:54:11 : Starting OrthoFinder
40 thread(s) for highly parallel tasks (BLAST searches etc.)
40 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "mafft /common/Data/Global/InP/OrthoFinder/Results_Nov15/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Test can run "FastTree /common/Data/Global/InP/OrthoFinder/Results_Nov15/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-11-15 20:54:12 : Creating diamond database 1 of 5
2018-11-15 20:54:12 : Creating diamond database 2 of 5
2018-11-15 20:54:12 : Creating diamond database 3 of 5
2018-11-15 20:54:12 : Creating diamond database 4 of 5
2018-11-15 20:54:13 : Creating diamond database 5 of 5

Running diamond all-versus-all
------------------------------
Using 40 thread(s)
2018-11-15 20:54:13 : This may take some time....
2018-11-15 20:56:29 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2018-11-15 20:56:29 : Initial processing of each species
2018-11-15 20:56:32 : Initial processing of species 0 complete
2018-11-15 20:56:32 : Initial processing of species 3 complete
2018-11-15 20:56:33 : Initial processing of species 2 complete
2018-11-15 20:56:33 : Initial processing of species 4 complete
2018-11-15 20:56:33 : Initial processing of species 1 complete
2018-11-15 20:56:37 : Connected putatitive homologs
2018-11-15 20:56:38 : Written final scores for species 0 to graph file
2018-11-15 20:56:38 : Written final scores for species 3 to graph file
2018-11-15 20:56:39 : Written final scores for species 4 to graph file
2018-11-15 20:56:39 : Written final scores for species 2 to graph file
2018-11-15 20:56:39 : Written final scores for species 1 to graph file
2018-11-15 20:56:42 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /common/Data/Global/InP/OrthoFinder/Results_Nov15/Orthogroups/Orthogroups.tsv
   /common/Data/Global/InP/OrthoFinder/Results_Nov15/Orthogroups/Orthogroups.txt (OrthoMCL format)
   /common/Data/Global/InP/OrthoFinder/Results_Nov15/Orthogroups/Orthogroups_UnassignedGenes.tsv
Sequences for orthogroups:
   /common/Data/Global/InP/OrthoFinder/Results_Nov15/Orthogroup_Sequences/

2018-11-15 20:56:45 : Done orthogroups

Analysing Orthogroups
=====================
2018-11-15 20:56:45 : Starting MSA/Trees
Species tree: Using 2242 orthogroups with minimum of 100.0% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2018-11-15 20:56:47 : Done 0 of 2242
2018-11-15 20:56:55 : Done 1000 of 2242
2018-11-15 20:57:05 : Done 2000 of 2242
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1629, in <module>
  File "orthofinder/orthofinder.py", line 1470, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 897, in OrthologuesWorkflow
  File "orthofinder/scripts/trees_msa.py", line 346, in DoTrees
  File "orthofinder/scripts/trees_msa.py", line 215, in CreateConcatenatedAlignment
  File "orthofinder/scripts/trees_msa.py", line 207, in ReadAlignment
  File "orthofinder/scripts/trees_msa.py", line 182, in __init__
IndexError: list index out of range
Failed to execute script orthofinder
```

Thank you !

**Comment by davidemms** [comment]
Hi

I think what's probably happened in the first case is that the alignment failed for one of your orthogroups and this has caused an error when orthofinder has tried to read it. Could you check the files and see if any of them are empty. The following will sort the files by size:
`ll -S /common/Data/Global/InP/OrthoFinder/Results_Nov15/WorkingDirectory/Alignments_ids/`
so you can see if the last files in the list are empty.

I'm not sure why that could have happened (unless all the alignments failed?). If it's just some of the files, you could see if there is anything wrong with the corresponding files in "Results_Nov15/WorkingDirectory/Sequences_ids". If you let me know then I can try improve the error handling here so orthofinder deals with this more helpfully. I'll have to have a look at the second case tomorrow....

All the best
David

**Comment by davidemms** [comment]
Hi

I don't suppose you got anywhere with this issue? Sorry for the delay but if you can send me some input files that provoke this issue then I'll see if I can identify and fix the issue.

Thanks
David

**Comment by TonyMannion** [comment]
Hi,

I am having a similar issue... 

tonymannion@DESKTOP-DEQB4ST:/mnt/c/Users/antho/Desktop$ ./OrthoFinder/orthofinder -fg EHS/OrthoFinder/Results_Jun21/ -M msa

OrthoFinder version 2.3.12 Copyright (C) 2014 David Emms

2020-06-21 19:43:01 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mafft /mnt/c/Users/antho/Desktop/EHS/OrthoFinder/Results_Jun21/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Test can run "FastTree /mnt/c/Users/antho/Desktop/EHS/OrthoFinder/Results_Jun21/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok

Analysing Orthogroups
=====================
2020-06-21 19:43:04 : Starting MSA/Trees
Species tree: Using 1187 orthogroups with minimum of 96.4% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2020-06-21 19:44:50 : Done 0 of 1187
2020-06-21 19:46:13 : Done 100 of 1187
2020-06-21 19:47:30 : Done 200 of 1187
2020-06-21 19:48:51 : Done 300 of 1187
2020-06-21 19:50:02 : Done 400 of 1187
2020-06-21 19:51:10 : Done 500 of 1187
2020-06-21 19:52:16 : Done 600 of 1187
2020-06-21 19:53:24 : Done 700 of 1187
2020-06-21 19:54:24 : Done 800 of 1187
2020-06-21 19:55:23 : Done 900 of 1187
2020-06-21 19:56:27 : Done 1000 of 1187
2020-06-21 19:57:36 : Done 1100 of 1187
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1754, in main
  File "scripts_of/__main__.py", line 1511, in GetOrthologues
  File "scripts_of/orthologues.py", line 905, in OrthologuesWorkflow
  File "scripts_of/trees_msa.py", line 357, in DoTrees
  File "scripts_of/trees_msa.py", line 222, in CreateConcatenatedAlignment
  File "scripts_of/trees_msa.py", line 214, in ReadAlignment
  File "scripts_of/trees_msa.py", line 189, in __init__
IndexError: list index out of range
[25583] Failed to execute script orthofinder

One of the alignments in the Alignments_ids folder is blank (no data).  Is there any fix to this problem?

Thanks!
Tony
