### ISSUE TITLE
Running orthofinder on thousands of genomes

### ISSUE THREAD

**Issue by fschjgi** [davidemms/OrthoFinder#221]
How could we run orthofinder on thousands of genomes? 

One strategy might be to use 1) the -op option on the query genomes to generate orthofinder compatible names. 2) Then run diamond blast separately (chunks of thousands of proteins against a single database containing all proteins) and 3) split the blast output to generate the pairwise blast output orthofinder needs. 

However, for the last step the current orthofinder code needs two files per pairwise comparison (including empty files if no blast hits between species pair) - for 3000 genomes this would result in almost 9 million files to be stored in a single working directory (highly problematic or even impossible depending on the file system).

Might it be an option to structure the working directory differently and organize the pairwise blast output in subdirectories?

**Comment by davidemms** [comment]
Hi

It may be that 3000 genomes is going to be too many for it to be able to deal with, depending on computer resources etc. I'm currently working on a version of OrthoFinder that will be designed to deal with exactly this use case though. There will likely be a version ready in a few months time, but I can't give any guarantees as it will depend how smoothly everything goes. 

All the best
David

**Comment by xiaofan474** [comment]
Hi David,
 I am working on a project on 1500 genomes using 2.2.6. I failed for several times. It seems to require >200G RAM. Have the latest version 2.3.3 solved out this issue yet?
Thank you.

**Comment by davidemms** [comment]
Hi

What step of the algorithm did it get to?

There's no lower RAM version available yet. The best advice would be to use "-M msa", this uses multiple sequence alignments to infer trees and will have lower RAM requirements for large analyses. You will need to have MAFFT and FastTree installed for this. Also, use "-a 1" since anything larger than this will increase RAM requirements. 

All the best
David

**Comment by xiaofan474** [comment]
Hi David,
By learning from your suggestion I have made another round running. Here is my command:
orthofinder -og -t 50 -a 1 -I 1.4 -b /home/data/Results_Jul12/WorkingDirectory 

And at last it ended with error log:" 
Process Process-2:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 476, in ProcessBlastHits
  File "orthofinder/scripts/matrices.py", line 42, in DumpMatrixArray
  File "orthofinder/scripts/matrices.py", line 38, in DumpMatrix
IOError: [Errno 28] No space left on device
"

Does this mean my memory is not enough or my disk space is not enough?  I checked the disk space after orthofind ended, there is more than 5T left. Will there be many large temporary files in the middle of running the program? 

Thank you.

**Comment by davidemms** [comment]
Hi

The error message is from python (rather than OrthoFinder itself) and says like there is no space left on the disk.

All the best
David

**Comment by xiaofan474** [comment]
Hi David,
Thank you for the kind reply. The problem I was well resolved. 
From then on, I met a new problem when I deal with thousand of genome using OrthoFinder_v2.2.6 because of the large RAM requirement. Luckily I got the file of OrthoFinder_v2.2.6_graph.txt.tar.gz. By independently running 'mcl' on this file in the other platform I got the cluster file ( equal to clusters_OrthoFinder_v2.2.6_I??.txt). So what can I do next using Orthofinder with this result? I wonder whether in the Orthofinder source code it include some sub-scripts that can be used to deal with this processing result to obtain the Ortholog Groups and the statistics? 

Best wishes,
Xiao

**Comment by bitahu** [comment]
can you help me ?

2023-05-11 21:00:13 : Initial processing of species 105 complete
2023-05-11 21:00:16 : Initial processing of species 106 complete
Process Process-50:
Traceback (most recent call last):
  File "/home/hang/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hang/miniconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hang/miniconda3/bin/scripts_of/__main__.py", line 529, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, d_pickle=d_pickle, qDoubleBlast=qDoubleBlast)
  File "/home/hang/miniconda3/bin/scripts_of/__main__.py", line 519, in ProcessBlastHits
    matrices.DumpMatrixArray("B", Bi, iSpecies, d_pickle)
  File "/home/hang/miniconda3/bin/scripts_of/matrices.py", line 43, in DumpMatrixArray
    DumpMatrix(name, m, iSpecies, jSpecies, d_pickle)
  File "/home/hang/miniconda3/bin/scripts_of/matrices.py", line 39, in DumpMatrix
    pic.dump(m, picFile, protocol=util.picProtocol)
OSEr

**Comment by sapuizait** [comment]
HI there - i realize this is an old thread but I have run in the same problem. In my case I have 1500 bacterial genomes but I m running it on a cluster with 64 cores and 500G RAM. 
Yet it seems to freeze as when the diamond blast starts it keeps saying "This may take a while" but then for days it gets stuck at this step. And there is no progress. Any ideas?
For the record, I would be happy even if I could only get the orthogroups step finished '-og'.

$orthofinder -f $WORKDIR/input/ -S diamond -t 64 -a 64
