### ISSUE TITLE
Resuming --from-trees with removed species IDs in the results

### ISSUE THREAD

**Issue by josiahseaman** [davidemms/OrthoFinder#237]
I've been very happy with OrthoFinder so far.  I'm attempting to resume a gene tree reconciliation from a result set that took ~2 weeks to compute.  I have two ignored species 2: FRAX02, 29:FRAX34 which are commented out in SpeciesIDs.txt.  But I'm having issues resuming the job.  All I want is the old gene trees reconciled to a new species tree.  So that I can get an updated Duplications.csv.  Would it be possible to change OrthoFinder so it simply ignores mentions of species that are commented out?

```
$ /data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/orthofinder.py \
> --from-trees /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/ \
> -s /data/SBCS-BuggsLab/Josiah/DNA_Duplications/CAFE-4.2/data/corrected_root/Species_tree_corrected_root_ultrametric_integers.tre \
> -t 1

OrthoFinder version 2.2.6 Copyright (C) 2014 David Emms

1 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Using orthogroups in file:
    /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/../Orthogroups.txt
and corresponding clusters file:
    /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/../WorkingDirectory/clusters_OrthoFinder_v2.2.6_I1.5.txt_id_pairs.txt

Checking required programs are installed
----------------------------------------
Test can run "fastme -i /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/../WorkingDirectory/SimpleTest.phy -o /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/../WorkingDirectory/SimpleTest.tre" - ok

Using orthogroups in file:
    /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/../Orthogroups.txt
and corresponding clusters file:
    /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/../WorkingDirectory/clusters_OrthoFinder_v2.2.6_I1.5.txt_id_pairs.txt

Running Orthologue Prediction
=============================


Running Orthologue Prediction
=============================

Reconciling gene and species trees
----------------------------------
2019-01-22 11:09:19 : Starting OF Orthologues
2_17935
2
Traceback (most recent call last):
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/orthofinder.py", line 1612, in <module>
    summaryText = GetOrthologues_FromTrees(orthologuesDir, options)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/orthofinder.py", line 1423, in GetOrthologues_FromTrees
    return orthologues.OrthologuesFromTrees(options.recon_method, groupsDir, workingDir, options.nBlast, options.speciesTreeFN, pickleDir=options.separatePickleDir)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/orthologues.py", line 971, in OrthologuesFromTrees
    ReconciliationAndOrthologues(recon_method, TreePatIDs, ogSet, speciesTree_fn, workingDir, resultsDir_new, reconTreesRenamedDir, nHighParallel, pickleDir=pickleDir)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/orthologues.py", line 913, in ReconciliationAndOrthologues
    nOrthologues_SpPair = trees2ologs_of.DoOrthologuesForOrthoFinder(ogSet, treesIDsPatFn, speciesTree_fn, trees2ologs_of.GeneToSpecies_dash, workingDir, resultsDir, reconTreesRenamedDir, all_stride_dup_genes)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 562, in DoOrthologuesForOrthoFinder
    orthologues, recon_tree, suspect_genes = GetOrthologues_from_tree(iog, treesIDsPatFn(iog), species_tree_rooted, GeneToSpecies, neighbours, dupsWriter=dupWriter, seqIDs=ogSet.Spec_SeqDict(), spIDs=ogSet.SpeciesDict(), all_stride_dup_genes=all_stride_dup_genes)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 290, in GetOrthologues_from_tree
    root = GetRoot(tree, species_tree_rooted, GeneToSpecies)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 271, in GetRoot
    roots = GetRoots(tree, species_tree_rooted, GeneToSpecies)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 129, in GetRoots
    StoreSpeciesSets(tree, GeneMap, "inout_") # ingroup/outgroup identification
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 62, in StoreSpeciesSets
    node.add_feature(tag_down, {GeneMap(node.name)})
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 55, in GeneMap
    raise Exception
Exception
```

Checked that species tree and original fasta files still have the same names:

```
((((((((((((FRAX30:2.0,FRAX32:2.0):1.0,FRAX28:3.0):2.0,FRAX12:5.0):4.0,(FRAX07:8.0,FRAX29:8.0):1.0):4.0,FRAX08:13.0):1.0,(((((FRAX01:2.0,FRAX16:2.0):4.0,FRAX15:6.0):2.0,FRAX00:8.0):2.0,(FRAX06:9.0,FRAX23:9.0):1.0):3.0,FRAX25:13.0):1.0):3.0,FRAX21:17.0):2.0,(((FRAX19:8.0,FRAX20:8.0):2.0,((FRAX11:5.0,FRAX27:5.0):4.0,FRAX04:9.0):1.0):1.0,(((((FRAX03:1.0,FRAX09:1.0):1.0,FRAX13:2.0):2.0,(FRAX26:2.0,FRAX14:2.0):2.0):3.0,FRAX05:7.0):2.0,FRAX33:9.0):2.0):8.0):15.0,FRAX31:34.0):2.0,Oeuropea:36.0):36.0,Mguttatus:72.0):7.0,Slycopersicum:79.0):0.0;

ls /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome
backup_Results_Jun25    FRAX03.faa  FRAX08.faa  FRAX14.faa  FRAX21.faa  FRAX28.faa  FRAX33.faa       Results_Jun25
data_sources_notes.txt  FRAX04.faa  FRAX09.faa  FRAX15.faa  FRAX23.faa  FRAX29.faa  FRAX34.faa       Slycopersicum.faa
FRAX00.faa              FRAX05.faa  FRAX11.faa  FRAX16.faa  FRAX25.faa  FRAX30.faa  Mguttatus.faa
FRAX01.faa              FRAX06.faa  FRAX12.faa  FRAX19.faa  FRAX26.faa  FRAX31.faa  Oeuropea.faa
FRAX02.faa              FRAX07.faa  FRAX13.faa  FRAX20.faa  FRAX27.faa  FRAX32.faa
```

Checked that two species I wanted removed are commented in the SpeciesID.txt in the dir referenced:

``` 
cat /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/WorkingDirectory/SpeciesIDs.txt
0: FRAX00.faa
1: FRAX01.faa
#2: FRAX02.faa
3: FRAX03.faa
4: FRAX04.faa
5: FRAX05.faa
6: FRAX06.faa
7: FRAX07.faa
8: FRAX08.faa
9: FRAX09.faa
10: FRAX11.faa
11: FRAX12.faa
12: FRAX13.faa
13: FRAX14.faa
14: FRAX15.faa
15: FRAX16.faa
16: FRAX19.faa
17: FRAX20.faa
18: FRAX21.faa
19: FRAX23.faa
20: FRAX25.faa
21: FRAX26.faa
22: FRAX27.faa
23: FRAX28.faa
24: FRAX29.faa
25: FRAX30.faa
26: FRAX31.faa
27: FRAX32.faa
28: FRAX33.faa
#29: FRAX34.faa
30: Mguttatus.faa
31: Oeuropea.faa
32: Slycopersicum.faa
``` 

Since it's in a parent directory I wonder if OrthoFinder isn't reading that file?

``` 
find Ash_Proteome/ -name "SpeciesIDs.txt"
Ash_Proteome/Results_Jun19_1/WorkingDirectory/SpeciesIDs.txt
Ash_Proteome/Results_Jun25/WorkingDirectory/SpeciesIDs.txt
Ash_Proteome/backup_Results_Jun25/WorkingDirectory/SpeciesIDs.txt
``` 

To test if the problem was exclusive to species matching I added in the excluded species:

```
$ /data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/orthofinder.py --from-trees /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/ -s /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/Species_tree_corrected_root_added_02_34.tre  -t 1

OrthoFinder version 2.2.6 Copyright (C) 2014 David Emms

1 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Using orthogroups in file:
    /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/../Orthogroups.txt
and corresponding clusters file:
    /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/../WorkingDirectory/clusters_OrthoFinder_v2.2.6_I1.5.txt_id_pairs.txt

Checking required programs are installed
----------------------------------------
Test can run "fastme -i /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/../WorkingDirectory/SimpleTest.phy -o /data/SBCS-BuggsLab/Josiah/DNA_Duplications/Ash_Proteome/Results_Jun25/Orthologues_Jul04_2/../WorkingDirectory/SimpleTest.tre" - ok
ERROR: Additional species 'FRAX02' in species tree
ERROR: Additional species 'FRAX34' in species tree
ERROR: An error occurred, please review error messages for more information.
```
Which was not the result I was expecting.  So the mcl clusters file mentions genes belonging to 2_ but it doesn't have an entry for FRAX02?  Editing SpeciesIDs.txt to uncomment the two species seemed to run fine.

Next, I used regular expressions to edit Orthogroups.txt and clusters_...id_pairs.txt to remove all mentions of genes belonging to these two species.  I removed any line of orhtogroup that then became blank, meaning orthogroups are not longer consecutive.  That's when I run into an error that looks a lot like a consecutive requirement.

```
Running Orthologue Prediction
=============================

Reconciling gene and species trees
----------------------------------
2019-01-22 12:58:45 : Starting OF Orthologues
Traceback (most recent call last):
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/orthofinder.py", line 1612, in <module>
    summaryText = GetOrthologues_FromTrees(orthologuesDir, options)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/orthofinder.py", line 1423, in GetOrthologues_FromTrees
    return orthologues.OrthologuesFromTrees(options.recon_method, groupsDir, workingDir, options.nBlast, options.speciesTreeFN, pickleDir=options.separatePickleDir)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/orthologues.py", line 971, in OrthologuesFromTrees
    ReconciliationAndOrthologues(recon_method, TreePatIDs, ogSet, speciesTree_fn, workingDir, resultsDir_new, reconTreesRenamedDir, nHighParallel, pickleDir=pickleDir)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/orthologues.py", line 913, in ReconciliationAndOrthologues
    nOrthologues_SpPair = trees2ologs_of.DoOrthologuesForOrthoFinder(ogSet, treesIDsPatFn, speciesTree_fn, trees2ologs_of.GeneToSpecies_dash, workingDir, resultsDir, reconTreesRenamedDir, all_stride_dup_genes)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 555, in DoOrthologuesForOrthoFinder
    nOgs = len(ogSet.OGs())
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/orthologues.py", line 147, in OGs
    ogs = MCL.GetPredictedOGs(self.clustersFN)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/mcl.py", line 61, in GetPredictedOGs
    assert(len(predictedOGs) == int(nOGsString) + 1)
AssertionError
```

I removed the Assert, but that just moved the problem to GeneMap() which is referenced in several places.  **Would it be possible to change OrthoFinder so it simply ignores mentions of species that are commented out?**

```
Traceback (most recent call last):
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/orthofinder.py", line 1612, in <module>
    summaryText = GetOrthologues_FromTrees(orthologuesDir, options)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/orthofinder.py", line 1423, in GetOrthologues_FromTrees
    return orthologues.OrthologuesFromTrees(options.recon_method, groupsDir, workingDir, options.nBlast, options.speciesTreeFN, pickleDir=options.separatePickleDir)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/orthologues.py", line 971, in OrthologuesFromTrees
    ReconciliationAndOrthologues(recon_method, TreePatIDs, ogSet, speciesTree_fn, workingDir, resultsDir_new, reconTreesRenamedDir, nHighParallel, pickleDir=pickleDir)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/orthologues.py", line 913, in ReconciliationAndOrthologues
    nOrthologues_SpPair = trees2ologs_of.DoOrthologuesForOrthoFinder(ogSet, treesIDsPatFn, speciesTree_fn, trees2ologs_of.GeneToSpecies_dash, workingDir, resultsDir, reconTreesRenamedDir, all_stride_dup_genes)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 562, in DoOrthologuesForOrthoFinder
    orthologues, recon_tree, suspect_genes = GetOrthologues_from_tree(iog, treesIDsPatFn(iog), species_tree_rooted, GeneToSpecies, neighbours, dupsWriter=dupWriter, seqIDs=ogSet.Spec_SeqDict(), spIDs=ogSet.SpeciesDict(), all_stride_dup_genes=all_stride_dup_genes)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 290, in GetOrthologues_from_tree
    root = GetRoot(tree, species_tree_rooted, GeneToSpecies)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 271, in GetRoot
    roots = GetRoots(tree, species_tree_rooted, GeneToSpecies)
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 129, in GetRoots
    StoreSpeciesSets(tree, GeneMap, "inout_") # ingroup/outgroup identification
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 62, in StoreSpeciesSets
    node.add_feature(tag_down, {GeneMap(node.name)})
  File "/data/SBCS-BuggsLab/Josiah/OrthoFinder-2.2.6_source/scripts/trees2ologs_of.py", line 55, in GeneMap
    raise Exception
```

**Comment by davidemms** [comment]
Hi

Were the gene trees you want to use inferred with the species FRAX02 & FRAX34 included or excluded? To reanalyse the gene trees you'll have to include the same set of species in the SpeciesIDs.txt file as were used to infer the gene trees. Are you still getting a crash when you do that?

If you want to use a different a different set of species then you can use the -b option to re-infer the orthogroups and gene trees since the orthogroups can change if the set of species changes (since it's possible that the last common ancestor changes when the species set changes).

All the best
David

**Comment by josiahseaman** [comment]
Thank you David,
The excluded species are in the gene trees.  I was hoping it would simply ignore the tips with excluded species in them.  It sounds like you're saying that's a contradiction in definitions of orthogroups.  I will re-run with -b then and hope that the already computed blast pairs speed up the process.
Kind regards,
Josiah
