### ISSUE TITLE
Problem with writing orthogroups to file

### ISSUE THREAD

**Issue by NathanKenny** [davidemms/OrthoFinder#256]
Hi! Sorry to be a pain but we are having a problem with Orthofinder for one particular dataset, and I am having problems identifying the cause.

After the blast step, the clusters_OrthoFinder_I1.5.txt, clusters_OrthoFinder_I1.5.txt_id_pairs.txt and OrthoFinder_graph.txt files are created without a problem. However, the program then immediately finishes, showing what could be a python error (see below).

I have checked for symbols  (*, |, : etc) within the fasta files to ensure that this wasn't causing the problem, but I can't spot anything obvious

2019-04-16 23:43:37 : Initial processing of each species
2019-04-16 23:43:58 : Initial processing of species 5 complete
2019-04-16 23:44:03 : Initial processing of species 1 complete
2019-04-16 23:44:03 : Initial processing of species 7 complete
2019-04-16 23:44:12 : Initial processing of species 4 complete
2019-04-16 23:44:26 : Initial processing of species 3 complete
2019-04-16 23:44:38 : Initial processing of species 6 complete
2019-04-16 23:45:23 : Initial processing of species 0 complete
2019-04-16 23:45:29 : Initial processing of species 2 complete
2019-04-16 23:45:35 : Initial processing of species 8 complete
2019-04-16 23:45:38 : Initial processing of species 9 complete
2019-04-16 23:45:51 : Connected putatitive homologs
2019-04-16 23:45:56 : Written final scores for species 5 to graph file
2019-04-16 23:45:57 : Written final scores for species 1 to graph file
2019-04-16 23:45:57 : Written final scores for species 7 to graph file
2019-04-16 23:46:00 : Written final scores for species 4 to graph file
2019-04-16 23:46:03 : Written final scores for species 3 to graph file
2019-04-16 23:46:06 : Written final scores for species 6 to graph file
2019-04-16 23:46:12 : Written final scores for species 2 to graph file
2019-04-16 23:46:14 : Written final scores for species 0 to graph file
2019-04-16 23:46:16 : Written final scores for species 9 to graph file
2019-04-16 23:46:20 : Written final scores for species 8 to graph file
[mcl] cut <30> instances of overlap
2019-04-16 23:48:10 : Ran MCL

Writing orthogroups to file
---------------------------

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2015), Genome Biology 16:157

 If you use the species tree in your work then please also cite:
 Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
 Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101/267914
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1626, in <module>
  File "orthofinder/orthofinder.py", line 1307, in DoOrthogroups
  File "orthofinder/orthofinder.py", line 204, in WriteOrthogroupFiles
  File "orthofinder/scripts/util.py", line 379, in __init__
IndexError: list index out of range
Failed to execute script orthofinder

(there is no more output, and nothing in the Log file)

If you have any hints, I would be very grateful!

Many thanks,

Nathan

**Comment by NathanKenny** [comment]
Hi! I think I have worked this out - it was related to the names of the sequences in the fasta files - they needed a consistent name ahead of the specific one.

e.g. instead of 
>ABC
and
>DEF

they needed to be

>Hsap_ABC
and
>Hsap_DEF

Sorry for not noting this earlier!
