### ISSUE TITLE
OrthoFinder dies at 'Writing orthogroups to file'

### ISSUE THREAD

**Issue by davidemms** [davidemms/OrthoFinder#261]
Quoting message from @zhaotao1987:

Hi David,

Sorry to bother you. I got a similar problem like this: 

```
OrthoFinder version 2.3.1 Copyright (C) 2014 David Emms

2019-05-15 00:20:02 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Using previously calculated BLAST results in /ngsprojects/synnet/data_archive/Project_Trial/Arthur_trial/fix_blastfiles/fixed/

Running OrthoFinder algorithm
-----------------------------
2019-05-15 00:20:09 : Initial processing of each species
2019-05-15 00:21:06 : Initial processing of species 0 complete
2019-05-15 00:22:51 : Initial processing of species 1 complete
2019-05-15 00:23:40 : Initial processing of species 2 complete
2019-05-15 00:24:29 : Initial processing of species 3 complete
2019-05-15 00:25:30 : Initial processing of species 4 complete
2019-05-15 00:26:56 : Initial processing of species 5 complete
2019-05-15 00:27:53 : Initial processing of species 6 complete
2019-05-15 00:28:50 : Initial processing of species 7 complete
2019-05-15 00:29:34 : Initial processing of species 8 complete
2019-05-15 00:30:24 : Initial processing of species 9 complete
2019-05-15 00:31:51 : Connected putatitive homologs
2019-05-15 00:32:10 : Written final scores for species 0 to graph file
2019-05-15 00:32:45 : Written final scores for species 1 to graph file
2019-05-15 00:32:58 : Written final scores for species 2 to graph file
2019-05-15 00:33:14 : Written final scores for species 3 to graph file
2019-05-15 00:33:36 : Written final scores for species 4 to graph file
2019-05-15 00:34:09 : Written final scores for species 5 to graph file
2019-05-15 00:34:25 : Written final scores for species 6 to graph file
2019-05-15 00:34:45 : Written final scores for species 7 to graph file
2019-05-15 00:34:59 : Written final scores for species 8 to graph file
2019-05-15 00:35:18 : Written final scores for species 9 to graph file
**[mcl] cut <74> instances of overlap**
2019-05-15 00:38:44 : Ran MCL

Writing orthogroups to file
---------------------------

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2015), Genome Biology 16:157

 If you use the species tree in your work then please also cite:
 Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
 Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101/267914
**Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1646, in <module>
  File "orthofinder/orthofinder.py", line 1307, in DoOrthogroups
  File "orthofinder/orthofinder.py", line 204, in WriteOrthogroupFiles
  File "orthofinder/scripts/util.py", line 378, in __init__
ValueError: need more than 1 value to unpack
Failed to execute script orthofinder**
```

My command is like this : orthofinder -og -b fixed/

Thanks in advance for your help.

Best, Tao

**Comment by davidemms** [comment]
Hi Tao

The error message has occurred because there is a problem in the SequenceIDs.txt file. I'm guessing that the file has been manually edited? 

Make sure that each line looks something like this:
`0_4: gi|290752271|emb|CBH40242.1| NADH dependent flavin oxidoreductase [Mycoplasma agalactiae]`

i.e.
`seq_id: accession`

It might just be that there is a empty line at the end of the file in which case delete that (as that line won't be of the expected format).

Once that's fixed it should run fine. Let me know how you get on.

All the best
David

**Comment by zhaotao1987** [comment]
> Hi Tao
> 
> The error message has occurred because there is a problem in the SequenceIDs.txt file. I'm guessing that the file has been manually edited?
> 
> Make sure that each line looks something like this:
> `0_4: gi|290752271|emb|CBH40242.1| NADH dependent flavin oxidoreductase [Mycoplasma agalactiae]`
> 
> i.e.
> `seq_id: accession`
> 
> It might just be that there is a empty line at the end of the file in which case delete that (as that line won't be of the expected format).
> 
> Once that's fixed it should run fine. Let me know how you get on.
> 
> All the best
> David

Hi David:

Thank you so much for pointing this out! 
It worked. Indeed, I changed the SequencesIDs.txt at earlier step in a tab delimited step, and forgot to change it back. 
I now got the result files:

```     5360 May 15 11:18 Statistics_PerSpecies.csv
     1558 May 15 11:18 Statistics_Overall.csv
      696 May 15 11:18 Orthogroups_SpeciesOverlaps.csv
     1989 May 15 11:18 SingleCopyOrthogroups.txt
  3536305 May 15 11:18 Orthogroups.csv
  3265363 May 15 11:18 Orthogroups_UnassignedGenes.csv
   738956 May 15 11:18 Orthogroups.GeneCount.csv
  5733643 May 15 11:18 Orthogroups.txt
  4269773 May 15 11:18 clusters_OrthoFinder_v2.1.2_I1.5.txt_id_pairs.txt
  3476389 May 15 11:18 clusters_OrthoFinder_v2.1.2_I1.5.txt
 34685825 May 15 11:17 OrthoFinder_v2.1.2_graph.txt```
Log file: 
```
Running OrthoFinder algorithm
-----------------------------
2019-05-15 11:13:16 : Initial processing of each species
2019-05-15 11:13:32 : Initial processing of species 8 complete
2019-05-15 11:13:33 : Initial processing of species 3 complete
2019-05-15 11:13:34 : Initial processing of species 9 complete
2019-05-15 11:13:35 : Initial processing of species 7 complete
2019-05-15 11:13:35 : Initial processing of species 6 complete
2019-05-15 11:13:35 : Initial processing of species 2 complete
2019-05-15 11:13:36 : Initial processing of species 4 complete
2019-05-15 11:13:37 : Initial processing of species 0 complete
2019-05-15 11:13:46 : Initial processing of species 5 complete
2019-05-15 11:13:58 : Initial processing of species 1 complete
2019-05-15 11:14:08 : Connected putatitive homologs
2019-05-15 11:14:14 : Written final scores for species 8 to graph file
2019-05-15 11:14:14 : Written final scores for species 9 to graph file
2019-05-15 11:14:14 : Written final scores for species 6 to graph file
2019-05-15 11:14:14 : Written final scores for species 7 to graph file
2019-05-15 11:14:16 : Written final scores for species 4 to graph file
2019-05-15 11:14:15 : Written final scores for species 2 to graph file
2019-05-15 11:14:20 : Written final scores for species 5 to graph file
2019-05-15 11:14:23 : Written final scores for species 1 to graph file
2019-05-15 11:16:04 : Ran MCL

Writing orthogroups to file
---------------------------

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2015), Genome Biology 16:157

Orthogroups have been written to tab-delimited files:
   /ngsprojects/synnet/data_archive/Project_Trial/Arthur_trial/fix_blastfiles/fixed/Orthogroups.csv
   /ngsprojects/synnet/data_archive/Project_Trial/Arthur_trial/fix_blastfiles/fixed/Orthogroups.txt (OrthoMCL format)
   /ngsprojects/synnet/data_archive/Project_Trial/Arthur_trial/fix_blastfiles/fixed/Orthogroups_UnassignedGenes.csv
2019-05-15 11:16:10 : Done orthogroups

Orthogroup statistics:
   Statistics_PerSpecies.csv   Statistics_Overall.csv   Orthogroups_SpeciesOverlaps.csv

OrthoFinder assigned 236571 genes (70.6% of total) to 22011 orthogroups. Fifty percent of all genes were in orthogroups
with 11 or more genes (G50 was 11) and were contained in the largest 9036 orthogroups (O50 was 9036). There were 7972
orthogroups with all species present and 199 of these consisted entirely of single-copy genes.

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2015), Genome Biology 16:157
```
However, I still get one warning/ error message: 
`[mcl] cut <74> instances of overlap`

**Comment by davidemms** [comment]
Hi Tao

That's great, thanks for letting me know. The message from MCL is normal, it's just a report on how the clustering went.

All the best
David

**Comment by zhaotao1987** [comment]
> Hi Tao
> 
> That's great, thanks for letting me know. The message from MCL is normal, it's just a report on how the clustering went.
> 
> All the best
> David

Thank you very much for the help David, I am pretty happy about it. 

Best, Tao
