### ISSUE TITLE
[OrthoFinder-2.3.3] running error report

### ISSUE THREAD

**Issue by yyuangy** [davidemms/OrthoFinder#264]
Hi, I try to install the last release of OrthoFinder-2.3.3 on MacOS 10.12.6 with python 3.7.3.
When I ran "orthofinder -h", the error message "-bash: OrthoFinder-2.3.3/orthofinder: cannot execute binary file" was shown.
And if I ran the source version "python orthofinder.py -h", the following error message was shown.
---------------------
Traceback (most recent call last):
  File "OrthoFinder-2.3.3_source/orthofinder/orthofinder.py", line 27, in <module>
    from scripts import parallel_task_manager
  File "/Users/esspn/Software/OrthoFinder-2.3.3_source/orthofinder/scripts/parallel_task_manager.py", line 29, in <module>
    import Queue
ModuleNotFoundError: No module named 'Queue'
-----------------------

Could you help me to solve this problem?

**Comment by yyuangy** [comment]
When I changed the python 3.7.3 to python 2.7.16 and ran "python orthofinder.py -h" again, the error message was also shown as "OrthoFinder-2.3.3_source/orthofinder/orthofinder.py -h
Traceback (most recent call last):
  File "OrthoFinder-2.3.3_source/orthofinder/orthofinder.py", line 27, in <module>
    from scripts import parallel_task_manager
  File "/Users/esspn/Software/OrthoFinder-2.3.3_source/orthofinder/scripts/parallel_task_manager.py", line 31, in <module>
    import util
  File "/Users/esspn/Software/OrthoFinder-2.3.3_source/orthofinder/scripts/util.py", line 31, in <module>
    import numpy as np
ImportError: No module named numpy".

**Comment by yyuangy** [comment]
I fixed the running errors by installing SciPy package.

**Comment by davidemms** [comment]
Hi

Sorry I didn't respond to this earlier, I've been away for the last week. Thanks very much for posting the steps you took to resolve it, that's very useful for other users who might have the same problem!

All the best
David
