### ISSUE TITLE
I am new to bioinformatics and while running the orthoFnder I find the following problem, could you please help me to resolve the issue.

### ISSUE THREAD

**Issue by lakshmansahoo** [davidemms/OrthoFinder#283]

**Comment by davidemms** [comment]
The message from the user was:

Traceback (most recent call last): File "/apps/scratch/source/OrthoFinder-2.3.3/orthofinder/orthofinder.py", line 1649, in <module> statsFile, summaryText, orthogroupsResultsFilesString = DoOrthogroups(options, speciesInfoObj, seqsInfo) File "/apps/scratch/source/OrthoFinder-2.3.3/orthofinder/orthofinder.py", line 1320, in DoOrthogroups idsDict = MCL.WriteOrthogroupFiles(ogs, [scripts.files.FileHandler.GetSequenceIDsFN()], resultsBaseFilename, clustersFilename_pairs) File "/apps/scratch/source/OrthoFinder-2.3.3/orthofinder/orthofinder.py", line 213, in WriteOrthogroupFiles idExtract = util.FirstWordExtractor(idsFilename) File "/home/apps/scratch/source/OrthoFinder-2.3.3/orthofinder/scripts/util.py", line 391, in __init__ accession = rest.split(None, 1)[0] IndexError: list index out of range

**Comment by davidemms** [comment]
Hi

A couple of things to check first of all:
Is this on the Example Dataset or your own dataset?
If it's your own dataset, have you successfully run OrthoFinder on the Example Dataset first?

Looking at the error message, OrthoFinder is complaining because it is looking in the file it created (WorkingDirectory/SequenceIDs.txt) of sequence accession lines from the input fasta files and one of the accession lines appears to be blank. We're any of the accession lines in your input files blank, i.e. had no text after the ">" symbol?

All the best
David
