### ISSUE TITLE
Error: A duplicate accession was found using just first part

### ISSUE THREAD

**Issue by majogomezhughes** [davidemms/OrthoFinder#298]
Good morning, I have been encountering an error while running OrthoFinder and I can't find out why. I have tried using different versions of OrthoFinder, but this error persists:

`OrthoFinder version 2.3.7 Copyright (C) 2014 David Emms

2019-10-27 21:20:10 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "muscle" - ok
Test can run "FastTree /hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Species/OrthoFinder/Results_Oct27_2/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2019-10-27 21:20:18 : Creating diamond database 1 of 16
2019-10-27 21:20:19 : Creating diamond database 2 of 16
2019-10-27 21:20:19 : Creating diamond database 3 of 16
2019-10-27 21:20:20 : Creating diamond database 4 of 16
2019-10-27 21:20:20 : Creating diamond database 5 of 16
2019-10-27 21:20:20 : Creating diamond database 6 of 16
2019-10-27 21:20:21 : Creating diamond database 7 of 16
2019-10-27 21:20:21 : Creating diamond database 8 of 16
2019-10-27 21:20:21 : Creating diamond database 9 of 16
2019-10-27 21:20:21 : Creating diamond database 10 of 16
2019-10-27 21:20:22 : Creating diamond database 11 of 16
2019-10-27 21:20:22 : Creating diamond database 12 of 16
2019-10-27 21:20:22 : Creating diamond database 13 of 16
2019-10-27 21:20:23 : Creating diamond database 14 of 16
2019-10-27 21:20:23 : Creating diamond database 15 of 16
2019-10-27 21:20:23 : Creating diamond database 16 of 16

Running diamond all-versus-all
------------------------------
Using 8 thread(s)
2019-10-27 21:20:23 : This may take some time....
2019-10-27 21:20:23 : Done 0 of 256
2019-10-27 22:38:24 : Done 100 of 256
2019-10-27 23:35:06 : Done 200 of 256
2019-10-28 00:02:21 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2019-10-28 00:02:24 : Initial processing of each species
2019-10-28 00:05:00 : Initial processing of species 0 complete
2019-10-28 00:06:31 : Initial processing of species 1 complete
2019-10-28 00:08:07 : Initial processing of species 2 complete
2019-10-28 00:09:46 : Initial processing of species 3 complete
2019-10-28 00:10:46 : Initial processing of species 4 complete
2019-10-28 00:12:14 : Initial processing of species 5 complete
2019-10-28 00:13:29 : Initial processing of species 6 complete
2019-10-28 00:14:54 : Initial processing of species 7 complete
2019-10-28 00:16:23 : Initial processing of species 8 complete
2019-10-28 00:17:48 : Initial processing of species 9 complete
2019-10-28 00:19:14 : Initial processing of species 10 complete
2019-10-28 00:20:35 : Initial processing of species 11 complete
2019-10-28 00:22:26 : Initial processing of species 12 complete
2019-10-28 00:23:46 : Initial processing of species 13 complete
2019-10-28 00:25:15 : Initial processing of species 14 complete
2019-10-28 00:26:55 : Initial processing of species 15 complete
2019-10-28 00:28:46 : Connected putative homologues
2019-10-28 00:29:11 : Written final scores for species 0 to graph file
2019-10-28 00:29:25 : Written final scores for species 1 to graph file
2019-10-28 00:29:40 : Written final scores for species 2 to graph file
2019-10-28 00:29:56 : Written final scores for species 3 to graph file
2019-10-28 00:30:06 : Written final scores for species 4 to graph file
2019-10-28 00:30:20 : Written final scores for species 5 to graph file
2019-10-28 00:30:32 : Written final scores for species 6 to graph file
2019-10-28 00:30:48 : Written final scores for species 7 to graph file
2019-10-28 00:31:04 : Written final scores for species 8 to graph file
2019-10-28 00:31:18 : Written final scores for species 9 to graph file
2019-10-28 00:31:31 : Written final scores for species 10 to graph file
2019-10-28 00:31:44 : Written final scores for species 11 to graph file
2019-10-28 00:32:03 : Written final scores for species 12 to graph file
2019-10-28 00:32:16 : Written final scores for species 13 to graph file
2019-10-28 00:32:30 : Written final scores for species 14 to graph file
2019-10-28 00:32:46 : Written final scores for species 15 to graph file
2019-10-28 00:34:59 : Ran MCL

Writing orthogroups to file
---------------------------
A duplicate accession was found using just first part: MGP_SPRETEiJ_G0002246|MGP_SPRETEiJ_G0002246.1|408
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

ERROR: /hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Species/OrthoFinder/Results_Oct27_2/WorkingDirectory/SequenceIDs.txt contains a duplicate ID. The IDs for the orthogroups in /hpcfs/home/mj.g
omez12/files/Secuencias/Genome_Analyses/cafe/Species/OrthoFinder/Results_Oct27_2/WorkingDirectory/clusters_OrthoFinder_I1.5.txt_id_pairs.txt will not be replaced with the sequence accessions. If /hpcfs/home/mj
.gomez12/files/Secuencias/Genome_Analyses/cafe/Species/OrthoFinder/Results_Oct27_2/WorkingDirectory/SequenceIDs.txt was prepared manually then please check the IDs are correct. 
ERROR: An error occurred, please review error messages for more information.`

The script I have been using is the following:

`./orthofinder/orthofinder.py -f ../cafe/Species/ -M msa -A muscle -T fasttree -t 8 -S diamond
`

Thank you so much for your help!

**Comment by davidemms** [comment]
Hi

That's odd, this was produced using a new analysis started with "-f", as in your command above? Could you send me the /Results_Oct27_2/WorkingDirectory/SequenceIDs.txt file it's complaining about and also the Results_Oct27_2/Log.txt file and I'll take a look. My email is at the top of the orthofinder.py file.

All the best
David

**Comment by davidemms** [comment]
Hi Maria

Thanks for sending me the files. Looking at the sequence accessions the problem is that there are a large number of sequences that have the same accession, e.g. "ENSMMMG00000013163|ENSMMMG00000013163.1|972" appears 10 times. This means that it wouldn't be possible to uniquely identify the sequences. For example, OrthoFinder could say that "ENSMMMG00000013163|ENSMMMG00000013163.1|972" is an ortholog of gene Y, but then you wouldn't know which one it was talking about. You'll need to use unique accessions for each of the input sequences, even if it's a single number after each of your original accessions in order to identify them. I'll send you a file of the repeated accessions I found in case that is helpful. I'll also change the error message in OrthoFinder so that it's more obvious what the problem is.

All the best
David

**Comment by davidemms** [comment]
Hi Maria

A correction, although the issue mentioned above isn't best practice I think OrthoFinder will still allow it. The actual issue in this case is that for the input file identified as Species 14 in WorkingDirectory/SpeciesIDs.txt there appears to be a blank accession line at the end of the file.

All the best
David

**Comment by majogomezhughes** [comment]
Hi David! 
Thank you so much for your help, it did solve the problem. Now Orthofinder is running fine, but is encountering a new problem. Apparently, one of the alignments doesn't exist so it's stopping the program. Do you know what can be done for this? Thank you so much again!

`OrthoFinder version 2.3.3 Copyright (C) 2014 David Emms

2019-11-02 12:41:00 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "muscle" - ok
Test can run "FastTree /hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Using previously calculated BLAST results in /hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory/

Running OrthoFinder algorithm
-----------------------------
2019-11-02 12:41:13 : Initial processing of each species
2019-11-02 12:48:35 : Initial processing of species 0 complete
2019-11-02 12:53:28 : Initial processing of species 1 complete
2019-11-02 12:59:56 : Initial processing of species 2 complete
2019-11-02 13:06:29 : Initial processing of species 3 complete
2019-11-02 13:13:02 : Initial processing of species 4 complete
2019-11-02 13:18:59 : Initial processing of species 5 complete
2019-11-02 13:24:49 : Initial processing of species 6 complete
2019-11-02 13:31:52 : Initial processing of species 7 complete
2019-11-02 13:37:24 : Initial processing of species 8 complete
2019-11-02 13:45:50 : Initial processing of species 9 complete
2019-11-02 13:52:29 : Initial processing of species 10 complete
2019-11-02 13:58:25 : Initial processing of species 11 complete
2019-11-02 14:05:13 : Initial processing of species 12 complete
2019-11-02 14:12:42 : Initial processing of species 13 complete
2019-11-02 14:18:52 : Initial processing of species 14 complete
2019-11-02 14:25:37 : Initial processing of species 15 complete
2019-11-02 14:36:29 : Initial processing of species 16 complete
2019-11-02 14:51:26 : Initial processing of species 17 complete
2019-11-02 15:02:20 : Initial processing of species 18 complete
2019-11-02 15:11:19 : Initial processing of species 19 complete
2019-11-02 15:23:02 : Initial processing of species 20 complete
2019-11-02 15:29:37 : Initial processing of species 21 complete
2019-11-02 15:36:07 : Initial processing of species 22 complete
2019-11-02 15:45:53 : Initial processing of species 23 complete
2019-11-02 15:52:53 : Initial processing of species 24 complete
2019-11-02 15:59:55 : Initial processing of species 25 complete
2019-11-02 16:06:46 : Initial processing of species 26 complete
2019-11-02 16:14:00 : Initial processing of species 27 complete
2019-11-02 16:26:25 : Connected putatitive homologs

WARNING: program called by OrthoFinder produced output to stderr

Command: ['mcl', '/hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory/OrthoFinder/Results_Nov02/WorkingDirectory/OrthoFinder_graph.txt', '-
I', '1.5', '-o', '/hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory/OrthoFinder/Results_Nov02/WorkingDirectory/clusters_OrthoFinder_I1.5.
txt', '-te', '1', '-V', 'all']

stdout
------

stderr
------
[mcl] cut <85> instances of overlap

2019-11-02 17:30:24 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory/OrthoFinder/Results_Nov02/Orthogroups/Orthogroups.tsv
   /hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory/OrthoFinder/Results_Nov02/Orthogroups/Orthogroups.txt (OrthoMCL format)
   /hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory/OrthoFinder/Results_Nov02/Orthogroups/Orthogroups_UnassignedGenes.tsv
Sequences for orthogroups:
   /hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory/OrthoFinder/Results_Nov02/Orthogroup_Sequences/

2019-11-02 17:34:11 : Done orthogroups

Analysing Orthogroups
=====================
2019-11-02 17:34:14 : Starting MSA/Trees
Species tree: Using 860 orthogroups with minimum of 78.6% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2019-11-02 17:38:18 : Done 100 of 860
2019-11-02 17:39:03 : Done 200 of 860
2019-11-02 17:41:00 : Done 500 of 860
2019-11-02 17:42:43 : Done 800 of 860
2019-11-02 17:42:09 : Done 700 of 860
2019-11-02 17:37:20 : Done 0 of 860
2019-11-02 17:39:42 : Done 300 of 860
2019-11-02 17:40:20 : Done 400 of 860
2019-11-02 17:41:37 : Done 600 of 860

Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
2019-11-02 20:34:00 : Done 1000 of 29499
2019-11-03 01:15:41 : Done 8000 of 29499
2019-11-03 02:58:22 : Done 15000 of 29499
2019-11-03 03:05:02 : Done 16000 of 29499
2019-11-03 03:12:47 : Done 21000 of 29499
2019-11-03 03:16:01 : Done 27000 of 29499
2019-11-03 00:27:10 : Done 6000 of 29499
2019-11-03 02:27:48 : Done 12000 of 29499
2019-11-02 22:42:14 : Done 3000 of 29499
2019-11-03 02:14:52 : Done 11000 of 29499
2019-11-03 02:49:46 : Done 14000 of 29499
2019-11-03 03:14:26 : Done 24000 of 29499
2019-11-03 03:16:40 : Done 29000 of 29499
2019-11-03 03:08:15 : Done 17000 of 29499
2019-11-03 03:10:02 : Done 18000 of 29499
2019-11-03 03:14:59 : Done 25000 of 29499
2019-11-02 23:21:25 : Done 4000 of 29499
2019-11-03 02:40:13 : Done 13000 of 29499
2019-11-03 03:13:21 : Done 22000 of 29499
2019-11-03 03:15:31 : Done 26000 of 29499
2019-11-03 03:16:24 : Done 28000 of 29499
2019-11-02 21:47:23 : Done 2000 of 29499
2019-11-02 23:56:48 : Done 5000 of 29499
2019-11-03 00:53:35 : Done 7000 of 29499
2019-11-03 01:35:02 : Done 9000 of 29499
2019-11-03 01:56:51 : Done 10000 of 29499
2019-11-03 03:11:15 : Done 19000 of 29499
2019-11-03 03:13:54 : Done 23000 of 29499
2019-11-02 17:45:43 : Done 0 of 29499
2019-11-03 03:12:08 : Done 20000 of 29499
Traceback (most recent call last):
  File "/hpcfs/home/mj.gomez12/.conda/envs/orthofinder-env/bin/orthofinder", line 1672, in <module>
    GetOrthologues(speciesInfoObj, options, program_caller, orthogroupsResultsFilesString)
  File "/hpcfs/home/mj.gomez12/.conda/envs/orthofinder-env/bin/orthofinder", line 1482, in GetOrthologues
    options.name)
  File "/hpcfs/home/mj.gomez12/.conda/envs/orthofinder-env/bin/scripts/orthologues.py", line 906, in OrthologuesWorkflow
    seqs_alignments_dirs = treeGen.DoTrees(ogSet.OGs(qInclAll=True), ogSet.OrthogroupMatrix(), ogSet.Spec_SeqDict(), ogSet.SpeciesDict(), ogSet.speciesToUse, nHighParallel, qStopAfterSeqs, qStopAfterAlign or q
Phyldog, qDoSpeciesTree=qDoMSASpeciesTree) 
  File "/hpcfs/home/mj.gomez12/.conda/envs/orthofinder-env/bin/scripts/trees_msa.py", line 391, in DoTrees
    self.RenameAlignmentTaxa(alignmentFilesToUse, accessionAlignmentFNs, idDict)
  File "/hpcfs/home/mj.gomez12/.conda/envs/orthofinder-env/bin/scripts/trees_msa.py", line 299, in RenameAlignmentTaxa
    with open(alignFN, 'rb') as infile, open(outAlignFN, 'wb') as outfile:
IOError: [Errno 2] No such file or directory: '/hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory/OrthoFinder/Results_Nov02/WorkingDirecto
ry/Alignments_ids/OG0008644.fa'
2019-11-02 16:27:41 : Written final scores for species 0 to graph file
2019-11-02 16:28:37 : Written final scores for species 1 to graph file
2019-11-02 16:29:51 : Written final scores for species 2 to graph file
2019-11-02 16:31:05 : Written final scores for species 3 to graph file
2019-11-02 16:32:17 : Written final scores for species 4 to graph file
2019-11-02 16:33:21 : Written final scores for species 5 to graph file
2019-11-02 16:34:23 : Written final scores for species 6 to graph file
2019-11-02 16:35:40 : Written final scores for species 7 to graph file
2019-11-02 16:36:41 : Written final scores for species 8 to graph file
2019-11-02 16:38:15 : Written final scores for species 9 to graph file
2019-11-02 16:39:21 : Written final scores for species 10 to graph file
2019-11-02 16:40:25 : Written final scores for species 11 to graph file
2019-11-02 16:41:39 : Written final scores for species 12 to graph file
2019-11-02 16:42:57 : Written final scores for species 13 to graph file
2019-11-02 16:44:03 : Written final scores for species 14 to graph file
2019-11-02 16:45:15 : Written final scores for species 15 to graph file
2019-11-02 16:47:17 : Written final scores for species 16 to graph file
2019-11-02 16:50:04 : Written final scores for species 17 to graph file
2019-11-02 16:52:09 : Written final scores for species 18 to graph file
2019-11-02 16:53:45 : Written final scores for species 19 to graph file
2019-11-02 16:55:54 : Written final scores for species 20 to graph file
2019-11-02 16:57:20 : Written final scores for species 21 to graph file
2019-11-02 16:58:34 : Written final scores for species 22 to graph file
2019-11-02 17:00:18 : Written final scores for species 23 to graph file
2019-11-02 17:01:31 : Written final scores for species 24 to graph file
2019-11-02 17:02:53 : Written final scores for species 25 to graph file
2019-11-02 17:04:03 : Written final scores for species 26 to graph file
2019-11-02 17:05:22 : Written final scores for species 27 to graph file`

**Comment by davidemms** [comment]
Hi

Thanks for letting me know about this, I'll submit a fix so that OrthoFinder can handle the MSA failing for an orthogroup.

All the best
David

**Comment by majogomezhughes** [comment]
Hi David, 

So I tried running OrthoFinder again with the new fix, but now it's giving me this:

`
OrthoFinder version 2.3.7 Copyright (C) 2014 David Emms

2019-11-07 02:51:46 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "muscle" - ok
Test can run "FastTree /hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Using previously calculated BLAST results in /hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/Protein_sequences/OrthoFinder/Results_Oct31/WorkingDirectory/

Running OrthoFinder algorithm
-----------------------------
2019-11-07 02:52:03 : Initial processing of each species
2019-11-07 02:59:42 : Initial processing of species 0 complete
2019-11-07 03:04:42 : Initial processing of species 1 complete
2019-11-07 03:11:42 : Initial processing of species 2 complete
2019-11-07 03:18:36 : Initial processing of species 3 complete
2019-11-07 03:25:31 : Initial processing of species 4 complete
2019-11-07 03:31:42 : Initial processing of species 5 complete
2019-11-07 03:37:53 : Initial processing of species 6 complete
2019-11-07 03:45:08 : Initial processing of species 7 complete
2019-11-07 03:51:15 : Initial processing of species 8 complete
2019-11-07 03:59:42 : Initial processing of species 9 complete
2019-11-07 04:06:15 : Initial processing of species 10 complete
2019-11-07 04:12:21 : Initial processing of species 11 complete
2019-11-07 04:19:21 : Initial processing of species 12 complete
2019-11-07 04:27:05 : Initial processing of species 13 complete
2019-11-07 04:33:24 : Initial processing of species 14 complete
2019-11-07 04:40:15 : Initial processing of species 15 complete
2019-11-07 04:51:42 : Initial processing of species 16 complete
2019-11-07 05:07:33 : Initial processing of species 17 complete
2019-11-07 05:18:46 : Initial processing of species 18 complete
2019-11-07 05:27:53 : Initial processing of species 19 complete
2019-11-07 05:39:38 : Initial processing of species 20 complete
2019-11-07 05:46:14 : Initial processing of species 21 complete
2019-11-07 05:52:45 : Initial processing of species 22 complete
2019-11-07 06:02:53 : Initial processing of species 23 complete
2019-11-07 06:10:07 : Initial processing of species 24 complete
2019-11-07 06:17:20 : Initial processing of species 25 complete
2019-11-07 06:24:08 : Initial processing of species 26 complete
2019-11-07 06:31:41 : Initial processing of species 27 complete
2019-11-07 06:44:50 : Connected putative homologues
2019-11-07 06:46:05 : Written final scores for species 0 to graph file
2019-11-07 06:46:56 : Written final scores for species 1 to graph file
2019-11-07 06:48:02 : Written final scores for species 2 to graph file
2019-11-07 06:49:11 : Written final scores for species 3 to graph file
2019-11-07 06:50:20 : Written final scores for species 4 to graph file
2019-11-07 06:51:24 : Written final scores for species 5 to graph file
2019-11-07 06:52:29 : Written final scores for species 6 to graph file
2019-11-07 06:53:40 : Written final scores for species 7 to graph file
2019-11-07 06:54:44 : Written final scores for species 8 to graph file
2019-11-07 06:56:16 : Written final scores for species 9 to graph file
2019-11-07 06:57:26 : Written final scores for species 10 to graph file
2019-11-07 06:58:33 : Written final scores for species 11 to graph file
2019-11-07 06:59:48 : Written final scores for species 12 to graph file
2019-11-07 07:01:06 : Written final scores for species 13 to graph file
2019-11-07 07:02:13 : Written final scores for species 14 to graph file
2019-11-07 07:03:24 : Written final scores for species 15 to graph file
2019-11-07 07:05:29 : Written final scores for species 16 to graph file
2019-11-07 07:08:15 : Written final scores for species 17 to graph file
2019-11-07 07:10:20 : Written final scores for species 18 to graph file
2019-11-07 07:12:02 : Written final scores for species 19 to graph file
2019-11-07 07:14:14 : Written final scores for species 20 to graph file
2019-11-07 07:15:30 : Written final scores for species 21 to graph file
2019-11-07 07:16:42 : Written final scores for species 22 to graph file
2019-11-07 07:18:30 : Written final scores for species 23 to graph file
2019-11-07 07:19:46 : Written final scores for species 24 to graph file
2019-11-07 07:21:02 : Written final scores for species 25 to graph file
2019-11-07 07:22:14 : Written final scores for species 26 to graph file
2019-11-07 07:23:31 : Written final scores for species 27 to graph file
2019-11-07 07:37:49 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 884717 genes (98.5% of total) to 33165
orthogroups. Fifty percent of all genes were in orthogroups
with 44 or more genes (G50 was 44) and were contained in the
largest 6292 orthogroups (O50 was 6292). There were 6639
orthogroups with all species present and 44 of these
consisted entirely of single-copy genes.

2019-11-07 07:41:45 : Done orthogroups

Analysing Orthogroups
=====================
2019-11-07 07:41:49 : Starting MSA/Trees
Species tree: Using 858 orthogroups with minimum of 78.6% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2019-11-07 07:47:21 : Done 300 of 858
2019-11-07 07:46:02 : Done 100 of 858
2019-11-07 07:48:36 : Done 500 of 858
2019-11-07 07:49:10 : Done 600 of 858
2019-11-07 07:45:14 : Done 0 of 858
2019-11-07 07:47:58 : Done 400 of 858
2019-11-07 07:50:10 : Done 800 of 858
2019-11-07 07:49:40 : Done 700 of 858
2019-11-07 07:46:43 : Done 200 of 858

Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
2019-11-07 10:40:33 : Done 1000 of 32308
2019-11-07 14:28:30 : Done 6000 of 32308
2019-11-07 17:14:02 : Done 21000 of 32308
2019-11-07 17:17:46 : Done 28000 of 32308
2019-11-07 07:52:55 : Done 0 of 32308
2019-11-07 14:55:07 : Done 7000 of 32308
2019-11-07 16:28:06 : Done 12000 of 32308
2019-11-07 17:14:41 : Done 22000 of 32308
2019-11-07 13:57:58 : Done 5000 of 32308
2019-11-07 15:17:05 : Done 8000 of 32308
2019-11-07 17:15:12 : Done 23000 of 32308
2019-11-07 17:18:10 : Done 29000 of 32308
2019-11-07 12:46:17 : Done 3000 of 32308
2019-11-07 16:50:13 : Done 14000 of 32308
2019-11-07 17:09:06 : Done 17000 of 32308
2019-11-07 17:16:13 : Done 25000 of 32308
2019-11-07 17:18:25 : Done 30000 of 32308
2019-11-07 17:18:39 : Done 31000 of 32308
2019-11-07 17:11:00 : Done 18000 of 32308
2019-11-07 17:13:20 : Done 20000 of 32308
2019-11-07 17:17:16 : Done 27000 of 32308
2019-11-07 11:49:33 : Done 2000 of 32308
2019-11-07 16:15:10 : Done 11000 of 32308
2019-11-07 16:40:01 : Done 13000 of 32308
2019-11-07 17:12:15 : Done 19000 of 32308
2019-11-07 15:36:00 : Done 9000 of 32308
2019-11-07 17:05:54 : Done 16000 of 32308
2019-11-07 17:15:42 : Done 24000 of 32308
2019-11-07 17:18:54 : Done 32000 of 32308
2019-11-07 13:24:24 : Done 4000 of 32308
2019-11-07 15:56:59 : Done 10000 of 32308
2019-11-07 16:58:53 : Done 15000 of 32308
2019-11-07 17:16:43 : Done 26000 of 32308
2019-11-07 17:24:17 : Done MSA/Trees

Best outgroup(s) for species tree
---------------------------------
2019-11-07 17:24:17 : Starting STRIDE
2019-11-07 17:25:09 : Done STRIDE
Observed 538 well-supported, non-terminal duplications. 536 support the best roots and 2 contradict them.
Best outgroups for species tree:
  Ictidomys_tridecemlineatus.SpeTri2.0.pep.all, Spermophilus_dauricus.ASM240643v1.pep.all, Urocitellus_parryii.ASM342692v1.pep.all, Octodon_degus.OctDeg1.0.pep.all, Oryctolagus_cuniculus.OryCun2.0.pep.all, Cav
ia_aperea.CavAp1.0.pep.all, Chinchilla_lanigera.ChiLan1.0.pep.all, Cavia_porcellus.Cavpor3.0.pep.all, Heterocephalus_glaber_male.HetGla_1.0.pep.all, Fukomys_damarensis.DMR_v1.0.pep.all, Hydrochoerus_isthmius.H
ydIst_v1, Hydrochoerus_hydrochaeris.HydHyd_v1, Marmota_marmota_marmota.marMar2.1.pep.all
  Peromyscus_maniculatus_bairdii.HU_Pman_2.1.pep.all, Rattus_norvegicus.Rnor_6.0.pep.all, Meriones_unguiculatus.MunDraft-v1.0.pep.all, Mus_spretus.SPRET_EiJ_v1.pep.all, Nannospalax_galili.S.galili_v1.0.pep.all
, Mus_musculus.GRCm38.pep.all, Mus_caroli.CAROLI_EIJ_v1.1.pep.all, Mus_spicilegus.MUSP714.pep.all, Mus_pahari.PAHARI_EIJ_v1.1.pep.all, Cricetulus_griseus_crigri.CriGri_1.0.pep.all, Jaculus_jaculus.JacJac1.0.pe
p.all, Microtus_ochrogaster.MicOch1.0.pep.all, Mesocricetus_auratus.MesAur1.0.pep.all
  Octodon_degus.OctDeg1.0.pep.all, Oryctolagus_cuniculus.OryCun2.0.pep.all, Cavia_aperea.CavAp1.0.pep.all, Chinchilla_lanigera.ChiLan1.0.pep.all, Cavia_porcellus.Cavpor3.0.pep.all, Heterocephalus_glaber_male.H
etGla_1.0.pep.all, Fukomys_damarensis.DMR_v1.0.pep.all, Hydrochoerus_isthmius.HydIst_v1, Hydrochoerus_hydrochaeris.HydHyd_v1
  Ictidomys_tridecemlineatus.SpeTri2.0.pep.all, Spermophilus_dauricus.ASM240643v1.pep.all, Urocitellus_parryii.ASM342692v1.pep.all, Marmota_marmota_marmota.marMar2.1.pep.all
  Castor_canadensis.C.can_genome_v1.0.pep.all, Dipodomys_ordii.Dord_2.0.pep.all

WARNING: Multiple potential species tree roots were identified, only one will be analyed.

Reconciling gene trees and species tree
---------------------------------------
Outgroup: Ictidomys_tridecemlineatus.SpeTri2.0.pep.all, Spermophilus_dauricus.ASM240643v1.pep.all, Urocitellus_parryii.ASM342692v1.pep.all, Octodon_degus.OctDeg1.0.pep.all, Oryctolagus_cuniculus.OryCun2.0.pep.
all, Cavia_aperea.CavAp1.0.pep.all, Chinchilla_lanigera.ChiLan1.0.pep.all, Cavia_porcellus.Cavpor3.0.pep.all, Heterocephalus_glaber_male.HetGla_1.0.pep.all, Fukomys_damarensis.DMR_v1.0.pep.all, Hydrochoerus_is
thmius.HydIst_v1, Hydrochoerus_hydrochaeris.HydHyd_v1, Marmota_marmota_marmota.marMar2.1.pep.all
2019-11-07 17:25:09 : Starting Recon and orthologues
2019-11-07 17:25:09 : Starting OF Orthologues
2019-11-07 17:25:41 : Done 0 of 27120
2019-11-07 17:33:54 : Done 1000 of 27120
2019-11-07 17:37:19 : Done 2000 of 27120
2019-11-07 17:40:01 : Done 3000 of 27120
2019-11-07 17:42:24 : Done 4000 of 27120
2019-11-07 17:44:39 : Done 5000 of 27120
2019-11-07 17:46:37 : Done 6000 of 27120
2019-11-07 17:48:32 : Done 7000 of 27120
2019-11-07 17:50:19 : Done 8000 of 27120
Traceback (most recent call last):
  File "./OrthoFinder/orthofinder/orthofinder.py", line 1688, in <module>
    GetOrthologues(speciesInfoObj, options, program_caller)
  File "./OrthoFinder/orthofinder/orthofinder.py", line 1502, in GetOrthologues
    options.name)
  File "/hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/OrthoFinder/orthofinder/scripts/orthologues.py", line 1002, in OrthologuesWorkflow
    ReconciliationAndOrthologues(recon_method, db.ogSet, nHighParallel, i if qMultiple else None, all_stride_dup_genes=all_stride_dup_genes) 
  File "/hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/OrthoFinder/orthofinder/scripts/orthologues.py", line 800, in ReconciliationAndOrthologues
    nOrthologues_SpPair = trees2ologs_of.DoOrthologuesForOrthoFinder(ogSet, speciesTree_ids_fn, trees2ologs_of.GeneToSpecies_dash, all_stride_dup_genes, qNoRecon)
  File "/hpcfs/home/mj.gomez12/files/Secuencias/Genome_Analyses/cafe/OrthoFinder/orthofinder/scripts/trees2ologs_of.py", line 644, in DoOrthologuesForOrthoFinder
    rooted_tree_ids, qHaveSupport = CheckAndRootTree(files.FileHandler.GetOGsTreeFN(iog), species_tree_rooted, GeneToSpecies) # this can be parallelised easily
TypeError: 'NoneType' object is not iterable
`

I don't know if this may be coming from the same problem as the last one?

Thank you for your help!

**Comment by davidemms** [comment]
Hi 

Sorry about this and thanks for reporting it. I've submitted a fix to a new branch "python2.7_support" as I'm currently moving the code over to support both python 3 and python 2.7. You can download the python 2.7 branch with the fix by e.g. going to the main page and selecting the branch with the button on the left hand side.

Also, if you're able to identify the input "Orthogroup Sequences" file that caused the failed MSA I'd be curious to see it and see what the problem is as I've not encountered this before.

Many thanks
David

**Comment by davidemms** [comment]
Hi

This fix is now in the new release, version 2.3.8.

All the best
David
