### ISSUE TITLE
OSError: [Errno 39] Directory not empty

### ISSUE THREAD

**Issue by ajwnewkirk** [davidemms/OrthoFinder#30]
I'm attempting to get OrthoFinder working on my group's CentOS 7 system. When running the example data set I'm seeing:

conda run -- python orthofinder/orthofinder.py -f orthofinder/ExampleDataset/
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....

OrthoFinder version 1.0.3 Copyright (C) 2014 David Emms

    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.
    For details please see the License.md that came with this software.

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

1. Checking required programs are installed
-------------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok

2. Temporarily renaming sequences with unique, simple identifiers
------------------------------------------------------------------

3. Dividing up work for BLAST for parallel processing
-----------------------------------------------------
2016-09-12 15:28:00 : Creating Blast database 1 of 4
2016-09-12 15:28:00 : Creating Blast database 2 of 4
2016-09-12 15:28:00 : Creating Blast database 3 of 4
2016-09-12 15:28:00 : Creating Blast database 4 of 4

4. Running BLAST all-versus-all
-------------------------------
Using 16 thread(s)
2016-09-12 15:28:00 : This may take some time....
2016-09-12 15:28:00 : Done 0 of 16

5. Running OrthoFinder algorithm
--------------------------------
2016-09-12 15:28:15 : Initial processing of each species
2016-09-12 15:28:15 : Initial processing of species 0 complete
2016-09-12 15:28:15 : Initial processing of species 1 complete
2016-09-12 15:28:16 : Initial processing of species 2 complete
2016-09-12 15:28:16 : Initial processing of species 3 complete
2016-09-12 15:28:21 : Connected putatitive homologs
2016-09-12 15:28:21 : Writen final scores for species 0 to graph file
2016-09-12 15:28:21 : Writen final scores for species 1 to graph file
2016-09-12 15:28:21 : Writen final scores for species 2 to graph file
2016-09-12 15:28:21 : Writen final scores for species 3 to graph file
2016-09-12 15:28:22 : Ran MCL

6. Writing orthogroups to file
------------------------------
Orthogroups have been written to tab-delimited files:
   /scicomp/home/user/bin/OrthoFinder-master/orthofinder/ExampleDataset/Results_Sep12/Orthogroups.csv
   /scicomp/home/user/bin/OrthoFinder-master/orthofinder/ExampleDataset/Results_Sep12/Orthogroups.txt (OrthoMCL format)
   /scicomp/home/user/bin/OrthoFinder-master/orthofinder/ExampleDataset/Results_Sep12/Orthogroups_UnassignedGenes.csv

Running Orthologue Prediction
=============================

1. Checking required programs are installed
-------------------------------------------
Test can run "fastme -i /scicomp/home/user/bin/OrthoFinder-master/orthofinder/ExampleDataset/Results_Sep12/WorkingDirectory/SimpleTest.phy -o /scicomp/home/user/bin/OrthoFinder-master/orthofinder/ExampleDataset/Results_Sep12/WorkingDirectory/SimpleTest.tre" - ok
Test can run "dlcpar_search --version" - ok

2. Calculating gene distances
-----------------------------
2016-09-12 15:28:24 : Done 0 of 16
2016-09-12 15:28:25 : Processing species 0
2016-09-12 15:28:25 : Processing species 1
2016-09-12 15:28:25 : Processing species 2
2016-09-12 15:28:25 : Processing species 3

3. Inferring gene and species trees
-----------------------------------
2016-09-12 15:28:28 : Done 0 of 315
2016-09-12 15:28:28 : Done 100 of 315
2016-09-12 15:28:30 : Done 200 of 315

4. Best outgroup(s) for species tree
------------------------------------
Observed 3 duplications. 3 support the best root and 0 contradict it.
Best outgroup for species tree:
  Mycoplasma_agalactiae, Mycoplasma_hyopneumoniae

5. Reconciling gene and species trees
-------------------------------------
Outgroup: Mycoplasma_agalactiae, Mycoplasma_hyopneumoniae
2016-09-12 15:28:40 : Done 0 of 314
2016-09-12 15:28:48 : Done 100 of 314
2016-09-12 15:28:54 : Done 200 of 314

6. Inferring orthologues from gene trees
----------------------------------------
2016-09-12 15:29:06 : Processing orthologues for species 0
2016-09-12 15:29:06 : Processing orthologues for species 1
2016-09-12 15:29:06 : Processing orthologues for species 2
2016-09-12 15:29:06 : Processing orthologues for species 3
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1190, in <module>
    orthologuesResultsFilesString = get_orthologues.GetOrthologues(workingDir, resultsDir, clustersFilename_pairs, nBlast)
  File "/scicomp/home/user/bin/OrthoFinder-master/orthofinder/scripts/get_orthologues.py", line 602, in GetOrthologues
    CleanWorkingDir(db)
  File "/scicomp/home/user/bin/OrthoFinder-master/orthofinder/scripts/get_orthologues.py", line 540, in CleanWorkingDir
    shutil.rmtree(dFull)
  File "/scicomp/home/user/bin/anaconda2/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/scicomp/home/user/bin/anaconda2/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/scicomp/home/user/bin/OrthoFinder-master/orthofinder/ExampleDataset/Results_Sep12/Orthologues_Sep12/WorkingDirectory/Trees_ids_arbitraryRoot/'
user@monolith1> cd orthofinder/ExampleDataset/Results_Sep12/
user@monolith1> ls -a Orthologues_Sep12/WorkingDirectory/Trees_ids_arbitraryRoot/
.  ..

I'm running Anaconda Python 2.7.11, MCL-edge 14-137, NCBI BLAST+ 2.3.0, Fastme 2.1.5, DLCpar 0.9.1.

The error seemed related to a discussion that I found [here](http://github.com/hashdist/hashdist/issues/113).

I'm very excited about this software and looking forward to hearing back about resolving this issue.

**Comment by davidemms** [comment]
Thanks for reporting this, it looks like the link you give covers exactly the problem. I'll submit a fix to resolve the issue now and upload a new release package later today.

All the best
David
