### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by snmendoz** [davidemms/OrthoFinder#309]
Hi, I would like to run Orthofinder on Windows 10. I download it and ran it for a simple case but there was an error with MCL. I guess the binary of MCL is for Linux and therefore, does not work on Windows. I would appreciate your advice to make Orthofinder work on Windows. 

This is the output I got:
OrthoFinder version 2.3.7 Copyright (C) 2014 David Emms

2019-11-19 14:11:08 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
-Traceback (most recent call last):
---------------------------------------  File "<string>", line 1, in <module>

  File "D:\Programs\Anaconda2\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "D:\Programs\Anaconda2\lib\multiprocessing\forking.py", line 510, in prepare
    '__parents_main__', file, path_name, etc
  File "D:\Dropbox\Research_Projects\MetaDraft\OrthoFinder-2.3.7\orthofinder\orthofinder.py", line 27, in <module>
    from scripts import parallel_task_manager
  File "D:\Dropbox\Research_Projects\MetaDraft\OrthoFinder-2.3.7\orthofinder\scripts\parallel_task_manager.py", line 129, in <module>
    ptm_initialised = ParallelTaskManager_singleton()
  File "D:\Dropbox\Research_Projects\MetaDraft\OrthoFinder-2.3.7\orthofinder\scripts\parallel_task_manager.py", line 99, in __init__
    ParallelTaskManager_singleton.instance = ParallelTaskManager_singleton.__Singleton()
  File "D:\Dropbox\Research_Projects\MetaDraft\OrthoFinder-2.3.7\orthofinder\scripts\parallel_task_manager.py", line 94, in __init__
    self.manager_process.start()
  File "D:\Programs\Anaconda2\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "D:\Programs\Anaconda2\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "D:\Programs\Anaconda2\lib\multiprocessing\forking.py", line 358, in get_command_line
    is not going to be frozen to produce a Windows executable.''')
RuntimeError:
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
Test can run "mcl -h" - failed

stdout:

stderr:
'mcl' is not recognized as an internal or external command,

operable program or batch file.

ERROR: Cannot run MCL with the command "mcl -h"
Please check MCL is installed and in the system path

ERROR: An error occurred, please review error messages for more information.

Best,

**Comment by davidemms** [comment]
Hi

At the moment there are quite a few parts of the OrthoFinder code itself that rely on linux/mac and so supporting windows is not something that's currently being considering. I think the best thing to do is to create a linux virtual machine e.g. VMWare Player + Ubuntu. This is very easily done, and on this setup you can just download and run OrthoFinder immediately.

All the best
David
