### ISSUE TITLE
[Errno 24] Too many open files:

### ISSUE THREAD

**Issue by Neo-sage** [davidemms/OrthoFinder#313]
Hi,

When running the gene and species tree reconciliation I keep having this error, my dataset is 293 proteomes (is this too many?). Is there anyway I can limit the number of files being opened at once?

Reconciling gene and species trees
----------------------------------
2019-11-29 09:28:01 : Starting OF Orthologues
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1675, in <module>
  File "orthofinder/orthofinder.py", line 1486, in GetOrthologues_FromTrees
  File "orthofinder/scripts/orthologues.py", line 824, in OrthologuesFromTrees
  File "orthofinder/scripts/orthologues.py", line 800, in ReconciliationAndOrthologues
  File "orthofinder/scripts/trees2ologs_of.py", line 640, in DoOrthologuesForOrthoFinder
  File "orthofinder/scripts/trees2ologs_of.py", line 592, in __enter__
IOError: [Errno 24] Too many open files: '/home/em16077/work/orthof/arch_bac_all/OrthoFinder/Results_Nov29/Orthologues/Orthologues_DPANN4/DPANN4__v__CPRBERK6.tsv'
[214562] Failed to execute script orthofinder

**Comment by davidemms** [comment]
Hi

There's no way to limit the number of files that will be opened. Basically, each tree could (and some will) contain orthologs from every pair of species. So that would be at least 85,000 files for that many species. I think there is often a setting in Linux to change the maximum number of files that can be opened at once, which might solve the problem for you. I don't think 293 proteomes is necessarily too many, I was able to quite happily run a dataset with 256 proteomes for the most recent paper.

All the best
David

**Comment by TheBigFatTony** [comment]
You have to change your computers `ulimit`: https://linuxhint.com/linux_ulimit_command/
