### ISSUE TITLE
convert_orthofinder_tree_ids.py and  make_ultrametric.py stcuj with -h option 

### ISSUE THREAD

**Issue by EricDeveaud** [davidemms/OrthoFinder#325]
while installing and testing OrthoFinder-2.3.8 (installed from sources) I noticed this problem

when called with -h (or --help) option convert_orthofinder_tree_ids.py and  make_ultrametric.py display the help message but does not exit neicely
they stay stuck after CITATION display.

and only Ctrl^C can stop it.
see

```
bigmess:OrthoFinder-2.3.8/tools > python make_ultrametric.py

OrthoFinder version 2.3.8 Copyright (C) 2014 David Emms

SIMPLE USAGE:
Run full OrthoFinder analysis on FASTA format proteomes in <dir>
  orthofinder [options] -f <dir>

Add new species in <dir1> to previous run in <dir2> and run new analysis
  orthofinder [options] -f <dir1> -b <dir2>

OPTIONS:
 -t <int>          Number of parallel sequence search threads [Default = 8]
 -a <int>          Number of parallel analysis threads [Default = 1]
 -M <txt>          Method for gene tree inference. Options 'dendroblast' & 'msa'
                   [Default = dendroblast]
 -S <txt>          Sequence search program [Default = diamond]
                   Options: blast, mmseqs, blast_gz, diamond
 -A <txt>          MSA program, requires '-M msa' [Default = mafft]
                   Options: muscle, mafft
 -T <txt>          Tree inference method, requires '-M msa' [Default = fasttree]
                   Options: iqtree, raxml-ng, fasttree, raxml
 -s <file>         User-specified rooted species tree
 -I <int>          MCL inflation parameter [Default = 1.5]
 -x <file>         Info for outputting results in OrthoXML format
 -p <dir>          Write the temporary pickle files to <dir>
 -1                Only perform one-way sequence search 
 -X                Don't add species names to sequence IDs
 -n <txt>          Name to append to the results directory
 -o <txt>          Non-default results directory
 -h                Print this help text

WORKFLOW STOPPING OPTIONS:
 -op               Stop after preparing input files for BLAST
 -og               Stop after inferring orthogroups
 -os               Stop after writing sequence files for orthogroups
                   (requires '-M msa')
 -oa               Stop after inferring alignments for orthogroups
                   (requires '-M msa')
 -ot               Stop after inferring gene trees for orthogroups 

WORKFLOW RESTART COMMANDS:
 -b  <dir>         Start OrthoFinder from pre-computed BLAST results in <dir>
 -fg <dir>         Start OrthoFinder from pre-computed orthogroups in <dir>
 -ft <dir>         Start OrthoFinder from pre-computed gene trees in <dir>

LICENSE:
 Distributed under the GNU General Public License (GPLv3). See License.md

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2019), Genome Biology 20:238

 If you use the species tree in your work then please also cite:
 Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
 Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101
^CProcess Process-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "make_ultrametric.py", line 12, in <module>
    from orthofinder.scripts import tree
  File "/local/gensoft2/adm/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/mount/gensoft2/src/OrthoFinder/OrthoFinder-2.3.8/orthofinder.py", line 6, in <module>
    main(args)
  File "/mount/gensoft2/src/OrthoFinder/OrthoFinder-2.3.8/scripts_of/__main__.py", line 1631, in main
    self.run()
  File "/local/gensoft2/adm/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/mount/gensoft2/src/OrthoFinder/OrthoFinder-2.3.8/scripts_of/parallel_task_manager.py", line 286, in _I_Spawn_Processes
    options, fastaDir, continuationDir, resultsDir_nonDefault, pickleDir_nonDefault = ProcessArgs(prog_caller, args)  
  File "/mount/gensoft2/src/OrthoFinder/OrthoFinder-2.3.8/scripts_of/__main__.py", line 946, in ProcessArgs
    time.sleep(1) # there wasn't anything this time, sleep then try again
KeyboardInterrupt
    util.Success() 
  File "/mount/gensoft2/src/OrthoFinder/OrthoFinder-2.3.8/scripts_of/util.py", line 149, in Success
    parallel_task_manager.Success()
  File "/mount/gensoft2/src/OrthoFinder/OrthoFinder-2.3.8/scripts_of/parallel_task_manager.py", line 344, in Success
    ptm.Stop()  
  File "/mount/gensoft2/src/OrthoFinder/OrthoFinder-2.3.8/scripts_of/parallel_task_manager.py", line 339, in Stop
    self.instance.manager_process.join()
  File "/local/gensoft2/adm/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/local/gensoft2/adm/lib/python2.7/multiprocessing/forking.py", line 148, in wait
    return self.poll(0)
  File "/local/gensoft2/adm/lib/python2.7/multiprocessing/forking.py", line 133, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

execution is stick at ParallelTaskManager_singleton.stop() from  scripts_of/parallel_task_manager.py 
more precisely at self.instance.manager_process.join()

regards

Eric

**Comment by davidemms** [comment]
Hi Eric

Thanks for submitting this, I'm pretty sure I know what will be causing it and will submit a fix in the new year.

All the best
David
