### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str' when running the OrthoFinder algorithm

### ISSUE THREAD

**Issue by wuxiaopei0509** [davidemms/OrthoFinder#329]
dear OrthoFinder developer
When I use OrthoFinder, the diamond all-versus-all work well ,how ever when proceeding to OrthoFinder algorithm, it occurs error as follows:
Traceback (most recent call last):
  File "/home/wuxiaopei/miniconda2/envs/orthofinder/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/wuxiaopei/miniconda2/envs/orthofinder/bin/scripts_of/__main__.py", line 1678, in main
    DoOrthogroups(options, speciesInfoObj, seqsInfo)    
  File "/home/wuxiaopei/miniconda2/envs/orthofinder/bin/scripts_of/__main__.py", line 1334, in DoOrthogroups
    MCL.RunMCL(graphFilename, clustersFilename, options.nProcessAlg, options.mclInflation)
  File "/home/wuxiaopei/miniconda2/envs/orthofinder/bin/scripts_of/__main__.py", line 211, in RunMCL
    parallel_task_manager.RunCommand(command, qShell=False, qPrintOnError=True)
  File "/home/wuxiaopei/miniconda2/envs/orthofinder/bin/scripts_of/parallel_task_manager.py", line 116, in RunCommand
    elif qPrintStderr and len(stderr) > 0 and not stderr_exempt(stderr):
  File "/home/wuxiaopei/miniconda2/envs/orthofinder/bin/scripts_of/parallel_task_manager.py", line 64, in stderr_exempt
    lines = stderr.split("\n")
TypeError: a bytes-like object is required, not 'str'

it likes some error with python, but I install orthofinder through conda, and python version is 3.7 .
can you tell me where is the problem ? Thank you !
Best!

**Comment by davidemms** [comment]
Hi

A fix has been submitted for this: 400087e3137ae86a2c5c7230f77aa594125b06c6. You can download the source code version from the front page of the OrthoFinder repository, which will contain this fix (https://github.com/davidemms/OrthoFinder - click the green button). You'll need scipy and numpy installed. Your conda environment will should already have this so you can probably just run the downloaded orthofinder.py program within your conda environment as you would with any other python script.

I will also create a new release with this fix but it will take a bit longer to propagate this to through conda. 

All the best 
David
