### ISSUE TITLE
OrthoFinder error after 2 hours

### ISSUE THREAD

**Issue by 14zac2** [davidemms/OrthoFinder#341]
Hi David,

To give you some context, I was just commenting on your recent thread: [https://github.com/davidemms/OrthoFinder/issues/328]

I've run into a new issue so I'm putting it here. I got OrthoFinder to work after the steps discussed in the previous thread, but it has come up with an error after about 2 hours of running and I'm having trouble debugging.

I gave the command: orthofinder -f FastaFiles/

Here is the output on my terminal (I'm using MacOS Catalina, diamond 0.9.24, mcl 14-137, fastme 2.1.5, python 3.7.4):

```{r}
OrthoFinder version 2.3.8 Copyright (C) 2014 David Emms

2020-02-06 19:16:21 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /Users/zoeclarke/Documents/Woodchuck_data/OrthoFinder/FastaFiles/OrthoFinder/Results_Feb06_4/WorkingDirectory/SimpleTest.phy -o /Users/zoeclarke/Documents/Woodchuck_data/OrthoFinder/FastaFiles/OrthoFinder/Results_Feb06_4/WorkingDirectory/SimpleTest.tre" - ok

WARNING: Files have been ignored as they don't appear to be FASTA files:
.DS_Store
OrthoFinder expects FASTA files to have one of the following extensions: fa, fasta, faa, fas

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2020-02-06 19:16:24 : Creating diamond database 1 of 2
2020-02-06 19:16:25 : Creating diamond database 2 of 2

Running diamond all-versus-all
------------------------------
Using 8 thread(s)
2020-02-06 19:16:28 : This may take some time....
2020-02-06 21:39:16 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2020-02-06 21:39:17 : Initial processing of each species
2020-02-06 21:40:31 : Initial processing of species 0 complete
2020-02-06 21:45:12 : Initial processing of species 1 complete
2020-02-06 21:45:22 : Connected putative homologues
2020-02-06 21:45:24 : Written final scores for species 0 to graph file
2020-02-06 21:45:33 : Written final scores for species 1 to graph file
Traceback (most recent call last):
  File "/Users/zoeclarke/miniconda3/bin/orthofinder", line 7, in <module>
    main(args)
  File "/Users/zoeclarke/miniconda3/bin/scripts_of/__main__.py", line 1678, in main
    DoOrthogroups(options, speciesInfoObj, seqsInfo)    
  File "/Users/zoeclarke/miniconda3/bin/scripts_of/__main__.py", line 1334, in DoOrthogroups
    MCL.RunMCL(graphFilename, clustersFilename, options.nProcessAlg, options.mclInflation)
  File "/Users/zoeclarke/miniconda3/bin/scripts_of/__main__.py", line 211, in RunMCL
    parallel_task_manager.RunCommand(command, qShell=False, qPrintOnError=True)
  File "/Users/zoeclarke/miniconda3/bin/scripts_of/parallel_task_manager.py", line 109, in RunCommand
    popen = subprocess.Popen(command, env=my_env, shell=qShell, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Any help on this would be much appreciated!

Thanks,
Zoe

**Comment by davidemms** [comment]
Hi Zoe

That's odd, I've looked up that error message online and basically it's not finding the mcl executable, even though it found it at the start. There is a slight difference, which shouldn't matter. 

Could you test what happens when you do the following:
1. Open a python prompt:
```
python
```
2. In the python prompt run:
```
import subprocess
subprocess.call("mcl -h", shell=True)
```
3. And then run
```
subprocess.call(["mcl"])
```

From the look of the error message (2) is successful but (3) fails. Could you confirm if that is the case?

Thanks
David

**Comment by 14zac2** [comment]
Hi David,

I think there is something going on with the version of subprocess. "shell=True" is no longer a valid argument for subprocess.call in python 3.7 and I can't seem to find an equivalent command. Here is what I was able to run:

```{r}
>>> import subprocess
>>> subprocess.call("mcl -h")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zoeclarke/miniconda3/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/zoeclarke/miniconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/zoeclarke/miniconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mcl -h': 'mcl -h'

>>> subprocess.call(["mcl"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zoeclarke/miniconda3/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/zoeclarke/miniconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/zoeclarke/miniconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mcl': 'mcl'
```{r}

Not sure exactly where to go from there...

Thanks!
Zoe

**Comment by davidemms** [comment]
Hi Zoe

That's odd, that suggests it is unable to call mcl at all. From what I can see in the documentation "shell=True" should be fine: <https://docs.python.org/3.7/library/subprocess.html#subprocess.call> so I don't think that's the problem. 

Is there a problem with the mcl installation possibly? Just to check, could you run the following (updated) commands in the same terminal:

```
which mcl
mcl
python
```
at this stage you will now have a python prompt open, in that prompt try the following commands again
```
import subprocess
subprocess.call("mcl -h", shell=True)
subprocess.call(["mcl"])
quit()
```
and then back at the standard shell, now that the python prompt is closed
(you might need to download and unpack one of the releases, e.g. <https://github.com/davidemms/OrthoFinder/releases/download/2.3.10/OrthoFinder_source.tar.gz> to get the ExampleDataset, but just call the 'orthofinder' you called before, rather than the one in this package):
```
orthofinder -f ExampleDataset/
```

Thanks
David

**Comment by 14zac2** [comment]
Hi David,

There's certainly a problem with mcl somewhere, but I can't figure out what it is. mcl --version returns mcl 14-137, and you're right, the shell command works on subprocess (not sure how I got that wrong!). Unfortunately I got tripped up here:

```{r}
>>> subprocess.call(["mcl"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zoeclarke/miniconda3/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/zoeclarke/miniconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/zoeclarke/miniconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mcl': 'mcl'
```
I tried reinstalling mcl with Bioconda (conda install mcl) but a message returned saying all requested packages were already installed.

And then with the ExampleData:
```{r}
bash-3.2$ orthofinder -f ExampleData/

OrthoFinder version 2.3.8 Copyright (C) 2014 David Emms

2020-02-10 07:05:49 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /Users/zoeclarke/OrthoFinder/ExampleData/OrthoFinder/Results_Feb10/WorkingDirectory/SimpleTest.phy -o /Users/zoeclarke/OrthoFinder/ExampleData/OrthoFinder/Results_Feb10/WorkingDirectory/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2020-02-10 07:05:49 : Creating diamond database 1 of 4
2020-02-10 07:05:49 : Creating diamond database 2 of 4
2020-02-10 07:05:49 : Creating diamond database 3 of 4
2020-02-10 07:05:49 : Creating diamond database 4 of 4

Running diamond all-versus-all
------------------------------
Using 8 thread(s)
2020-02-10 07:05:49 : This may take some time....
2020-02-10 07:05:49 : Done 0 of 16
2020-02-10 07:05:56 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2020-02-10 07:05:56 : Initial processing of each species
2020-02-10 07:05:57 : Initial processing of species 0 complete
2020-02-10 07:05:57 : Initial processing of species 1 complete
2020-02-10 07:05:58 : Initial processing of species 2 complete
2020-02-10 07:05:58 : Initial processing of species 3 complete
2020-02-10 07:06:00 : Connected putative homologues
2020-02-10 07:06:00 : Written final scores for species 0 to graph file
2020-02-10 07:06:00 : Written final scores for species 1 to graph file
2020-02-10 07:06:00 : Written final scores for species 2 to graph file
2020-02-10 07:06:00 : Written final scores for species 3 to graph file
Traceback (most recent call last):
  File "/Users/zoeclarke/miniconda3/bin/orthofinder", line 7, in <module>
    main(args)
  File "/Users/zoeclarke/miniconda3/bin/scripts_of/__main__.py", line 1678, in main
    DoOrthogroups(options, speciesInfoObj, seqsInfo)    
  File "/Users/zoeclarke/miniconda3/bin/scripts_of/__main__.py", line 1334, in DoOrthogroups
    MCL.RunMCL(graphFilename, clustersFilename, options.nProcessAlg, options.mclInflation)
  File "/Users/zoeclarke/miniconda3/bin/scripts_of/__main__.py", line 211, in RunMCL
    parallel_task_manager.RunCommand(command, qShell=False, qPrintOnError=True)
  File "/Users/zoeclarke/miniconda3/bin/scripts_of/parallel_task_manager.py", line 109, in RunCommand
    popen = subprocess.Popen(command, env=my_env, shell=qShell, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Interesting to note that when I call mcl on python3, it uses the subprocess.py script in my python3.7 library, but when I run orthofinder it uses the python2.7 script.

Sorry, I really appreciate your help on this!!
Zoe

**Comment by 14zac2** [comment]
I forgot to add the output with the first subprocess.call command:
```{r}
>>> subprocess.call("mcl -h", shell=True)
________ mcl verbosity modes
--show ....... print MCL iterands (small graphs only)
-v all ....... turn on all -v options

________ on multi-processor systems
-te <i> ...... number of threads to use                                  [0]

________ mcl info options
-z ........... shows current settings (takes other arguments into account)
--show-schemes shows the resource schemes accessible via the -scheme option
--version .... shows version and license information

________ speed/quality control
-scheme <i> .. use a preset pruning scheme (i=1,2,3,4,5,6,7)             [7]
                 --show-schemes shows the preset schemes
                 higher schemes are costlier and possibly more accurate

________ mcl cluster controls
-I <f> ....... inflation (varying this parameter affects granularity)  [2.0]
-o <fname> ... direct cluster output to file fname (- for stdout)  [out.mcl]
                 if omitted, mcl will create a meaningful output name -
                 try it out, it's convenient. (cf. -az).

________ input format
--abc ........ assume row-based input with format
                 LABEL1 <tab> LABEL2 <tab> WEIGHT
                 where the trailing <tab> WEIGHT part is optional

This is a selection of the mcl options and their defaults. Try different
-I values for finding clusterings of different granularity, (e.g. in the
range 1.2 - 4.0). See 'man mcl' and 'man mclfaq' for more information.

====|   mcl <graph.mci> -I 2.0        |==== should get you going, or
====|   mcl <input.abc> --abc -I 2.0  |==== (abc format, see above)

Usually you should only need the -I option.
mcl --help shows a summary listing more options.

0
```

**Comment by davidemms** [comment]
Thanks, I think the problem may be that the programs installed (using bioconda?) are only accessible if called via the shell. I'm going to try changing the code so that this is the approach that is always used. What process are you using to install OrthoFinder so that I can prepare an updated version for you to test?

**Comment by 14zac2** [comment]
No problem, David - thank you! Yes, all has been installed using Bioconda. Do you mean change the code so that calling things from the shell is always used?

I also used Bioconda to install OrthoFinder.

**Comment by davidemms** [comment]
Yes, I'll try getting OrthoFinder to always use the shell when calling external programs since it could be that some of the environment setup requires the shell to be used. I'll email you an updated package to test and if that's successful then I can push it to bioconda.

**Comment by davidemms** [comment]
Just an update for anyone visiting this thread the fix appears to resolve the problem. 

In the conda environment,
this appears to work: `subprocess.call("mcl -h", shell=True)`
but this doesn't: `subprocess.call(["mcl", "-h"])`

I've switched all calls to external programs to use the first approach. I'll update the version on bioconda.

David
