### ISSUE TITLE
Error Reconciling gene trees and species tree

### ISSUE THREAD

**Issue by Edison2021** [davidemms/OrthoFinder#351]
Hi David
I just tried the latest version 2.3.11. Each step seems good expect "Reconciling gene trees and species tree". The error message is below. 

Outgroup: N1,N2,N3,N4
2020-02-25 12:55:38 : Starting Recon and orthologues
2020-02-25 12:55:38 : Starting OF Orthologues
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1687, in main
  File "scripts_of/__main__.py", line 1513, in GetOrthologues
  File "scripts_of/orthologues.py", line 1012, in OrthologuesWorkflow
  File "scripts_of/orthologues.py", line 810, in ReconciliationAndOrthologues
  File "scripts_of/trees2ologs_of.py", line 648, in DoOrthologuesForOrthoFinder
  File "scripts_of/trees2ologs_of.py", line 600, in __enter__
IOError: [Errno 24] Too many open files: '/media/edison2018/DATADRIVE1/project2/02222020/ortholog/OrthoFinder/Results_Feb22/Orthologues/Orthologues_M.aa/M.aa__v__F.aa.tsv'
[12790] Failed to execute script orthofinder.

Any suggestions are appreciated.

Edison

**Comment by davidemms** [comment]
Hi Edison

It will just be that the limit is set too low on your computer for the number of files that can be opened at once. You just need to update the limit: <https://linuxhint.com/linux_ulimit_command/>. Setting it to something like 1,000,000 should be fine I think.

All the best
David
