### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy' on MacOS Catalina

### ISSUE THREAD

**Issue by cparsania** [davidemms/OrthoFinder#359]
Hi, I installed orthofinder using `conda`. Installation completed without error. However, when I run `orthofinder -h` t throws below error 

<img width="924" alt="image" src="https://user-images.githubusercontent.com/10338600/77164764-f2f66100-6ad6-11ea-88a7-a711e821379c.png">

**Comment by davidemms** [comment]
Hi

Could you show me the output when you use conda to install OrthoFinder? Running it again should be fine.

Thanks
David

**Comment by cparsania** [comment]
Hi, Below is the installation log. 

```
(base) chiragparsania@Chirags-MacBook-Pro expt % conda install orthofinder 
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/chiragparsania/opt/miniconda2

  added / updated specs:
    - orthofinder


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blast-2.9.0                |       h58d6d27_1        17.9 MB  bioconda
    boost-1.68.0               |py27h9888f84_1001         326 KB  conda-forge
    boost-cpp-1.68.0           |    h6f8c590_1000        18.6 MB  conda-forge
    diamond-0.9.24             |       hbde9309_1         500 KB  bioconda
    gmp-6.2.0                  |       h4a8c4bd_2         788 KB  conda-forge
    gnutls-3.6.5               |    h53004b3_1002         2.0 MB  conda-forge
    icu-58.2                   |    h0a44026_1000        22.3 MB  conda-forge
    nettle-3.4.1               |    h3efe00b_1002         1.0 MB  conda-forge
    pcre-8.44                  |       h4a8c4bd_0         222 KB  conda-forge
    perl-archive-tar-2.32      |          pl526_0          31 KB  bioconda
    perl-carp-1.38             |          pl526_3          15 KB  bioconda
    perl-common-sense-3.74     |          pl526_2          15 KB  bioconda
    perl-compress-raw-bzip2-2.087|  pl526h6de7cb9_0          47 KB  bioconda
    perl-compress-raw-zlib-2.087|  pl526h770b8ee_0          71 KB  bioconda
    perl-exporter-5.72         |          pl526_1          13 KB  bioconda
    perl-exporter-tiny-1.002001|          pl526_0          23 KB  bioconda
    perl-extutils-makemaker-7.36|          pl526_1         153 KB  bioconda
    perl-io-compress-2.087     |  pl526h6de7cb9_0          81 KB  bioconda
    perl-io-zlib-1.10          |          pl526_2           9 KB  bioconda
    perl-json-4.02             |          pl526_0          52 KB  bioconda
    perl-json-xs-2.34          |  pl526h04f5b5a_3          61 KB  bioconda
    perl-list-moreutils-0.428  |          pl526_1          28 KB  bioconda
    perl-list-moreutils-xs-0.428|          pl526_0          40 KB  bioconda
    perl-pathtools-3.75        |  pl526h1de35cc_1          39 KB  bioconda
    perl-scalar-list-utils-1.52|  pl526h01d97ff_0          35 KB  bioconda
    perl-types-serialiser-1.0  |          pl526_2          10 KB  bioconda
    perl-xsloader-0.24         |          pl526_0           8 KB  bioconda
    xz-5.2.4                   |    h1de35cc_1001         268 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        64.5 MB

The following NEW packages will be INSTALLED:

  blast              bioconda/osx-64::blast-2.9.0-h58d6d27_1
  boost              conda-forge/osx-64::boost-1.68.0-py27h9888f84_1001
  boost-cpp          conda-forge/osx-64::boost-cpp-1.68.0-h6f8c590_1000
  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0b31af3_2
  diamond            bioconda/osx-64::diamond-0.9.24-hbde9309_1
  fastme             bioconda/osx-64::fastme-2.1.5-0
  fasttree           bioconda/osx-64::fasttree-2.1.10-h1de35cc_3
  gawk               conda-forge/osx-64::gawk-5.0.1-h6a5b60f_0
  gettext            conda-forge/osx-64::gettext-0.19.8.1-h46ab8bc_1002
  gmp                conda-forge/osx-64::gmp-6.2.0-h4a8c4bd_2
  gnutls             conda-forge/osx-64::gnutls-3.6.5-h53004b3_1002
  icu                conda-forge/osx-64::icu-58.2-h0a44026_1000
  iqtree             bioconda/osx-64::iqtree-1.6.12-h2dec4b4_0
  libblas            conda-forge/osx-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/osx-64::libcblas-3.8.0-14_openblas
  libgcc             conda-forge/osx-64::libgcc-4.8.5-1
  libgfortran        conda-forge/osx-64::libgfortran-4.0.0-2
  libiconv           conda-forge/osx-64::libiconv-1.15-h0b31af3_1006
  libidn2            conda-forge/osx-64::libidn2-2.3.0-h0b31af3_0
  liblapack          conda-forge/osx-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.7-h3d69b6c_4
  libunistring       conda-forge/osx-64::libunistring-0.9.10-h1de35cc_0
  llvm-openmp        conda-forge/osx-64::llvm-openmp-8.0.1-h770b8ee_0
  mafft              bioconda/osx-64::mafft-7.455-h01d97ff_0
  mcl                bioconda/osx-64::mcl-14.137-pl526h01d97ff_5
  mmseqs2            bioconda/osx-64::mmseqs2-11.e1a1c-h21ccd2c_0
  muscle             bioconda/osx-64::muscle-3.8.1551-h770b8ee_5
  nettle             conda-forge/osx-64::nettle-3.4.1-h3efe00b_1002
  numpy              conda-forge/osx-64::numpy-1.16.5-py27hde6bac1_0
  openmp             conda-forge/osx-64::openmp-8.0.1-0
  orthofinder        bioconda/noarch::orthofinder-2.3.11-0
  pcre               conda-forge/osx-64::pcre-8.44-h4a8c4bd_0
  perl               conda-forge/osx-64::perl-5.26.2-haec8ef5_1006
  perl-archive-tar   bioconda/osx-64::perl-archive-tar-2.32-pl526_0
  perl-carp          bioconda/osx-64::perl-carp-1.38-pl526_3
  perl-common-sense  bioconda/osx-64::perl-common-sense-3.74-pl526_2
  perl-compress-raw~ bioconda/osx-64::perl-compress-raw-bzip2-2.087-pl526h6de7cb9_0
  perl-compress-raw~ bioconda/osx-64::perl-compress-raw-zlib-2.087-pl526h770b8ee_0
  perl-exporter      bioconda/osx-64::perl-exporter-5.72-pl526_1
  perl-exporter-tiny bioconda/osx-64::perl-exporter-tiny-1.002001-pl526_0
  perl-extutils-mak~ bioconda/osx-64::perl-extutils-makemaker-7.36-pl526_1
  perl-io-compress   bioconda/osx-64::perl-io-compress-2.087-pl526h6de7cb9_0
  perl-io-zlib       bioconda/osx-64::perl-io-zlib-1.10-pl526_2
  perl-json          bioconda/osx-64::perl-json-4.02-pl526_0
  perl-json-xs       bioconda/osx-64::perl-json-xs-2.34-pl526h04f5b5a_3
  perl-list-moreuti~ bioconda/osx-64::perl-list-moreutils-0.428-pl526_1
  perl-list-moreuti~ bioconda/osx-64::perl-list-moreutils-xs-0.428-pl526_0
  perl-pathtools     bioconda/osx-64::perl-pathtools-3.75-pl526h1de35cc_1
  perl-scalar-list-~ bioconda/osx-64::perl-scalar-list-utils-1.52-pl526h01d97ff_0
  perl-types-serial~ bioconda/osx-64::perl-types-serialiser-1.0-pl526_2
  perl-xsloader      bioconda/osx-64::perl-xsloader-0.24-pl526_0
  raxml              bioconda/osx-64::raxml-8.2.12-h1de35cc_1
  scipy              conda-forge/osx-64::scipy-1.2.1-py27h7e0e109_2
  wget               conda-forge/osx-64::wget-1.20.1-h33e2efd_0
  xz                 conda-forge/osx-64::xz-5.2.4-h1de35cc_1001


Proceed ([y]/n)? y


Downloading and Extracting Packages
perl-types-serialise | 10 KB     | ########################################################################################################################################################### | 100% 
perl-exporter-5.72   | 13 KB     | ########################################################################################################################################################### | 100% 
perl-archive-tar-2.3 | 31 KB     | ########################################################################################################################################################### | 100% 
nettle-3.4.1         | 1.0 MB    | ########################################################################################################################################################### | 100% 
perl-xsloader-0.24   | 8 KB      | ########################################################################################################################################################### | 100% 
boost-1.68.0         | 326 KB    | ########################################################################################################################################################### | 100% 
perl-scalar-list-uti | 35 KB     | ########################################################################################################################################################### | 100% 
perl-list-moreutils- | 28 KB     | ########################################################################################################################################################### | 100% 
perl-list-moreutils- | 40 KB     | ########################################################################################################################################################### | 100% 
perl-exporter-tiny-1 | 23 KB     | ########################################################################################################################################################### | 100% 
perl-json-xs-2.34    | 61 KB     | ########################################################################################################################################################### | 100% 
gnutls-3.6.5         | 2.0 MB    | ########################################################################################################################################################### | 100% 
perl-compress-raw-bz | 47 KB     | ########################################################################################################################################################### | 100% 
pcre-8.44            | 222 KB    | ########################################################################################################################################################### | 100% 
boost-cpp-1.68.0     | 18.6 MB   | ########################################################################################################################################################### | 100% 
icu-58.2             | 22.3 MB   | ########################################################################################################################################################### | 100% 
perl-carp-1.38       | 15 KB     | ########################################################################################################################################################### | 100% 
gmp-6.2.0            | 788 KB    | ########################################################################################################################################################### | 100% 
perl-compress-raw-zl | 71 KB     | ########################################################################################################################################################### | 100% 
blast-2.9.0          | 17.9 MB   | ########################################################################################################################################################### | 100% 
perl-io-zlib-1.10    | 9 KB      | ########################################################################################################################################################### | 100% 
perl-pathtools-3.75  | 39 KB     | ########################################################################################################################################################### | 100% 
perl-json-4.02       | 52 KB     | ########################################################################################################################################################### | 100% 
diamond-0.9.24       | 500 KB    | ########################################################################################################################################################### | 100% 
xz-5.2.4             | 268 KB    | ########################################################################################################################################################### | 100% 
perl-extutils-makema | 153 KB    | ########################################################################################################################################################### | 100% 
perl-io-compress-2.0 | 81 KB     | ########################################################################################################################################################### | 100% 
perl-common-sense-3. | 15 KB     | ########################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

```

**Comment by davidemms** [comment]
I'm not too sure what's going on here. It may that the bioconda support can give you better help with this. 

The only thing I can currently think of is a mismatch between the versions of scipy and python, but I would assume this wouldn't occur. Could you run the following commands and let me know the output (including the output from opening the python terminal:
```
python
import scipy
quit()
```
Back in the terminal:
```
which orthofinder
```
and then use the path it returns to call this executable with python directly. E.g. for me:
```
python /home/emms/miniconda3/bin/orthofinder -h
```

All the best
David

**Comment by cardiandra** [comment]
Hi, I'm new to OrthoFinder and I also got exactly the same issue after using bioconda to install orthofinder. I've tried to change my default python version from 2.7 to 3.7 (which is the version that SciPy package seems to be installed under miniconda), and then I got these error messages, different from the first one: 

`Traceback (most recent call last):
  File "./orthofinder", line 3, in <module>
    from scripts_of.__main__ import main
  File "/Users/Chrysosplenium/miniconda3/bin/scripts_of/__main__.py", line 42, in <module>
    from scipy.optimize import curve_fit            # install
  File "/Users/Chrysosplenium/miniconda3/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 390, in <module>
    from ._minimize import *
  File "/Users/Chrysosplenium/miniconda3/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 26, in <module>
    from ._trustregion_dogleg import _minimize_dogleg
  File "/Users/Chrysosplenium/miniconda3/lib/python3.7/site-packages/scipy/optimize/_trustregion_dogleg.py", line 5, in <module>
    import scipy.linalg
  File "/Users/Chrysosplenium/miniconda3/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 195, in <module>
    from .misc import *
  File "/Users/Chrysosplenium/miniconda3/lib/python3.7/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/Users/Chrysosplenium/miniconda3/lib/python3.7/site-packages/scipy/linalg/blas.py", line 215, in <module>
    from scipy.linalg import _fblas
ImportError: dlopen(/Users/Chrysosplenium/miniconda3/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/Chrysosplenium/miniconda3/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-darwin.so
  Reason: image not found`

Is there any suggestion for solving this? Thank you very much.

All the best
Tien-Hao

**Comment by cardiandra** [comment]
Hi, 

I finally found out that using anaconda3 to install orthofinder works. I have tried using miniconda3, anaconda2 and anaconda3, and anaconda3 is the only one can run orthofinder without the error about Scipy. Just FYI.

**Comment by davidemms** [comment]
Hi

That's really useful to know, thanks! That's on a Mac presumably?

All the best
David

**Comment by cardiandra** [comment]
Yes, it's macOS Catalina (10.15.4). Thanks.

Best, Tien-Hao

**Comment by davidemms** [comment]
As this is a conda issue I'm going to close this issue on the OrthoFinder page.
