### ISSUE TITLE
The running job is stopped by the error!

### ISSUE THREAD

**Issue by sunnycqcn** [davidemms/OrthoFinder#372]
Hello,
It was well before I run my gene set with OrthoFinder. However, recently I met the error as following. I checked the protein sequence. I did not see any errors. Could you look my error?
Thanks,
Fuyou

Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/orthofinder/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 1678, in main
    DoOrthogroups(options, speciesInfoObj, seqsInfo)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 1334, in DoOrthogroups
    MCL.RunMCL(graphFilename, clustersFilename, options.nProcessAlg, options.mclInflation)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 211, in RunMCL
    parallel_task_manager.RunCommand(command, qShell=False, qPrintOnError=True)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/orthofinder/bin/scripts_of/parallel_task_manager.py", line 116, in RunCommand
    elif qPrintStderr and len(stderr) > 0 and not stderr_exempt(stderr):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/orthofinder/bin/scripts_of/parallel_task_manager.py", line 64, in stderr_exempt
    lines = stderr.split("\n")

**Comment by davidemms** [comment]
Hi Foyou

You can update to the latest release, it fixes this issue.

All the best
David
