### ISSUE TITLE
error when Writing orthogroups to file

### ISSUE THREAD

**Issue by wuxiaopei0509** [davidemms/OrthoFinder#375]
Dear, develop
I install Orthofinder by conda and the orthofinder version is 2.3.11.When the blastp procedure runs over and proceeds to orthogroups,it stopped with the following error：
Writing orthogroups to file
---------------------------
Traceback (most recent call last):
  File "/home/wuxiaopei/miniconda2/envs/OrthoFinder/bin/scripts_of/__main__.py", line 226, in WriteOrthogroupFiles
    idExtract = util.FirstWordExtractor(idsFilename)
  File "/home/wuxiaopei/miniconda2/envs/OrthoFinder/bin/scripts_of/util.py", line 205, in __init__
    raise RuntimeError("A duplicate accession was found using just first part: % s" % accession)
RuntimeError: A duplicate accession was found using just first part: BG8803123-T1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wuxiaopei/miniconda2/envs/OrthoFinder/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/wuxiaopei/miniconda2/envs/OrthoFinder/bin/scripts_of/__main__.py", line 1684, in main
    DoOrthogroups(options, speciesInfoObj, seqsInfo)    
  File "/home/wuxiaopei/miniconda2/envs/OrthoFinder/bin/scripts_of/__main__.py", line 1347, in DoOrthogroups
    idsDict = MCL.WriteOrthogroupFiles(ogs, [files.FileHandler.GetSequenceIDsFN()], resultsBaseFilename, clustersFilename_pairs)
  File "/home/wuxiaopei/miniconda2/envs/OrthoFinder/bin/scripts_of/__main__.py", line 235, in WriteOrthogroupFiles
    print(error.message)
AttributeError: 'RuntimeError' object has no attribute 'message'
Thank you so much!

**Comment by davidemms** [comment]
Hi

Thanks for reporting this. It was caused by the change to python 3. I have submitted a fix to github. I think you'll be able to run the new code by downloading it and then running the new code from within your conda environment:
```
python path_to_new_code/orthofinder.py
``` 

All the best
David
