### ISSUE TITLE
Unexisting tree file or Malformed newick tree structure

### ISSUE THREAD

**Issue by galoppo** [davidemms/OrthoFinder#376]
Dear David,

I'm getting an error when using OrthoFinder 2.2.6

```
Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2020-04-26 11:27:56 : Done

Inferring gene and species trees
--------------------------------
2020-04-26 11:27:56 : Done 0 of 17367
2020-04-26 11:28:24 : Done 1000 of 17367
2020-04-26 11:28:35 : Done 2000 of 17367
2020-04-26 11:28:46 : Done 3000 of 17367
2020-04-26 11:28:58 : Done 4000 of 17367
2020-04-26 11:29:09 : Done 5000 of 17367
2020-04-26 11:29:20 : Done 6000 of 17367
2020-04-26 11:29:32 : Done 7000 of 17367
2020-04-26 11:29:43 : Done 8000 of 17367
2020-04-26 11:29:54 : Done 9000 of 17367
2020-04-26 11:30:06 : Done 10000 of 17367
2020-04-26 11:30:18 : Done 11000 of 17367
2020-04-26 11:30:29 : Done 12000 of 17367
2020-04-26 11:30:40 : Done 13000 of 17367
2020-04-26 11:30:52 : Done 14000 of 17367
2020-04-26 11:31:02 : Done 15000 of 17367
2020-04-26 11:31:13 : Done 16000 of 17367
2020-04-26 11:31:24 : Done 17000 of 17367

OG0003034_tree_id.txt - WARNING: ETE could not interpret tree file, it will be ignored
OG0017356_tree_id.txt - WARNING: ETE could not interpret tree file, it will be ignored
11828 trees had all species present and will be used by STAG to infer the species tree


Best outgroup(s) for species tree
---------------------------------
2020-04-26 11:39:21 : Starting STRIDE
Traceback (most recent call last):
  File "/bin/orthofinder", line 1596, in <module>
    GetOrthologues(dirs, options, program_caller, clustersFilename_pairs, orthogroupsResultsFilesString)
  File "/bin/orthofinder", line 1415, in GetOrthologues
    options.name)
  File "/scripts/orthologues.py", line 1097, in Orth                                                                                                                                     ologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, all_stride_dup_genes = stride.GetRoot(                                                                                                                                     spTreeFN_ids, os.path.split(db.TreeFilename_IDs(0))[0] + "/", stride.GeneToSpecies_dash, nHighParallel,                                                                                                                                      qWriteRootedTree=True)
  File "/scripts/stride.py", line 505, in GetRoot
    list_of_dicts = pool.map(SupportedHierachies_wrapper2, [(fn, GeneToSpeciesMap, species, dict_clades,                                                                                                                                      clade_names, qWriteDupTrees) for fn in glob.glob(treesDir + "/*")])
  File "/multiprocessing/pool.py", line 25                                                                                                                                     3, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/multiprocessing/pool.py", line 57                                                                                                                                     2, in get
    raise self._value
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.

```

Could you please help with this?
Thank you so much in advance.

**Comment by davidemms** [comment]
Hi

Yes, this has been fixed a while ago. You just need to update to the latest version.

All the best
David
