### ISSUE TITLE
AttributeError: module 'scripts_of.trees2ologs_of' has no attribute 'HogWriter'

### ISSUE THREAD

**Issue by Kennyluo4** [davidemms/OrthoFinder#380]
Hello,
I'm using Orthofinder version 2.3.11 for my analysis, an issue occurred as following: 
```
Reconciling gene trees and species tree
---------------------------------------
Outgroup: pvu
2020-05-04 20:16:50 : Starting Recon and orthologues
2020-05-04 20:16:50 : Starting OF Orthologues
Traceback (most recent call last):
  File "/apps/orthofinder/2.3.11/bin/orthofinder", line 7, in <module>
    main(args)
  File "/apps/orthofinder/2.3.11/bin/scripts_of/__main__.py", line 1685, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/apps/orthofinder/2.3.11/bin/scripts_of/__main__.py", line 1511, in GetOrthologues
    options.name)
  File "/apps/orthofinder/2.3.11/bin/scripts_of/orthologues.py", line 1049, in OrthologuesWorkflow
    ReconciliationAndOrthologues(recon_method, db.ogSet, nHighParallel, i if qMultiple else None, all_stride_dup_genes=all_stride_dup_genes) 
  File "/apps/orthofinder/2.3.11/bin/scripts_of/orthologues.py", line 844, in ReconciliationAndOrthologues
    hog_writer = trees2ologs_of.HogWriter(species_tree_rooted_labelled, node_names, SequenceDict, speciesDict)
AttributeError: module 'scripts_of.trees2ologs_of' has no attribute 'HogWriter'
```
Is there any python version conflict? I just requested our instutue to update the source code today, so I believe it's the newest version. Could you help to solve this issue?
Thanks
Ziliang

**Comment by davidemms** [comment]
Hi Ziliang

Yes, it looks like you're using some of the files from the 2.3.11 release and some of the files from the github master branch creating a mismatch.

All the best
David
