### ISSUE TITLE
Can't use raxml-ng with GTR+G model

### ISSUE THREAD

**Issue by WU-WEIHONG** [davidemms/OrthoFinder#383]
Hi,
Thank you very much for this great tool. I use Orthofinder to identity the WGD events, but i get some troubles when i use raxml-ng as tree inference method.
"cmd_line": "raxml-ng --msa INPUT --model LG+G4 --seed 12345 --threads 1" can pass the test. However, when i changed the LG+G4 model to GTR+G model the test failed.

Test can run "raxml-ng" - failed
Traceback (most recent call last):
  File "/public1/user/wu/.conda/envs/orthofinder/bin/orthofinder", line 7, in <module>
    main(args)
  File "/public1/user/wu/.conda/envs/orthofinder/bin/scripts_of/__main__.py", line 1641, in main
    CheckDependencies(options, prog_caller, files.FileHandler.GetWorkingDirectory1_Read()[0]) 
  File "/public1/user/wu/.conda/envs/orthofinder/bin/scripts_of/__main__.py", line 1301, in CheckDependencies
    options.qStopAfterAlignments):
  File "/public1/user/wu/.conda/envs/orthofinder/bin/scripts_of/orthologues.py", line 622, in CanRunOrthologueDependencies
    if not program_caller.TestTreeMethod(temp_dir, tree_method):
  File "/public1/user/wu/.conda/envs/orthofinder/bin/scripts_of/program_caller.py", line 180, in TestTreeMethod
    return self._TestMethod(working_dir, 'tree', method_name)
  File "/public1/user/wu/.conda/envs/orthofinder/bin/scripts_of/program_caller.py", line 229, in _TestMethod
    print(("".join(stdout)))
TypeError: sequence item 0: expected str instance, bytes found

Many thanks

Wu

**Comment by davidemms** [comment]
Hi Wu

Thanks for getting in touch. The latest version of OrthoFinder ([2.3.12](https://github.com/davidemms/OrthoFinder/releases/tag/2.3.12)) now correctly works on python 3 to report the error message from raxml-ng in this instance.

All the best
David
