### ISSUE TITLE
Errors during orthofinder with new species adding

### ISSUE THREAD

**Issue by Tdanis** [davidemms/OrthoFinder#389]
Hello again, during running orthofinder with precomputed species and 4 new  and this command (orthofinder -S blast -M msa -T raxml-ng -b previous_results/WorkingDirectory 
-f new_Proteomes -t 20 -a 10) 

I am taking this error...

OrthoFinder version 2.3.11 Copyright (C) 2014 David Emms

2020-05-15 01:45:07 : Starting OrthoFinder
20 thread(s) for highly parallel tasks (BLAST searches etc.)
10 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "mafft /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Test can run "raxml-ng" - ok

Adding new species in /mnt/scratch/tdanis/orthofinder/new_ortho_analysis/Proteomes/ to existing analysis in /mnt/scratch/tdanis/orthofinder/WorkingDirectory/

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2020-05-15 01:45:16 : Creating Blast database 1 of 34
2020-05-15 01:45:17 : Creating Blast database 2 of 34
...

Running BLAST all-versus-all
----------------------------
Using 20 thread(s)
2020-05-15 01:45:51 : This may take some time....

ERROR: external program called by OrthoFinder returned an error code: 6

Command: blastp -outfmt 6 -evalue 0.001 -query /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/Species30.fa -db /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/BlastDBSpecies29 -out /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/Blast30_29.txt

stdout
------

stderr
------
BLAST failed to write output

ERROR: external program called by OrthoFinder returned an error code: 1

Command: blastp -outfmt 6 -evalue 0.001 -query /mnt/scratch/tdanis/orthofinder/WorkingDirectory/Species29.fa -db /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/BlastDBSpecies30 -out /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/Blast29_30.txt

stdout
------

stderr
------
Command line argument error: Argument "out". File is not accessible:  `/mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/Blast22020-05-16 10:50:06 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2020-05-16 10:50:09 : Initial processing of each species
Malformatted line in /mnt/scratch/tdanis/orthofinder/WorkingDirectory/Blast7_30.txt
Offending line was:

Process Process-29:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 516, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 503, in ProcessBlastHits
  File "scripts_of/blast_file_processor.py", line 63, in GetBLAST6Scores
IOError: [Errno 2] No such file or directory: '/mnt/scratch/tdanis/orthofinder/WorkingDirectory/Blast7_30.txt'

ERROR: 12th field in BLAST results file line should be the bit-score for the hit
Malformatted line in /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/Blast9_30.txt
Offending line was:
9_9853  30_5602 31.183  93      62      2       21      111     424
Process Process-31:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 516, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 503, in ProcessBlastHits
  File "scripts_of/blast_file_processor.py", line 75, in GetBLAST6Scores
IndexError: list index out of range
Malformatted line in /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/Blast8_30.txt
Offending line was:
8_4245  30_26168        27.260  697     413     21      22      640     26  706      3.81e-64        229
Process Process-30:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 516, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 503, in ProcessBlastHits
  File "scripts_of/blast_file_processor.py", line 65, in GetBLAST6Scores
Error: line contains NULL byte

ERROR: 12th field in BLAST results file line should be the bit-score for the hit
Malformatted line in /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/Blast2_30.txt
Offending line was:
2_1939  30_14615        3
Process Process-24:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 516, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 503, in ProcessBlastHits
  File "scripts_of/blast_file_processor.py", line 75, in GetBLAST6Scores
IndexError: list index out of range

ERROR: 12th field in BLAST results file line should be the bit-score for the hit
Malformatted line in /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/Blast1_30.txt
Offending line was:
1_14814 30_17191        63.725  204     73      1       1       203     185420
Process Process-23:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 516, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 503, in ProcessBlastHits
  File "scripts_of/blast_file_processor.py", line 75, in GetBLAST6Scores
IndexError: list index out of range
Process Process-28:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 516, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 506, in ProcessBlastHits
  File "scripts_of/matrices.py", line 43, in DumpMatrixArray
  File "scripts_of/matrices.py", line 39, in DumpMatrix
IOError: [Errno 122] Disk quota exceeded
Malformatted line in /mnt/scratch/tdanis/orthofinder/WorkingDirectory/Blast3_31.txt
Offending line was:

Process Process-25:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 516, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 503, in ProcessBlastHits
  File "scripts_of/blast_file_processor.py", line 63, in GetBLAST6Scores
IOError: [Errno 2] No such file or directory: '/mnt/scratch/tdanis/orthofinder/WorkingDirectory/Blast3_31.txt'
Malformatted line in /mnt/scratch/tdanis/orthofinder/WorkingDirectory/Blast0_31.txt
Offending line was:

Process Process-22:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 516, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 503, in ProcessBlastHits
  File "scripts_of/blast_file_processor.py", line 63, in GetBLAST6Scores
IOError: [Errno 2] No such file or directory: '/mnt/scratch/tdanis/orthofinder/WorkingDirectory/Blast0_31.txt'
Process Process-27:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 516, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 508, in ProcessBlastHits
  File "scripts_of/matrices.py", line 43, in DumpMatrixArray
  File "scripts_of/matrices.py", line 39, in DumpMatrix
IOError: [Errno 122] Disk quota exceeded
Malformatted line in /mnt/scratch/tdanis/orthofinder/WorkingDirectory/Blast4_31.txt
Offending line was:

Process Process-26:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 516, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 503, in ProcessBlastHits
  File "scripts_of/blast_file_processor.py", line 63, in GetBLAST6Scores
IOError: [Errno 2] No such file or directory: '/mnt/scratch/tdanis/orthofinder/WorkingDirectory/Blast4_31.txt'
ERROR: An error occurred, please review error messages for more information.

Could you help me please??

Thank you

**Comment by davidemms** [comment]
Hi

In the output you've shown the error starts starts when calling this command:
```blastp -outfmt 6 -evalue 0.001 -query /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/Species30.fa -db /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/BlastDBSpecies29 -out /mnt/scratch/tdanis/orthofinder/WorkingDirectory/OrthoFinder/Results_May15/WorkingDirectory/Blast30_29.txt```

BLAST returns an error code and its stderr is, "BLAST failed to write output".

It seems likely that there were some kind of disk issues on your machine (disk space perhaps?) that prevented BLAST from being able to write its output file.

All the best
David

**Comment by davidemms** [comment]
Have you been able to resolve this issue?

All the best
David

**Comment by Tdanis** [comment]
Hello, my job is still running without errors. It seems that it is ok, but I am not sure unitl the end.

Thank you
