### ISSUE TITLE
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure

### ISSUE THREAD

**Issue by priyanka8590** [davidemms/OrthoFinder#394]
Hello, I have 10 species for which I want to find orthologs. I have the fasta files and Orthofinder seems to fail after 20 hours of running with the following error:
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure

**This is what the output file looks like**

```2020-05-21 19:41:33 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/Results_May21/Orthogroups.csv
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/Results_May21/Orthogroups.txt (OrthoMCL format)
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/Results_May21/Orthogroups_UnassignedGenes.csv
2020-05-21 19:41:57 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2020-05-22 14:09:46 : Done 0 of 18803
2020-05-22 14:10:29 : Done 1000 of 18803
2020-05-22 14:11:04 : Done 2000 of 18803
2020-05-22 14:11:37 : Done 3000 of 18803
2020-05-22 14:12:07 : Done 4000 of 18803
2020-05-22 14:12:37 : Done 5000 of 18803
2020-05-22 14:13:08 : Done 6000 of 18803
2020-05-22 14:13:38 : Done 7000 of 18803
2020-05-22 14:14:08 : Done 8000 of 18803
2020-05-22 14:14:38 : Done 9000 of 18803
2020-05-22 14:15:09 : Done 10000 of 18803
2020-05-22 14:15:39 : Done 11000 of 18803
2020-05-22 14:16:09 : Done 12000 of 18803
2020-05-22 14:16:40 : Done 13000 of 18803
2020-05-22 14:17:12 : Done 14000 of 18803
2020-05-22 14:17:44 : Done 15000 of 18803
2020-05-22 14:18:15 : Done 16000 of 18803
2020-05-22 14:18:48 : Done 17000 of 18803
2020-05-22 14:19:20 : Done 18000 of 18803
2020-05-22 14:09:43 : Done

Inferring gene and species trees
--------------------------------

OG0000000_tree_id.txt - WARNING: ETE could not interpret tree file, it will be ignored
OG0014592_tree_id.txt - WARNING: ETE could not interpret tree file, it will be ignored
6813 trees had all species present and will be used by STAG to infer the species tree


Best outgroup(s) for species tree
---------------------------------
2020-05-22 14:25:47 : Starting STRIDE
```

**This is what the error file looks like:**

```___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 327046
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 20133
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 135202
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 20012
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 21344
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 7698
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 131974
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 178812
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 191187
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 221705
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 274862
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 327650
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 2654
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 97249
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 97250
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 189547
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 215732
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 270218
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 326619
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 4879
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 114975
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 114976
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 142500
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 159977
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 164133
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 189116
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 216335
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 266326
___ [mclvInflate] warning: nonpositive sum <0.000000> for vector 320549
[mcl] cut <42> instances of overlap
[mcl] added <92400> garbage entries
Traceback (most recent call last):
  File "/work/LAS/mash-lab/bhandary/softwares/anaconda/envs/phylogenetic/bin/orthofinder", line 1577, in <module>
    GetOrthologues(dirs, options, program_caller, clustersFilename_pairs, orthogroupsResultsFilesString)
  File "/work/LAS/mash-lab/bhandary/softwares/anaconda/envs/phylogenetic/bin/orthofinder", line 1415, in GetOrthologues
    options.name)
  File "/work/LAS/mash-lab/bhandary/softwares/anaconda/envs/phylogenetic/bin/scripts/orthologues.py", line 1097, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, all_stride_dup_genes = stride.GetRoot(spTreeFN_ids, os.path.split(db.TreeFilename_IDs(0))[0] + "/", stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
  File "/work/LAS/mash-lab/bhandary/softwares/anaconda/envs/phylogenetic/bin/scripts/stride.py", line 505, in GetRoot
    list_of_dicts = pool.map(SupportedHierachies_wrapper2, [(fn, GeneToSpeciesMap, species, dict_clades, clade_names, qWriteDupTrees) for fn in glob.glob(treesDir + "/*")])
  File "/work/LAS/mash-lab/bhandary/softwares/anaconda/envs/phylogenetic/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/work/LAS/mash-lab/bhandary/softwares/anaconda/envs/phylogenetic/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
```

**My SLURM script looks like this:**

```#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=70:00:00
#SBATCH --mem=120G
#SBATCH --mail-user=bhandary@iastate.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --error=/work/LAS/mash-lab/bhandary/phylogenetic_analysis/ortholatest.error
#SBATCH --output=/work/LAS/mash-lab/bhandary/phylogenetic_analysis/ortholatest.output
conda activate phylogenetic
orthofinder -f /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ -S diamond
```

I have been running it with 16 CPUs and it always fails after 20 hours. Could you help me with this?
Thank you in advance!

**Comment by davidemms** [comment]
HI

Could you email me the input files so I can try to reproduce it? 
david.emms@plants.ox.ac.uk

Thanks
David

**Comment by priyanka8590** [comment]
Sure! I have emailed them to you! 

Thank you,
Priyanka

**Comment by davidemms** [comment]
Hi

I've run OrthoFinder on my computer on the input data and it's ran without any problems. I'm not sure what the error might have been when you ran it but I can see that mcl is producing some unexpected warning messages. It makes be wonder what happened before that in OrthoFinder's preparation of the data for MCL. Do you have the complete output from OrthoFinder, specifically the messages from the start to when the first warning messages occurred? 

Also, have you run any other OrthoFinder analyses on that server? If not, could you try the Example Dataset and see if that runs successfully?

Thanks
David

**Comment by priyanka8590** [comment]
Hello David,

**Here is what the output file looks like (for my dataset):**
```Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/Results_May21/Orthogroups.csv
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/Results_May21/Orthogroups.txt (OrthoMCL format)
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/Results_May21/Orthogroups_UnassignedGenes.csv
2020-05-21 19:41:57 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2020-05-22 14:09:46 : Done 0 of 18803
2020-05-22 14:10:29 : Done 1000 of 18803
2020-05-22 14:11:04 : Done 2000 of 18803
2020-05-22 14:11:37 : Done 3000 of 18803
2020-05-22 14:12:07 : Done 4000 of 18803
2020-05-22 14:12:37 : Done 5000 of 18803
2020-05-22 14:13:08 : Done 6000 of 18803
2020-05-22 14:13:38 : Done 7000 of 18803
2020-05-22 14:14:08 : Done 8000 of 18803
2020-05-22 14:14:38 : Done 9000 of 18803
2020-05-22 14:15:09 : Done 10000 of 18803
2020-05-22 14:15:39 : Done 11000 of 18803
2020-05-22 14:16:09 : Done 12000 of 18803
2020-05-22 14:16:40 : Done 13000 of 18803
2020-05-22 14:17:12 : Done 14000 of 18803
2020-05-22 14:17:44 : Done 15000 of 18803
2020-05-22 14:18:15 : Done 16000 of 18803
2020-05-22 14:18:48 : Done 17000 of 18803
2020-05-22 14:19:20 : Done 18000 of 18803
2020-05-22 14:09:43 : Done

Inferring gene and species trees
--------------------------------

OG0000000_tree_id.txt - WARNING: ETE could not interpret tree file, it will be ignored
OG0014592_tree_id.txt - WARNING: ETE could not interpret tree file, it will be ignored
6813 trees had all species present and will be used by STAG to infer the species tree


Best outgroup(s) for species tree
---------------------------------
2020-05-22 14:25:47 : Starting STRIDE
```

I tried it with the Example dataset and it completed successfully. I got all the file and it completed in 45 seconds (16 CPUs on the cluster). I have attached the output file for the Example dataset too below:

```OrthoFinder version 2.2.6 Copyright (C) 2014 David Emms

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ExampleDataset/SimpleTest.phy -o /work/LAS/mash-lab/bhandary/phylogenet
ic_analysis/OrthoFinder/ExampleDataset/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2020-05-29 16:44:34 : Creating diamond database 1 of 4
2020-05-29 16:44:34 : Creating diamond database 2 of 4
2020-05-29 16:44:34 : Creating diamond database 3 of 4
2020-05-29 16:44:34 : Creating diamond database 4 of 4

Running diamond all-versus-all
------------------------------
Using 16 thread(s)
2020-05-29 16:44:34 : This may take some time....
2020-05-29 16:44:34 : Done 0 of 16

Running OrthoFinder algorithm
-----------------------------
2020-05-29 16:44:40 : Initial processing of each species
2020-05-29 16:44:40 : Initial processing of species 0 complete
2020-05-29 16:44:40 : Initial processing of species 1 complete
2020-05-29 16:44:40 : Initial processing of species 2 complete
2020-05-29 16:44:41 : Initial processing of species 3 complete
2020-05-29 16:44:44 : Connected putatitive homologs
2020-05-29 16:44:45 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ExampleDataset/Results_May29/Orthogroups.csv
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ExampleDataset/Results_May29/Orthogroups.txt (OrthoMCL format)
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ExampleDataset/Results_May29/Orthogroups_UnassignedGenes.csv
2020-05-29 16:44:45 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
2020-05-29 16:44:49 : Done 0 of 299
2020-05-29 16:44:51 : Done 100 of 299
2020-05-29 16:44:54 : Done 200 of 299
2020-05-29 16:44:48 : Done

Inferring gene and species trees
--------------------------------

269 trees had all species present and will be used by STAG to infer the species tree


Best outgroup(s) for species tree
---------------------------------
2020-05-29 16:45:01 : Starting STRIDE
2020-05-29 16:45:01 : Done STRIDE
Observed 2 well-supported, non-terminal duplications. 2 support the best roots and 0 contradict them.
Best outgroups for species tree:
  Mycoplasma_hyopneumoniae
  Mycoplasma_agalactiae, Mycoplasma_hyopneumoniae
  Mycoplasma_agalactiae


Multiple potential species tree roots were identified, only one will be analyed.
================================================================================

Reconciling gene trees and species tree
---------------------------------------
Outgroup: Mycoplasma_hyopneumoniae
2020-05-29 16:45:01 : Starting Recon and orthologues
2020-05-29 16:45:01 : Starting OF Orthologues
2020-05-29 16:45:01 : Done 0 of 299
2020-05-29 16:45:02 : Done 100 of 299
2020-05-29 16:45:03 : Done 200 of 299
2020-05-29 16:45:03 : Done OF Orthologues
2020-05-29 16:45:03 : Done Recon

Writing results files
=====================
2020-05-29 16:45:04 : Done orthologues
Orthogroups have been written to tab-delimited files:
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ExampleDataset/Results_May29/Orthogroups.csv
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ExampleDataset/Results_May29/Orthogroups.txt (OrthoMCL format)
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ExampleDataset/Results_May29/Orthogroups_UnassignedGenes.csv

Gene trees:
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ExampleDataset/Results_May29/Orthologues_May29/Gene_Trees/

Rooted species tree:
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ExampleDataset/Results_May29/Orthologues_May29/SpeciesTree_rooted.txt

Species-by-species orthologues:
   /work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/ExampleDataset/Results_May29/Orthologues_May29/Orthologues/

Orthogroup statistics:
   Statistics_PerSpecies.csv   Statistics_Overall.csv   Orthogroups_SpeciesOverlaps.csv

OrthoFinder assigned 1779 genes (65.1% of total) to 507 orthogroups. Fifty percent of all genes were in orthogroups with 3 or more genes (G50 was 3) and were contained in the largest 322 orthogroups (O50 was 322). There were 269 orthogroups with all species present and 248 of these consisted entirely of single-copy genes.

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2015), Genome Biology 16:157

 If you use the species tree in your work then please also cite:
 Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
 Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101/267914
```

I don't understand why it won't work with my dataset. Is there somewhere I'm going wrong? Also, I running it with a condo environment. 

Thank you,
Priyanka

**Comment by priyanka8590** [comment]
Hello David,

I also noticed that when I ran it with the Example dataset, it didn't output the folder 'Orthogroup Sequences'. It ran successfully and completed in 10 minutes when I ran it with 16 CPUs. Is there a specific reason why it wouldn't output that folder? 

Thank you,
Priyanka

**Comment by davidemms** [comment]
Hi Priyanka

Unfortunately that's only the end of the output, it doesn't have the messages from the start which might contain clues as to what happened.

For the Example Dataset, the 'Orthogroup Sequences' directory was not available in the release that you are using--I'm guessing something before 2.3.3?

The original problem may be associated with disk space or other server resources or it could be an issue that's since been resolved. I think the best thing all round is to update to the latest release and try running it again on your dataset. 

All the best
David

**Comment by priyanka8590** [comment]
Hi David,

It worked. There were clashes between the python version and OrthoFinder version. I was using an older version of OrthoFinder too. Thank you so much for all your help!

Priyanka

**Comment by davidemms** [comment]
Hi Priyanka

No problem, I'm glad you got it working!

All the best
David
