### ISSUE TITLE
Error with exampledata

### ISSUE THREAD

**Issue by Lathomas42** [davidemms/OrthoFinder#449]
Orthofinder on OSX 10.15.6 installed via bioconda.
The exampledata errors with this error. Not entirely sure how it gets into this state. however I tried uninstalling and reinstalling and it still fails. 

orthofinder -f ExampleData

Running OrthoFinder algorithm
-----------------------------
2020-08-31 13:26:03 : Initial processing of each species
Process Process-6:
Traceback (most recent call last):
  File "<userdir>/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "<userdir>/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<userdir>/miniconda3/bin/scripts_of/__main__.py", line 520, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, qDoubleBlast=qDoubleBlast)
  File "<userdir>/miniconda3/bin/scripts_of/__main__.py", line 510, in ProcessBlastHits
    matrices.DumpMatrixArray("B", Bi, iSpecies)
  File "<userdir>/miniconda3/bin/scripts_of/matrices.py", line 43, in DumpMatrixArray
    DumpMatrix(name, m, iSpecies, jSpecies)
  File "<userdir>/miniconda3/bin/scripts_of/matrices.py", line 38, in DumpMatrix
    with open(files.FileHandler.GetPickleDir() + "%s%d_%d.pic" % (name, iSpecies, jSpecies), 'wb') as picFile:
  File "<userdir>/miniconda3/bin/scripts_of/files.py", line 215, in GetPickleDir
    d = self.wd_current + "pickle/"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.

**Comment by davidemms** [comment]
That's strange, I can't think how that could arise. Could you tell me what version of OrthoFinder you're using? And what output do you get if you run `tree` on the newly created results directory inside "ExampleData/OrthoFinder/" (or some other command to list the directory contents)?

All the best
David
