### ISSUE TITLE
OrthoFinder restart options fail if the containing folder is renamed

### ISSUE THREAD

**Issue by davidemms** [davidemms/OrthoFinder#476]
**Steps to reproduce**
Run orthofinder on a directory X within another directory Y, change the name of the directory Y, restart orthofinder from the results of the first run
```
mkdir test
cd test
wget https://github.com/davidemms/OrthoFinder/releases/download/2.4.0/OrthoFinder_source.tar.gz
tar xzf OrthoFinder_source.tar.gz
cd OrthoFinder_source/
python orthofinder.py -f ExampleData/ -n path_error
cd ../../
mv test test2
cd test2/OrthoFinder_source/
python orthofinder.py -ft ExampleData/OrthoFinder/Results_path_error/
```

**Expected result**
OrthoFinder should continue the analysis from the previous results directory

**Actual result**
OrthoFinder crashes:
```
OrthoFinder version 2.4.0 Copyright (C) 2014 David Emms

2020-11-06 14:32:51 : Starting OrthoFinder
48 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm
Traceback (most recent call last):
  File "OrthoFinder_source/orthofinder.py", line 7, in <module>
    main(args)
  File "/home/emms/test2/OrthoFinder_source/scripts_of/__main__.py", line 1685, in main
    files.InitialiseFileHandler(options, fastaDir, continuationDir, resultsDir_nonDefault, pickleDir_nonDefault)     
  File "/home/emms/test2/OrthoFinder_source/scripts_of/files.py", line 834, in InitialiseFileHandler
    FileHandler.CreateOutputDirectories(options, pfl, base_dir, fastaDir)    
  File "/home/emms/test2/OrthoFinder_source/scripts_of/files.py", line 194, in CreateOutputDirectories
    user_name=options.name)
  File "/home/emms/test2/OrthoFinder_source/scripts_of/files.py", line 153, in StartFromTrees
    shutil.copy(speciesTreeFN, self.GetSpeciesTreeIDsRootedFN())
  File "/usr/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/emms/test/OrthoFinder_source/ExampleData/OrthoFinder/Results_path_error/WorkingDirectory/SpeciesTree_rooted_ids.txt'
```

**Comment by davidemms** [comment]
Note, start from BLAST:
```
python orthofinder.py -b ExampleData/OrthoFinder/Results_path_error/
```
and start from orthogroups:
```
python orthofinder.py -fg ExampleData/OrthoFinder/Results_path_error/
```
both work.

**Comment by davidemms** [comment]
This also applies if there is a chain of linked OrthoFinder runs and the series of working directories for these must be located using relative paths because the containing directory has been moved:
```
Test can run "fastme -i /home/emms/OrthoFinder_source/ExampleData/OrthoFinder/Results_Nov06_1/../Results_Nov06_1/WorkingDirectory/SimpleTest.phy -o /home/emms/OrthoFinder_source/ExampleData/OrthoFinder/Results_Nov06_1/../Results_Nov06_1/WorkingDirectory/SimpleTest.tre" - ok
ERROR: Not all expected fasta files are present. Index of last fasta file is 5 but found 2 fasta files.

ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.
```
