### ISSUE TITLE
TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by mdayii** [davidemms/OrthoFinder#487]
Dear David,

I have installed orthofinder version 2.5.1. It works for orthologs, but not for gene alignments and gene trees and species trees. 
I received an error:

```
/tmp/11025382.1.medium.q/_MEI7pw6rM/scripts_of/trees_msa.py:246: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1765, in main
  File "scripts_of/__main__.py", line 1545, in GetOrthologues
  File "scripts_of/orthologues.py", line 975, in OrthologuesWorkflow
  File "scripts_of/trees_msa.py", line 373, in DoTrees
  File "scripts_of/trees_msa.py", line 246, in CreateConcatenatedAlignment
TypeError: 'bool' object is not iterable
[75513] Failed to execute script orthofinder
```

and 

Analysing Orthogroups
=====================
2020-12-08 18:57:56 : Starting MSA/Trees
Species tree: Using 1090 orthogroups with minimum of 97.3% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
WARNING: 
list index out of range
WARNING: 
list index out of range
WARNING: 
list index out of range
WARNING: 
list index out of range
WARNING: 
list index out of range

```
No tree or orthologs will be inferred for this orthogroup. To correct the issue, identify & correct the problematic gene sequence and rerun.
WARNING: An MSA failed for an unknown reason: /lustre7/home/lustre4/user10/Projects/OrthoFinder/Results_Dec08/WorkingDirectory/Alignments_ids/OG0006938.fa
No tree or orthologs will be inferred for this orthogroup. To correct the issue, identify & correct the problematic gene sequence and rerun.
```

 there are many warnings for all orthogroups.**

**Comment by davidemms** [comment]
Hi

I think this might be the issue described here:
https://stackoverflow.com/questions/40659212/futurewarning-elementwise-comparison-failed-returning-scalar-but-in-the-futur

I'm not able to reproduce it at the moment, but would you be able to let me know what version of python and what version of numpy you are using as I think it will allow me to reproduce the issue on my machine and fix it.
```
python
import numpy
numpy.__version__
```
should print out the version info.

Could you also check to see if this same problem occurs with the ExampleDataset, and if you so could you attach the full output that orthofinder prints to the terminal.
```
python
import numpy
numpy.__version__
```
should print out the version info.

And lastly, could you also attach the file: /lustre7/home/lustre4/user10/Projects/OrthoFinder/Results_Dec08/WorkingDirectory/Alignments_ids/OG0006938.fa and I'll see if there are any particular issues apparent in that file.

Many thanks 
David

**Comment by mdayii** [comment]
Dear David,

Thanks for your fast reply.

```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.16.4'
>>> 
```

When I used the Example data set, OrthoFinder produced the same error as in the attached file.



[ortfinder.error.txt](https://github.com/davidemms/OrthoFinder/files/5660972/ortfinder.error.txt)

I have used several version of OrthoFinder as below:
`/home/user10/applications/OrthoFinder-2.2.6/orthofinder -f ./ -t 256 -a 2 -S diamond -M msa`

it produced:

```
[mcl] cut <19> instances of overlap
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1577, in <module>
  File "orthofinder/orthofinder.py", line 1415, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 1031, in OrthologuesWorkflow
  File "orthofinder/scripts/trees_msa.py", line 362, in DoTrees
  File "orthofinder/scripts/trees_msa.py", line 214, in CreateConcatenatedAlignment
  File "orthofinder/scripts/trees_msa.py", line 206, in ReadAlignment
  File "orthofinder/scripts/trees_msa.py", line 181, in __init__
IndexError: list index out of range
Failed to execute script orthofinder
```
and another version:

```
Traceback (most recent call last):
  File "/home/user10/miniconda3/envs/OrthoFinder/bin/orthofinder", line 7, in <module>
    main(args)
  File "/lustre7/home/lustre4/user10/miniconda3/envs/OrthoFinder/bin/scripts_of/__main__.py", line 1687, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/lustre7/home/lustre4/user10/miniconda3/envs/OrthoFinder/bin/scripts_of/__main__.py", line 1497, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
  File "/lustre7/home/lustre4/user10/miniconda3/envs/OrthoFinder/bin/scripts_of/orthologues.py", line 897, in OrthologuesWorkflow
 seqs_alignments_dirs = treeGen.DoTrees(ogSet.OGs(qInclAll=True), ogSet.OrthogroupMatrix(), ogSet.Spec_SeqDict(), ogSet.SpeciesDict(), ogSet.speciesToUse, nHighParallel, qStopAfterSeqs, qStopAfterAlign or qPhyldog, qDoSpeciesTree=qDoMSASpeciesTree) 
  File "/lustre7/home/lustre4/user10/miniconda3/envs/OrthoFinder/bin/scripts_of/trees_msa.py", line 359, in DoTrees
    CreateConcatenatedAlignment(iOgsForSpeciesTree, ogs, self.GetAlignmentFilename, concatenated_algn_fn, fSingleCopy)
  File "/lustre7/home/lustre4/user10/miniconda3/envs/OrthoFinder/bin/scripts_of/trees_msa.py", line 222, in CreateConcatenatedAlignment
    alignment = ReadAlignment(alignment_filename_function(iOg))
  File "/lustre7/home/lustre4/user10/miniconda3/envs/OrthoFinder/bin/scripts_of/trees_msa.py", line 214, in ReadAlignment
    return MSA(msa)
  File "/lustre7/home/lustre4/user10/miniconda3/envs/OrthoFinder/bin/scripts_of/trees_msa.py", line 189, in __init__
    self.length = len(list(msa_dict.values())[0])
IndexError: list index out of range
```
I attached error file of conda version of OrthoFinder.
[orthofinder.conda.version.txt](https://github.com/davidemms/OrthoFinder/files/5661037/orthofinder.conda.version.txt)

**Comment by davidemms** [comment]
Hi

It looks like the problem might be with the MSA program (not numpy as I expected earlier), since it looks like all or most of the MSA fail in the output from the Example Dataset:
```
WARNING: An MSA failed for an unknown reason: /lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec09/WorkingDirectory/Alignments_ids/OG0000053.fa
No tree or orthologs will be inferred for this orthogroup. To correct the issue, identify & correct the problematic gene sequence and rerun.
```

By default OrthoFinder will use mafft for alignments. Could you try:
```
mafft /lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec09/WorkingDirectory/Sequences_ids/OG0000053.fa > OG0000053.aln.fa
```
I think you might get an error. If so, then you'll need to resolve the issue with mafft and that should resolve the issue for OrthoFinder. If instead mafft runs successfully, could you post the output it prints and also attach the output file "OG0000053.aln.fa" and check whether it is the same as "/lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec09/WorkingDirectory/Alignments_ids/OG0000053.fa"

All the best
David

**Comment by mdayii** [comment]
Hi David,

I used mafft as you suggested. I attached two files. 
mafft works regularly. 


[maff.txt](https://github.com/davidemms/OrthoFinder/files/5665369/maff.txt)

[maffft.out.txt](https://github.com/davidemms/OrthoFinder/files/5665378/maffft.out.txt)

Best wishes,

**Comment by davidemms** [comment]
Hi 

So the alignment files (e.g. /lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec09/WorkingDirectory/Alignments_ids/OG0000053.fa) are empty at the point that OrthoFinder tries to read them, which is just after mafft has run. I'm trying to figure out why that might be. 

Best wishes
David

**Comment by davidemms** [comment]
An example of one of the MSA that was empty according to the output from your test using the example dataset was: `/lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec09/WorkingDirectory/Alignments_ids/OG0000053.fa`

Would you be able to confirm if this file is empty or not?

Best wishes 
David

**Comment by mdayii** [comment]
Hi David,

Yes, not aligments were produced. 
I attached results.
[test.ortinder.txt](https://github.com/davidemms/OrthoFinder/files/5667512/test.ortinder.txt)

**Comment by davidemms** [comment]
This is a different directory, `WorkingDirectory/Alignments_ids/`. 

Would you be able to run `ls -l WorkingDirectory/Alignments_ids/`

**Comment by mdayii** [comment]
I checked and all alignments are empty.

**Comment by davidemms** [comment]
To work out what is going wrong with the alignments, edit the OrthoFinder config file to include this entry:
```
"mafft_debug": { 
"program_type": "msa", 
"cmd_line": "mafft --localpair --maxiterate 1000 --anysymbol INPUT > OUTPUT 2>> mafft_stderr.txt",
"cmd_line_fast": "mafft --anysymbol INPUT > OUTPUT 2>> mafft_stderr.txt", 
"n_seqs_use_fast" : "500"}
```
(you'll need to put a comma after the previous entry so that the JSON formatting is correct)

Then call orthofinder using this mafft_debug option:
```
python ~/workspace/git/OrthoFinder/orthofinder.py -A mafft_debug -t 1 -M msa -fg /lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec09/
```

It will produce a file called `mafft_stderr.txt` in your current directory with the output from mafft, which should hopefully identify what's going wrong. 

If you want, you can also use a different alignment program with OrthoFinder, by selecting it using the "-A" option as above and as described on the orthofinder help file. The config.json file describes how to call the program, there's an entry for muscle and you can also add entries for any other alignment program too.

All the best
David

**Comment by mdayii** [comment]
Hi David,

OK. I edited config file as below:

 ```
   "mafft_debug": { 
    "program_type": "msa", 
    "cmd_line": "mafft --localpair --maxiterate 1000 --anysymbol INPUT > OUTPUT 2>> mafft_stderr.txt", 
    "cmd_line_fast": "mafft --anysymbol INPUT > OUTPUT 2>> mafft_stderr.txt", 
    "n_seqs_use_fast" : "500"}
}
```

Later, I run orthofinder as below:

```
./orthofinder -A mafft_debug -t 1 -M msa -fg ExampleData/OrthoFinder/Results_Dec10 -t 2

OrthoFinder version 2.5.1 Copyright (C) 2014 David Emms

2020-12-10 17:49:08 : Starting OrthoFinder 2.5.1
2 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mafft_debug" - ok
Test can run "FastTree /lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec10/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok

Analysing Orthogroups
=====================
2020-12-10 17:49:08 : Starting MSA/Trees
Species tree: Using 246 orthogroups with minimum of 100.0% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2020-12-10 17:49:15 : Done 0 of 246
2020-12-10 17:49:51 : Done 100 of 246
2020-12-10 17:50:25 : Done 200 of 246

Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
2020-12-10 17:50:41 : Done 0 of 359
2020-12-10 17:51:53 : Done 100 of 359
2020-12-10 17:52:06 : Done 200 of 359
2020-12-10 17:52:14 : Done 300 of 359
2020-12-10 17:52:24 : Done MSA/Trees

Best outgroup(s) for species tree
---------------------------------
2020-12-10 17:52:24 : Starting STRIDE
2020-12-10 17:52:24 : Done STRIDE
Observed 2 well-supported, non-terminal duplications. 2 support the best roots and 0 contradict them.
Best outgroups for species tree:
  Mycoplasma_hyopneumoniae
  Mycoplasma_agalactiae, Mycoplasma_hyopneumoniae
  Mycoplasma_agalactiae

WARNING: Multiple potential species tree roots were identified, only one will be analyed.

Reconciling gene trees and species tree
---------------------------------------
Outgroup: Mycoplasma_hyopneumoniae
2020-12-10 17:52:24 : Starting Recon and orthologues
2020-12-10 17:52:24 : Starting OF Orthologues
2020-12-10 17:52:24 : Done 0 of 325
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
2020-12-10 17:52:24 : Done 100 of 325
2020-12-10 17:52:25 : Done 200 of 325
2020-12-10 17:52:25 : Done 300 of 325
2020-12-10 17:52:26 : Done OF Orthologues

Writing results files
=====================
2020-12-10 17:52:26 : Done orthologues

Results:
    /lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec10_8/

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2019), Genome Biology 20:238

 If you use the species tree in your work then please also cite:
 Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
 Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101/267914
```

This time I have alignments, gene trees and species tree.

Later, I run orthofinder as below:

```
./orthofinder -f ExampleData/ -M msa -t 2 

OrthoFinder version 2.5.1 Copyright (C) 2014 David Emms

2020-12-10 17:56:33 : Starting OrthoFinder 2.5.1
2 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "mafft /lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec10_9/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Test can run "FastTree /lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec10_9/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2020-12-10 17:56:33 : Creating diamond database 1 of 4
2020-12-10 17:56:33 : Creating diamond database 2 of 4
2020-12-10 17:56:33 : Creating diamond database 3 of 4
2020-12-10 17:56:33 : Creating diamond database 4 of 4

Running diamond all-versus-all
------------------------------
Using 2 thread(s)
2020-12-10 17:56:33 : This may take some time....
2020-12-10 17:56:33 : Done 0 of 16
2020-12-10 17:56:42 : Done 10 of 16
2020-12-10 17:56:47 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2020-12-10 17:56:47 : Initial processing of each species
2020-12-10 17:56:48 : Initial processing of species 0 complete
2020-12-10 17:56:48 : Initial processing of species 1 complete
2020-12-10 17:56:48 : Initial processing of species 2 complete
2020-12-10 17:56:48 : Initial processing of species 3 complete
2020-12-10 17:56:50 : Connected putative homologues
2020-12-10 17:56:50 : Written final scores for species 0 to graph file
2020-12-10 17:56:50 : Written final scores for species 1 to graph file
2020-12-10 17:56:50 : Written final scores for species 2 to graph file
2020-12-10 17:56:51 : Written final scores for species 3 to graph file
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
2020-12-10 17:56:51 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 2202 genes (80.6% of total) to 604 orthogroups. Fifty percent of all genes were in orthogroups with 4 or more genes (G50 was 4) and were contained in the largest 281 orthogroups (O50 was 281). There were 269 orthogroups with all species present and 246 of these consisted entirely of single-copy genes.

2020-12-10 17:56:53 : Done orthogroups

Analysing Orthogroups
=====================
2020-12-10 17:56:53 : Starting MSA/Trees
Species tree: Using 246 orthogroups with minimum of 100.0% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2020-12-10 17:56:55 : Done 0 of 246
2020-12-10 17:57:21 : Done 100 of 246
2020-12-10 17:57:48 : Done 200 of 246

Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
2020-12-10 17:58:03 : Done 0 of 359
2020-12-10 17:59:14 : Done 100 of 359
2020-12-10 17:59:27 : Done 200 of 359
2020-12-10 17:59:35 : Done 300 of 359
2020-12-10 17:59:45 : Done MSA/Trees

Best outgroup(s) for species tree
---------------------------------
2020-12-10 17:59:45 : Starting STRIDE
2020-12-10 17:59:45 : Done STRIDE
Observed 2 well-supported, non-terminal duplications. 2 support the best roots and 0 contradict them.
Best outgroups for species tree:
  Mycoplasma_hyopneumoniae
  Mycoplasma_agalactiae, Mycoplasma_hyopneumoniae
  Mycoplasma_agalactiae

WARNING: Multiple potential species tree roots were identified, only one will be analyed.

Reconciling gene trees and species tree
---------------------------------------
Outgroup: Mycoplasma_hyopneumoniae
2020-12-10 17:59:45 : Starting Recon and orthologues
2020-12-10 17:59:45 : Starting OF Orthologues
2020-12-10 17:59:45 : Done 0 of 325
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
2020-12-10 17:59:46 : Done 100 of 325
2020-12-10 17:59:46 : Done 200 of 325
2020-12-10 17:59:47 : Done 300 of 325
2020-12-10 17:59:47 : Done OF Orthologues

Writing results files
=====================
2020-12-10 17:59:47 : Done orthologues

Results:
    /lustre7/home/lustre4/mdayi/applications/OrthoFinder/ExampleData/OrthoFinder/Results_Dec10_9/

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2019), Genome Biology 20:238

 If you use the species tree in your work then please also cite:
 Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
 Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101/267914
```

Now everything is fine. I figured out what was wrong. It is my fault.
In `mafft` debug file there was a problem regarding mafft location as below:

```
nseq =  4
nlen = 
distance =  local
iterate =  16
cycle =  1
/home/mdayi/applications/prank/bin/mafft: line 1195: /home/mdayi/applications/prank/bin/lib/replaceu: No such file or directory
/home/mdayi/applications/prank/bin/mafft: line 1393: /tmp/mafft.XuntMVnYgd/pre: No such file or directory
```


`mafft` was also found in prank tool bin directory. I removed prank path from `bashrc`, then `mafft` worked correctly.

Thank you very much for your great effort and help. Sorry again. It is pleasure to use orthofinder.
