### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by macmanes** [davidemms/OrthoFinder#51]
Hi David

I am having problems getting OrthoFinder up and running on PSC Bridges.

```bash
/home/macmanes/OrthoFinder/orthofinder/orthofinder.py -f /home/macmanes/genomes/
OrthoFinder version 1.1.5 Copyright (C) 2014 David Emms

    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.
    For details please see the License.md that came with this software.

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "fastme -i /home/macmanes/genomes/SimpleTest.phy -o /home/macmanes/genomes/SimpleTest.tre" - ok
Test can run "dlcpar_search --version" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2017-03-02 14:15:33 : Creating Blast database 1 of 45
Traceback (most recent call last):
  File "/home/macmanes/OrthoFinder/orthofinder/orthofinder.py", line 1375, in <module>
    CreateBlastDatabases(dirs)
  File "/home/macmanes/OrthoFinder/orthofinder/orthofinder.py", line 1204, in CreateBlastDatabases
    RunBlastDBCommand(command)
  File "/home/macmanes/OrthoFinder/orthofinder/orthofinder.py", line 71, in RunBlastDBCommand
    capture = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=my_env)
  File "/opt/packages/python/2_7_11_gcc/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/packages/python/2_7_11_gcc/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

my fasta files are indeed at `/home/macmanes/genomes/`, and in fact in `WorkingDirectory` they are all copied there as per normal. 

```bash
ls -lth /home/macmanes/genomes/
-rw-r--r-- 1 macmanes mc3bg6p 7.3M Jan 21  2016 Egretta_garzetta.fasta
-rw-r--r-- 1 macmanes mc3bg6p 6.1M Jan 21  2016 Fulmarus_glacialis.fasta
-rw-r--r-- 1 macmanes mc3bg6p 8.0M Jan 21  2016 Gallus_gallus.fasta
-rw-r--r-- 1 macmanes mc3bg6p 5.8M Jan 21  2016 Gavia_stellata.fasta
-rw-r--r-- 1 macmanes mc3bg6p 7.7M Jan 21  2016 Geospiza_fortis.gene.fasta
-rw-r--r-- 1 macmanes mc3bg6p 6.1M Jan 21  2016 Haliaeetus_albicilla.fasta
-rw-r--r-- 1 macmanes mc3bg6p 7.8M Jan 21  2016 Haliaeetus_leucocephalus.fasta
-rw-r--r-- 1 macmanes mc3bg6p 6.4M Jan 21  2016 Leptosomus_discolor.fasta
-rw-r--r-- 1 macmanes mc3bg6p 7.3M Jan 21  2016 Manacus_vitellinus.fasta
-rw-r--r-- 1 macmanes mc3bg6p 6.1M Jan 21  2016 Cariama_cristata.fasta
-rw-r--r-- 1 macmanes mc3bg6p 5.2M Jan 21  2016 Cathartes_aura.fasta
```

Any ideas?

**Comment by macmanes** [comment]
and using the binary:

```
orthofinder -f /home/macmanes/genomes/
OrthoFinder version 1.1.4 Copyright (C) 2014 David Emms

    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.
    For details please see the License.md that came with this software.

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "fastme -i /home/macmanes/genomes/SimpleTest.phy -o /home/macmanes/genomes/SimpleTest.tre" - ok
Test can run "dlcpar_search --version" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2017-03-02 14:53:03 : Creating Blast database 1 of 45
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1370, in <module>
  File "orthofinder/orthofinder.py", line 1200, in CreateBlastDatabases
  File "orthofinder/orthofinder.py", line 71, in RunBlastDBCommand
  File "subprocess.py", line 679, in __init__
  File "subprocess.py", line 1259, in _execute_child
OSError: [Errno 2] No such file or directory
Failed to execute script orthofinder

```

**Comment by davidemms** [comment]
Hi Matt

The problem is occurring when calling makeblastdb to create the BLAST databases. Do you know if BLAST is correctly installed and if the commands "makeblastdb" and "blastp" are working? In the above output OrthoFinder has checked that it can call makeblastdb and it appeared to work fine, that's what the line  

> Test can run "makeblastdb -help" - ok

is about. The only thing I can currently think of is that when it tests makeblastdb it uses the shell whereas the second time it call the program directly. I don't know why this would be a problem but you could test if it is by calling the attached script (it's a python program but I've given it a .txt. ending so github will let me attach it). If it prints

> Call using shell
> OK
> 
> Call without using shell
> OK 

then the problem is probably elsewhere. Otherwise, if the first part works and the second part produces the error you've reported above then we've found the problem and I can get it fixed.

All the best 
David


[test_execute.txt](https://github.com/davidemms/OrthoFinder/files/855543/test_execute.txt)

**Comment by davidemms** [comment]
Hi

I don't suppose you have any new information on this? If there's a problem with OrthoFinder then I can fix it or if there was something that you needed to do to resolve it then that info could be helpful to other users.

Thanks
David

**Comment by AlexPersa7** [comment]
Hi Mat, 
Did you check if numpy is correctly installed?

cheers,
