### ISSUE TITLE
OrthoFinder with -ft

### ISSUE THREAD

**Issue by Edison2021** [davidemms/OrthoFinder#530]
Hi David

Orthofinder was killed at the stage of gene tree construction due to time limitation. I ran the remaining gene trees and moved them to “Trees_ids”. I would like to continue the pipeline with -ft. The Orthofinder asked me to provide the species tree for that. I checked the result folder and did not find rooted species tree. Only a file named “SpeciesTree_unrooted_ids.txt” from WorkingDirectry is relevant. 

How can I make my own species tree using the correct names for each species? 
Does -ft option require resolved gene trees? or the trees in “Trees_ids”?

Thanks
Edison

**Comment by davidemms** [comment]
Hi Edison

You can use the script `tools/convert_orthofinder_tree_ids.py` to do the conversion:
```
python convert_orthofinder_tree_ids.py SpeciesTree_unrooted_ids.txt SpeciesIDs.txt
```
(with the relative paths to the script/files altered for where they are on your computer)

The -ft option will use the trees in Trees_ids/. You can provide the species tree you prepare as an argument using the -s option. You will need to root the species tree yourself first, you can use something like dendroscope to do this and  export it as newick.

Best wishes
David

**Comment by Edison2021** [comment]
Hi David
I tried -ft and -s but got a error below. 

Reconciling gene and species trees
----------------------------------
2021-05-06 06:07:10 : Starting OF Orthologues
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1761, in main
  File "scripts_of/__main__.py", line 1517, in GetOrthologues_FromTrees
  File "scripts_of/orthologues.py", line 844, in OrthologuesFromTrees
  File "scripts_of/orthologues.py", line 820, in ReconciliationAndOrthologues
  File "scripts_of/trees2ologs_of.py", line 636, in DoOrthologuesForOrthoFinder
  File "scripts_of/files.py", line 374, in GetOGsTreeFN
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[14752] Failed to execute script orthofinder


Could you give me some suggestions?

Thanks
Edison

**Comment by davidemms** [comment]
Is this the latest version?

**Comment by Edison2021** [comment]
No, the version is OrthoFinder v2.3.14.

**Comment by davidemms** [comment]
Hi Edison

Try the latest version and let me know if you have any problems. 

Option '-ft' uses trees in Trees_ids, these OrthoFinder internal files and will have the OrthoFinder internal IDs. When you supply as species tree using the '-s' argument this is user-facing functionality and so it expects user species names in the species tree, it will tell you if any of the names don't match.

Best wishes 
David

**Comment by Edison2021** [comment]
Can not run the latest one

Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_certifi.py", line 11, in <module>
  File "/tmp/pip-build-gBA2sl/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "ssl.py", line 98, in <module>
  File "/tmp/pip-build-gBA2sl/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 684, in load_module
ImportError: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEI87vDvS/libcrypto.so.1.1)
[29068] Failed to execute script pyi_rth_certifi

**Comment by Edison2021** [comment]
Hi David 
Any option can be used to remove largest orthogroups for downstream analyses such as tree construction and reconciliation?

Thanks
Edison

**Comment by Edison2021** [comment]
I ran the latest OrthoFinder.tar.gz but it did not work. I also tried OrthoFinder_source.tar.gz but got a error below: 

Running Orthologue Prediction
=============================

Reconciling gene and species trees
----------------------------------
2021-05-07 18:48:31 : Starting OF Orthologues
Traceback (most recent call last):
  File "/home/fg/fg02/fg0287/src/OrthoFinder_source/scripts_of/trees2ologs_of.py", line 1164, in AnalyseTree
    if not os.path.exists(files.FileHandler.GetOGsTreeFN(iog)):
  File "/home/fg/fg02/fg0287/src/OrthoFinder_source/scripts_of/files.py", line 374, in GetOGsTreeFN
    return self.wd_trees + "Trees_ids/" + (self.baseOgFormat % iOG) + "_tree_id.txt"   
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by Edison2021** [comment]
> Hi Edison
> 
> Try the latest version and let me know if you have any problems.
> 
> Option '-ft' uses trees in Trees_ids, these OrthoFinder internal files and will have the OrthoFinder internal IDs. When you supply as species tree using the '-s' argument this is user-facing functionality and so it expects user species names in the species tree, it will tell you if any of the names don't match.
> 
> Best wishes
> David

Hi David
I tried the latest version but still got an error 

Running Orthologue Prediction
=============================

Reconciling gene and species trees
----------------------------------
2021-05-12 23:32:08 : Starting OF Orthologues
Traceback (most recent call last):
  File "/home/fg/fg02/fg0287/src/OrthoFinder_source/scripts_of/trees2ologs_of.py", line 1164, in AnalyseTree
    if not os.path.exists(files.FileHandler.GetOGsTreeFN(iog)):
  File "/home/fg/fg02/fg0287/src/OrthoFinder_source/scripts_of/files.py", line 374, in GetOGsTreeFN
    return self.wd_trees + "Trees_ids/" + (self.baseOgFormat % iOG) + "_tree_id.txt"   
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
