### ISSUE TITLE
something wrong with the Initial processing of each species

### ISSUE THREAD

**Issue by sulin12352** [davidemms/OrthoFinder#541]
2021-04-15 21:13:40 : Initial processing of each species
Malformatted line in /home/name/fasta/OrthoFinder/Results_Apr15/WorkingDirectory/Blast5_1.txt
Offending line was:
5_32513	1_20089	34.7	449	240	11	510	939	907	1321	6.4e-59	226.9
Process Process-27:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/__main__.py", line 520, in Worker_ProcessBlastHits
  File "scripts_of/__main__.py", line 507, in ProcessBlastHits
  File "scripts_of/blast_file_processor.py", line 65, in GetBLAST6Scores
  File "gzip.py", line 450, in readline
  File "gzip.py", line 256, in read
  File "gzip.py", line 303, in _read
  File "gzip.py", line 342, in _read_eof
IOError: CRC check failed 0xb92d41ea != 0x8cf0699eL
2021-04-15 21:24:48 : Initial processing of species 0 complete
2021-04-15 21:32:54 : Initial processing of species 1 complete
2021-04-15 21:42:25 : Initial processing of species 2 complete
2021-04-15 21:52:31 : Initial processing of species 3 complete
2021-04-15 21:54:39 : Initial processing of species 4 complete
ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.
I want to cluster my data with orthofinder （orthofinder -f /home/name/fasta -t 25 -og）,but something went wrong with it,there still is a thread going in the background, but nohup file report a error.Does this matter for my result, and if so, what is it , and is there anything I can do to avoid it?Thank you in advance for your help.

**Comment by davidemms** [comment]
Hi

There appears to be some error in the file access on your system:
"IOError: CRC check failed 0xb92d41ea != 0x8cf0699eL"

I don't know what this means but I think the options are:
1. The file /home/name/fasta/OrthoFinder/Results_Apr15/WorkingDirectory/Blast5_1.txt.gz is corrupted in some way. Have a look at it and see if there are any problems with the file. You can look at it in a text editor, you may have to unzip it first. I don't think this will be the cause but it's worth checking first.
2. There was a file system error, it's possible it will not reoccur if you try it again. If it does then you may need to investigate it yourself or speak to your system admin.

From the output you've posted the all-vs-all search stage has completed (assuming there weren't any other error messages reported earlier on?) in which case you can restart OrthoFinder from the clustering stage:
```orthofinder -b /home/name/fasta/OrthoFinder/RESULTS_DIR_NAME```

Best wishes
David
