### ISSUE TITLE
[97781] Failed to execute script orthofinder

### ISSUE THREAD

**Issue by abhijeetsingh1704** [davidemms/OrthoFinder#542]
Can anyone help with this?

`Writing orthogroups to file
---------------------------
/tmp/_MEI6hTcHS/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
/tmp/_MEI6hTcHS/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1762, in main
  File "scripts_of/__main__.py", line 1389, in DoOrthogroups
  File "scripts_of/__main__.py", line 751, in Stats
StopIteration
[97781] Failed to execute script orthofinder`

**Comment by davidemms** [comment]
Hi 

Were there any other warnings before this? Could you post me the results file "Comparative_Genomics_Statistics/Statistics_Overall.tsv"

All the best
David

**Comment by abhijeetsingh1704** [comment]
Hi David,
Thanks for your reply.
The example data did not have any problem, but the problem was only with any other data. I don't think there were any other warnings other than that while any data except the one I mentioned. Unfortunately, I discarded the data and execution logs. I tried to use the docker version of Orthofinder instead. However, I realized the docker version is not updated and it is missing few dependencies, for example, I could not use any other tree building program other than fasttree. 

I could rerun the analysis with previous data and will post the errors.

Best,
Abhijeet
