### ISSUE TITLE
Failed to execute script orthofinder

### ISSUE THREAD

**Issue by lisiruiyu** [davidemms/OrthoFinder#558]
I have downloaded OrthoFinder-2.5.2.tar.gz,After unzipping, I started to execute the code：orthofinder -f ExampleData
[Log.txt](https://github.com/davidemms/OrthoFinder/files/6447568/Log.txt)

OrthoFinder version 2.5.2 Copyright (C) 2014 David Emms

2021-05-09 20:58:07 : Starting OrthoFinder 2.5.2
4 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1719, in main
  File "scripts_of/__main__.py", line 1310, in CheckDependencies
  File "scripts_of/program_caller.py", line 188, in TestSearchMethod
  File "scripts_of/program_caller.py", line 170, in CallSearchMethod_DB
  File "scripts_of/program_caller.py", line 202, in _CallMethod
  File "scripts_of/program_caller.py", line 285, in _GetCommand
  File "scripts_of/program_caller.py", line 243, in _ReplaceVariables
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 14: ordinal not in range(128)
[221160] Failed to execute script orthofinder

**Comment by davidemms** [comment]
Hi

It sounds like OrthoFinder can't handle the non-ascii characters in your path, "下载". I will see if I can make some changes to the code so that it will be able to in the future. For now, I think it should work if you create a directory for your OrthoFinder work using ascii characters.

Best wishes
David
