### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by etcProfile** [davidemms/OrthoFinder#564]
Dear Davide
When I use orthofinder, I come across a strange problem
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1765, in main
  File "scripts_of/__main__.py", line 1545, in GetOrthologues
  File "scripts_of/orthologues.py", line 1090, in OrthologuesWorkflow
  File "scripts_of/orthologues.py", line 880, in ReconciliationAndOrthologues
  File "scripts_of/orthologues.py", line 710, in WriteOrthologuesStats
ValueError: too many values to unpack
[36828] Failed to execute script orthofinder
**Strangely enough, when I use /Orthofinder/Exampledata, everything goes well
Is there a problem with the data I input??**

**Comment by etcProfile** [comment]
OrthoFinder version 2.5.2 Copyright (C) 2014 David Emms

2021-05-14 18:29:33 : Starting OrthoFinder 2.5.2
35 thread(s) for highly parallel tasks (BLAST searches etc.)
35 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "mafft /home/lsf/data/workdir_14/OrthoFinder/Results_May14/WorkingDirectory//_dependencies_check/Sk
Test can run "raxml" - ok

WARNING: Files have been ignored as they don't appear to be FASTA files:
nohup.out
OrthoFinder expects FASTA files to have one of the following extensions: fa, fasta, faa, pep, fas

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2021-05-14 18:29:34 : Creating diamond database 1 of 6
2021-05-14 18:29:34 : Creating diamond database 2 of 6
2021-05-14 18:29:34 : Creating diamond database 3 of 6
2021-05-14 18:29:34 : Creating diamond database 4 of 6
2021-05-14 18:29:34 : Creating diamond database 5 of 6
2021-05-14 18:29:34 : Creating diamond database 6 of 6

Running diamond all-versus-all
------------------------------
Using 35 thread(s)
2021-05-14 18:29:34 : This may take some time....
2021-05-14 18:29:35 : Done 0 of 36
2021-05-14 18:33:15 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2021-05-14 18:33:15 : Initial processing of each species
2021-05-14 18:33:19 : Initial processing of species 4 complete
2021-05-14 18:33:19 : Initial processing of species 0 complete
2021-05-14 18:33:20 : Initial processing of species 1 complete
2021-05-14 18:33:27 : Initial processing of species 3 complete
2021-05-14 18:33:31 : Initial processing of species 5 complete
2021-05-14 18:33:31 : Initial processing of species 2 complete
2021-05-14 18:33:35 : Connected putative homologues
2021-05-14 18:33:37 : Written final scores for species 4 to graph file
2021-05-14 18:33:39 : Written final scores for species 3 to graph file
2021-05-14 18:33:40 : Written final scores for species 5 to graph file
2021-05-14 18:33:40 : Written final scores for species 2 to graph file
2021-05-14 18:33:54 : Ran MCL

Writing orthogroups to file
---------------------------
A duplicate accession was found using just first part: GWHPAAEX001147
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

OrthoFinder assigned 87960 genes (84.8% of total) to 17211 orthogroups. Fifty percent of all genes were in orth more genes (G50 was 5) and were contained in the largest 5762 orthogroups (O50 was 5762). There were 1245 orthspecies present and 139 of these consisted entirely of single-copy genes.

2021-05-14 18:33:58 : Done orthogroups

Analysing Orthogroups
=====================
2021-05-14 18:33:58 : Starting MSA/Trees
A duplicate accession was found using just first part: GWHPAAEX001147
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

Species tree: Using 1593 orthogroups with minimum of 66.7% of species having single-copy genes in any orthogrou

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2021-05-14 18:34:00 : Done 0 of 1593
2021-05-14 18:35:01 : Done 600 of 1593
2021-05-14 18:35:24 : Done 1500 of 1593
2021-05-14 18:35:11 : Done 800 of 1593
2021-05-14 18:35:15 : Done 900 of 1593
2021-05-14 18:35:21 : Done 1300 of 1593
2021-05-14 18:35:20 : Done 1200 of 1593
2021-05-14 18:35:19 : Done 1100 of 1593
2021-05-14 18:35:23 : Done 1400 of 1593
2021-05-14 18:34:20 : Done 100 of 1593
2021-05-14 18:34:31 : Done 200 of 1593
2021-05-14 18:34:41 : Done 300 of 1593
2021-05-14 18:34:49 : Done 400 of 1593
2021-05-14 18:34:55 : Done 500 of 1593
2021-05-14 18:35:17 : Done 1000 of 1593
2021-05-14 18:35:06 : Done 700 of 1593

Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
2021-05-14 18:35:29 : Done 0 of 15619
2021-05-14 19:38:32 : Done 8000 of 15619
2021-05-14 19:39:17 : Done 13000 of 15619
2021-05-14 19:38:52 : Done 10000 of 15619
2021-05-14 19:32:39 : Done 2000 of 15619
2021-05-14 19:37:28 : Done 5000 of 15619
2021-05-14 19:38:42 : Done 9000 of 15619
2021-05-14 19:39:24 : Done 14000 of 15619
2021-05-14 19:39:01 : Done 11000 of 15619
2021-05-14 19:26:48 : Done 1000 of 15619
2021-05-14 19:36:52 : Done 4000 of 15619
2021-05-14 19:39:10 : Done 12000 of 15619
2021-05-14 19:38:18 : Done 7000 of 15619
2021-05-14 19:35:27 : Done 3000 of 15619
2021-05-14 19:38:03 : Done 6000 of 15619
2021-05-14 19:39:31 : Done 15000 of 15619
2021-05-14 20:41:11 : Done MSA/Trees

Best outgroup(s) for species tree
---------------------------------
2021-05-14 20:41:11 : Starting STRIDE
2021-05-14 20:41:12 : Done STRIDE
Observed 74 well-supported, non-terminal duplications. 68 support the best root and 6 contradict it.
Best outgroup for species tree:
  Apostasia_shenzhenica_protein_select

Reconciling gene trees and species tree
---------------------------------------
Outgroup: Apostasia_shenzhenica_protein_select
2021-05-14 20:41:12 : Starting Recon and orthologues
2021-05-14 20:41:12 : Starting OF Orthologues
2021-05-14 20:41:13 : Done 9000 of 9978
2021-05-14 20:41:12 : Done 1000 of 9978
2021-05-14 20:41:13 : Done 7000 of 9978
2021-05-14 20:41:13 : Done 6000 of 9978
2021-05-14 20:41:13 : Done 5000 of 9978
2021-05-14 20:41:13 : Done 2000 of 9978
2021-05-14 20:41:13 : Done 3000 of 9978
2021-05-14 20:41:13 : Done 4000 of 9978
2021-05-14 20:41:13 : Done 8000 of 9978
2021-05-14 20:41:15 : Done OF Orthologues
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1765, in main
  File "scripts_of/__main__.py", line 1545, in GetOrthologues
  File "scripts_of/orthologues.py", line 1090, in OrthologuesWorkflow
  File "scripts_of/orthologues.py", line 880, in ReconciliationAndOrthologues
  File "scripts_of/orthologues.py", line 710, in WriteOrthologuesStats
ValueError: too many values to unpack
[36828] Failed to execute script orthofinder

**Comment by etcProfile** [comment]
Well, there is something wrong with my input data. :P

**Comment by dcf774967** [comment]
Hello, I get the same error! Can you give me some advise?  Thanks

**Comment by dcf774967** [comment]
> Hello, I get the same error! Can you give me some advise? Thanks

    for og, node, _, support, _, _, _ in reader:
ValueError: too many values to unpack (expected 7)

**Comment by davidemms** [comment]
Are you using the latest version of OrthoFinder? If not then try updating and check if the issue has already been fixed.

**Comment by etcProfile** [comment]
> Hello, I get the same error! Can you give me some advise? Thanks

I remember that there is a problem with my input protein sequence，There is a lot of useless information behind the symbol ">", You should try to simplify the ID of the protein sequence。

**Comment by dcf774967** [comment]
> Are you using the latest version of OrthoFinder? If not then try updating and check if the issue has already been fixed.

Thank you. I will try.

**Comment by justqzt** [comment]
> > Hello, I get the same error! Can you give me some advise? Thanks
> 
> ```
> for og, node, _, support, _, _, _ in reader:
> ```
> 
> ValueError: too many values to unpack (expected 7)

hello , I have the same question.Have you solved it yet？

    for og, node, _, support, _, _, _ in reader:
ValueError: too many values to unpack (expected 7)

**Comment by etcProfile** [comment]
> > > Hello, I get the same error! Can you give me some advise? Thanks
> > 
> > 
> > ```
> > for og, node, _, support, _, _, _ in reader:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ValueError: too many values to unpack (expected 7)
> 
> hello , I have the same question.Have you solved it yet？
> 
> ```
> for og, node, _, support, _, _, _ in reader:
> ```
> 
> ValueError: too many values to unpack (expected 7)

Are you using the latest version?

**Comment by justqzt** [comment]
> > > > Hello, I get the same error! Can you give me some advise? Thanks
> > > 
> > > 
> > > ```
> > > for og, node, _, support, _, _, _ in reader:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ValueError: too many values to unpack (expected 7)
> > 
> > 
> > hello , I have the same question.Have you solved it yet？
> > ```
> > for og, node, _, support, _, _, _ in reader:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ValueError: too many values to unpack (expected 7)
> 
> Are you using the latest version?

No,, OrthoFinder version 2.5.2

**Comment by justqzt** [comment]
> > > > > Hello, I get the same error! Can you give me some advise? Thanks
> > > > 
> > > > 
> > > > ```
> > > > for og, node, _, support, _, _, _ in reader:
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ValueError: too many values to unpack (expected 7)
> > > 
> > > 
> > > hello , I have the same question.Have you solved it yet？
> > > ```
> > > for og, node, _, support, _, _, _ in reader:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ValueError: too many values to unpack (expected 7)
> > 
> > 
> > Are you using the latest version?
> 
> No,, OrthoFinder version 2.5.2

I have upgraded.Should I start all over again ??

**Comment by justqzt** [comment]
> > > > > Hello, I get the same error! Can you give me some advise? Thanks
> > > > 
> > > > 
> > > > ```
> > > > for og, node, _, support, _, _, _ in reader:
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ValueError: too many values to unpack (expected 7)
> > > 
> > > 
> > > hello , I have the same question.Have you solved it yet？
> > > ```
> > > for og, node, _, support, _, _, _ in reader:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ValueError: too many values to unpack (expected 7)
> > 
> > 
> > Are you using the latest version?
> 
> No,, OrthoFinder version 2.5.2

I have upgraded.Should I start all over again ??
 This is my result  :(
Reconciling gene trees and species tree
---------------------------------------
Outgroup: Porphyra_umbilicalis
2021-12-25 13:43:38 : Starting Recon and orthologues
2021-12-25 13:43:38 : Starting OF Orthologues
A duplicate accession was found using just first part: BG8803123-T1
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.
2021-12-25 14:05:21 : Done 20000 of 65931
2021-12-25 14:05:40 : Done 27000 of 65931
....
2021-12-25 14:07:28 : Done OF Orthologues
Traceback (most recent call last):
  File "/home/qzt/miniconda3/envs/ortho/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/qzt/miniconda3/envs/ortho/bin/scripts_of/__main__.py", line 1781, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/qzt/miniconda3/envs/ortho/bin/scripts_of/__main__.py", line 1527, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
  File "/home/qzt/miniconda3/envs/ortho/bin/scripts_of/orthologues.py", line 1090, in OrthologuesWorkflow
    ReconciliationAndOrthologues(recon_method, db.ogSet, nHighParallel, nLowParallel, i if qMultiple else None, stride_dups=stride_dups, q_split_para_clades=q_split_para_clades) 
  File "/home/qzt/miniconda3/envs/ortho/bin/scripts_of/orthologues.py", line 880, in ReconciliationAndOrthologues
    WriteOrthologuesStats(ogSet, nOrthologues_SpPair)
  File "/home/qzt/miniconda3/envs/ortho/bin/scripts_of/orthologues.py", line 710, in WriteOrthologuesStats
    for og, node, _, support, _, _, _ in reader:
ValueError: too many values to unpack (expected 7)

**Comment by davidemms** [comment]
You can restart from the trees using the "-ft" option.

**Comment by shbrainard** [comment]
I'm having the same issue, running 2.5.4 (latest version on Docker) in a container:

` docker run --ulimit nofile=1000000:1000000 -it --rm -v
`

Here is the output:

```
(base) ➜  peptide_sequences_primary docker run --ulimit nofile=1000000:1000000 -it --rm -v /Volumes/genomics/corylus_genomes/comparative-genomics/OrthoFinder/peptide_sequences_primary:/input:Z davidemms/orthofinder:2.5.4 orthofinder -f /input


OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms

2023-01-13 02:53:49 : Starting OrthoFinder 2.5.4
2 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /input/OrthoFinder/Results_Jan13_1/WorkingDirectory/SimpleTest.phy -o /input/OrthoFinder/Results_Jan13_1/WorkingDirectory/SimpleTest.tre" - ok

WARNING: Files have been ignored as they don't appear to be FASTA files:
.DS_Store
OrthoFinder expects FASTA files to have one of the following extensions: fa, fasta, faa, pep, fas

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2023-01-13 02:55:04 : Creating diamond database 1 of 11
2023-01-13 02:55:05 : Creating diamond database 2 of 11
2023-01-13 02:55:06 : Creating diamond database 3 of 11
2023-01-13 02:55:07 : Creating diamond database 4 of 11
2023-01-13 02:55:08 : Creating diamond database 5 of 11
2023-01-13 02:55:08 : Creating diamond database 6 of 11
2023-01-13 02:55:09 : Creating diamond database 7 of 11
2023-01-13 02:55:10 : Creating diamond database 8 of 11
2023-01-13 02:55:11 : Creating diamond database 9 of 11
2023-01-13 02:55:12 : Creating diamond database 10 of 11
2023-01-13 02:55:13 : Creating diamond database 11 of 11

Running diamond all-versus-all
------------------------------
Using 2 thread(s)
2023-01-13 02:55:13 : This may take some time....
2023-01-13 02:55:13 : Done 0 of 121
2023-01-13 03:50:07 : Done 10 of 121
2023-01-13 04:32:23 : Done 20 of 121
2023-01-13 05:19:34 : Done 30 of 121
2023-01-13 05:51:50 : Done 40 of 121
2023-01-13 06:28:59 : Done 50 of 121
2023-01-13 07:05:37 : Done 60 of 121
2023-01-13 08:00:56 : Done 70 of 121
2023-01-13 08:35:24 : Done 80 of 121
2023-01-13 09:10:55 : Done 90 of 121
2023-01-13 09:39:12 : Done 100 of 121
2023-01-13 10:09:11 : Done 110 of 121
2023-01-13 10:32:26 : Done 120 of 121
2023-01-13 10:36:56 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2023-01-13 10:36:58 : Initial processing of each species
2023-01-13 10:38:37 : Initial processing of species 0 complete
2023-01-13 10:40:23 : Initial processing of species 1 complete
2023-01-13 10:42:34 : Initial processing of species 2 complete
2023-01-13 10:44:55 : Initial processing of species 3 complete
2023-01-13 10:47:13 : Initial processing of species 4 complete
2023-01-13 10:48:38 : Initial processing of species 5 complete
2023-01-13 10:51:23 : Initial processing of species 6 complete
2023-01-13 10:54:03 : Initial processing of species 7 complete
2023-01-13 10:56:50 : Initial processing of species 8 complete
2023-01-13 10:58:40 : Initial processing of species 9 complete
2023-01-13 11:00:24 : Initial processing of species 10 complete
2023-01-13 11:02:24 : Connected putative homologues
2023-01-13 11:02:40 : Written final scores for species 0 to graph file
2023-01-13 11:02:56 : Written final scores for species 1 to graph file
2023-01-13 11:03:16 : Written final scores for species 2 to graph file
2023-01-13 11:03:36 : Written final scores for species 3 to graph file
2023-01-13 11:03:56 : Written final scores for species 4 to graph file
2023-01-13 11:04:10 : Written final scores for species 5 to graph file
2023-01-13 11:04:35 : Written final scores for species 6 to graph file
2023-01-13 11:05:01 : Written final scores for species 7 to graph file
2023-01-13 11:05:29 : Written final scores for species 8 to graph file
2023-01-13 11:05:45 : Written final scores for species 9 to graph file
2023-01-13 11:06:01 : Written final scores for species 10 to graph file
2023-01-13 11:09:14 : Ran MCL

Writing orthogroups to file
---------------------------
A duplicate accession was found using just first part: rf
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

OrthoFinder assigned 341910 genes (94.0% of total) to 26675 orthogroups. Fifty percent of all genes were in orthogroups with 16 or more genes (G50 was 16) and were contained in the largest 6111 orthogroups (O50 was 6111). There were 5922 orthogroups with all species present and 92 of these consisted entirely of single-copy genes.

2023-01-13 11:14:59 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2023-01-13 11:32:43 : Done

Inferring gene and species trees
--------------------------------
2023-01-13 11:32:48 : Done 0 of 19772
2023-01-13 11:35:41 : Done 1000 of 19772
2023-01-13 11:37:56 : Done 2000 of 19772
2023-01-13 11:40:12 : Done 3000 of 19772
2023-01-13 11:42:31 : Done 4000 of 19772
2023-01-13 11:45:02 : Done 5000 of 19772
2023-01-13 11:47:20 : Done 6000 of 19772
2023-01-13 11:49:36 : Done 7000 of 19772
2023-01-13 11:51:52 : Done 8000 of 19772
2023-01-13 11:54:09 : Done 9000 of 19772
2023-01-13 11:56:27 : Done 10000 of 19772
2023-01-13 11:58:44 : Done 11000 of 19772
2023-01-13 12:01:00 : Done 12000 of 19772
2023-01-13 12:03:17 : Done 13000 of 19772
2023-01-13 12:05:36 : Done 14000 of 19772
2023-01-13 12:07:52 : Done 15000 of 19772
2023-01-13 12:10:06 : Done 16000 of 19772
2023-01-13 12:12:25 : Done 17000 of 19772
2023-01-13 12:14:42 : Done 18000 of 19772
2023-01-13 12:16:57 : Done 19000 of 19772

5922 trees had all species present and will be used by STAG to infer the species tree

Best outgroup(s) for species tree
---------------------------------
2023-01-13 12:29:30 : Starting STRIDE
2023-01-13 12:30:44 : Done STRIDE
Observed 465 well-supported, non-terminal duplications. 451 support the best root and 14 contradict it.
Best outgroup for species tree:
  Quro.1_0.pep

Reconciling gene trees and species tree
---------------------------------------
Outgroup: Quro.1_0.pep
2023-01-13 12:30:44 : Starting Recon and orthologues
2023-01-13 12:30:44 : Starting OF Orthologues
A duplicate accession was found using just first part: rf
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

2023-01-13 12:30:49 : Done 0 of 19772
2023-01-13 12:34:19 : Done 1000 of 19772
2023-01-13 12:37:09 : Done 2000 of 19772
2023-01-13 12:39:49 : Done 3000 of 19772
2023-01-13 12:42:22 : Done 4000 of 19772
2023-01-13 12:45:13 : Done 5000 of 19772
2023-01-13 12:47:46 : Done 6000 of 19772
2023-01-13 12:50:20 : Done 7000 of 19772
2023-01-13 12:52:50 : Done 8000 of 19772
2023-01-13 12:55:23 : Done 9000 of 19772
2023-01-13 12:57:48 : Done 10000 of 19772
2023-01-13 13:00:15 : Done 11000 of 19772
2023-01-13 13:02:35 : Done 12000 of 19772
2023-01-13 13:05:06 : Done 13000 of 19772
2023-01-13 13:07:29 : Done 14000 of 19772
2023-01-13 13:09:11 : Done 15000 of 19772
2023-01-13 13:10:49 : Done 16000 of 19772
2023-01-13 13:11:49 : Done 17000 of 19772
2023-01-13 13:12:38 : Done 18000 of 19772
2023-01-13 13:13:20 : Done 19000 of 19772
2023-01-13 13:13:44 : Done OF Orthologues
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1778, in main
  File "scripts_of/__main__.py", line 1558, in GetOrthologues
  File "scripts_of/orthologues.py", line 1090, in OrthologuesWorkflow
  File "scripts_of/orthologues.py", line 880, in ReconciliationAndOrthologues
  File "scripts_of/orthologues.py", line 710, in WriteOrthologuesStats
ValueError: too many values to unpack
[7] Failed to execute script orthofinder
```

My FASTA file header names are not particularly complex, but I'd be happy to simplify them based on any suggestions.  Or any other thoughts for what's going wrong?  Thanks!

**Comment by Buckaroo1** [comment]
> > Hello, I get the same error! Can you give me some advise? Thanks您好，我遇到同样的错误！你能给我一些建议吗？谢谢
> 
> I remember that there is a problem with my input protein sequence，There is a lot of useless information behind the symbol ">", You should try to simplify the ID of the protein sequence。我记得我输入的蛋白质序列有问题，符号“>”后面有很多无用信息，你应该尝试简化蛋白质序列的ID。

Thanks alot! Problem solved. 😘
