### ISSUE TITLE
Cannot Allocate Memory

### ISSUE THREAD

**Issue by niederhuth** [davidemms/OrthoFinder#589]
I have tried multiple times and keep running up against this same error:

Reconciling gene trees and species tree
---------------------------------------
Outgroup: GCF_013320495.1_ASM1332049v1
2021-07-10 02:05:43 : Starting Recon and orthologues
2021-07-10 02:05:43 : Starting OF Orthologues
Traceback (most recent call last):
  File "/mnt/home/niederhu/miniconda3/envs/agro/bin/orthofinder", line 7, in <module>
    main(args)
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/agro/bin/scripts_of/__main__.py", line 1788, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/agro/bin/scripts_of/__main__.py", line 1527, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/agro/bin/scripts_of/orthologues.py", line 1090, in OrthologuesWorkflow
    ReconciliationAndOrthologues(recon_method, db.ogSet, nHighParallel, nLowParallel, i if qMultiple else None, stride_dups=stride_dups, q_split_para_clades=q_split_para_clades)
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/agro/bin/scripts_of/orthologues.py", line 870, in ReconciliationAndOrthologues
    nOrthologues_SpPair = trees2ologs_of.DoOrthologuesForOrthoFinder(ogSet, species_tree_rooted_labelled, trees2ologs_of.GeneToSpecies_dash,
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/agro/bin/scripts_of/trees2ologs_of.py", line 1123, in DoOrthologuesForOrthoFinder
    nOrthologues_SpPair = RunOrthologsParallel(ta, len(ogSet.speciesToUse), args_queue, n_parallel)
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/agro/bin/scripts_of/trees2ologs_of.py", line 1264, in RunOrthologsParallel
    proc.start()
  File "/mnt/home/niederhu/miniconda3/envs/agro/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/mnt/home/niederhu/miniconda3/envs/agro/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/mnt/home/niederhu/miniconda3/envs/agro/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/mnt/home/niederhu/miniconda3/envs/agro/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/mnt/home/niederhu/miniconda3/envs/agro/lib/python3.9/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by davidemms** [comment]
Hi

Could you let me know how many species you are using and how many sequences? For the number of sequences you can see how many lines there are in the WorkingDirectory/SequencesIDs.txt file. Could you also let me know how much RAM you have on your computer. 

What's happening is that when OrthoFinder is trying to create additional processes to analyse the trees in parallel, the computer is saying there is not enough RAM available to do that. You can try restarting from the trees you've already calculated using "-ft PREVIOUS_RESULTS_DIRECTORY" AND try specifying "-a 1" which asks orthofinder to just use one process. You could also try using a more powerful computer or reducing the number of species in your analysis.

Best wishes
David

**Comment by niederhuth** [comment]
Hi David,

I am running 601 genomes. I was running this with 3 threads and 1TB memory. I will try rerunning with 1 thread and 1TB and hope that works.
