### ISSUE TITLE
[1802661] Failed to execute script orthofinder

### ISSUE THREAD

**Issue by TonyMannion** [davidemms/OrthoFinder#590]
Hello David,

I am trying to run OrthoFinder (version 2.5.4), but after several attempts it fails with same error:

Best outgroup(s) for species tree
---------------------------------
2021-07-11 11:15:08 : Starting STRIDE
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1801, in main
  File "scripts_of/__main__.py", line 1558, in GetOrthologues
  File "scripts_of/orthologues.py", line 1039, in OrthologuesWorkflow
  File "scripts_of/stride.py", line 509, in GetRoot
  File "scripts_of/tree.py", line 221, in __init__
  File "scripts_of/newick.py", line 216, in read_newick
scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
[1802661] Failed to execute script orthofinder

In the working directory folder, I see Distance folder (46,116 items in it) and Tree_ids folder (23,057 items in it) as well as SpeciesIDs.txt (8.5kb size) and SpeciesTree_unrooted_ids.txt (0 byte size).  Any ideas on if this can be resolved?

Thanks!
Tony

**Comment by davidemms** [comment]
Hi Tony

For some reason the species tree inference has failed. Would you be post the output that OrthoFinder produces which will provide some details and/or email me the WorkingDirectory/SpeciesTrees_ids/ directory to david.emms@plants.ox.ac.uk.

As a temporary workaround you can use the "-M msa" option which will use a different method (multiple sequence alignments) for the species tree inference and so may succeed where this has failed. Once I've got the additional data I can try to fix this issue.

All the best
David
