### ISSUE TITLE
Can't produce OrthoXML output file

### ISSUE THREAD

**Issue by mpmeurville** [davidemms/OrthoFinder#631]
Dear David, 

I would like to produce an Orthoxml output file from my analysis, and everything goes well until building the file. The data I use are private so not on an online database, could that be a problem? I have 15 species. 

This is my command line : ./orthofinder -f GAGA_annotation_final_24092021/ -x GAGA_annotation_final_24092021/OrthoFinder/data_species_files.txt

my species file looks like this : 
GAGA-0004_final_annotation_representative_repfilt.pep.fasta	Messor barbarus	87890	GAGA	GAGA-0004_final_annotation_representative_repfilt.pep.fasta

where GAGA refers to my private database. 

I also paste the end of the log here so you can see the error: 

[... everything goes well ...]
2021-10-06 18:47:31 : Written final scores for species 15 to graph file
2021-10-06 18:47:46 : Ran MCL

Writing orthogroups to file

OrthoFinder assigned 211032 genes (95.8% of total) to 13652 orthogroups. Fifty percent of all genes were in orthogroups with 17 or more genes (G50 was 17) and were contained in the largest 4824 orthogroups (O50 was 4824). There were 7535 orthogroups with all species present and 3103 of these consisted entirely of single-copy genes.
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1775, in main
  File "scripts_of/__main__.py", line 1404, in DoOrthogroups
NameError: global name 'speciesXML' is not defined
[2668625] Failed to execute script orthofinder

I thank you in advance for your help!  

Marie-Pierre

**Comment by eli1199** [comment]
Hi @mpmeurville! did you end up figuring this out? I'm getting a very similar error message to yours:

"NameError: name 'speciesXML' is not defined"

Thank you!

**Comment by amarosaco** [comment]
I ran into the same error. The species file seems to be fine however.

**Comment by mpmeurville** [comment]
Hi, no I never managed to have it working ...
