### ISSUE TITLE
Segmentation fault with -b option and 18 species

### ISSUE THREAD

**Issue by blsfoxfox** [davidemms/OrthoFinder#64]
Hi,

I am running OrthoFinder by using -b option and 18 species like this:
/gpfs0/home/lzb0021/orthofinder/OrthoFinder-1.1.4/orthofinder -b  /gpfs0/home/lzb0021/ouc2/Results_Apr27/WorkingDirectory -t 64

However the software was aborted after 7 hours running, and the log file is like following:
Exited with exit code 139.

Resource usage summary:

    CPU time   :  22282.15 sec.
    Max Memory :     50992 MB
    Max Swap   :    158655 MB

    Max Processes  :        70
    Max Threads    :        77

The output (if any) follows:

OrthoFinder version 1.1.4 Copyright (C) 2014 David Emms

    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.
    For details please see the License.md that came with this software.

64 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /gpfs0/home/lzb0021/ouc2/Results_Apr27/WorkingDirectory/SimpleTest.phy -o /gpfs0/home/lzb0021/ouc2/Results_Apr27/WorkingDirectory/SimpleTest.tre" - ok
Test can run "dlcpar_search --version" - ok
Using previously calculated BLAST results in /gpfs0/home/lzb0021/ouc2/Results_Apr27/WorkingDirectory/

Running OrthoFinder algorithm
-----------------------------
2017-04-27 22:42:58 : Initial processing of each species
2017-04-27 22:50:54 : Initial processing of species 0 complete
2017-04-27 22:57:01 : Initial processing of species 1 complete
2017-04-27 23:13:36 : Initial processing of species 2 complete
2017-04-27 23:19:40 : Initial processing of species 3 complete
2017-04-27 23:22:44 : Initial processing of species 4 complete
2017-04-27 23:39:47 : Initial processing of species 5 complete
2017-04-27 23:44:45 : Initial processing of species 6 complete
2017-04-27 23:55:39 : Initial processing of species 7 complete
2017-04-27 23:59:31 : Initial processing of species 8 complete
2017-04-28 00:04:53 : Initial processing of species 9 complete
2017-04-28 00:07:10 : Initial processing of species 10 complete
2017-04-28 00:18:12 : Initial processing of species 11 complete
2017-04-28 00:23:15 : Initial processing of species 12 complete
2017-04-28 00:26:10 : Initial processing of species 13 complete
2017-04-28 00:38:17 : Initial processing of species 14 complete
2017-04-28 00:46:44 : Initial processing of species 15 complete
2017-04-28 00:52:20 : Initial processing of species 16 complete
2017-04-28 00:57:51 : Initial processing of species 17 complete
2017-04-28 01:03:53 : Connected putatitive homologs
2017-04-28 01:26:42 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /gpfs0/home/lzb0021/ouc2/Results_Apr27/WorkingDirectory/Orthogroups.csv
   /gpfs0/home/lzb0021/ouc2/Results_Apr27/WorkingDirectory/Orthogroups.txt (OrthoMCL format)
   /gpfs0/home/lzb0021/ouc2/Results_Apr27/WorkingDirectory/Orthogroups_UnassignedGenes.csv

Running Orthologue Prediction
=============================

Calculating gene distances
--------------------------
2017-04-28 01:26:56 : Done 0 of 324
2017-04-28 02:10:24 : Done 100 of 324
2017-04-28 02:40:15 : Done 200 of 324
2017-04-28 03:17:26 : Done 300 of 324
2017-04-28 03:23:57 : Processing species 0
2017-04-28 03:26:11 : Processing species 1
2017-04-28 03:28:18 : Processing species 2
2017-04-28 03:32:07 : Processing species 3
2017-04-28 03:33:56 : Processing species 4
2017-04-28 03:34:47 : Processing species 5
2017-04-28 03:37:42 : Processing species 6
2017-04-28 03:38:50 : Processing species 7
2017-04-28 03:40:49 : Processing species 8
2017-04-28 03:42:13 : Processing species 9
2017-04-28 03:44:10 : Processing species 10
2017-04-28 03:45:02 : Processing species 11
2017-04-28 03:47:26 : Processing species 12
2017-04-28 03:48:53 : Processing species 13
2017-04-28 03:49:48 : Processing species 14
2017-04-28 03:52:28 : Processing species 15
2017-04-28 03:54:17 : Processing species 16
2017-04-28 03:55:54 : Processing species 17

Inferring gene and species trees
--------------------------------
2017-04-28 04:10:37 : Done 0 of 13661
2017-04-28 04:43:15 : Done 1000 of 13661
2017-04-28 04:45:17 : Done 2000 of 13661
2017-04-28 04:47:22 : Done 3000 of 13661
2017-04-28 04:49:15 : Done 4000 of 13661
2017-04-28 04:51:11 : Done 5000 of 13661
2017-04-28 04:53:06 : Done 6000 of 13661
2017-04-28 04:55:03 : Done 7000 of 13661
2017-04-28 04:56:58 : Done 8000 of 13661
2017-04-28 04:58:57 : Done 9000 of 13661
2017-04-28 05:00:53 : Done 10000 of 13661
2017-04-28 05:02:30 : Done 11000 of 13661
2017-04-28 05:04:05 : Done 12000 of 13661
2017-04-28 05:05:40 : Done 13000 of 13661

Best outgroup(s) for species tree
---------------------------------
Observed 3724 duplications. 3700 support the best root and 24 contradict it.
Best outgroup for species tree:
  Mmus_uniq_protein, Drer_uniq_protein, Xtro_uniq_protein, Homo_uniq_protein, Ggal_uniq_protein

Reconciling gene trees and species tree
---------------------------------------
Outgroup: Mmus_uniq_protein, Drer_uniq_protein, Xtro_uniq_protein, Homo_uniq_protein, Ggal_uniq_protein
/home/lzb0021/.lsbatch/1493347366.271095.shell: line 1:   441 Segmentation fault      (core dumped) /gpfs0/home/lzb0021/orthofinder/OrthoFinder-1.1.4/orthofinder -b /gpfs0/home/lzb0021/ouc2/Results_Apr27/WorkingDirectory -t 64
2017-04-28 01:04:27 : Writen final scores for species 0 to graph file
2017-04-28 01:05:08 : Writen final scores for species 1 to graph file
2017-04-28 01:05:58 : Writen final scores for species 2 to graph file
2017-04-28 01:06:38 : Writen final scores for species 3 to graph file
2017-04-28 01:06:57 : Writen final scores for species 4 to graph file
2017-04-28 01:07:38 : Writen final scores for species 5 to graph file
2017-04-28 01:08:10 : Writen final scores for species 6 to graph file
2017-04-28 01:08:52 : Writen final scores for species 7 to graph file
2017-04-28 01:09:20 : Writen final scores for species 8 to graph file
2017-04-28 01:09:50 : Writen final scores for species 9 to graph file
2017-04-28 01:10:11 : Writen final scores for species 10 to graph file
2017-04-28 01:10:45 : Writen final scores for species 11 to graph file
2017-04-28 01:11:16 : Writen final scores for species 12 to graph file
2017-04-28 01:11:35 : Writen final scores for species 13 to graph file
2017-04-28 01:12:14 : Writen final scores for species 14 to graph file
2017-04-28 01:13:05 : Writen final scores for species 15 to graph file
2017-04-28 01:13:37 : Writen final scores for species 16 to graph file
2017-04-28 01:14:08 : Writen final scores for species 17 to graph file

I notice the peak memory usage is up to 158Gb, could this be the problem?
Looking forward to your response.

Thanks!

**Comment by davidemms** [comment]
Hi

I've not seen something like this before but it looks like the problem has occurred when using dlcpar to do gene-tree/species-tree reconciliation. If you could look at the directory:
`
/gpfs0/home/lzb0021/ouc2/Results_Apr27/WorkingDirectory/Orthologues_Apr28/WorkingDirectory/dlcpar/`

you can see which orthogroups were successfully analysed by dlcapr before the crash occurred. For each orthogroup successfully run there will be non-empty files OG*_tree_id.dlcpar.coal.recon,  OG*_tree_id.dlcpar.coal.tree,  OG*_tree_id.dlcpar.daughters,  OG*_tree_id.dlcpar.locus.recon,  OG*_tree_id.dlcpar.locus.tree &  OG*_tree_id.txt.

As the orthogroups go from largest to smallest, the most likely is that OG0000000 caused the problem although you may find it was one of the other ones.

If you identify the likely candidate and run 
`dlcpar_search -s Trees_ids/SpeciesTree_ids_0_rooted.txt -S dlcpar/GeneMap.smap dlcpar/OG0000000_tree_id.txt`
(or whichever is the problem OG)

from directory 
`/gpfs0/home/lzb0021/ouc2/Results_Apr27/WorkingDirectory/Orthologues_Apr28/WorkingDirectory`

you can see if you can reproduce the crash.

If we can identify the problem this way then hopefully we can work out a fix. 

All the best
David

**Comment by blsfoxfox** [comment]
Hi David,

Thanks for your response!

After running the dlcpar_search command, I get following error:

dlcpar_search -s Trees_ids/SpeciesTree_ids_0_rooted.txt -S dlcpar/GeneMap.smap dlcpar/OG0000000_tree_id.txt
--------------------------------------

**Comment by davidemms** [comment]
Hi

Is there some text missing from your post, I don't see any error messages? Did the command reproduce the crash?

Thanks
David

**Comment by blsfoxfox** [comment]
Hi David,

Sorry, it seems there is something wrong with my email client and some words are missing. I get following error with the dlcpar_search command:
dlcpar_search -s Trees_ids/SpeciesTree_ids_0_rooted.txt -S dlcpar/GeneMap.smap dlcpar/OG0000000_tree_id.txt
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time   :      0.22 sec.
    Max Memory :         2 MB
    Max Swap   :        34 MB

    Max Processes  :         1
    Max Threads    :         1

The output (if any) follows:

Traceback (most recent call last):
  File "/gpfs0/home/lzb0021/python/Python-2.7.9/bin/dlcpar_search", line 15, in <module>
    import dlcpar.simplerecon
  File "/gpfs0/home/lzb0021/python/Python-2.7.9/lib/python2.7/site-packages/dlcpar/simplerecon.py", line 12, in <module>
    from rasmus import util, stats, treelib
  File "/gpfs0/home/lzb0021/python/Python-2.7.9/lib/python2.7/site-packages/dlcpar/deps/rasmus/stats.py", line 20, in <module>
    from rasmus import tablelib
  File "/gpfs0/home/lzb0021/python/Python-2.7.9/lib/python2.7/site-packages/dlcpar/deps/rasmus/tablelib.py", line 45, in <module>
    from sqlite3 import dbapi2 as sqlite
  File "/gpfs0/home/lzb0021/python/Python-2.7.9/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/gpfs0/home/lzb0021/python/Python-2.7.9/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

It is strange because I think sqlite3 is a standard library of python. I have reinstalled python but still no luck.

Thanks!

**Comment by davidemms** [comment]
I'm assuming the same thing happens if you try to run it on one of the smaller orthogroups then, something like OG0000500_tree_id.txt? 

And if you open a python interpreter and type , "from sqlite3 import dbapi2 as sqlite" what happens?

Thanks
David

**Comment by davidemms** [comment]
Hi

Any news on this? Were you able to resolve the problem with sqlite3?

Thanks
David

**Comment by blsfoxfox** [comment]
Hi David,

Although it didn't go through the whole process, I got the Orthogroups.csv, so I used that file for down-stream analysis.

Thanks,

Lisui Bao
