### ISSUE TITLE
when it will complete,give me a "Failed"

### ISSUE THREAD

**Issue by ilee-ui** [davidemms/OrthoFinder#643]
![image](https://user-images.githubusercontent.com/71112013/142229345-fb73df1f-bf26-4ead-ac40-cc40cabab9de.png)
2021-11-17 23:18:58 : Written final scores for species 38 to graph file
2021-11-17 23:18:58 : Written final scores for species 39 to graph file
2021-11-17 23:18:58 : Ran MCL

Writing orthogroups to file
---------------------------
/tmp/_MEIzM2iyu/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
/tmp/_MEIzM2iyu/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1762, in main
  File "scripts_of/__main__.py", line 1389, in DoOrthogroups
  File "scripts_of/__main__.py", line 751, in Stats
StopIteration
[3789740] Failed to execute script orthofinder

like this!and only generate three files

**Comment by davidemms** [comment]
Hi

It has failed. You need to provide the complete set of protein sequences for each species you include, it looks like you might have only given it some sequences here?

Best wishes
David
