### ISSUE TITLE
ValueError: too many values to unpack (expected 7)

### ISSUE THREAD

**Issue by justqzt** [davidemms/OrthoFinder#659]
Hi David,
Recently,I ran 163 plant species in Orthofinder for one week and I got this error.

Reconciling gene trees and species tree
---------------------------------------
Outgroup: Porphyra_umbilicalis
2021-12-25 13:43:38 : Starting Recon and orthologues
2021-12-25 13:43:38 : Starting OF Orthologues
A duplicate accession was found using just first part: BG8803123-T1
Tried to use only the first part of the accession in order to list the sequences in each orthogroup
more concisely but these were not unique. The full accession line will be used instead.

2021-12-25 14:05:21 : Done 20000 of 65931
2021-12-25 14:05:40 : Done 27000 of 65931
2021-12-25 14:06:19 : Done 44000 of 65931
2021-12-25 14:06:25 : Done 47000 of 65931
2021-12-25 14:06:27 : Done 48000 of 65931
2021-12-25 13:57:34 : Done 2000 of 65931
2021-12-25 14:04:32 : Done 10000 of 65931
2021-12-25 14:04:47 : Done 12000 of 65931
2021-12-25 14:05:26 : Done 22000 of 65931
2021-12-25 14:05:37 : Done 26000 of 65931
2021-12-25 14:05:47 : Done 30000 of 65931
2021-12-25 14:05:52 : Done 32000 of 65931
2021-12-25 14:05:54 : Done 33000 of 65931
2021-12-25 14:06:17 : Done 43000 of 65931
2021-12-25 14:06:29 : Done 49000 of 65931
2021-12-25 14:06:34 : Done 51000 of 65931
2021-12-25 14:06:40 : Done 54000 of 65931
2021-12-25 14:06:59 : Done 64000 of 65931
2021-12-25 13:55:32 : Done 1000 of 65931
2021-12-25 14:04:40 : Done 11000 of 65931
2021-12-25 14:05:17 : Done 19000 of 65931
2021-12-25 14:05:29 : Done 23000 of 65931
2021-12-25 14:05:32 : Done 24000 of 65931
2021-12-25 14:05:34 : Done 25000 of 65931
2021-12-25 14:05:59 : Done 35000 of 65931
2021-12-25 14:06:14 : Done 42000 of 65931
2021-12-25 14:06:21 : Done 45000 of 65931
2021-12-25 14:06:23 : Done 46000 of 65931
2021-12-25 14:06:32 : Done 50000 of 65931
2021-12-25 14:06:46 : Done 57000 of 65931
2021-12-25 13:58:58 : Done 3000 of 65931
2021-12-25 14:01:08 : Done 5000 of 65931
2021-12-25 14:04:17 : Done 9000 of 65931
2021-12-25 14:04:57 : Done 14000 of 65931
2021-12-25 14:05:02 : Done 15000 of 65931
2021-12-25 14:05:42 : Done 28000 of 65931
2021-12-25 14:06:01 : Done 36000 of 65931
2021-12-25 14:06:04 : Done 37000 of 65931
2021-12-25 14:06:06 : Done 38000 of 65931
2021-12-25 14:06:08 : Done 39000 of 65931
2021-12-25 14:06:10 : Done 40000 of 65931
2021-12-25 14:06:12 : Done 41000 of 65931
2021-12-25 14:06:36 : Done 52000 of 65931
2021-12-25 14:06:42 : Done 55000 of 65931
2021-12-25 14:06:49 : Done 59000 of 65931
2021-12-25 14:06:51 : Done 60000 of 65931
2021-12-25 14:06:53 : Done 61000 of 65931
2021-12-25 14:00:08 : Done 4000 of 65931
2021-12-25 14:02:04 : Done 6000 of 65931
2021-12-25 14:02:58 : Done 7000 of 65931
2021-12-25 14:03:45 : Done 8000 of 65931
2021-12-25 14:04:52 : Done 13000 of 65931
2021-12-25 14:05:05 : Done 16000 of 65931
2021-12-25 14:05:09 : Done 17000 of 65931
2021-12-25 14:05:13 : Done 18000 of 65931
2021-12-25 14:05:24 : Done 21000 of 65931
2021-12-25 14:05:44 : Done 29000 of 65931
2021-12-25 14:05:49 : Done 31000 of 65931
2021-12-25 14:05:57 : Done 34000 of 65931
2021-12-25 14:06:38 : Done 53000 of 65931
2021-12-25 14:06:44 : Done 56000 of 65931
2021-12-25 14:06:48 : Done 58000 of 65931
2021-12-25 14:06:55 : Done 62000 of 65931
2021-12-25 14:06:58 : Done 63000 of 65931
2021-12-25 14:07:02 : Done 65000 of 65931
2021-12-25 14:07:28 : Done OF Orthologues
Traceback (most recent call last):
  File "~/envs/ortho/bin/orthofinder", line 7, in <module>
    main(args)
  File "~envs/ortho/bin/scripts_of/__main__.py", line 1781, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "~envs/ortho/bin/scripts_of/__main__.py", line 1527, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
  File "~/envs/ortho/bin/scripts_of/orthologues.py", line 1090, in OrthologuesWorkflow
    ReconciliationAndOrthologues(recon_method, db.ogSet, nHighParallel, nLowParallel, i if qMultiple else None, stride_dups=stride_dups, q_split_para_clades=q_split_para_clades) 
  File "~/envs/ortho/bin/scripts_of/orthologues.py", line 880, in ReconciliationAndOrthologues
    WriteOrthologuesStats(ogSet, nOrthologues_SpPair)
  File "~/envs/ortho/bin/scripts_of/orthologues.py", line 710, in WriteOrthologuesStats
    for og, node, _, support, _, _, _ in reader:
ValueError: too many values to unpack (expected 7)

I used version 2.5.2 and maybe my input protein have a lot of useless information behind the symbol ">" .

Actually, I have no idea what the reason is,
is it because I choose too many species or other reasons?

**Comment by davidemms** [comment]
Hi

Could you email me your Duplications.tsv file, or just the first and last 10 lines if the file is very large. You can use david_emms@hotmail.com. OrthoFinder is trying to read this file in order to work out some stats at the end of the run. It is expecting 7 columns per line and for some reason that is not the case. You may be able to identify the line in the file that is causing the problem. In the meantime, almost all of you OrthoFinder results should be complete (trees, orthologs, orthogroups etc.) so you can use them already.

Best wishes
David
