### ISSUE TITLE
Potential MCL error getting swallowed

### ISSUE THREAD

**Issue by mpdprot** [davidemms/OrthoFinder#660]
Hello David :)

I'm trying to run OrthoFinder on a large(ish?) number of species – 58. I've installed it on an Ubuntu machine using `conda -c bioconda install orthofinder`. I am running it using `orthofinder -f .`

After the runs of Diamond BLAST, I encounter the following error:

```
. . .
2022-01-06 11:23:28 : Written final scores for species 51 to graph file
2022-01-06 11:24:05 : Written final scores for species 52 to graph file
2022-01-06 11:24:40 : Written final scores for species 53 to graph file
2022-01-06 11:25:16 : Written final scores for species 54 to graph file
2022-01-06 11:25:54 : Written final scores for species 55 to graph file
2022-01-06 11:26:30 : Written final scores for species 56 to graph file
2022-01-06 11:26:37 : Written final scores for species 57 to graph file
Traceback (most recent call last):
  File "/opt/conda/bin/orthofinder", line 7, in <module>
    main(args)
  File "/opt/conda/bin/scripts_of/__main__.py", line 1678, in main
    DoOrthogroups(options, speciesInfoObj, seqsInfo)
  File "/opt/conda/bin/scripts_of/__main__.py", line 1334, in DoOrthogroups
    MCL.RunMCL(graphFilename, clustersFilename, options.nProcessAlg, options.mclInflation)
  File "/opt/conda/bin/scripts_of/__main__.py", line 211, in RunMCL
    parallel_task_manager.RunCommand(command, qShell=False, qPrintOnError=True)
  File "/opt/conda/bin/scripts_of/parallel_task_manager.py", line 116, in RunCommand
    elif qPrintStderr and len(stderr) > 0 and not stderr_exempt(stderr):
  File "/opt/conda/bin/scripts_of/parallel_task_manager.py", line 64, in stderr_exempt
    lines = stderr.split("\n")
TypeError: a bytes-like object is required, not 'str'
```

These are the most recent writes to the output directory:

```
1641469665.3008747550  Thu  Jan  6  11:47:45  2022  6444495    ./clusters_OrthoFinder_I1.5.txt
1641469656.3688602600  Thu  Jan  6  11:47:36  2022  135168     .
1641468399.3868446970  Thu  Jan  6  11:26:39  2022  294912     ./pickle
1641468398.7228436340  Thu  Jan  6  11:26:38  2022  298375049  ./OrthoFinder_graph.txt
1641464155.8481921620  Thu  Jan  6  10:15:55  2022  32368      ./Blast42_42.txt.gz
1641464154.1321896470  Thu  Jan  6  10:15:54  2022  14992      ./Blast20_42.txt.gz
1641464153.1081881460  Thu  Jan  6  10:15:53  2022  14224      ./Blast42_20.txt.gz
1641464152.3081869730  Thu  Jan  6  10:15:52  2022  12228      ./Blast42_48.txt.gz
1641464151.8881863580  Thu  Jan  6  10:15:51  2022  12381      ./Blast48_42.txt.gz
1641464151.7641861760  Thu  Jan  6  10:15:51  2022  14717      ./Blast7_42.txt.gz
1641464150.6121844880  Thu  Jan  6  10:15:50  2022  14176      ./Blast42_7.txt.gz
. . .
```

Looks like maybe MCL is failing but the error message isn't getting through, any ideas?

**Comment by davidemms** [comment]
Hi Michael

Hope all's good! I think this has been fixed in the latest release of OrthoFinder (>=v2.5.2). MCL is reporting something but in the older version of OrthoFinder it wasn't converted to a string first when using python 3. With the new version it should work and you should see the message. It's likely to be info about splitting groups and can be ignored.

Code change: https://github.com/davidemms/OrthoFinder/commit/60ed2ec8af9027876f3c4c9830fac8d7e089a571

All the best
David

**Comment by mpdprot** [comment]
Actually it might have been because I installed it using BioConda - maybe there’s an old version still on there?

**Comment by davidemms** [comment]
I think the old versions will always be available conda, if you have an old one installed then you may have to force it to update (this is a guess) using orthofinder==2.5.4, or whatever the syntax is for conda.
