### ISSUE TITLE
Gene_tree、orthologues 、Species_Tree and MultipleSequenceAlignments files are empty

### ISSUE THREAD

**Issue by sha1987-sss** [davidemms/OrthoFinder#665]
When I use orthofinder to analyze 18 species, I  always can't get the contents of Gene_tree、orthologues 、Species_Tree and MultipleSequenceAlignments four files. The command I use is as follows: orthofinder -f pep -M msa -S diamond -T raxml-ng -t 24 -a 24. So I would like to ask you, do you know what caused it? The running program will stop every time it reaches the following step

Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
2022-01-30 03:23:52 : Done 0 of 32315

**Comment by davidemms** [comment]
Is raxml still running? RAxML will take a very long time to infer the first 1000 trees. Have you tried running the line `top` command to see what process are running?

Best wishes
David

**Comment by sha1987-sss** [comment]
hi david
Thanks for your answer, I have tested with 2 species and got all the results, but when using 18 species it stops at the same step every time. I used the top command to check that raxml-ng is no longer running, so I don't know if this software has species restrictions? Or is there a limit to the sequence name? Most of my sequence names start with English letters and only contain underscores and numbers.
Best wishes
David

**Comment by sha1987-sss** [comment]
when I try to replace raxml-ng with fasttree, I can get all result file, but the following error message will appear:

Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
2022-02-04 02:50:36 : Done 0 of 29545
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ortho/bin/scripts_of/parallel_task_manager.py", line 209, in Worker_RunCommands_And_Move
    fn(fns)
  File "/home/ubuntu/anaconda3/envs/ortho/bin/scripts_of/trees_msa.py", line 262, in trim_fn
    trim.main(fn, fn, 0.1, 500, 0.75)
  File "/home/ubuntu/anaconda3/envs/ortho/bin/scripts_of/trim.py", line 94, in main
    msa = MSA(infn)
  File "/home/ubuntu/anaconda3/envs/ortho/bin/scripts_of/trim.py", line 35, in __init__
    self.non_gap_pos[-1].extend([current_length + i for i,c in enumerate(line) if (c != "*" and c != "-")])
IndexError: list index out of range

So I would like to ask you, do you know what is the reason for this?
Thank you very much for your reply.
Best wishes
Hu ShaSha

**Comment by davidemms** [comment]
Hi Hu ShaSha

Would you be able to send me a link that I can download your input files from and I will try and debug the issue. The address is at the top of the "/home/ubuntu/anaconda3/envs/ortho/bin/scripts_of/__main__.py" file.

Best wishes
David

**Comment by sha1987-sss** [comment]
Hi
Thank you for your reply, the attachment is my protein sequence file and do you need any other files?
Best wishes
Shasha Hu




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "davidemms/OrthoFinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月23日(星期三) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [davidemms/OrthoFinder] Gene_tree、orthologues 、Species_Tree and MultipleSequenceAlignments files are empty (Issue #665)





 
Hi Hu ShaSha
 
Would you be able to send me a link that I can download your input files from and I will try and debug the issue. The address is at the top of the "/home/ubuntu/anaconda3/envs/ortho/bin/scripts_of/main.py" file.
 
Best wishes
 David
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

pep.zip (104.29M, 2022年03月27日 08:48 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=5f3930630207499ac1c74d151563004c5a0f0002520700524e080000504e060257581d5a03050a4e5b5c055506570a07550a05013364321306491e195a13325e&code=c90c3c2c

**Comment by davidemms** [comment]
Just the protein sequence files. You'll need to send a link, replying to github with an email attachment doesn't work.

**Comment by sha1987-sss** [comment]
Hi, Below is a link of my protein sequence file, but I don't know if you can open it
Link: https://pan.baidu.com/s/1912duhGQnUUc2R4Ixr1wIQ
Extraction code: 5gfb
