### ISSUE TITLE
parallel task manager issue

### ISSUE THREAD

**Issue by GavinLu42** [davidemms/OrthoFinder#669]
Greetings!

I'm attempting to follow the tutorial, but running `orthofinder -f ExampleData` is returning this error:

Traceback (most recent call last):
  File "/Users/gavinlu/miniconda3/pkgs/orthofinder-2.3.8-2/bin/orthofinder", line 3, in <module>
    from scripts_of.__main__ import main
  File "/Users/gavinlu/miniconda3/pkgs/orthofinder-2.3.8-2/bin/scripts_of/__main__.py", line 30, in <module>
    from . import parallel_task_manager
  File "/Users/gavinlu/miniconda3/pkgs/orthofinder-2.3.8-2/bin/scripts_of/parallel_task_manager.py", line 46, in <module>
    __location__ = os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__)))
OSError: [Errno 1] Operation not permitted

What may be the problem? Thank you in advance!

**Comment by davidemms** [comment]
Hi

Could it be that your input files are somewhere where OrthoFinder doesn't have read/write access? What happens if you put the input files in your home directory?

Best wishes
David

**Comment by GavinLu42** [comment]
Hi David,

Thanks for all the help! Since the last time I posted, I've had to reinstall the entire package due to other reasons, and the package is running perfectly well now judging from the completion of the tutorial analysis.

Although I do have another issue that I am trying to figure out. When I run orthofinder on my actual data, it seems to get stuck in the middle of BLASTing. The computer goes from heating and fan working loudly to completely quiet and I waited for about 10 hours before interrupting it. The last step that is always displayed is "[Time]: Done 70 of 81". Previously when I was working with a subset of my data (8 proteomes, all less than 25 MB) it would finish within an hour. Now that I have added another proteome (84 MB) I'm facing the problem previously described. I am now isolating the largest proteome with the two other smallest proteomes and it still does not seem to be working. I highly suspect that the new proteome may be too large for my computer to run orthofinder on. I would really love some inputs to why it could be happening, and how I could fix it.

Thank you so much again!

Best Regards,
Gavin
