### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 2: invalid start byte

### ISSUE THREAD

**Issue by Upasana1991** [davidemms/OrthoFinder#697]

**Comment by Upasana1991** [comment]
Hi when I run the the command "./orthofinder.py -f Proteomes/primary_transcripts/" on the two proteomes 
It gives me this error below
OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms

2022-05-06 11:57:35 : Starting OrthoFinder 2.5.4
32 thread(s) for highly parallel tasks (BLAST searches etc.)
4 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /net/scratch2/n81047us/orthoF/OrthoFinder-2.5.4/Proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/SimpleTest.phy -o /net/scratch2/n81047us/orthoF/OrthoFinder-2.5.4/Proteomes/primary_transcripts/OrthoFinder/Results_May06_1/WorkingDirectory/SimpleTest.tre" - ok
Traceback (most recent call last):
  File "./orthofinder.py", line 7, in <module>
    main(args)
  File "/net/scratch2/n81047us/orthoF/OrthoFinder-2.5.4/scripts_of/__main__.py", line 1761, in main
    speciesInfoObj = ProcessesNewFasta(fastaDir, options.dna)
  File "/net/scratch2/n81047us/orthoF/OrthoFinder-2.5.4/scripts_of/__main__.py", line 1624, in ProcessesNewFasta
    for iLine, line in enumerate(fastaFile):
  File "/opt/gridware/depots/8e896c5a/el7/pkg/apps/python3/3.6.4/gcc-4.8.5/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 2: invalid start byte

could suggest me wheat should I do to make this work.

**Comment by tayyrov** [comment]
Hi,

It seems you have a problem with the input fasta files. Make sure that the all input fasta files are **unzipped**. I can replicate your error when at least one of the input fasta files is zipped.
best

**Comment by Upasana1991** [comment]
Hi David
Thanks for your reply, I figured out before I received your email and it worked.
Best regards

Upasana

From: tayyrov ***@***.***>
Date: Monday, 30 May 2022 at 10:15
To: davidemms/OrthoFinder ***@***.***>
Cc: Upasana Singh ***@***.***>, Author ***@***.***>
Subject: Re: [davidemms/OrthoFinder] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 2: invalid start byte (Issue #697)

Hi,

It seems you have a problem with the input fasta files. Make sure that the all input fasta files are unzipped. I can replicate your error when at least one of the input fasta files is zipped.
best

**Comment by Bon-jour** [comment]
diamond 0.9.14 can solve this problem try yi try
