### ISSUE TITLE
OrthoFinder crash if fastme creates an empty tree file

### ISSUE THREAD

**Issue by davidemms** [davidemms/OrthoFinder#70]
If, for whatever reason, fastme creates an empty tree file then OrthoFinder crashes when it tries open the file (as the newick tree reader throws an exception):

> Best outgroup(s) for species tree
> ---------------------------------
> Traceback (most recent call last):
>   File "/home/david/workspace/git/OrthoFinder/orthofinder/orthofinder.py", line 1524, in <module>
>     GetOrthologues(dirs, options, program_caller, clustersFilename_pairs)
>   File "/home/david/workspace/git/OrthoFinder/orthofinder/orthofinder.py", line 1355, in GetOrthologues
>     options.qPhyldog)
>   File "/home/david/workspace/git/OrthoFinder/orthofinder/scripts/get_orthologues.py", line 798, in OrthologuesWorkflow
>     roots, clusters, rootedSpeciesTreeFN, nSupport = rfd.GetRoot(spTreeFN_ids, os.path.split(db.TreeFilename_IDs(0))[0] + "/", rfd.GeneToSpecies_dash, nHighParallel, treeFmt = 1)
>   File "/home/david/workspace/git/OrthoFinder/orthofinder/scripts/root_from_duplications.py", line 420, in GetRoot
>     list_of_lists = pool.map(SupportedHierachies_wrapper2, [(fn, GeneToSpeciesMap, species, dict_clades, clade_names) for fn in glob.glob(treesDir + "/*")])
>   File "/usr/lib/python2.7/multiprocessing/pool.py", line 250, in map
>     return self.map_async(func, iterable, chunksize).get()
>   File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
>     raise self._value
> scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.

**Comment by davidemms** [comment]
I'll fix this by making this code robust to invalid newick files.

When dlcpar is run, it will still print an error message because it can't read the file. This is correct behaviour and the OrthoFinder run will still complete. I'll allow dlcpar to continue printing its error message as this will alert the user to a problem with one of the trees. There will be no orthologues identified for this orthogroup since we have no tree to infer the orthologues from! all other orthologues will be unaffected. Dlcpar's error message will look like this:

> Reconciling gene trees and species tree
> ---------------------------------------
> Outgroup: Mycoplasma_agalactiae, Mycoplasma_hyopneumoniae
> WARNING: Some trees could not be rooted
> Usually this is because the tree contains genes from a single species.
> 2017-05-23 11:52:33 : Done 0 of 312
> Traceback (most recent call last):
>   File "/usr/local/bin/dlcpar_search", line 236, in <module>
>     sys.exit(main())
>   File "/usr/local/bin/dlcpar_search", line 187, in main
>     coal_trees = list(treelib.iter_trees(treefile))
>   File "/usr/local/lib/python2.7/dist-packages/dlcpar/deps/rasmus/treelib.py", line 638, in iter_trees
>     infile = util.open_stream(treefile)
>   File "/usr/local/lib/python2.7/dist-packages/dlcpar/deps/rasmus/util.py", line 1171, in open_stream
>     stream = open(filename, mode)
> IOError: [Errno 2] No such file or directory: '/home/david/projects/OrthoFinder/Support/GilbertSmith_fastme/Results_May23/Orthologues_May23_2/WorkingDirectory/dlcpar/OG0000018_tree_id.txt'
