### ISSUE TITLE
ERROR: external program called by OrthoFinder returned an error code: 137

### ISSUE THREAD

**Issue by Xu-chy** [davidemms/OrthoFinder#726]
Hi David, I am currently running orthofinder on my pc . I am using orthofinder 2.5.4. And the program returns some errors now.

**(orthofinder) soil@soil-PC:/media/soil/_dde_data/1_protein$** orthofinder -b Result_Jul14/WorkingDirectory/ -t 4 -a 4
......
2022-7-30 21:27:50 : Written final scores for species 271 to graph file
2022-7-30 21:27:50 : Written final scores for species 271 to graph file

ERROR: external program called by OrthoFinder returned an error code: 137

Command: mcl /media /soil/_dde_data/1_protein/Results_Jul14/WorkingDirectory/OrthoFinder/Results_Jul30/WorkingDirectory/Orthofinder_graph.txt -I 1.5 -o /media /soil/_dde_data/1_protein/Results_Jul14/WorkingDirectory/OrthoFinder/Results_Jul30/WorkingDirectory/clusters_Orthofinder_I1.5.txt -te 4 -V all

stdout
------
b' '
stderr
------
b'Killed\n'
2022-07-31 00:02:30 : Run MCL
Traceback (most recent call last):
   File "/home/soil/miniconda3/envs/orthofinder/bin/orthofinder", line 7, in <module>
     main(args)
   File "/home/soil/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 1791, in main 
     DoOrthogroups(options, speciesInfo0bj, seqsInfo)
   File "/home/soil/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 1791, in DoOrthogroups  
     mcl.ConvertSingleIDsToIDPair(seqsInfo, clustersFilename, clustersFilename_pairs)
   File "/home/soil/miniconda3/envs/orthofinder/bin/scripts_of/mcl.py", line 78, in ConvertSigleIDsToIDPair
     with open(clustersFilename, 'r') as clusterFile, open(newFilename, "w") as output:
FileNotFoundError: [Errno 2] No such file or directory: '/media/soil/_dde_data/1_protein/Results_Jul14/WorkingDirectory/OrthoFinder/Results_Jul30/WorkingDirectory/clusters_OrthoFinder_I1.5txt'

Actually I don't know what's wrong with it.
Looking forward to your help.

Best Wishes!

**Comment by Statistic-Qin** [comment]
Have you solved your problem?
