### ISSUE TITLE
Orthofinder fails at Gene Distances for large dataset

### ISSUE THREAD

**Issue by stubrown** [davidemms/OrthoFinder#780]
Hello, I am using OrthoFinder on a set of 150 genomes. I have tried this on 3 computers (laptop, server, and high memory cluster node) and it fails at about the same point on all of them. The Diamond phase finishes and I get the file of orthogroups.txt (very useful), but then it enters the phase of computing gene trees and I get an error. 

2023-01-21 03:48:31 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------

PS:

Read file <my_test_job.75626181.error> for stderr output of this job.

I can't really figure out from this error message where the problem occurred or what to change in order to get it through the gene tree phase. 
Here is what the standard error dumped into  my_test_job.75626181.error file looks like:

[browns02@hpclogin ~]$ more my_test_job.75626181.error
INFO:    Downloading library image to tmp cache: /scratch/sbuild-tmp-cache-880709492
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
2023/01/20 14:17:19  info unpack layer: sha256:dc65f448a2e2f2ea557e69ed9ac65aa8ac0e16f1bce68f90de91
0b4d5a2f1ba1
2023/01/20 14:17:22  info unpack layer: sha256:67e6f9a1a951d68542b72a305420067dc0a56981d256937b03ad
64c74642b5cf
2023/01/20 14:17:22  info unpack layer: sha256:9cf157065a7e41d45a86167dd3ed0defd4969f88c90f934747aa
5b5391f98607
2023/01/20 14:17:23  info unpack layer: sha256:2905c80ac47496aaf71ecc6031daf032be8789b6a401b9d1a991
bbdfa79db69c
2023/01/20 14:17:27  info unpack layer: sha256:7e78fde5f3d5943ba2ab1b4072c2b0df289adc226c704d2200ab
27467d4d0f25
2023/01/20 14:17:27  info unpack layer: sha256:d8790fe8640270b64f659cb7985c9f15bb0d2bbf3e02db892de0
cda92eff64b4
2023/01/20 14:17:27  info unpack layer: sha256:c1989620753b4c532c30298ba747af1db8bae2584ed1912185f3
f8e9baf93ae3
2023/01/20 14:17:28  info unpack layer: sha256:ba1f76799d1089f37e0027660a28abe11a6ca02493ea8fbf41f8
d78d052b6e12
2023/01/20 14:17:29  info unpack layer: sha256:52798560e2e4f0ff71b01cc8ff03421c61bc891be49f14ebb9b2
dad62449ebb1
2023/01/20 14:17:29  info unpack layer: sha256:bb2fbce10f9d1273079756e488bcea6a96c18472aaff033cb0d5
1ad931de22bc
2023/01/20 14:17:29  info unpack layer: sha256:85325052770975571a1f26d42fdde097eaaf8ef2c14dfcbe9b41
a4a1d3a74cd4
2023/01/20 14:17:29  info unpack layer: sha256:9f2105aa5472d33d8b24cd2601773ada8218e3dabfc988f56b9a
85c0b0b7150f
2023/01/20 14:17:30  info unpack layer: sha256:30904ce9c7b563fb5fe3d32d4d9317a3aa0e611d493f0ef18fdb
dcb7109fb0c6
INFO:    Creating SIF file...
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1778, in main
  File "scripts_of/__main__.py", line 1558, in GetOrthologues
  File "scripts_of/orthologues.py", line 999, in OrthologuesWorkflow
  File "scripts_of/orthologues.py", line 455, in RunAnalysis
  File "scripts_of/orthologues.py", line 342, in GetOGMatrices_FullParallel
  File "warnings.py", line 380, in __exit__
KeyboardInterrupt
[283261] Failed to execute script orthofinder
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/parallel_task_manager.py", line 330, in _I_Spawn_Processes
KeyboardInterrupt
Process Process-118:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/orthologues.py", line 260, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
KeyboardInterrupt
Process Process-117:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/orthologues.py", line 251, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
  File "scripts_of/blast_file_processor.py", line 57, in GetBLAST6Scores
  File "scipy/sparse/lil.py", line 114, in __init__
KeyboardInterrupt
Process Process-121:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/orthologues.py", line 251, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
  File "scripts_of/blast_file_processor.py", line 94, in GetBLAST6Scores
  File "gzip.py", line 385, in close
KeyboardInterrupt
Process Process-112:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/orthologues.py", line 251, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
  File "scripts_of/blast_file_processor.py", line 94, in GetBLAST6Scores
  File "gzip.py", line 385, in close
KeyboardInterrupt
Process Process-114:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/orthologues.py", line 251, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
  File "scripts_of/blast_file_processor.py", line 94, in GetBLAST6Scores
  File "gzip.py", line 385, in close
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "atexit.py", line 24, in _run_exitfuncs
  File "multiprocessing/util.py", line 308, in _exit_function
  File "multiprocessing/util.py", line 271, in _run_finalizers
KeyboardInterrupt
Error in sys.exitfunc:
Process Process-113:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/orthologues.py", line 251, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
  File "scripts_of/blast_file_processor.py", line 57, in GetBLAST6Scores
  File "scipy/sparse/lil.py", line 115, in __init__
KeyboardInterrupt
Process Process-120:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/orthologues.py", line 260, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
KeyboardInterrupt
Process Process-116:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/orthologues.py", line 251, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
  File "scripts_of/blast_file_processor.py", line 57, in GetBLAST6Scores
  File "scipy/sparse/lil.py", line 115, in __init__
KeyboardInterrupt
Process Process-119:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/orthologues.py", line 251, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
  File "scripts_of/blast_file_processor.py", line 57, in GetBLAST6Scores
  File "scipy/sparse/lil.py", line 114, in __init__
KeyboardInterrupt
Process Process-115:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "scripts_of/orthologues.py", line 260, in Worker_OGMatrices_ReadBLASTAndUpdateDistances
KeyboardInterrupt
Terminated

**Comment by davidemms** [comment]
Hi

Unfortunately this steps requires a large amount of RAM, and it scales quadratically with the number of species. You could try with the `-M msa` option, this uses MSA-based gene tree inference, and is probably a better option all round. It often uses less RAM. If still necessary you can use the `-t` option to reduce the number of parallel threads used.

To use this option and restart from where your previous run got to use:
```
orthofinder -fg RESULTS_DIR -M msa
```

All the best
David
