### ISSUE TITLE
2.5.4: scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure

### ISSUE THREAD

**Issue by EvanneD** [davidemms/OrthoFinder#782]
Hello,

In version 2.5.4 i got this error message: 
```
Best outgroup(s) for species tree
---------------------------------
2023-01-23 15:56:51 : Starting STRIDE
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1778, in main
  File "scripts_of/__main__.py", line 1558, in GetOrthologues
  File "scripts_of/orthologues.py", line 1039, in OrthologuesWorkflow
  File "scripts_of/stride.py", line 509, in GetRoot
  File "scripts_of/tree.py", line 221, in __init__
  File "scripts_of/newick.py", line 216, in read_newick
scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
[5857] Failed to execute script orthofinder
```

The same issue was posted before [#159](https://github.com/davidemms/OrthoFinder/issues/159) but for this version I don't see that it was solved. 
Can someone help?

-- Evanne

**Comment by konetom** [comment]
I have the same problem:

<pre>
Best outgroup(s) for species tree
---------------------------------
2023-01-22 05:39:20 : Starting STRIDE
Traceback (most recent call last):
  File "/home/users/anand/miniconda3/envs/ortho/bin/scripts_of/stride.py", line 506, in GetRoot
    speciesTree = tree.Tree(speciesTreeFN, format=2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/anand/miniconda3/envs/ortho/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/users/anand/miniconda3/envs/ortho/bin/scripts_of/newick.py", line 216, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/anand/miniconda3/envs/ortho/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/users/anand/miniconda3/envs/ortho/bin/scripts_of/__main__.py", line 1710, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/users/anand/miniconda3/envs/ortho/bin/scripts_of/__main__.py", line 1497, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/anand/miniconda3/envs/ortho/bin/scripts_of/orthologues.py", line 961, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, all_stride_dup_genes = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/anand/miniconda3/envs/ortho/bin/scripts_of/stride.py", line 509, in GetRoot
    speciesTree = tree.Tree(speciesTreeFN, format=1)                    
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/anand/miniconda3/envs/ortho/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/users/anand/miniconda3/envs/ortho/bin/scripts_of/newick.py", line 216, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
</pre>

**Comment by baptisteImbert** [comment]
A simple patch is to force an earlier version of python in you conda env @konetom. The 'rU' was not deprecated in python=3.10.8 and therefore works for me.

**Comment by konetom** [comment]
Dear @baptisteImbert thank you for the suggestion. I will give it a try and let you know.

**Comment by konetom** [comment]
Dear @baptisteImbert, your solution unfortunately didn't work. I've tried it with python 3.10.8 and later also with python 3.8 but without any success.

**Comment by baptisteImbert** [comment]
> Dear @baptisteImbert, your solution unfortunately didn't work. I've tried it with python 3.10.8 and later also with python 3.8 but without any success. Afterwards, I reinstalled the whole Orthofinder package and tried to run it again but another error appeared... please see the new issue here: #783

Sorry to hear that. The two issues might actually be unrelated. I'm just a casual user, I unfortunately don't have any clue regarding your new issue. Hope you will find a solution soon.
