### ISSUE TITLE
2.5.4/scripts_of/stride.py_UnboundLocalError: local variable 'speciesTree' referenced before assignment

### ISSUE THREAD

**Issue by konetom** [davidemms/OrthoFinder#783]
Hello, I've been trying to run *OrthoFinder version 2.5.4* for several days now but it still doesn't complete successfully. The most recent failed run shows me this message:

<pre>
2023-01-31 17:20:58 : Starting STRIDE
~/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
~/miniconda3/lib/python3.8/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
ERROR: Species tree inference failed
Traceback (most recent call last):
  File "/home/software/OrthoFinder-2.5.4/orthofinder.py", line 7, in <module>
    main(args)
  File "/home/software/OrthoFinder-2.5.4/scripts_of/__main__.py", line 1781, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/software/OrthoFinder-2.5.4/scripts_of/__main__.py", line 1543, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
  File "/home/software/OrthoFinder-2.5.4/scripts_of/orthologues.py", line 1039, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
  File "/home/software/OrthoFinder-2.5.4/scripts_of/stride.py", line 513, in GetRoot
    species, dict_clades, clade_names = AnalyseSpeciesTree(speciesTree)
UnboundLocalError: local variable 'speciesTree' referenced before assignment
</pre>

Could anyone help me, please?

**Comment by konetom** [comment]
Reinstalling the whole package helped to overcome this issue with STRIDE.

**Comment by Zerong0513** [comment]
Hi, how many species do you include? I have the same problem.
