### ISSUE TITLE
Error while gene tree and species tree estimation

### ISSUE THREAD

**Issue by pragyr** [davidemms/OrthoFinder#801]
Hi,
My orthofinder analysis, of 26 transcriptomes, ran into an error while estimating gene trees and species trees after completing gene distance calculation. I do see that there are many unassigned genes and there are 0 orthogroups with all species present and 0 of these consisted entirely of single-copy genes. Does this have anything to do with this sort of error? Can someone suggest me what should be the way out?

Following is the standard output and error

```
OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms

2023-02-12 12:53:41 : Starting OrthoFinder 2.5.4
112 thread(s) for highly parallel tasks (BLAST searches etc.)
32 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /home/pragya/transcriptomes/orthofinder_output/Results_Feb04/WorkingDirectory/SimpleTest.phy -o /home/pragya/transcriptomes/orthofinder_output/Results_Feb04/WorkingDirectory/SimpleTest.tre" - ok
Using previously calculated BLAST results in /home/pragya/transcriptomes/orthofinder_output/Results_Feb04/WorkingDirectory/

Running OrthoFinder algorithm
-----------------------------
2023-02-12 12:54:18 : Initial processing of each species
WARNING: Too few hits between species 3 and species 15 to normalise the scores, these hits will be ignored
2023-02-12 12:55:05 : Initial processing of species 3 complete
WARNING: Too few hits between species 4 and species 15 to normalise the scores, these hits will be ignored
2023-02-12 12:55:09 : Initial processing of species 4 complete
WARNING: Too few hits between species 15 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 3 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 4 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 5 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 6 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 7 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 9 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 10 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 11 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 12 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 16 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 17 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 19 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 21 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 23 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 24 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 15 and species 25 to normalise the scores, these hits will be ignored
2023-02-12 12:55:10 : Initial processing of species 15 complete
WARNING: Too few hits between species 1 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 12:55:10 : Initial processing of species 1 complete
WARNING: Too few hits between species 17 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 8 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 13 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 14 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 15 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 16 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 19 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 20 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 21 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 22 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 23 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 24 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 17 and species 25 to normalise the scores, these hits will be ignored
2023-02-12 12:55:11 : Initial processing of species 17 complete
WARNING: Too few hits between species 5 and species 15 to normalise the scores, these hits will be ignored
2023-02-12 12:55:17 : Initial processing of species 5 complete
WARNING: Too few hits between species 6 and species 15 to normalise the scores, these hits will be ignored
2023-02-12 12:55:18 : Initial processing of species 6 complete
2023-02-12 12:55:24 : Initial processing of species 2 complete
WARNING: Too few hits between species 7 and species 15 to normalise the scores, these hits will be ignored
2023-02-12 12:55:34 : Initial processing of species 7 complete
WARNING: Too few hits between species 0 and species 15 to normalise the scores, these hits will be ignored
2023-02-12 12:55:41 : Initial processing of species 0 complete
2023-02-12 12:55:42 : Initial processing of species 18 complete
WARNING: Too few hits between species 8 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 12:55:48 : Initial processing of species 8 complete
WARNING: Too few hits between species 16 and species 15 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 16 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 12:55:56 : Initial processing of species 16 complete
WARNING: Too few hits between species 13 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 12:55:57 : Initial processing of species 13 complete
WARNING: Too few hits between species 12 and species 15 to normalise the scores, these hits will be ignored
2023-02-12 12:55:59 : Initial processing of species 12 complete
WARNING: Too few hits between species 23 and species 15 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 23 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 12:56:03 : Initial processing of species 23 complete
WARNING: Too few hits between species 21 and species 15 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 21 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 12:56:07 : Initial processing of species 21 complete
WARNING: Too few hits between species 9 and species 15 to normalise the scores, these hits will be ignored
2023-02-12 12:56:09 : Initial processing of species 9 complete
WARNING: Too few hits between species 22 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 12:56:14 : Initial processing of species 22 complete
WARNING: Too few hits between species 20 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 12:56:35 : Initial processing of species 20 complete
WARNING: Too few hits between species 10 and species 15 to normalise the scores, these hits will be ignored
2023-02-12 12:56:48 : Initial processing of species 10 complete
WARNING: Too few hits between species 14 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 12:57:06 : Initial processing of species 14 complete
WARNING: Too few hits between species 11 and species 15 to normalise the scores, these hits will be ignored
2023-02-12 12:57:07 : Initial processing of species 11 complete
WARNING: Too few hits between species 25 and species 15 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 25 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 12:57:17 : Initial processing of species 25 complete
WARNING: Too few hits between species 19 and species 15 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 19 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 13:04:57 : Initial processing of species 19 complete
WARNING: Too few hits between species 24 and species 15 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 24 and species 17 to normalise the scores, these hits will be ignored
2023-02-12 13:09:34 : Initial processing of species 24 complete
2023-02-12 13:12:24 : Connected putative homologues
2023-02-12 13:12:24 : Written final scores for species 15 to graph file
2023-02-12 13:12:24 : Written final scores for species 17 to graph file
2023-02-12 13:12:40 : Written final scores for species 23 to graph file
2023-02-12 13:12:44 : Written final scores for species 18 to graph file
2023-02-12 13:12:48 : Written final scores for species 1 to graph file
2023-02-12 13:12:49 : Written final scores for species 21 to graph file
2023-02-12 13:12:51 : Written final scores for species 3 to graph file
2023-02-12 13:12:51 : Written final scores for species 22 to graph file
2023-02-12 13:12:55 : Written final scores for species 4 to graph file
2023-02-12 13:12:58 : Written final scores for species 5 to graph file
2023-02-12 13:12:59 : Written final scores for species 16 to graph file
2023-02-12 13:12:59 : Written final scores for species 2 to graph file
2023-02-12 13:13:00 : Written final scores for species 6 to graph file
2023-02-12 13:13:04 : Written final scores for species 7 to graph file
2023-02-12 13:13:07 : Written final scores for species 8 to graph file
2023-02-12 13:13:15 : Written final scores for species 0 to graph file
2023-02-12 13:13:16 : Written final scores for species 13 to graph file
2023-02-12 13:13:17 : Written final scores for species 12 to graph file
2023-02-12 13:13:23 : Written final scores for species 9 to graph file
2023-02-12 13:13:24 : Written final scores for species 20 to graph file
2023-02-12 13:13:33 : Written final scores for species 14 to graph file
2023-02-12 13:13:38 : Written final scores for species 25 to graph file
2023-02-12 13:13:51 : Written final scores for species 11 to graph file
2023-02-12 13:13:51 : Written final scores for species 10 to graph file
2023-02-12 13:20:47 : Written final scores for species 19 to graph file
2023-02-12 13:24:40 : Written final scores for species 24 to graph file

WARNING: program called by OrthoFinder produced output to stderr

Command: mcl /home/pragya/transcriptomes/orthofinder_output/Results_Feb04/WorkingDirectory/OrthoFinder/Results_Feb12_1/WorkingDirectory/OrthoFinder_graph.txt -I 1.5 -o /home/pragya/transcriptomes/orthofinder_output/Results_Feb04/WorkingDirectory/OrthoFinder/Results_Feb12_1/WorkingDirectory/clusters_OrthoFinder_I1.5.txt -te 32 -V all

stdout
------
b''
stderr
------
b'[mcl] cut <3> instances of overlap\n'
2023-02-13 09:23:04 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 2783230 genes (37.0% of total) to 641464 orthogroups. Fifty percent of all genes were in orthogroups with 1 or more genes (G50 was 1) and were contained in the largest 1619566 orthogroups (O50 was 1619566). There were 0 orthogroups with all species present and 0 of these consisted entirely of single-copy genes.

2023-02-20 12:21:49 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2023-02-20 12:45:48 : Done
/home/pragya/.conda/envs/revbayesenv/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/pragya/.conda/envs/revbayesenv/lib/python3.11/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
2023-02-20 12:46:11 : Done 0 of 170218
2023-02-20 12:46:33 : Done 1000 of 170218
2023-02-20 12:46:39 : Done 2000 of 170218
2023-02-20 12:46:50 : Done 3000 of 170218
2023-02-20 12:47:00 : Done 4000 of 170218
2023-02-20 12:47:10 : Done 5000 of 170218
2023-02-20 12:47:18 : Done 6000 of 170218
2023-02-20 12:47:23 : Done 7000 of 170218
2023-02-20 12:47:28 : Done 8000 of 170218
2023-02-20 12:47:32 : Done 9000 of 170218
2023-02-20 12:47:37 : Done 10000 of 170218
2023-02-20 12:47:43 : Done 11000 of 170218
2023-02-20 12:47:48 : Done 12000 of 170218
2023-02-20 12:47:53 : Done 13000 of 170218
2023-02-20 12:47:58 : Done 14000 of 170218
2023-02-20 12:48:05 : Done 15000 of 170218
2023-02-20 12:48:10 : Done 16000 of 170218
2023-02-20 12:48:16 : Done 17000 of 170218
2023-02-20 12:48:22 : Done 18000 of 170218
2023-02-20 12:48:28 : Done 19000 of 170218
2023-02-20 12:48:34 : Done 20000 of 170218
2023-02-20 12:48:40 : Done 21000 of 170218
2023-02-20 12:48:47 : Done 22000 of 170218
2023-02-20 12:48:55 : Done 23000 of 170218
2023-02-20 12:49:03 : Done 24000 of 170218
2023-02-20 12:49:10 : Done 25000 of 170218
2023-02-20 12:49:19 : Done 26000 of 170218
2023-02-20 12:49:26 : Done 27000 of 170218
2023-02-20 12:49:34 : Done 28000 of 170218
2023-02-20 12:49:41 : Done 29000 of 170218
2023-02-20 12:49:48 : Done 30000 of 170218
2023-02-20 12:49:55 : Done 31000 of 170218
2023-02-20 12:50:03 : Done 32000 of 170218
2023-02-20 12:50:10 : Done 33000 of 170218
2023-02-20 12:50:17 : Done 34000 of 170218
2023-02-20 12:50:24 : Done 35000 of 170218
2023-02-20 12:50:32 : Done 36000 of 170218
2023-02-20 12:50:40 : Done 37000 of 170218
2023-02-20 12:50:48 : Done 38000 of 170218
2023-02-20 12:50:56 : Done 39000 of 170218
2023-02-20 12:51:04 : Done 40000 of 170218
2023-02-20 12:51:12 : Done 41000 of 170218
2023-02-20 12:51:20 : Done 42000 of 170218
2023-02-20 12:51:28 : Done 43000 of 170218
2023-02-20 12:51:37 : Done 44000 of 170218
2023-02-20 12:51:47 : Done 45000 of 170218
2023-02-20 12:51:56 : Done 46000 of 170218
2023-02-20 12:52:05 : Done 47000 of 170218
2023-02-20 12:52:15 : Done 48000 of 170218
2023-02-20 12:52:24 : Done 49000 of 170218
2023-02-20 12:52:34 : Done 50000 of 170218
2023-02-20 12:52:43 : Done 51000 of 170218
2023-02-20 12:52:53 : Done 52000 of 170218
2023-02-20 12:53:01 : Done 53000 of 170218
2023-02-20 12:53:13 : Done 54000 of 170218
2023-02-20 12:53:24 : Done 55000 of 170218
2023-02-20 12:53:35 : Done 56000 of 170218
2023-02-20 12:53:46 : Done 57000 of 170218
2023-02-20 12:53:56 : Done 58000 of 170218
2023-02-20 12:54:08 : Done 59000 of 170218
2023-02-20 12:54:21 : Done 60000 of 170218
2023-02-20 12:54:33 : Done 61000 of 170218
2023-02-20 12:54:45 : Done 62000 of 170218
2023-02-20 12:54:57 : Done 63000 of 170218
2023-02-20 12:55:11 : Done 64000 of 170218
2023-02-20 12:55:25 : Done 65000 of 170218
2023-02-20 12:55:39 : Done 66000 of 170218
2023-02-20 12:55:53 : Done 67000 of 170218
2023-02-20 12:56:07 : Done 68000 of 170218
2023-02-20 12:56:22 : Done 69000 of 170218
2023-02-20 12:56:36 : Done 70000 of 170218
2023-02-20 12:56:50 : Done 71000 of 170218
2023-02-20 12:57:03 : Done 72000 of 170218
2023-02-20 12:57:17 : Done 73000 of 170218
2023-02-20 12:57:32 : Done 74000 of 170218
2023-02-20 12:57:46 : Done 75000 of 170218
2023-02-20 12:58:01 : Done 76000 of 170218
2023-02-20 12:58:16 : Done 77000 of 170218
2023-02-20 12:58:29 : Done 78000 of 170218
2023-02-20 12:58:46 : Done 79000 of 170218
2023-02-20 12:59:02 : Done 80000 of 170218
2023-02-20 12:59:20 : Done 81000 of 170218
2023-02-20 12:59:37 : Done 82000 of 170218
2023-02-20 12:59:53 : Done 83000 of 170218
2023-02-20 13:00:11 : Done 84000 of 170218
2023-02-20 13:00:27 : Done 85000 of 170218
2023-02-20 13:00:45 : Done 86000 of 170218
2023-02-20 13:01:03 : Done 87000 of 170218
2023-02-20 13:01:21 : Done 88000 of 170218
2023-02-20 13:01:38 : Done 89000 of 170218
2023-02-20 13:01:57 : Done 90000 of 170218
2023-02-20 13:02:17 : Done 91000 of 170218
2023-02-20 13:02:36 : Done 92000 of 170218
2023-02-20 13:02:56 : Done 93000 of 170218
2023-02-20 13:03:16 : Done 94000 of 170218
2023-02-20 13:03:36 : Done 95000 of 170218
2023-02-20 13:03:56 : Done 96000 of 170218
2023-02-20 13:04:18 : Done 97000 of 170218
2023-02-20 13:04:39 : Done 98000 of 170218
2023-02-20 13:04:57 : Done 99000 of 170218
2023-02-20 13:05:21 : Done 100000 of 170218
2023-02-20 13:05:44 : Done 101000 of 170218
2023-02-20 13:06:05 : Done 102000 of 170218
2023-02-20 13:06:27 : Done 103000 of 170218
2023-02-20 13:06:51 : Done 104000 of 170218
2023-02-20 13:07:13 : Done 105000 of 170218
2023-02-20 13:07:36 : Done 106000 of 170218
2023-02-20 13:07:58 : Done 107000 of 170218
2023-02-20 13:08:20 : Done 108000 of 170218
2023-02-20 13:08:42 : Done 109000 of 170218
2023-02-20 13:09:06 : Done 110000 of 170218
2023-02-20 13:09:29 : Done 111000 of 170218
2023-02-20 13:09:53 : Done 112000 of 170218
2023-02-20 13:10:15 : Done 113000 of 170218
2023-02-20 13:10:39 : Done 114000 of 170218
2023-02-20 13:11:03 : Done 115000 of 170218
2023-02-20 13:11:27 : Done 116000 of 170218
2023-02-20 13:11:50 : Done 117000 of 170218
2023-02-20 13:12:12 : Done 118000 of 170218
2023-02-20 13:12:38 : Done 119000 of 170218
2023-02-20 13:12:59 : Done 120000 of 170218
2023-02-20 13:13:23 : Done 121000 of 170218
2023-02-20 13:13:49 : Done 122000 of 170218
2023-02-20 13:14:14 : Done 123000 of 170218
2023-02-20 13:14:35 : Done 124000 of 170218
2023-02-20 13:14:57 : Done 125000 of 170218
2023-02-20 13:15:21 : Done 126000 of 170218
2023-02-20 13:15:43 : Done 127000 of 170218
2023-02-20 13:16:05 : Done 128000 of 170218
2023-02-20 13:16:29 : Done 129000 of 170218
2023-02-20 13:16:55 : Done 130000 of 170218
2023-02-20 13:17:18 : Done 131000 of 170218
2023-02-20 13:17:42 : Done 132000 of 170218
2023-02-20 13:18:08 : Done 133000 of 170218
2023-02-20 13:18:32 : Done 134000 of 170218
2023-02-20 13:19:00 : Done 135000 of 170218
2023-02-20 13:19:22 : Done 136000 of 170218
2023-02-20 13:19:48 : Done 137000 of 170218
2023-02-20 13:20:15 : Done 138000 of 170218
2023-02-20 13:20:40 : Done 139000 of 170218
2023-02-20 13:21:03 : Done 140000 of 170218
2023-02-20 13:21:28 : Done 141000 of 170218
2023-02-20 13:21:55 : Done 142000 of 170218
2023-02-20 13:22:16 : Done 143000 of 170218
2023-02-20 13:22:38 : Done 144000 of 170218
2023-02-20 13:23:05 : Done 145000 of 170218
2023-02-20 13:23:32 : Done 146000 of 170218
2023-02-20 13:23:56 : Done 147000 of 170218
2023-02-20 13:24:26 : Done 148000 of 170218
2023-02-20 13:24:54 : Done 149000 of 170218
2023-02-20 13:25:17 : Done 150000 of 170218
2023-02-20 13:25:41 : Done 151000 of 170218
2023-02-20 13:26:10 : Done 152000 of 170218
2023-02-20 13:26:37 : Done 153000 of 170218
2023-02-20 13:26:57 : Done 154000 of 170218
2023-02-20 13:27:18 : Done 155000 of 170218
2023-02-20 13:27:45 : Done 156000 of 170218
2023-02-20 13:28:11 : Done 157000 of 170218
2023-02-20 13:28:36 : Done 158000 of 170218
2023-02-20 13:29:08 : Done 159000 of 170218
2023-02-20 13:29:43 : Done 160000 of 170218
2023-02-20 13:30:07 : Done 161000 of 170218
2023-02-20 13:30:41 : Done 162000 of 170218
2023-02-20 13:31:13 : Done 163000 of 170218
2023-02-20 13:31:43 : Done 164000 of 170218
2023-02-20 13:32:17 : Done 165000 of 170218
2023-02-20 13:32:45 : Done 166000 of 170218
2023-02-20 13:33:21 : Done 167000 of 170218
2023-02-20 13:33:52 : Done 168000 of 170218
2023-02-20 13:34:24 : Done 169000 of 170218
2023-02-20 13:34:58 : Done 170000 of 170218
Using fallback species tree inference method

Inferring gene and species trees
--------------------------------

Best outgroup(s) for species tree
---------------------------------
2023-02-20 13:35:03 : Starting STRIDE
Traceback (most recent call last):
  File "/home/pragya/.conda/envs/revbayesenv/bin/scripts_of/stride.py", line 506, in GetRoot
    speciesTree = tree.Tree(speciesTreeFN, format=2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pragya/.conda/envs/revbayesenv/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/pragya/.conda/envs/revbayesenv/bin/scripts_of/newick.py", line 208, in read_newick
    nw = open(newick, 'rU').read()
         ^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pragya/.conda/envs/revbayesenv/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/pragya/.conda/envs/revbayesenv/bin/scripts_of/__main__.py", line 1794, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/pragya/.conda/envs/revbayesenv/bin/scripts_of/__main__.py", line 1540, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pragya/.conda/envs/revbayesenv/bin/scripts_of/orthologues.py", line 1039, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pragya/.conda/envs/revbayesenv/bin/scripts_of/stride.py", line 509, in GetRoot
    speciesTree = tree.Tree(speciesTreeFN, format=1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pragya/.conda/envs/revbayesenv/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/pragya/.conda/envs/revbayesenv/bin/scripts_of/newick.py", line 208, in read_newick
    nw = open(newick, 'rU').read()
         ^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```

**Comment by davidemms** [comment]
Thanks for reporting this, it has been resolved in the new version, 2.5.5: https://github.com/davidemms/OrthoFinder/releases/tag/v2.5.5
