### ISSUE TITLE
Value Error: Invalid mode 'rU' when inferring trees

### ISSUE THREAD

**Issue by mjosmurphy** [davidemms/OrthoFinder#821]
Dear Dr. Emms,

I am running OrthoFinder v. 2.5.4 on a WSL2 Ubuntu instance, on a Windows 10 machine. I was doing a test run using a few CDS files, some of which I downloaded and some of which I made using the BRAKER3 pipeline.

I downloaded OrthoFinder and its dependencies into an empty conda environment using the command
`conda install -c bioconda orthofinder`

Everything works fine until the end of the gene/species tree inference process, when I get an error that stops the program.
I have attached the console output below:

Thanks for your consideration!
-Matt Murphy

` (OrthoFinderEnv) mjosmurphy@IRIS:~$ orthofinder \\
> -f ~/projects/butterfly_annotation/cds/orthofinder_test/ \\
> -t 6 \\
> -a 3 \\
> -S diamond \\
> -d #input is DNA

OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms

2023-05-17 22:14:55 : Starting OrthoFinder 2.5.4
6 thread(s) for highly parallel tasks (BLAST searches etc.)
3 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /home/mjosmurphy/projects/butterfly_annotation/cds/orthofinder_test/OrthoFinder/Results_May17/WorkingDirectory/SimpleTest.phy -o /home/mjosmurphy/projects/butterfly_annotation/cds/orthofinder_test/OrthoFinder/Results_May17/WorkingDirectory/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2023-05-17 22:14:57 : Creating blast_nucl database 1 of 5
2023-05-17 22:14:59 : Creating blast_nucl database 2 of 5
2023-05-17 22:15:00 : Creating blast_nucl database 3 of 5
2023-05-17 22:15:02 : Creating blast_nucl database 4 of 5
2023-05-17 22:15:04 : Creating blast_nucl database 5 of 5

Running blast_nucl all-versus-all
---------------------------------
Using 6 thread(s)
2023-05-17 22:15:05 : This may take some time....
2023-05-17 22:15:05 : Done 0 of 25
2023-05-17 22:16:09 : Done 10 of 25
2023-05-17 22:16:59 : Done 20 of 25
2023-05-17 22:20:53 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2023-05-17 22:20:54 : Initial processing of each species
2023-05-17 22:21:03 : Initial processing of species 1 complete
2023-05-17 22:21:06 : Initial processing of species 2 complete
2023-05-17 22:21:08 : Initial processing of species 4 complete
2023-05-17 22:21:10 : Initial processing of species 3 complete
2023-05-17 22:21:18 : Initial processing of species 0 complete
2023-05-17 22:21:22 : Connected putative homologues
2023-05-17 22:21:26 : Written final scores for species 0 to graph file
2023-05-17 22:21:26 : Written final scores for species 1 to graph file
2023-05-17 22:21:26 : Written final scores for species 2 to graph file
2023-05-17 22:21:27 : Written final scores for species 4 to graph file
2023-05-17 22:21:29 : Written final scores for species 3 to graph file
2023-05-17 22:22:18 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 131062 genes (84.4% of total) to 31966 orthogroups. Fifty percent of all genes were in orthogroups with 4 or more genes (G50 was 4) and were contained in the largest 9128 orthogroups (O50 was 9128). There were 1567 orthogroups with all species present and 66 of these consisted entirely of single-copy genes.

2023-05-17 22:22:24 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2023-05-17 22:24:18 : Done

Inferring gene and species trees
--------------------------------
2023-05-17 22:24:19 : Done 0 of 9481
2023-05-17 22:24:21 : Done 1000 of 9481
2023-05-17 22:24:21 : Done 2000 of 9481
2023-05-17 22:24:22 : Done 3000 of 9481
2023-05-17 22:24:23 : Done 4000 of 9481
2023-05-17 22:24:23 : Done 5000 of 9481
2023-05-17 22:24:24 : Done 6000 of 9481
2023-05-17 22:24:24 : Done 7000 of 9481
2023-05-17 22:24:25 : Done 8000 of 9481
2023-05-17 22:24:25 : Done 9000 of 9481

Traceback (most recent call last):
  File "/home/mjosmurphy/anaconda3/envs/OrthoFinderEnv/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/mjosmurphy/anaconda3/envs/OrthoFinderEnv/bin/scripts_of/__main__.py", line 1778, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/mjosmurphy/anaconda3/envs/OrthoFinderEnv/bin/scripts_of/__main__.py", line 1540, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mjosmurphy/anaconda3/envs/OrthoFinderEnv/bin/scripts_of/orthologues.py", line 999, in OrthologuesWorkflow
    spTreeFN_ids, qSTAG = db.RunAnalysis(userSpeciesTree == None)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mjosmurphy/anaconda3/envs/OrthoFinderEnv/bin/scripts_of/orthologues.py", line 481, in RunAnalysis
    stag.Run_ForOrthoFinder(files.FileHandler.GetOGsTreeDir(), files.FileHandler.GetWorkingDirectory_Write(), self.ogSet.seqsInfo.speciesToUse, spTreeFN_ids)
  File "/home/mjosmurphy/anaconda3/envs/OrthoFinderEnv/bin/scripts_of/stag.py", line 262, in Run_ForOrthoFinder
    ProcessTrees(dir_in, dir_matrices, dir_trees_out, gene_to_species, qVerbose=False, qForOF=True)
  File "/home/mjosmurphy/anaconda3/envs/OrthoFinderEnv/bin/scripts_of/stag.py", line 191, in ProcessTrees
    t = tree.Tree(fn)
        ^^^^^^^^^^^^^
  File "/home/mjosmurphy/anaconda3/envs/OrthoFinderEnv/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/mjosmurphy/anaconda3/envs/OrthoFinderEnv/bin/scripts_of/newick.py", line 208, in read_newick
    nw = open(newick, 'rU').read()
         ^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'`

In addition, here is a list of the packages installed to my conda environment:
`(OrthoFinderEnv) mjosmurphy@IRIS:~$ conda list
###
### Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
blast                     2.5.0                hc0b0e79_3    bioconda
boost                     1.82.0          py311hcb41070_0    conda-forge
boost-cpp                 1.82.0               he19a28c_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
diamond                   2.1.6                h5b5514e_1    bioconda
fastme                    2.1.6.1              h031d066_3    bioconda
fasttree                  2.1.11               h031d066_2    bioconda
gawk                      5.1.0                h7f98852_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
iqtree                    2.2.2.3              h2202e69_2    bioconda
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
mafft                     7.520                h031d066_2    bioconda
mcl                       14.137          pl5321hec16e2b_8    bioconda
mmseqs2                   13.45111        pl5321hf1761c0_2    bioconda
mpi                       1.0                     openmpi    conda-forge
muscle                    5.1                  h4ac6f70_3    bioconda
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.24.3          py311h64a7726_0    conda-forge
openmpi                   4.1.5              h414af15_101    conda-forge
openssl                   3.1.0                hd590300_3    conda-forge
orthofinder               2.5.4                hdfd78af_0    bioconda
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
python                    3.11.3          h2755cc3_0_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
raxml                     8.2.12               h031d066_6    bioconda
raxml-ng                  1.2.0                h22e3c99_0    bioconda
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.9.3           py311h69910c8_2    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge`

**Comment by mjosmurphy** [comment]
As a follow-up, I downgraded Python in my environment to v. 3.6.15 and everything appears to work okay now:

`(OrthoFinderEnv) mjosmurphy@IRIS:~$ orthofinder -f ~/projects/butterfly_annotation/cds/orthofinder_test/ -t 6 -a 6 -S diamond -d #input is DNA

OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms

2023-05-17 23:07:41 : Starting OrthoFinder 2.5.4
6 thread(s) for highly parallel tasks (BLAST searches etc.)
6 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /home/mjosmurphy/projects/butterfly_annotation/cds/orthofinder_test/OrthoFinder/Results_May17_2/WorkingDirectory/SimpleTest.phy -o /home/mjosmurphy/projects/butterfly_annotation/cds/orthofinder_test/OrthoFinder/Results_May17_2/WorkingDirectory/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2023-05-17 23:07:43 : Creating blast_nucl database 1 of 5
2023-05-17 23:07:44 : Creating blast_nucl database 2 of 5
2023-05-17 23:07:46 : Creating blast_nucl database 3 of 5
2023-05-17 23:07:48 : Creating blast_nucl database 4 of 5
2023-05-17 23:07:49 : Creating blast_nucl database 5 of 5

Running blast_nucl all-versus-all
---------------------------------
Using 6 thread(s)
2023-05-17 23:07:50 : This may take some time....
2023-05-17 23:07:50 : Done 0 of 25
2023-05-17 23:08:56 : Done 10 of 25
2023-05-17 23:09:49 : Done 20 of 25
2023-05-17 23:13:46 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2023-05-17 23:13:47 : Initial processing of each species
2023-05-17 23:13:51 : Initial processing of species 4 complete
2023-05-17 23:13:58 : Initial processing of species 3 complete
2023-05-17 23:14:02 : Initial processing of species 1 complete
2023-05-17 23:14:05 : Initial processing of species 2 complete
2023-05-17 23:14:21 : Initial processing of species 0 complete
2023-05-17 23:14:25 : Connected putative homologues
2023-05-17 23:14:27 : Written final scores for species 4 to graph file
2023-05-17 23:14:30 : Written final scores for species 1 to graph file
2023-05-17 23:14:30 : Written final scores for species 0 to graph file
2023-05-17 23:14:31 : Written final scores for species 2 to graph file
2023-05-17 23:14:31 : Written final scores for species 3 to graph file
2023-05-17 23:15:09 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 131062 genes (84.4% of total) to 31966 orthogroups. Fifty percent of all genes were in orthogroups with 4 or more genes (G50 was 4) and were contained in the largest 9128 orthogroups (O50 was 9128). There were 1567 orthogroups with all species present and 66 of these consisted entirely of single-copy genes.

2023-05-17 23:15:16 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2023-05-17 23:17:47 : Done

Inferring gene and species trees
--------------------------------
2023-05-17 23:17:48 : Done 0 of 9481
2023-05-17 23:17:51 : Done 1000 of 9481
2023-05-17 23:17:52 : Done 2000 of 9481
2023-05-17 23:17:54 : Done 3000 of 9481
2023-05-17 23:17:55 : Done 4000 of 9481
2023-05-17 23:17:56 : Done 5000 of 9481
2023-05-17 23:17:57 : Done 6000 of 9481
2023-05-17 23:17:58 : Done 7000 of 9481
2023-05-17 23:17:59 : Done 8000 of 9481
2023-05-17 23:18:00 : Done 9000 of 9481

1567 trees had all species present and will be used by STAG to infer the species tree

Best outgroup(s) for species tree
---------------------------------
2023-05-17 23:29:55 : Starting STRIDE
2023-05-17 23:29:56 : Done STRIDE
Observed 22 well-supported, non-terminal duplications. 22 support the best roots and 0 contradict them.
Best outgroups for species tree:
  LycPhl
  PapMac, PapGla
  BicAny, HelSar

WARNING: Multiple potential species tree roots were identified, only one will be analyed.

Reconciling gene trees and species tree
---------------------------------------
Outgroup: LycPhl
2023-05-17 23:29:56 : Starting Recon and orthologues
2023-05-17 23:29:56 : Starting OF Orthologues
2023-05-17 23:29:59 : Done 1000 of 9481
2023-05-17 23:29:59 : Done 2000 of 9481
2023-05-17 23:30:00 : Done 3000 of 9481
2023-05-17 23:30:01 : Done 4000 of 9481
2023-05-17 23:30:01 : Done 5000 of 9481
2023-05-17 23:30:02 : Done 6000 of 9481
2023-05-17 23:30:02 : Done 7000 of 9481
2023-05-17 23:30:03 : Done 8000 of 9481
2023-05-17 23:30:03 : Done 9000 of 9481
2023-05-17 23:30:11 : Done 0 of 9481
2023-05-17 23:30:12 : Done OF Orthologues

Writing results files
=====================
2023-05-17 23:30:14 : Done orthologues

Results:
    /home/mjosmurphy/projects/butterfly_annotation/cds/orthofinder_test/OrthoFinder/Results_May17_2/

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2019), Genome Biology 20:238

 If you use the species tree in your work then please also cite:
 Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
 Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101/267914`

List of packages:
`
### Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
blast                     2.5.0                hc0b0e79_3    bioconda
boost                     1.63.0                   py36_2    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
certifi                   2016.9.26                py36_0    conda-forge
diamond                   2.1.6                h5b5514e_1    bioconda
fastme                    2.1.6.1              h031d066_3    bioconda
fasttree                  2.1.11               h031d066_2    bioconda
gawk                      5.1.0                h7f98852_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
icu                       56.1                          4    conda-forge
iqtree                    2.2.2.3              h2202e69_2    bioconda
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
mafft                     7.520                h031d066_2    bioconda
mcl                       14.137          pl5321hec16e2b_8    bioconda
mmseqs2                   13.45111        pl5321hf1761c0_2    bioconda
mpi                       1.0                     openmpi    conda-forge
muscle                    5.1                  h4ac6f70_3    bioconda
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.19.5           py36hfc0c790_2    conda-forge
openmpi                   4.1.5              h414af15_101    conda-forge
openssl                   1.1.1t               h0b41bf4_0    conda-forge
orthofinder               2.5.4                hdfd78af_0    bioconda
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pip                       20.0.2                   py36_1    conda-forge
python                    3.6.15          hb7a2778_0_cpython    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
raxml                     8.2.12               h031d066_6    bioconda
raxml-ng                  1.2.0                h22e3c99_0    bioconda
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.5.3            py36h81d768a_1    conda-forge
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
sqlite                    3.42.0               h2c6b66d_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wget                      1.20.3               ha56f1ee_1    conda-forge
wheel                     0.34.2                   py36_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge`
