### ISSUE TITLE
OrthoXML output issues

### ISSUE THREAD

**Issue by ens-sb** [davidemms/OrthoFinder#827]
Hi David,

I am trying to generate OrthoXML output from the example dataset included in Orthofinder 2.5.4 with the following "made up" species list file:

```
Mycoplasma_agalactiae.faa       Mycoplasma agalactiae   37      Ensembl Mycoplasma_agalactiae.fa
Mycoplasma_gallisepticum.faa    Mycoplasma gallisepticum        38      Ensembl Mycoplasma_gallisepticum.fa
Mycoplasma_genitalium.faa       Mycoplasma genitalium   39      Ensembl Mycoplasma_genitalium.fa
Mycoplasma_hyopneumoniae.faa    Mycoplasma hyopneumoniae        40      Ensembl Mycoplasma_hyopneumoniae.fa
```

The analysis runs, however at the end I get the following error:

```
Writing orthogroups to file
---------------------------
OrthoFinder assigned 2216 genes (81.1% of total) to 608 orthogroups. Fifty percent of all genes were in orthogroups with 4 or more genes (G50 was 4) and were contained in the largest 280 orthogroups (O50 was 280). There were 268 orthogroups with all species present and 245 of these consisted entirely of single-copy genes.
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1775, in main
  File "scripts_of/__main__.py", line 1404, in DoOrthogroups
NameError: global name 'speciesXML' is not defined
[1800709] Failed to execute script orthofinder
```
Thanks in advance for looking into this!

Regards,
Botond

**Comment by sinamajidian** [comment]
Dear OrthoFinder team and Botond,

I'm wondering whether there is an update on generating OrthoXML file with OrthoFinder. 
I found some info in the code https://github.com/davidemms/OrthoFinder/blob/d5726f5af908d99b0e08791fcbda14650ca24bec/scripts_of/__main__.py#L767 but I couldn't find information in the Readme or the tutorial.  
We recently developed [orthoXML-tools](https://github.com/DessimozLab/orthoxml-tools) for manipulating OrthoXML files and would love to test it on OrthoXML file generated by OrthoFinder. 

Thank you in advance
Best regards,
Sina
