### ISSUE TITLE
Error: Species tree inference failed 

### ISSUE THREAD

**Issue by emdtr** [davidemms/OrthoFinder#835]
Hello,

I'm running into an error with v 2.5.5: "ERROR: Species tree inference failed / local variable 'speciesTree' referenced before assignment"

I think this might be a similar error to one previously reported (#782). I tried changing the python version in my conda environment to one earlier than 3.11 (3.10.8) but got the same error.

Any help would be much appreciated. Thanks!

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2023-06-16 16:09:29 : Done
Using fallback species tree inference method
/Users/emilytrudeau/miniconda3/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/emilytrudeau/miniconda3/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Inferring gene and species trees
--------------------------------
2023-06-16 16:09:29 : Done 0 of 5

Best outgroup(s) for species tree
---------------------------------
2023-06-16 16:09:31 : Starting STRIDE
ERROR: Species tree inference failed
local variable 'speciesTree' referenced before assignment
  File "/Users/emilytrudeau/miniconda3/bin/scripts_of/__main__.py", line 1790, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/Users/emilytrudeau/miniconda3/bin/scripts_of/__main__.py", line 1550, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
  File "/Users/emilytrudeau/miniconda3/bin/scripts_of/orthologues.py", line 1047, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
  File "/Users/emilytrudeau/miniconda3/bin/scripts_of/stride.py", line 513, in GetRoot
    species, dict_clades, clade_names = AnalyseSpeciesTree(speciesTree)
Traceback (most recent call last):
  File "/Users/emilytrudeau/miniconda3/bin/orthofinder", line 7, in <module>
    main(args)
  File "/Users/emilytrudeau/miniconda3/bin/scripts_of/__main__.py", line 1790, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/Users/emilytrudeau/miniconda3/bin/scripts_of/__main__.py", line 1550, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
  File "/Users/emilytrudeau/miniconda3/bin/scripts_of/orthologues.py", line 1047, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
  File "/Users/emilytrudeau/miniconda3/bin/scripts_of/stride.py", line 513, in GetRoot
    species, dict_clades, clade_names = AnalyseSpeciesTree(speciesTree)
UnboundLocalError: local variable 'speciesTree' referenced before assignment

**Comment by jmagui** [comment]
I'm having the same issue--did either of you end up figuring out a work around?

**Comment by JDuffyEx** [comment]
Same issue for me, running a range of complete and incomplete viral proteomes, I can only get species tree inference to work by excluding smaller proteomes. Wondering if there is a workaround or if either of you figured out a solution?

**Comment by Buckaroo1** [comment]
Same problem when using the command on ExampleData:
`$ orthofinder -M msa -T iqtree -f ExampleData/`
