### ISSUE TITLE
error : UnboundLocalError: cannot access local variable 'speciesTree' where it is not associated with a value

### ISSUE THREAD

**Issue by yogurtYH** [davidemms/OrthoFinder#839]
Best outgroup(s) for species tree
---------------------------------
2023-07-17 20:17:11 : Starting STRIDE
ERROR: Species tree inference failed
cannot access local variable 'speciesTree' where it is not associated with a value
  File "/mnt/subuser/public/soft_scripts/anaconda3/envs/orth/bin/scripts_of/__main__.py", line 1790, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/mnt/subuser/public/soft_scripts/anaconda3/envs/orth/bin/scripts_of/__main__.py", line 1550, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
  File "/mnt/subuser/public/soft_scripts/anaconda3/envs/orth/bin/scripts_of/orthologues.py", line 1047, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/subuser/public/soft_scripts/anaconda3/envs/orth/bin/scripts_of/stride.py", line 513, in GetRoot
    species, dict_clades, clade_names = AnalyseSpeciesTree(speciesTree)
                                                           ^^^^^^^^^^^
Traceback (most recent call last):
  File "/mnt/subuser/public/soft_scripts/anaconda3/envs/orth/bin/orthofinder", line 7, in <module>
    main(args)
  File "/mnt/subuser/public/soft_scripts/anaconda3/envs/orth/bin/scripts_of/__main__.py", line 1790, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/mnt/subuser/public/soft_scripts/anaconda3/envs/orth/bin/scripts_of/__main__.py", line 1550, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/subuser/public/soft_scripts/anaconda3/envs/orth/bin/scripts_of/orthologues.py", line 1047, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/subuser/public/soft_scripts/anaconda3/envs/orth/bin/scripts_of/stride.py", line 513, in GetRoot
    species, dict_clades, clade_names = AnalyseSpeciesTree(speciesTree)
                                                           ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'speciesTree' where it is not associated with a value

can you help me ？ thanks

**Comment by yogurtYH** [comment]
@https://github.com/davidemms

**Comment by Zerong0513** [comment]
Hello, I had the same problem, do you fix it?

**Comment by Artifice120** [comment]
Same exact problem
