### ISSUE TITLE
Too many open files orthofinder 2.5.5

### ISSUE THREAD

**Issue by jeankeller** [davidemms/OrthoFinder#847]
Hello,

I am trying to run orthofinder v2.5.5 on a HPC (thus I cannot modify the ulimit) and 120 genomes but it fails at the gene distance calculation step with the following error:

`Calculating gene distances
--------------------------
[Errno 24] Too many open files
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/__main__.py", line 1806, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/__main__.py", line 1550, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/orthologues.py", line 1007, in OrthologuesWorkflow
    spTreeFN_ids, qSTAG = db.RunAnalysis(userSpeciesTree == None)
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/orthologues.py", line 455, in RunAnalysis
    ogs, ogMatrices_partial = self.GetOGMatrices_FullParallel()
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/orthologues.py", line 299, in GetOGMatrices_FullParallel
    ogMatrices = [[mp.Array('d', n, lock=False) for _ in range(n)] for n in nGenes]
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/orthologues.py", line 299, in <listcomp>
    ogMatrices = [[mp.Array('d', n, lock=False) for _ in range(n)] for n in nGenes]
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/orthologues.py", line 299, in <listcomp>
    ogMatrices = [[mp.Array('d', n, lock=False) for _ in range(n)] for n in nGenes]
  File "/usr/lib/python3.10/multiprocessing/context.py", line 141, in Array
    return Array(typecode_or_type, size_or_initializer, lock=lock,
  File "/usr/lib/python3.10/multiprocessing/sharedctypes.py", line 88, in Array
    obj = RawArray(typecode_or_type, size_or_initializer)
  File "/usr/lib/python3.10/multiprocessing/sharedctypes.py", line 61, in RawArray
    obj = _new_value(type_)
  File "/usr/lib/python3.10/multiprocessing/sharedctypes.py", line 41, in _new_value
    wrapper = heap.BufferWrapper(size)
  File "/usr/lib/python3.10/multiprocessing/heap.py", line 331, in __init__
    block = BufferWrapper._heap.malloc(size)
  File "/usr/lib/python3.10/multiprocessing/heap.py", line 309, in malloc
    (arena, start, stop) = self._malloc(size)
  File "/usr/lib/python3.10/multiprocessing/heap.py", line 192, in _malloc
    return self._new_arena(size)
  File "/usr/lib/python3.10/multiprocessing/heap.py", line 166, in _new_arena
    arena = Arena(length)
  File "/usr/lib/python3.10/multiprocessing/heap.py", line 89, in __init__
    self.buffer = mmap.mmap(self.fd, self.size)
Traceback (most recent call last):
  File "/home/jkeller/install/OrthoFinder-2.5.5/orthofinder.py", line 7, in <module>
    main(args)
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/__main__.py", line 1806, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/__main__.py", line 1550, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/orthologues.py", line 1007, in OrthologuesWorkflow
    spTreeFN_ids, qSTAG = db.RunAnalysis(userSpeciesTree == None)
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/orthologues.py", line 455, in RunAnalysis
    ogs, ogMatrices_partial = self.GetOGMatrices_FullParallel()
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/orthologues.py", line 299, in GetOGMatrices_FullParallel
    ogMatrices = [[mp.Array('d', n, lock=False) for _ in range(n)] for n in nGenes]
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/orthologues.py", line 299, in <listcomp>
    ogMatrices = [[mp.Array('d', n, lock=False) for _ in range(n)] for n in nGenes]
  File "/home/jkeller/install/OrthoFinder-2.5.5/scripts_of/orthologues.py", line 299, in <listcomp>
    ogMatrices = [[mp.Array('d', n, lock=False) for _ in range(n)] for n in nGenes]
  File "/usr/lib/python3.10/multiprocessing/context.py", line 141, in Array
    return Array(typecode_or_type, size_or_initializer, lock=lock,
  File "/usr/lib/python3.10/multiprocessing/sharedctypes.py", line 88, in Array
    obj = RawArray(typecode_or_type, size_or_initializer)
  File "/usr/lib/python3.10/multiprocessing/sharedctypes.py", line 61, in RawArray
    obj = _new_value(type_)
  File "/usr/lib/python3.10/multiprocessing/sharedctypes.py", line 41, in _new_value
    wrapper = heap.BufferWrapper(size)
  File "/usr/lib/python3.10/multiprocessing/heap.py", line 331, in __init__
    block = BufferWrapper._heap.malloc(size)
  File "/usr/lib/python3.10/multiprocessing/heap.py", line 309, in malloc
    (arena, start, stop) = self._malloc(size)
  File "/usr/lib/python3.10/multiprocessing/heap.py", line 192, in _malloc
    return self._new_arena(size)
  File "/usr/lib/python3.10/multiprocessing/heap.py", line 166, in _new_arena
    arena = Arena(length)
  File "/usr/lib/python3.10/multiprocessing/heap.py", line 89, in __init__
    self.buffer = mmap.mmap(self.fd, self.size)
OSError: [Errno 24] Too many open files`

Is there a way to fix this without having to modify the hard limit?

Thanks,
Jean

**Comment by jeankeller** [comment]
fixed by increasing the ulimit but I've got any warnings at the start of the script as in the 2.5.4 version. A bit sad since it takes a relatively long time before raising this error (it came after the diamond blast)
