### ISSUE TITLE
An error is reported when running orthofinder for more than 15 species

### ISSUE THREAD

**Issue by MYP0130** [davidemms/OrthoFinder#868]
OrthoFinder version 2.4.0 runs in a python2.7 environment

Running diamond all-versus-all
------------------------------
Using 6 thread(s)
2023-11-23 20:14:23 : This may take some time....
2023-11-23 20:14:23 : Done 0 of 324
2023-11-23 20:52:43 : Done 100 of 324

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species9.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast9_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'
2023-11-23 21:21:09 : Done 200 of 324

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species2.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast2_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species4.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast4_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species5.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast5_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'

ERROR: external program called by OrthoFinder returned an error code: 137

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species3.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast3_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Killed\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species13.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast13_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species1.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast1_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species15.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast15_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species17.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast17_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'
2023-11-23 21:48:01 : Done 300 of 324

ERROR: external program called by OrthoFinder returned an error code: 137

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species8.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast8_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Killed\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species0.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast0_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'

ERROR: external program called by OrthoFinder returned an error code: 137

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species14.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast14_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Killed\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species16.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast16_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species10.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast10_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'

ERROR: external program called by OrthoFinder returned an error code: 137

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species12.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast12_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Killed\n'

ERROR: external program called by OrthoFinder returned an error code: 137

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species11.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast11_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Killed\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species6.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast6_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'

ERROR: external program called by OrthoFinder returned an error code: 134

Command: diamond blastp -d /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/diamondDBSpecies7 -q /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Species7.fa -o /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast7_7.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Error: std::bad_alloc\nAborted\n'
2023-11-23 21:57:44 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2023-11-23 21:57:46 : Initial processing of each species
Malformatted line in /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast0_7.txt
Offending line was:
0_1786  7_5587  37.0    73      40      2       456     524     9       79      5.3e-04 44.3
Process Process-8:
Traceback (most recent call last):
  File "/home/mengyiping/miniconda3/envs/py27/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/mengyiping/miniconda3/envs/py27/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mengyiping/miniconda3/envs/py27/bin/scripts_of/__main__.py", line 520, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, qDoubleBlast=qDoubleBlast)
  File "/home/mengyiping/miniconda3/envs/py27/bin/scripts_of/__main__.py", line 507, in ProcessBlastHits
    Bij = blast_file_processor.GetBLAST6Scores(seqsInfo, blastDir_list, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mengyiping/miniconda3/envs/py27/bin/scripts_of/blast_file_processor.py", line 65, in GetBLAST6Scores
    for row in blastreader:
  File "/home/mengyiping/miniconda3/envs/py27/lib/python3.12/gzip.py", line 337, in read1
    return self._buffer.read1(size)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mengyiping/miniconda3/envs/py27/lib/python3.12/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mengyiping/miniconda3/envs/py27/lib/python3.12/gzip.py", line 547, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
Malformatted line in /home/mengyiping/pep/OrthoFinder/Results_Nov23/WorkingDirectory/Blast1_7.txt
Offending line was:
1_534   7_6160  43.5    283     147     5       433     713     55      326     1.3e-49 196.1
Process Process-9:
Traceback (most recent call last):
  File "/home/mengyiping/miniconda3/envs/py27/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/mengyiping/miniconda3/envs/py27/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mengyiping/miniconda3/envs/py27/bin/scripts_of/__main__.py", line 520, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, qDoubleBlast=qDoubleBlast)
  File "/home/mengyiping/miniconda3/envs/py27/bin/scripts_of/__main__.py", line 507, in ProcessBlastHits
    Bij = blast_file_processor.GetBLAST6Scores(seqsInfo, blastDir_list, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mengyiping/miniconda3/envs/py27/bin/scripts_of/blast_file_processor.py", line 65, in GetBLAST6Scores
    for row in blastreader:
  File "/home/mengyiping/miniconda3/envs/py27/lib/python3.12/gzip.py", line 337, in read1
    return self._buffer.read1(size)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mengyiping/miniconda3/envs/py27/lib/python3.12/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mengyiping/miniconda3/envs/py27/lib/python3.12/gzip.py", line 547, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.

When I used less than 15 species, the program was running properly. However, once the number of species exceeds 15, an error will be reported. I don't know how to resolved this problem. I sincerely hope someone can put forward suggestions.

**Comment by Ygg-Bu** [comment]
Hello, may I ask if you have resolved this issue？
