### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by Ming314** [davidemms/OrthoFinder#924]
Hi, I want to use OrthoFinder to study orthology relationships for all genes in multiple species.
I ran orthofinder with the command : orthofinder -f prot
and got this error:

Traceback (most recent call last):
  File "/home/ming/miniconda3/envs/orthofinder/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/ming/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 1806, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/ming/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 1550, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ming/miniconda3/envs/orthofinder/bin/scripts_of/orthologues.py", line 1061, in OrthologuesWorkflow
    shutil.copy(rootedSpeciesTreeFN[0], files.FileHandler.GetSpeciesTreeIDsRootedFN())
  File "/home/ming/miniconda3/envs/orthofinder/lib/python3.12/shutil.py", line 436, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ming/miniconda3/envs/orthofinder/lib/python3.12/shutil.py", line 317, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: '/mnt/f/metagenome_analysis/SPM_namco_sjy_metagenome/data_analysis/DNRA_ANR/nrfA_MAGs/prot/OrthoFinder/Results_Sep21/WorkingDirectory/OrthoFinder/Results_Sep23/WorkingDirectory/SpeciesTree_rooted_ids.txt'

Did that happen because I am not the root user? But i ran with the command: ls -l, 'SpeciesTree_rooted_ids.txt' exists and is under root. 
 How can I fix this?
Thanks!

**Comment by Ming314** [comment]
> 嗨，我想使用 OrthoFinder 来研究多个物种中所有基因的正字关系。我使用命令 orthofinder -f prot 运行 orthofinder 并收到此错误：
> 
> 回溯（最近调用最后一次）：文件 “/home/ming/miniconda3/envs/orthofinder/bin/orthofinder”，第 7 行，在 main（args） 文件中 文件“/home/ming/miniconda3/envs/orthofinder/bin/scripts_of/**main**.py”，第 1806 行，在 main GetOrthologues（speciesInfoObj， options， prog_caller） 文件 “/home/ming/miniconda3/envs/orthofinder/bin/scripts_of/**main**.py”，第 1550 行，在 GetOrthologues 中直系同源物。OrthologuesWorkflow（speciesInfoObj.speciesToUse， ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 文件 “/home/ming/miniconda3/envs/orthofinder/bin/scripts_of/orthologues.py”， 第 1061 行， in OrthologuesWorkflow shutil.copy（rootedSpeciesTreeFN[0]， files.FileHandler.GetSpeciesTreeIDsRootedFN（）） 文件 “/home/ming/miniconda3/envs/orthofinder/lib/python3.12/shutil.py”，第 436 行，在 copy copymode（src， dst， follow_symlinks=follow_symlinks） 文件 “/home/ming/miniconda3/envs/orthofinder/lib/python3.12/shutil.py”，第 317 行，在 copymode chmod_func（dst， stat.S_IMODE（st.st_mode）） PermissionError： [Errno 1] 不允许操作： '/mnt/f/metagenome_analysis/SPM_namco_sjy_metagenome/data_analysis/DNRA_ANR/nrfA_MAGs/prot/OrthoFinder/Results_Sep21/WorkingDirectory/OrthoFinder/Results_Sep23/WorkingDirectory/SpeciesTree_rooted_ids.txt'
> 
> 发生这种情况是因为我不是 root 用户吗？但是我使用命令运行：ls -l，'SpeciesTree_rooted_ids.txt' 存在并在 root 下。我该如何解决这个问题？ 谢谢！

I've solved this problem, it seems to be due to a computer memory problem, I ran it successfully on another computer with more memory and arithmetic power

**Comment by Ming314** [comment]
> Hi, I want to use OrthoFinder to study orthology relationships for all genes in multiple species. I ran orthofinder with the command : orthofinder -f prot and got this error:
> 
> Traceback (most recent call last): File "/home/ming/miniconda3/envs/orthofinder/bin/orthofinder", line 7, in main(args) File "/home/ming/miniconda3/envs/orthofinder/bin/scripts_of/**main**.py", line 1806, in main GetOrthologues(speciesInfoObj, options, prog_caller) File "/home/ming/miniconda3/envs/orthofinder/bin/scripts_of/**main**.py", line 1550, in GetOrthologues orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/ming/miniconda3/envs/orthofinder/bin/scripts_of/orthologues.py", line 1061, in OrthologuesWorkflow shutil.copy(rootedSpeciesTreeFN[0], files.FileHandler.GetSpeciesTreeIDsRootedFN()) File "/home/ming/miniconda3/envs/orthofinder/lib/python3.12/shutil.py", line 436, in copy copymode(src, dst, follow_symlinks=follow_symlinks) File "/home/ming/miniconda3/envs/orthofinder/lib/python3.12/shutil.py", line 317, in copymode chmod_func(dst, stat.S_IMODE(st.st_mode)) PermissionError: [Errno 1] Operation not permitted: '/mnt/f/metagenome_analysis/SPM_namco_sjy_metagenome/data_analysis/DNRA_ANR/nrfA_MAGs/prot/OrthoFinder/Results_Sep21/WorkingDirectory/OrthoFinder/Results_Sep23/WorkingDirectory/SpeciesTree_rooted_ids.txt'
> 
> Did that happen because I am not the root user? But i ran with the command: ls -l, 'SpeciesTree_rooted_ids.txt' exists and is under root. How can I fix this? Thanks!

I've solved this problem, it seems to be due to a computer memory problem, I ran it successfully on another computer with more memory and arithmetic power
