### ISSUE TITLE
ERROR: Species tree inference failed

### ISSUE THREAD

**Issue by dmckeow** [davidemms/OrthoFinder#948]
Using OrthoFinder 2.5.5, running it on eukaryotic proteomes, on HPC via Nextflow pipeline.
The following error seems to occur only when certain samples in my dataset are included in the same run - for example two sets of 50 genomes run fine, but when run together this error appears.
It runs with no error on some sets of 50-100 genomes, but others cause this error, and I cannot tell why. I have tried large memory runs (128 GB) on an HPC, and it does not seem to be an out of memory problem.
The syntax warnings at the start of the log appear on successful runs, so I do not think this is the issue.
I'm reallly stumped here - any pointers of how to get to the bottom of this would be really appreciated.
Alternatively, any workaround also appreciated.

/usr/local/bin/scripts_of/tree.py:367: SyntaxWarning: invalid escape sequence '\-'
  """
/usr/local/bin/scripts_of/tree.py:1422: SyntaxWarning: invalid escape sequence '\-'
  """
/usr/local/bin/scripts_of/newick.py:54: SyntaxWarning: invalid escape sequence '\['
  _ILEGAL_NEWICK_CHARS = ":;(),\[\]\t\n\r="
/usr/local/bin/scripts_of/newick.py:57: SyntaxWarning: invalid escape sequence '\['
  _NHX_RE = "\[&&NHX:[^\]]*\]"
/usr/local/bin/scripts_of/newick.py:58: SyntaxWarning: invalid escape sequence '\d'
  _FLOAT_RE = "[+-]?\d+\.?\d*(?:[eE][-+]\d+)?"
/usr/local/bin/scripts_of/newick.py:60: SyntaxWarning: invalid escape sequence '\['
  _NAME_RE = "[^():,;\[\]]+"
/usr/local/bin/scripts_of/newick.py:337: SyntaxWarning: invalid escape sequence '\s'
  MATCH = '%s\s*%s\s*(%s)?' % (FIRST_MATCH, SECOND_MATCH, _NHX_RE)
/usr/local/bin/scripts_of/probroot.py:10: SyntaxWarning: invalid escape sequence '\i'
  """
/usr/local/bin/scripts_of/probroot.py:201: SyntaxWarning: invalid escape sequence '\l'
  """
/usr/local/bin/scripts_of/probroot.py:267: SyntaxWarning: invalid escape sequence '\l'
  """

OrthoFinder version 2.5.5 Copyright (C) 2014 David Emms

2024-12-05 08:13:29 : Starting OrthoFinder 2.5.5
8 thread(s) for highly parallel tasks (BLAST searches etc.)
2 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /users/asebe/dmckeown/projects/crg-bcaortho/work/54/f24b6771b150179ba230dda159420b/input/OrthoFinder/Results_orthofinder/WorkingDirectory/dependencies/SimpleTest.phy -o /users/asebe/dmckeown/projects/crg-bcaortho/work/54/f24b6771b150179ba230dda159420b/input/OrthoFinder/Results_orthofinder/WorkingDirectory/dependencies/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2024-12-05 08:13:29 : Creating diamond database 1 of 19
2024-12-05 08:13:29 : Creating diamond database 2 of 19
2024-12-05 08:13:29 : Creating diamond database 3 of 19
2024-12-05 08:13:29 : Creating diamond database 4 of 19
2024-12-05 08:13:29 : Creating diamond database 5 of 19
2024-12-05 08:13:30 : Creating diamond database 6 of 19
2024-12-05 08:13:30 : Creating diamond database 7 of 19
2024-12-05 08:13:30 : Creating diamond database 8 of 19
2024-12-05 08:13:30 : Creating diamond database 9 of 19
2024-12-05 08:13:30 : Creating diamond database 10 of 19
2024-12-05 08:13:30 : Creating diamond database 11 of 19
2024-12-05 08:13:30 : Creating diamond database 12 of 19
2024-12-05 08:13:30 : Creating diamond database 13 of 19
2024-12-05 08:13:30 : Creating diamond database 14 of 19
2024-12-05 08:13:30 : Creating diamond database 15 of 19
2024-12-05 08:13:30 : Creating diamond database 16 of 19
2024-12-05 08:13:30 : Creating diamond database 17 of 19
2024-12-05 08:13:30 : Creating diamond database 18 of 19
2024-12-05 08:13:30 : Creating diamond database 19 of 19

Running diamond all-versus-all
------------------------------
Using 8 thread(s)
2024-12-05 08:13:30 : This may take some time....
2024-12-05 08:13:30 : Done 0 of 361
2024-12-05 08:13:39 : Done 100 of 361
2024-12-05 08:13:48 : Done 200 of 361
2024-12-05 08:13:58 : Done 300 of 361
2024-12-05 08:14:03 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2024-12-05 08:14:03 : Initial processing of each species
2024-12-05 08:14:03 : Initial processing of species 0 complete
2024-12-05 08:14:03 : Initial processing of species 1 complete
2024-12-05 08:14:03 : Initial processing of species 2 complete
2024-12-05 08:14:04 : Initial processing of species 3 complete
2024-12-05 08:14:04 : Initial processing of species 4 complete
2024-12-05 08:14:04 : Initial processing of species 5 complete
2024-12-05 08:14:04 : Initial processing of species 6 complete
2024-12-05 08:14:04 : Initial processing of species 8 complete
2024-12-05 08:14:04 : Initial processing of species 7 complete
2024-12-05 08:14:05 : Initial processing of species 9 complete
2024-12-05 08:14:05 : Initial processing of species 11 complete
2024-12-05 08:14:05 : Initial processing of species 10 complete
2024-12-05 08:14:05 : Initial processing of species 12 complete
2024-12-05 08:14:05 : Initial processing of species 13 complete
2024-12-05 08:14:05 : Initial processing of species 14 complete
2024-12-05 08:14:05 : Initial processing of species 15 complete
2024-12-05 08:14:06 : Initial processing of species 16 complete
2024-12-05 08:14:06 : Initial processing of species 17 complete
2024-12-05 08:14:06 : Initial processing of species 18 complete
2024-12-05 08:14:09 : Connected putative homologues
2024-12-05 08:14:09 : Written final scores for species 0 to graph file
2024-12-05 08:14:09 : Written final scores for species 3 to graph file
2024-12-05 08:14:09 : Written final scores for species 1 to graph file
2024-12-05 08:14:09 : Written final scores for species 2 to graph file
2024-12-05 08:14:09 : Written final scores for species 4 to graph file
2024-12-05 08:14:09 : Written final scores for species 6 to graph file
2024-12-05 08:14:09 : Written final scores for species 5 to graph file
2024-12-05 08:14:09 : Written final scores for species 7 to graph file
2024-12-05 08:14:09 : Written final scores for species 9 to graph file
2024-12-05 08:14:09 : Written final scores for species 8 to graph file
2024-12-05 08:14:09 : Written final scores for species 12 to graph file
2024-12-05 08:14:09 : Written final scores for species 10 to graph file
2024-12-05 08:14:09 : Written final scores for species 13 to graph file
2024-12-05 08:14:09 : Written final scores for species 11 to graph file
2024-12-05 08:14:09 : Written final scores for species 14 to graph file
2024-12-05 08:14:09 : Written final scores for species 15 to graph file
2024-12-05 08:14:09 : Written final scores for species 16 to graph file
2024-12-05 08:14:09 : Written final scores for species 18 to graph file
2024-12-05 08:14:09 : Written final scores for species 17 to graph file
2024-12-05 08:14:12 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 2351 genes (97.7% of total) to 82 orthogroups. Fifty percent of all genes were in orthogroups with 132 or more genes (G50 was 132) and were contained in the largest 4 orthogroups (O50 was 4). There were 0 orthogroups with all species present and 0 of these consisted entirely of single-copy genes.

2024-12-05 08:14:12 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2024-12-05 08:14:17 : Done
/usr/local/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
2024-12-05 08:14:17 : Done 0 of 53
2024-12-05 08:14:17 : Done 10 of 53
2024-12-05 08:14:17 : Done 20 of 53
2024-12-05 08:14:17 : Done 30 of 53
2024-12-05 08:14:17 : Done 40 of 53
Using fallback species tree inference method

Inferring gene and species trees
--------------------------------

Best outgroup(s) for species tree
---------------------------------
2024-12-05 08:14:20 : Starting STRIDE
  File "/usr/local/bin/scripts_of/__main__.py", line 1790, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/usr/local/bin/scripts_of/__main__.py", line 1550, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
  File "/usr/local/bin/scripts_of/orthologues.py", line 1047, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/scripts_of/stride.py", line 513, in GetRoot
    species, dict_clades, clade_names = AnalyseSpeciesTree(speciesTree)
                                                           ^^^^^^^^^^^
Traceback (most recent call last):
ERROR: Species tree inference failed
cannot access local variable 'speciesTree' where it is not associated with a value
  File "/usr/local/bin/orthofinder", line 7, in <module>
    main(args)
  File "/usr/local/bin/scripts_of/__main__.py", line 1790, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/usr/local/bin/scripts_of/__main__.py", line 1550, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/scripts_of/orthologues.py", line 1047, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/scripts_of/stride.py", line 513, in GetRoot
    species, dict_clades, clade_names = AnalyseSpeciesTree(speciesTree)
                                                           ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'speciesTree' where it is not associated with a value

**Comment by Jonathan-Holmes-Bioinformatics** [comment]
Hi dmckeow,

The number of genes in your analysis seems quite low ~50-100. This may be causing STRIDE to fail. Is it possible for you to attach a zip file containing your 20 Proteomes from the example log 1 above so we can have a look and try to reproduce the error. 

Thanks
