### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by oddguyeee** [davidemms/OrthoFinder#952]
[orthofinder_20241204.txt](https://github.com/user-attachments/files/18140720/orthofinder_20241204.txt)
Hi, 
I encountered a problem while running this cmd:
```sh
for f in *faa ; 
  do
  python ../tools/primary_transcript.py $f 
  done
conda activate orthofinder
nohup orthofinder -f primary_transcripts/ -t 16 > orthofinder.20241204 2>&1 &
```
I am confused as to why an error occurred and the program did not . Additionally, how can I resolve this issue?
```sh
Best outgroup(s) for species tree
---------------------------------
Observed 2853 duplications. 2828 support the best root and 25 contradict it.
Best outgroup for species tree:
  Oryza_sativa

Reconciling gene trees and species tree
---------------------------------------
Outgroup: Oryza_sativa
Traceback (most recent call last):
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/bin/dlcpar_search", line 209, in <module>
    sys.exit(main())
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/bin/dlcpar_search", line 179, in main
    log=log_out)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/simplerecon.py", line 39, in dlc_recon
    return reconer.recon(nsearch).get_dict()
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/simplerecon.py", line 82, in recon
    proposal = self.proposer.init_proposal()
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/simplerecon.py", line 225, in init_proposal
    self._recon = self._recon_lca(self._locus_search.get_tree().copy())
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/simplerecon.py", line 259, in _recon_lca
    self._gene2species)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/compbio/phylo.py", line 130, in reconcile
    walk(gtree.root)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/compbio/phylo.py", line 124, in walk
    node.recurse(walk)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/rasmus/treelib.py", line 83, in recurse
    func(child, *args)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/compbio/phylo.py", line 124, in walk
    node.recurse(walk)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/rasmus/treelib.py", line 83, in recurse
...........................................................
File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/compbio/phylo.py", line 124, in walk
    node.recurse(walk)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/rasmus/treelib.py", line 83, in recurse
    func(child, *args)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/compbio/phylo.py", line 124, in walk
    node.recurse(walk)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/rasmus/treelib.py", line 83, in recurse
    func(child, *args)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/compbio/phylo.py", line 124, in walk
    node.recurse(walk)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/rasmus/treelib.py", line 83, in recurse
    func(child, *args)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/compbio/phylo.py", line 124, in walk
    node.recurse(walk)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/rasmus/treelib.py", line 83, in recurse
    func(child, *args)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/compbio/phylo.py", line 124, in walk
    node.recurse(walk)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/rasmus/treelib.py", line 83, in recurse
    func(child, *args)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/compbio/phylo.py", line 124, in walk
    node.recurse(walk)
  File "/nfs_fs/nfs1/sunwu/miniconda3/envs/orthofinder/lib/python2.7/site-packages/dlcpar/deps/rasmus/treelib.py", line 83, in recurse
    func(child, *args)
RuntimeError: maximum recursion depth exceeded
```
I attended  std file below, thanks.

**Comment by lauriebelch** [comment]
Hi oddguyeee,

I would try upgrading to a newer version of orthofinder (I notice you are on version 1.1.8)
